import {createElementComponent} from '../core/elementComponent.js';
import {shell4LocalAxes} from '../solver/shell4.js';
import {layeredShellSectionResponse} from './layeredShellSection.js';

export const NONLINEAR_SHELL4_COMPONENT_CONTRACT='nonlinear-shell4-component/v1';
const zeros=(r,c=r)=>Array.from({length:r},()=>Array(c).fill(0));
const transpose=A=>A[0].map((_,j)=>A.map(r=>r[j]));
const mm=(A,B)=>A.map(r=>B[0].map((_,j)=>r.reduce((s,v,k)=>s+v*B[k][j],0)));
const mv=(A,x)=>A.map(r=>r.reduce((s,v,j)=>s+v*x[j],0));
const addScaled=(K,Q,s=1)=>{for(let i=0;i<K.length;i++)for(let j=0;j<K[i].length;j++)K[i][j]+=s*Q[i][j]};
const addVector=(a,b,s=1)=>{for(let i=0;i<a.length;i++)a[i]+=s*b[i]};
const sub=(a,b)=>a.map((v,i)=>v-b[i]);
const finite=(name,v)=>{const n=Number(v);if(!Number.isFinite(n))throw new Error(`NonlinearShell4: ${name} deve ser finito.`);return n};
const positive=(name,v)=>{const n=finite(name,v);if(!(n>0))throw new Error(`NonlinearShell4: ${name} deve ser positivo.`);return n};
const byId=(rows,id,label,eid)=>{const row=(rows||[]).find(x=>String(x.id)===String(id));if(!row)throw new Error(`NonlinearShell4 ${eid}: ${label} ${id} ausente.`);return row};

function shape(xi,eta){return[.25*(1-xi)*(1-eta),.25*(1+xi)*(1-eta),.25*(1+xi)*(1+eta),.25*(1-xi)*(1+eta)]}
function shapeDerivatives(xi,eta){return{xi:[-.25*(1-eta),.25*(1-eta),.25*(1+eta),-.25*(1+eta)],eta:[-.25*(1-xi),-.25*(1+xi),.25*(1+xi),.25*(1-xi)]}}
function pointKinematics(coords,xi,eta){const N=shape(xi,eta),d=shapeDerivatives(xi,eta);let j11=0,j12=0,j21=0,j22=0;for(let i=0;i<4;i++){j11+=d.xi[i]*coords[i][0];j12+=d.xi[i]*coords[i][1];j21+=d.eta[i]*coords[i][0];j22+=d.eta[i]*coords[i][1]}const detJ=j11*j22-j12*j21;if(!(detJ>1e-12))throw new Error('NonlinearShell4: Jacobiano não positivo.');const inv=[[j22/detJ,-j12/detJ],[-j21/detJ,j11/detJ]],dNdx=[],dNdy=[];for(let i=0;i<4;i++){dNdx.push(inv[0][0]*d.xi[i]+inv[0][1]*d.eta[i]);dNdy.push(inv[1][0]*d.xi[i]+inv[1][1]*d.eta[i])}return{N,dNdx,dNdy,detJ}}
function bMatrices(coords,xi,eta){const q=pointKinematics(coords,xi,eta),Bm=zeros(3,24),Bb=zeros(3,24),Bs=zeros(2,24);for(let i=0;i<4;i++){const o=6*i,N=q.N[i],dx=q.dNdx[i],dy=q.dNdy[i];Bm[0][o]=dx;Bm[1][o+1]=dy;Bm[2][o]=dy;Bm[2][o+1]=dx;Bb[0][o+4]=dx;Bb[1][o+3]=-dy;Bb[2][o+3]=-dx;Bb[2][o+4]=dy;Bs[0][o+2]=dx;Bs[0][o+4]=N;Bs[1][o+2]=dy;Bs[1][o+3]=-N}return{...q,Bm,Bb,Bs}}
function transform24(R){const T=zeros(24);for(let n=0;n<4;n++)for(const o of [6*n,6*n+3])for(let i=0;i<3;i++)for(let j=0;j<3;j++)T[o+i][o+j]=R[i][j];return T}
function polygonArea(coords){let a=0;for(let i=0;i<4;i++){const j=(i+1)%4;a+=coords[i][0]*coords[j][1]-coords[j][0]*coords[i][1]}return Math.abs(a)/2}
function dofs(nodeIds){return nodeIds.flatMap(nodeId=>['ux','uy','uz','rx','ry','rz'].map(label=>({owner:String(nodeId),nodeId:String(nodeId),label})))}
function Bmb(b){return[...b.Bm.map(r=>[...r]),...b.Bb.map(r=>[...r])]}
function subMatrix(A,r0,rn,c0,cn){return A.slice(r0,rn).map(r=>r.slice(c0,cn))}
function btKb(B,K){return mm(transpose(B),mm(K,B))}
function btF(B,f){return mv(transpose(B),f)}

export function createNonlinearShell4Component({element,project}={}){
  if(!project||!element?.id)throw new Error('NonlinearShell4: element e project são obrigatórios.');const nodeIds=Array.isArray(element.nodeIds)?element.nodeIds:[element.n1,element.n2,element.n3,element.n4];if(nodeIds.length!==4||nodeIds.some(x=>!x)||new Set(nodeIds.map(String)).size!==4)throw new Error(`NonlinearShell4 ${element.id}: quatro nós distintos são obrigatórios.`);const nodes=nodeIds.map(id=>byId(project.nodes,id,'nó',element.id)),axes=shell4LocalAxes(nodes,element),coords=axes.local,area=polygonArea(coords),section=(project.sections||[]).find(s=>String(s.id)===String(element.sectionId))||{},thickness=positive('thickness',element.thickness??element.t??section.thickness??section.t),concreteMaterial=byId(project.materials,element.materialId,'material',element.id),reinforcementLayers=Array.from(element.reinforcementLayers||section.reinforcementLayers||[]).map((r,i)=>({...r,material:byId(project.materials,r.materialId,'material de armadura',`${element.id}/rebar${i+1}`)})),layerCount=Math.max(2,Math.min(40,Math.round(Number(element.layerCount??section.layerCount)||8))),characteristicLength=positive('characteristicLength',element.characteristicLength??section.characteristicLength??Math.sqrt(area)),T=transform24(axes.R),pressure=(project.elementLoads||[]).filter(l=>String(l.elementId)===String(element.id)&&['surface','pressure'].includes(l.kind)).reduce((s,l)=>s+(Number(l.pressure??l.pz??l.qz)||0),0),unsupported=(project.elementLoads||[]).filter(l=>String(l.elementId)===String(element.id)&&!['surface','pressure'].includes(l.kind));if(unsupported.length)throw new Error(`NonlinearShell4 ${element.id}: carga '${unsupported[0].kind}' não suportada.`);const E=positive('E',concreteMaterial.E),nu=finite('nu',concreteMaterial.nu??.2),G=E/(2*(1+nu)),drillingFactor=Math.max(0,Number(element.drillingFactor??1e-6)),kDrill=drillingFactor*G*thickness*area,sectionOptions={characteristicLength,fractureEnergy:element.fractureEnergy??concreteMaterial.Gf??concreteMaterial.fractureEnergy,compressionFractureEnergy:element.compressionFractureEnergy??concreteMaterial.Gc??concreteMaterial.compressionFractureEnergy,epsc0:element.epsc0,epscu:element.epscu,shearRetentionMin:element.shearRetentionMin??.05,shearRetentionExponent:element.shearRetentionExponent??1.5,aggregateInterlockMu:element.aggregateInterlockMu??.6,aggregateInterlockCohesion:element.aggregateInterlockCohesion??0,shearCorrection:element.shearCorrection??5/6,rebarHardeningRatio:element.rebarHardeningRatio??.01,rebarKinematicFraction:element.rebarKinematicFraction??1};const g=1/Math.sqrt(3),gps=[[-g,-g],[g,-g],[g,g],[-g,g]];
  return createElementComponent({id:element.id,type:element.type||'shell4-nonlinear',dofs:dofs(nodeIds),initialState:{contract:'nonlinear-shell4-history/v1',points:{}},metadata:{contract:NONLINEAR_SHELL4_COMPONENT_CONTRACT,dimension:'3d',family:'shell4',materialNonlinear:true,fixedCrack:true,smallStrain:true},evaluate:({u,committedState})=>{const ul=mv(T,u),K=zeros(24),fint=Array(24).fill(0),pLocal=Array(24).fill(0),trialPoints={},pointOutputs=[];for(let gp=0;gp<gps.length;gp++){const[xi,eta]=gps[gp],b=bMatrices(coords,xi,eta),em=mv(b.Bm,ul),kb=mv(b.Bb,ul),key=`gp${gp+1}`,response=layeredShellSectionResponse({thickness,concreteMaterial,reinforcementLayers,layerCount,generalizedStrain:[em[0],em[1],em[2],kb[0],kb[1],kb[2],0,0],committedHistory:committedState?.points?.[key],options:sectionOptions}),B=Bmb(b),K6=subMatrix(response.tangent,0,6,0,6),r6=response.resultantVector.slice(0,6);addScaled(K,btKb(B,K6),b.detJ);addVector(fint,btF(B,r6),b.detJ);for(let i=0;i<4;i++)pLocal[6*i+2]+=b.N[i]*pressure*b.detJ;trialPoints[key]=response.trialHistory;pointOutputs.push({key,xi,eta,detJ:b.detJ,crackedLayers:response.crackedLayers,crushedLayers:response.crushedLayers,aggregateInterlockLayers:response.aggregateInterlockLayers,meanShearRetention:response.meanShearRetention,resultants:response.resultants})}
    const bc=bMatrices(coords,0,0),emc=mv(bc.Bm,ul),kbc=mv(bc.Bb,ul),gc=mv(bc.Bs,ul),center=layeredShellSectionResponse({thickness,concreteMaterial,reinforcementLayers,layerCount,generalizedStrain:[emc[0],emc[1],emc[2],kbc[0],kbc[1],kbc[2],gc[0],gc[1]],committedHistory:committedState?.points?.shear,options:sectionOptions}),Ks=subMatrix(center.tangent,6,8,6,8),qs=center.resultantVector.slice(6,8);addScaled(K,btKb(bc.Bs,Ks),4*bc.detJ);addVector(fint,btF(bc.Bs,qs),4*bc.detJ);trialPoints.shear=center.trialHistory;for(let i=0;i<4;i++)K[6*i+5][6*i+5]+=kDrill/4;
    const kg=mm(transpose(T),mm(K,T)),internal=mv(transpose(T),fint),external=mv(transpose(T),pLocal),residual=sub(internal,external),state={contract:'nonlinear-shell4-history/v1',points:trialPoints};return{tangent:kg,residual,internalForce:internal,externalForce:external,state,outputs:{area,thickness,characteristicLength,layerCount,pressure,drillingStiffness:kDrill,localAxes:axes,gaussPoints:pointOutputs,shearPoint:{crackedLayers:center.crackedLayers,crushedLayers:center.crushedLayers,aggregateInterlockLayers:center.aggregateInterlockLayers,meanShearRetention:center.meanShearRetention,resultants:center.resultants},reinforcementLayerCount:reinforcementLayers.length}}}});
}
