import{test,expect}from'@playwright/test';

test('v0.53.8 combination flow remains compatible in the v0.53.10 explorer',async({page})=>{
  await page.addInitScript(()=>{localStorage.setItem('astrastruct.project',JSON.stringify({id:'combo-envelope-e2e',name:'Combo envelope E2E',levels:[{id:'L0',name:'Base',elevation:0},{id:'L1',name:'Pavimento 1',elevation:3}],nodes:[{id:'N1',x:0,y:0,z:0},{id:'N2',x:0,y:0,z:3},{id:'N3',x:4,y:0,z:3},{id:'N4',x:4,y:2.5,z:3}],materials:[{id:'steel355',name:'Aço',type:'steel',E:200e6,nu:.3,density:78.5,fy:355}],sections:[{id:'steel_space_demo',name:'Seção 3D',family:'steel3d',A:.012,Iy:.00018,Iz:.00022,J:.00003,I:.00022}],elements:[{id:'C1',label:'Pilar C1',type:'frame3d',n1:'N1',n2:'N2',materialId:'steel355',sectionId:'steel_space_demo',A:.012,Iy:.00018,Iz:.00022,J:.00003,levelId:'L1'},{id:'B1',label:'Viga B1',type:'frame3d',n1:'N2',n2:'N3',materialId:'steel355',sectionId:'steel_space_demo',A:.012,Iy:.00018,Iz:.00022,J:.00003,levelId:'L1'},{id:'B2',label:'Viga B2',type:'frame3d',n1:'N3',n2:'N4',materialId:'steel355',sectionId:'steel_space_demo',A:.012,Iy:.00018,Iz:.00022,J:.00003,orientation:{up:[0,0,1]},levelId:'L1'}],supports:[{nodeId:'N1',ux:true,uy:true,uz:true,rx:true,ry:true,rz:true}],loads:[{id:'LG',caseId:'G',nodeId:'N4',fx:6,fy:-3,fz:-20,mx:0,my:0,mz:0},{id:'LQ',caseId:'Q',nodeId:'N4',fx:8,fy:-5,fz:-10,mx:0,my:0,mz:0}],elementLoads:[],settlements:[],nodeSprings:[],nodalMasses:[],loadCases:[{id:'G',name:'Permanente',type:'permanent'},{id:'Q',name:'Variável',type:'variable'}],loadCombinations:[{id:'ULS1',name:'ELU fundamental',limitStateCategory:'ELU',terms:[{caseId:'G',factor:1.4},{caseId:'Q',factor:1.4}]},{id:'SLS1',name:'ELS rara',limitStateCategory:'ELS',terms:[{caseId:'G',factor:1},{caseId:'Q',factor:1}]}],connections:[],settings:{analysisType:'linear',analysisScenarioId:'ULS1',activeLoadCaseId:'G'}}))});
  await page.goto('');await page.waitForFunction(()=>document.documentElement.dataset.astraReady==='true');
  await expect(page.getByTestId('combination-envelope-open')).toBeAttached();
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('astrastruct:combination-envelope-open')));
  const explorer=page.getByTestId('combination-envelope-explorer');await expect(explorer).toBeVisible();await expect(explorer.getByText('Combinações & envoltórias · v0.53.10')).toBeVisible();
  await explorer.getByTestId('combination-calculate').click();await expect(explorer.getByTestId('combination-row-ULS1')).toBeVisible({timeout:30000});await expect(explorer.getByTestId('combination-row-ULS1').getByText('READY')).toBeVisible({timeout:30000});await expect(explorer.getByTestId('combination-row-SLS1').getByText('READY')).toBeVisible();
  await explorer.getByRole('button',{name:'Envoltórias N/V/M/T',exact:true}).click();await expect(explorer.getByTestId('envelope-row-B1')).toBeVisible();
  await explorer.getByRole('button',{name:'Drift & deslocamentos',exact:true}).click();await expect(explorer.getByText('Pavimento 1')).toBeVisible();await expect(explorer.getByText('Envelope global de deslocamento')).toBeVisible();
  await explorer.getByRole('button',{name:'Combinações',exact:true}).click();await explorer.getByTestId('combination-row-ULS1').click();await explorer.getByTestId('combination-preview-3d').click();await expect(explorer).toBeHidden();
  const preview=page.getByTestId('spatial3d-result-preview');await expect(preview).toBeVisible();await expect(preview.getByText(/ELU fundamental/)).toBeVisible();await expect(page.getByLabel('Escala da forma 3D')).toBeVisible();
  const host=page.locator('.spatial3d-ssi-host');await expect(host).toHaveAttribute('data-result-preview-combination','ULS1');await preview.getByTestId('spatial3d-preview-animate').click();await page.waitForFunction(()=>{const v=document.querySelector('.spatial3d-ssi-host')?.getAttribute('data-result-preview-phase');return v&&v!=='1.000'});await preview.getByTestId('spatial3d-preview-animate').click();
});
