import{test,expect}from'@playwright/test';

test('v0.53.11 maps solver support reactions in 3D and preserves the governing combination',async({page})=>{
  await page.addInitScript(()=>{localStorage.setItem('astrastruct.project',JSON.stringify({id:'reaction-map-e2e',name:'Reaction map E2E',levels:[{id:'L0',name:'Base',elevation:0},{id:'L1',name:'Pavimento 1',elevation:3}],nodes:[{id:'N1',x:0,y:0,z:0,levelId:'L0'},{id:'N2',x:0,y:0,z:3,levelId:'L1'},{id:'N3',x:4,y:0,z:3,levelId:'L1'}],materials:[{id:'steel355',name:'Aço',type:'steel',E:200e6,nu:.3,density:78.5,fy:355}],sections:[{id:'steel_space_demo',name:'Seção 3D',family:'steel3d',A:.012,Iy:.00018,Iz:.00022,J:.00003,I:.00022}],elements:[{id:'C1',label:'Pilar C1',type:'frame3d',n1:'N1',n2:'N2',materialId:'steel355',sectionId:'steel_space_demo',A:.012,Iy:.00018,Iz:.00022,J:.00003,levelId:'L1'},{id:'B1',label:'Viga B1',type:'frame3d',n1:'N2',n2:'N3',materialId:'steel355',sectionId:'steel_space_demo',A:.012,Iy:.00018,Iz:.00022,J:.00003,levelId:'L1'}],supports:[{nodeId:'N1',ux:true,uy:true,uz:true,rx:true,ry:true,rz:true}],loads:[{id:'LG',caseId:'G',nodeId:'N3',fx:5,fy:-2,fz:-18,mx:0,my:0,mz:0},{id:'LQ',caseId:'Q',nodeId:'N3',fx:7,fy:-4,fz:-9,mx:0,my:0,mz:0}],elementLoads:[],settlements:[],nodeSprings:[],nodalMasses:[],loadCases:[{id:'G',name:'Permanente',type:'permanent'},{id:'Q',name:'Variável',type:'variable'}],loadCombinations:[{id:'ULS1',name:'ELU fundamental',limitStateCategory:'ELU',terms:[{caseId:'G',factor:1.4},{caseId:'Q',factor:1.4}]},{id:'SLS1',name:'ELS rara',limitStateCategory:'ELS',terms:[{caseId:'G',factor:1},{caseId:'Q',factor:1}]}],connections:[],settings:{analysisType:'linear',analysisScenarioId:'ULS1',activeLoadCaseId:'G'}}))});
  await page.goto('');await page.waitForFunction(()=>document.documentElement.dataset.astraReady==='true');
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('astrastruct:combination-envelope-open',{detail:{tab:'reactions'}})));
  const explorer=page.getByTestId('combination-envelope-explorer');await expect(explorer).toBeVisible();await expect(explorer.getByText('Combinações & envoltórias · v0.53.11')).toBeVisible();
  await explorer.getByTestId('combination-calculate').click();await expect(explorer.getByTestId('combination-row-ULS1').getByText('READY')).toBeVisible({timeout:30000});await explorer.getByRole('button',{name:'Reações de apoio',exact:true}).click();
  await expect(explorer.getByTestId('reaction-row-N1')).toBeVisible();await expect(explorer.getByTestId('reaction-field-select')).toHaveValue('R');await expect(explorer.getByText(/Nenhuma capacidade de sapata, bloco, estaca ou solo é presumida/)).toBeVisible();
  await explorer.getByTestId('reaction-show-3d').click();await expect(explorer).toBeHidden();const host=page.locator('.spatial3d-ssi-host');await expect(host).toHaveAttribute('data-envelope-domain','reaction');await expect(host).toHaveAttribute('data-envelope-field','R');
  const overlay=page.getByTestId('spatial3d-envelope-overlay');await expect(overlay.locator('[data-envelope-support-id="N1"]')).toBeVisible();await expect(overlay.locator('[data-envelope-support-id="N1"]')).toHaveAttribute('data-envelope-critical','true');
  const status=page.getByTestId('spatial3d-envelope-status');await expect(status.getByText('Reações governantes 3D')).toBeVisible();await expect(status).toHaveAttribute('data-focus-id','N1');await expect(status.getByTestId('reaction-governing-combination')).toHaveText('Combinação governante: ULS1');await expect(status.getByText(/Nenhuma capacidade de fundação ou PASS\/FAIL normativo é inferido/)).toBeVisible();
  await status.getByTestId('reaction-select-critical-support').click();await expect(status).toBeVisible();await expect(status).toHaveAttribute('data-focus-id','N1');await expect(page.getByTestId('spatial-inspector-node')).toBeVisible();await expect(status.getByTestId('reaction-governing-combination')).toHaveText('Combinação governante: ULS1');
  await status.getByTestId('reaction-open-governing-combination').click();await expect(explorer).toBeVisible();await expect(explorer.getByRole('button',{name:'Combinações',exact:true})).toHaveClass(/active/);await expect(explorer.getByTestId('combination-row-ULS1')).toHaveClass(/selected/);
});
