import{test,expect}from'@playwright/test';

test('building ELU ELS dashboard groups by level and selects an element in the 3D canvas',async({page})=>{
  await page.addInitScript(()=>{localStorage.setItem('astrastruct.project',JSON.stringify({id:'elu-els-e2e',levels:[{id:'L0',name:'Base',elevation:0},{id:'L1',name:'Pavimento 1',elevation:3}],nodes:[{id:'N0',x:0,y:0,z:0},{id:'N1',x:0,y:0,z:3},{id:'N2',x:5,y:0,z:3},{id:'N3',x:5,y:4,z:3}],elements:[{id:'B1',label:'Viga B1',type:'frame3d',n1:'N1',n2:'N2',levelId:'L1'},{id:'C1',label:'Pilar C1',type:'frame3d',n1:'N0',n2:'N1',levelId:'L1'},{id:'S1',label:'Laje S1',type:'shell4',nodeIds:['N1','N2','N3','N1'],levelId:'L1'}],codeChecks:[{contract:'code-design-check/v1',id:'B1-ULS',elementId:'B1',discipline:'RC',limitState:'Flexão ELU',details:{limitStateCategory:'ELU'},demand:80,resistance:100,utilization:.8,ok:true,unit:'kN·m'},{contract:'code-design-check/v1',id:'B1-SLS',elementId:'B1',discipline:'RC',limitState:'Flecha ELS',details:{limitStateCategory:'ELS'},demand:10,resistance:20,utilization:.5,ok:true,unit:'mm'}],settings:{analysisType:'linear'},results:{analysisType:'linear',type:'linear3d',dimension:'3d',displacements:[{nodeId:'N0',ux:0,uy:0,uz:0},{nodeId:'N1',ux:.001,uy:0,uz:0},{nodeId:'N2',ux:.001,uy:-.006,uz:0},{nodeId:'N3',ux:.001,uy:-.004,uz:0}],elementForces:[{elementId:'B1',type:'frame3d',N1:40,Vy1:20,Vz1:4,My1:20,Mz1:70,T1:2}]}}))});
  await page.goto('');await page.waitForFunction(()=>document.documentElement.dataset.astraReady==='true');
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('astrastruct:elu-els-dashboard-open')));
  const shell=page.getByTestId('elu-els-dashboard');await expect(shell).toBeVisible();await expect(shell.getByText('Edifício · ELU/ELS · v0.53.7')).toBeVisible();await expect(shell.getByText('Pavimento 1').first()).toBeVisible();
  const row=page.getByTestId('elu-els-row-B1');await expect(row).toBeVisible();await expect(row.getByText('READY FOR REVIEW')).toBeVisible();await row.click();
  const detail=page.getByTestId('elu-els-detail');await expect(detail).toBeVisible();await expect(detail.getByText('Viga B1')).toBeVisible();await expect(detail.getByText(/u nodal máx\./)).toBeVisible();
  await page.evaluate(()=>{(window as any).__eluElsSelection=null;window.addEventListener('astrastruct:selection-changed',((e:CustomEvent)=>{(window as any).__eluElsSelection=e.detail?.selection}) as EventListener)});
  await detail.getByTestId('elu-els-select-canvas').click();await expect(shell).toBeHidden();await page.waitForFunction(()=>{const s=(window as any).__eluElsSelection;return s?.kind==='element'&&s?.id==='B1'});
});
