import{test,expect}from'@playwright/test';

test('v0.53.13 applies one reviewed same-combination reaction vector with audit metadata',async({page})=>{
  await page.addInitScript(()=>{localStorage.setItem('astrastruct.project',JSON.stringify({id:'foundation-transfer-e2e',name:'Foundation transfer E2E',nodes:[{id:'N1',x:0,y:0,z:0}],supports:[{nodeId:'N1',ux:true,uy:true,uz:true,rx:true,ry:true,rz:false}],foundationReview:{profile:{},items:[{id:'F1',label:'Sapata F1',nodeId:'N1',type:'footing',geometry:{B:2,L:2,h:.6},demand:{N:77,Hx:1,Hy:.5,Mx:3,My:2,VuPunching:88},soil:{qDesign:120}}]}}))});
  await page.goto('');await page.waitForFunction(()=>document.documentElement.dataset.astraReady==='true');
  await page.evaluate(()=>{(window as any).__foundationTransferCommit=null;window.addEventListener('astrastruct:project-external-commit',(event:any)=>{(window as any).__foundationTransferCommit=event.detail?.project||null},{once:true});window.dispatchEvent(new CustomEvent('astrastruct:foundation-dashboard-open',{detail:{source:'reaction-map',nodeId:'N1',reaction:{kind:'support',nodeId:'N1',label:'N1',field:'Fz',quantity:'force',value:30,magnitude:30,unit:'kN',vector:[0,0,30],restraints:{ux:true,uy:true,uz:true,rx:true,ry:true,rz:false},governingCombinationId:'ULS1',sourceCombinationReaction:{contract:'support-reaction-at-combination/v1',nodeId:'N1',combinationId:'ULS1',components:{Fx:12,Fy:-4,Fz:30,Mx:5,My:6,Mz:0},forceUnit:'kN',momentUnit:'kN·m',restraints:{ux:true,uy:true,uz:true,rx:true,ry:true,rz:false},complete:true}}}}))});
  const dashboard=page.getByTestId('foundation-decision-dashboard');await expect(dashboard).toBeVisible();const context=dashboard.getByTestId('foundation-reaction-context');await expect(context).toHaveAttribute('data-reaction-link-status','LINKED');await expect(context.getByTestId('foundation-reaction-physical-source')).toContainText('Fx 12.00');await expect(context.getByTestId('foundation-transfer-status')).toContainText('REVIEW_AXES');
  const apply=context.getByTestId('foundation-transfer-apply');await expect(apply).toBeDisabled();await context.getByTestId('foundation-transfer-axis-confirm').check();await expect(context.getByTestId('foundation-transfer-status')).toContainText('REVIEW_SIGN');await context.getByTestId('foundation-transfer-sign-mode').selectOption('opposite-sign');await expect(context.getByTestId('foundation-transfer-status')).toContainText('READY');await expect(context.getByTestId('foundation-transfer-preview')).toContainText('N -30.00');await expect(apply).toBeEnabled();await apply.click();await expect(context.getByTestId('foundation-transfer-message')).toContainText('combinação ULS1');
  const committed=await page.evaluate(()=>(window as any).__foundationTransferCommit);expect(committed).toBeTruthy();const item=committed.foundationReview.items.find((x:any)=>x.id==='F1');expect({N:item.demand.N,Hx:item.demand.Hx,Hy:item.demand.Hy,Mx:item.demand.Mx,My:item.demand.My,VuPunching:item.demand.VuPunching}).toEqual({N:-30,Hx:-12,Hy:4,Mx:-5,My:-6,VuPunching:88});expect(item.metadata.reactionDemandTransfer.combinationId).toBe('ULS1');expect(item.metadata.reactionDemandTransfer.signMode).toBe('opposite-sign');expect(item.metadata.reactionDemandTransfer.sourceComponents).toEqual({Fx:12,Fy:-4,Fz:30,Mx:5,My:6,Mz:0});
});

test('v0.53.13 blocks transfer when restrained Mz cannot be represented by foundation demand model',async({page})=>{
  await page.addInitScript(()=>{localStorage.setItem('astrastruct.project',JSON.stringify({id:'foundation-transfer-mz-e2e',nodes:[{id:'N1',x:0,y:0,z:0}],supports:[{nodeId:'N1',ux:true,uy:true,uz:true,rx:true,ry:true,rz:true}],foundationReview:{profile:{},items:[{id:'F1',label:'Sapata F1',nodeId:'N1',type:'footing',demand:{N:10}}]}}))});
  await page.goto('');await page.waitForFunction(()=>document.documentElement.dataset.astraReady==='true');await page.evaluate(()=>window.dispatchEvent(new CustomEvent('astrastruct:foundation-dashboard-open',{detail:{source:'reaction-map',nodeId:'N1',reaction:{nodeId:'N1',field:'M',quantity:'moment',value:4,magnitude:4,unit:'kN·m',vector:[2,1,4],restraints:{ux:true,uy:true,uz:true,rx:true,ry:true,rz:true},governingCombinationId:'ULS1',sourceCombinationReaction:{contract:'support-reaction-at-combination/v1',nodeId:'N1',combinationId:'ULS1',components:{Fx:1,Fy:2,Fz:30,Mx:2,My:1,Mz:4},forceUnit:'kN',momentUnit:'kN·m',complete:true}}}})));
  const context=page.getByTestId('foundation-reaction-context');await expect(context).toBeVisible();await expect(context.getByText(/Bloqueio de segurança/)).toBeVisible();await expect(context.getByTestId('foundation-transfer-status')).toContainText('BLOCKED_MZ');await context.getByTestId('foundation-transfer-axis-confirm').check();await context.getByTestId('foundation-transfer-sign-mode').selectOption('same-sign');await expect(context.getByTestId('foundation-transfer-apply')).toBeDisabled();
});
