import{test,expect}from'@playwright/test';

test('v0.53.12 reaction link remains non-persistent until explicit v0.53.13 review',async({page})=>{
  await page.addInitScript(()=>{localStorage.setItem('astrastruct.project',JSON.stringify({id:'foundation-reaction-e2e',name:'Foundation reaction E2E',levels:[{id:'L0',name:'Base',elevation:0},{id:'L1',name:'Pavimento 1',elevation:3}],nodes:[{id:'N1',x:0,y:0,z:0,levelId:'L0'},{id:'N2',x:0,y:0,z:3,levelId:'L1'},{id:'N3',x:4,y:0,z:3,levelId:'L1'}],materials:[{id:'steel355',name:'Aço',type:'steel',E:200e6,nu:.3,density:78.5,fy:355}],sections:[{id:'steel_space_demo',name:'Seção 3D',family:'steel3d',A:.012,Iy:.00018,Iz:.00022,J:.00003,I:.00022}],elements:[{id:'C1',label:'Pilar C1',type:'frame3d',n1:'N1',n2:'N2',materialId:'steel355',sectionId:'steel_space_demo',A:.012,Iy:.00018,Iz:.00022,J:.00003,levelId:'L1'},{id:'B1',label:'Viga B1',type:'frame3d',n1:'N2',n2:'N3',materialId:'steel355',sectionId:'steel_space_demo',A:.012,Iy:.00018,Iz:.00022,J:.00003,levelId:'L1'}],supports:[{nodeId:'N1',ux:true,uy:true,uz:true,rx:true,ry:true,rz:true}],loads:[{id:'LG',caseId:'G',nodeId:'N3',fx:5,fy:-2,fz:-18,mx:0,my:0,mz:0},{id:'LQ',caseId:'Q',nodeId:'N3',fx:7,fy:-4,fz:-9,mx:0,my:0,mz:0}],elementLoads:[],settlements:[],nodeSprings:[],nodalMasses:[],loadCases:[{id:'G',name:'Permanente',type:'permanent'},{id:'Q',name:'Variável',type:'variable'}],loadCombinations:[{id:'ULS1',name:'ELU fundamental',limitStateCategory:'ELU',terms:[{caseId:'G',factor:1.4},{caseId:'Q',factor:1.4}]},{id:'SLS1',name:'ELS rara',limitStateCategory:'ELS',terms:[{caseId:'G',factor:1},{caseId:'Q',factor:1}]}],connections:[],foundationReview:{profile:{},items:[{id:'F1',label:'Sapata F1',nodeId:'N1',type:'footing',geometry:{B:2,L:2,h:.6},demand:{N:77,Mx:3,My:2,Hx:1,Hy:.5},soil:{qDesign:120},enabledChecks:{bearing:true,sliding:false,overturning:false,punching:false,oneWayShear:false,flexure:false}}]},settings:{analysisType:'linear',analysisScenarioId:'ULS1',activeLoadCaseId:'G'}}))});
  await page.goto('');await page.waitForFunction(()=>document.documentElement.dataset.astraReady==='true');
  const demandBefore=await page.evaluate(()=>JSON.parse(localStorage.getItem('astrastruct.project')||'{}').foundationReview.items[0].demand);
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('astrastruct:combination-envelope-open',{detail:{tab:'reactions'}})));
  const explorer=page.getByTestId('combination-envelope-explorer');await expect(explorer).toBeVisible();await explorer.getByTestId('combination-calculate').click();await expect(explorer.getByTestId('reaction-row-N1')).toBeVisible({timeout:30000});await expect(explorer.getByText(/Nenhuma capacidade de sapata, bloco, estaca ou solo é presumida/)).toBeVisible();await explorer.getByTestId('reaction-show-3d').click();await expect(explorer).toBeHidden();
  const status=page.getByTestId('spatial3d-envelope-status');await expect(status).toHaveAttribute('data-envelope-domain','reaction');await expect(status).toHaveAttribute('data-focus-id','N1');await expect(status.getByTestId('reaction-governing-combination')).toHaveText('Combinação governante: ULS1');const openFoundation=status.getByTestId('reaction-open-foundation');await expect(openFoundation).toBeVisible();await openFoundation.click();
  const dashboard=page.getByTestId('foundation-decision-dashboard');await expect(dashboard).toBeVisible();await expect(dashboard.getByText('Fundação · SSI · Geotecnia · v0.53.13')).toBeVisible();const context=dashboard.getByTestId('foundation-reaction-context');await expect(context).toHaveAttribute('data-reaction-link-status','LINKED');await expect(context).toHaveAttribute('data-reaction-node-id','N1');await expect(context).toHaveAttribute('data-reaction-foundation-id','F1');await expect(context.getByText(/combinação ULS1/)).toBeVisible();await expect(context.getByText(/Confirme explicitamente o mapeamento global|Mz não é representado/)).toBeVisible();const row=dashboard.getByTestId('foundation-decision-F1');await expect(row).toHaveAttribute('data-reaction-linked','true');await expect(row.getByText(/Reação em contexto/)).toBeVisible();
  const demandAfter=await page.evaluate(()=>JSON.parse(localStorage.getItem('astrastruct.project')||'{}').foundationReview.items[0].demand);expect(demandAfter).toEqual(demandBefore);
});
