import {createElementComponent} from '../core/elementComponent.js';
import {frameLocalStiffness,frameTransform} from '../solver/frameElement.js';
import {frame3DLocalStiffness,spatialAxes} from '../solver/spatial3d.js';
import {materialFor,sectionFor,property,positive,elementDofs,zeros,transpose,mm,matVec,subtract,assertNoElementLoads,nodeFor,norm,sub,add,scale} from './utils.js';

function identity(n){const I=zeros(n);for(let i=0;i<n;i++)I[i][i]=1;return I}
function offset2(raw={}){return[Number(raw.x)||0,Number(raw.y)||0]}
function offset3(raw={}){return[Number(raw.x)||0,Number(raw.y)||0,Number(raw.z)||0]}
function deformableEnds(pa,pb,offsetA,offsetB,rigidZone1=0,rigidZone2=0,id=''){
  const p1=add(pa,offsetA),p2=add(pb,offsetB),chord=sub(p2,p1),L0=norm(chord);if(!(L0>1e-12))throw new Error(`RigidOffsetFrame ${id}: linha entre offsets degenerada.`);const rz1=Math.max(0,Number(rigidZone1)||0),rz2=Math.max(0,Number(rigidZone2)||0);if(rz1+rz2>=L0-1e-12)throw new Error(`RigidOffsetFrame ${id}: zonas rígidas ocupam todo o comprimento.`);const n=chord.map(v=>v/L0),a=add(p1,scale(n,rz1)),b=add(p2,scale(n,-rz2));return{a,b,L: L0-rz1-rz2,offsetLineLength:L0,rigidZone1:rz1,rigidZone2:rz2,direction:n}}
function rigidArm2D(rA,rB){const O=identity(6);O[0][2]+=-rA[1];O[1][2]+=rA[0];O[3][5]+=-rB[1];O[4][5]+=rB[0];return O}
function rigidArm3D(rA,rB){const O=identity(12),fill=(base,r)=>{const [x,y,z]=r,H=[[0,z,-y],[-z,0,x],[y,-x,0]];for(let i=0;i<3;i++)for(let j=0;j<3;j++)O[base+i][base+3+j]+=H[i][j]};fill(0,rA);fill(6,rB);return O}
function transform12(R){const T=zeros(12);for(const base of [0,3,6,9])for(let i=0;i<3;i++)for(let j=0;j<3;j++)T[base+i][base+j]=R[i][j];return T}
function chainStiffness(kl,T,O){return mm(transpose(O),mm(transpose(T),mm(kl,mm(T,O))))}

export function createRigidOffsetFrame2DComponent({element,project}){
  if(!project)throw new Error(`RigidOffsetFrame2D ${element?.id||'(sem id)'}: project é obrigatório.`);assertNoElementLoads(project,element,'RigidOffsetFrame2D');const na=nodeFor(project,element.n1,element.id),nb=nodeFor(project,element.n2,element.id),pa=[Number(na.x),Number(na.y)],pb=[Number(nb.x),Number(nb.y)],ends=deformableEnds(pa,pb,offset2(element.offset1),offset2(element.offset2),element.rigidZone1,element.rigidZone2,element.id),rA=sub(ends.a,pa),rB=sub(ends.b,pb),L=norm(sub(ends.b,ends.a)),d=sub(ends.b,ends.a),c=d[0]/L,s=d[1]/L,material=materialFor(project,element),section=sectionFor(project,element),E=positive('E',material.E,element.id),A=positive('A',property(element,section,'A'),element.id),I=positive('I',property(element,section,'I'),element.id),kl=frameLocalStiffness(E,A,I,L),T=frameTransform(c,s),O=rigidArm2D(rA,rB),kg=chainStiffness(kl,T,O),externalForce=Array(6).fill(0);
  return createElementComponent({id:element.id,type:element.type,dofs:elementDofs(element,['ux','uy','rz']),metadata:{dimension:'2d',family:'frame-rigid-offset',linear:true},evaluate:({u})=>{const ue=matVec(O,u),ul=matVec(T,ue),endForces=matVec(kl,ul),internalForce=matVec(kg,u);return{tangent:kg,residual:subtract(internalForce,externalForce),internalForce,externalForce,outputs:{deformableLength:L,offsetLineLength:ends.offsetLineLength,rigidZone1:ends.rigidZone1,rigidZone2:ends.rigidZone2,rigidArms:{n1:{x:rA[0],y:rA[1]},n2:{x:rB[0],y:rB[1]}},deformableEnds:{n1:{x:ends.a[0],y:ends.a[1]},n2:{x:ends.b[0],y:ends.b[1]}},localDisplacements:ul,endForces,properties:{E,A,I}}}}});
}

export function createRigidOffsetFrame3DComponent({element,project}){
  if(!project)throw new Error(`RigidOffsetFrame3D ${element?.id||'(sem id)'}: project é obrigatório.`);assertNoElementLoads(project,element,'RigidOffsetFrame3D');const na=nodeFor(project,element.n1,element.id),nb=nodeFor(project,element.n2,element.id),pa=[Number(na.x),Number(na.y),Number(na.z||0)],pb=[Number(nb.x),Number(nb.y),Number(nb.z||0)],ends=deformableEnds(pa,pb,offset3(element.offset1),offset3(element.offset2),element.rigidZone1,element.rigidZone2,element.id),rA=sub(ends.a,pa),rB=sub(ends.b,pb),ea={x:ends.a[0],y:ends.a[1],z:ends.a[2]},eb={x:ends.b[0],y:ends.b[1],z:ends.b[2]},axes=spatialAxes(ea,eb,element),material=materialFor(project,element),section=sectionFor(project,element),E=positive('E',material.E,element.id),nu=Number(material.nu),G=positive('G',material.G??(Number.isFinite(nu)?E/(2*(1+nu)):NaN),element.id),A=positive('A',property(element,section,'A'),element.id),Iy=positive('Iy',property(element,section,'Iy',property(element,section,'I')),element.id),Iz=positive('Iz',property(element,section,'Iz',property(element,section,'I')),element.id),J=positive('J',property(element,section,'J'),element.id),kl=frame3DLocalStiffness({E,G,A,Iy,Iz,J,L:axes.L}),T=transform12(axes.R),O=rigidArm3D(rA,rB),kg=chainStiffness(kl,T,O),externalForce=Array(12).fill(0);
  return createElementComponent({id:element.id,type:element.type,dofs:elementDofs(element,['ux','uy','uz','rx','ry','rz']),metadata:{dimension:'3d',family:'frame-rigid-offset',linear:true},evaluate:({u})=>{const ue=matVec(O,u),ul=matVec(T,ue),endForces=matVec(kl,ul),internalForce=matVec(kg,u);return{tangent:kg,residual:subtract(internalForce,externalForce),internalForce,externalForce,outputs:{deformableLength:axes.L,offsetLineLength:ends.offsetLineLength,rigidZone1:ends.rigidZone1,rigidZone2:ends.rigidZone2,rigidArms:{n1:{x:rA[0],y:rA[1],z:rA[2]},n2:{x:rB[0],y:rB[1],z:rB[2]}},deformableEnds:{n1:ea,n2:eb},localAxes:axes,localDisplacements:ul,endForces,properties:{E,G,A,Iy,Iz,J}}}}});
}
