import{buildingLevelInventory}from'./marketParityAdvanced.js';
import{foundationDecisionDashboard}from'../foundation/dashboard.js';

export const ELU_ELS_DASHBOARD_CONTRACT='building-elu-els-dashboard/v1';
export const ELU_ELS_DASHBOARD_VERSION='0.53.7-exp';
const PRIORITY={FAIL:0,INVALID:1,PENDING:2,READY_FOR_REVIEW:3};
const finite=v=>v!==''&&v!==null&&v!==undefined&&Number.isFinite(Number(v))?Number(v):null;
const text=(v,f='')=>String(v??f);
const norm=s=>text(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const nodeIds=e=>Array.isArray(e?.nodeIds)&&e.nodeIds.length?e.nodeIds:[e?.n1,e?.n2,e?.n3,e?.n4].filter(Boolean);
const latestResult=(project,resultInput)=>resultInput||project?.results||project?.lastResult||project?.analysisResults||null;
const unique=a=>[...new Set(a.filter(Boolean).map(String))];
function resultNature(result){const k=norm(`${result?.analysisType||''} ${result?.type||''}`);return /modal|buckling|eigen/.test(k)?'eigen-shape':'physical'}
function explicitTarget(raw,context=null){for(const v of[raw?.elementId,raw?.memberId,raw?.targetId,raw?.entityId,raw?.objectId,raw?.details?.elementId,raw?.details?.memberId,raw?.details?.targetId,raw?.metadata?.elementId])if(v!==null&&v!==undefined&&v!=='')return String(v);return context==null?null:String(context)}
function checkState(raw){if(raw?.ok===true)return'PASS';if(raw?.ok===false)return'FAIL';const s=norm(raw?.status||raw?.state);if(/invalid/.test(s))return'INVALID';if(/fail|reprov/.test(s))return'FAIL';if(/pass|aprov/.test(s)||s==='ok')return'PASS';if(/pending|pendente|nao aval|not evaluated/.test(s))return'PENDING';if(raw?.contract==='code-design-check/v1'&&finite(raw?.utilization)!=null)return Math.abs(Number(raw.utilization))<=1+1e-12?'PASS':'FAIL';return'PENDING'}
function classifyLimitState(raw){const explicit=norm(raw?.limitStateCategory||raw?.limitStateType||raw?.details?.limitStateCategory||raw?.details?.limitStateType||raw?.metadata?.limitStateCategory);if(/^(elu|uls|ultimate)$/.test(explicit)||/\b(elu|uls|ultimate)\b/.test(explicit))return{category:'ELU',source:'explicit'};if(/^(els|sls|serviceability)$/.test(explicit)||/\b(els|sls|serviceability)\b/.test(explicit))return{category:'ELS',source:'explicit'};const hay=norm(`${raw?.id||''} ${raw?.discipline||''} ${raw?.limitState||''} ${raw?.label||''} ${raw?.description||''}`);if(/service|deflect|desloc|drift|crack|fiss|vibr|settle|recal|opening|flecha|deformacao excess/.test(hay))return{category:'ELS',source:'semantic'};if(/flex|shear|cisal|punch|puncao|compression|compress|tension|tracao|buckl|flamb|stability|estabil|yield|escoam|bearing|apoio|sliding|desliz|overturn|tomb|strength|resistance|resistencia|capacity|capacidade|interaction|interacao|torsion|torcao|axial/.test(hay))return{category:'ELU',source:'semantic'};return{category:'UNKNOWN',source:'unknown'}}
function normalizeCheck(raw,contextElementId=null,combinationId=null,fallbackId='check'){const c=classifyLimitState(raw),util=finite(raw?.utilization);return{id:text(raw?.id,fallbackId),elementId:explicitTarget(raw,contextElementId),combinationId:text(raw?.combinationId??combinationId)||null,discipline:text(raw?.discipline),limitState:text(raw?.limitState||raw?.label||raw?.id,'Verificação'),category:c.category,categorySource:c.source,status:checkState(raw),utilization:util,demand:finite(raw?.demand),resistance:finite(raw?.resistance),unit:text(raw?.unit,'-'),code:text(raw?.code||raw?.profile?.code),profileId:text(raw?.profileId||raw?.profile?.id),clause:raw?.clause??null,sourceContract:text(raw?.contract),raw};}
function isCheck(v){return!!v&&typeof v==='object'&&(v.contract==='code-design-check/v1'||(v.limitState!=null&&('ok'in v||'utilization'in v||'demand'in v||'resistance'in v)))}
function collectFrom(value,contextElementId,out,seen,combinationId=null){if(value==null)return;if(Array.isArray(value)){for(const v of value)collectFrom(v,contextElementId,out,seen,combinationId);return}if(typeof value!=='object')return;if(seen.has(value))return;seen.add(value);const target=explicitTarget(value,contextElementId),combo=value.combinationId??combinationId;if(isCheck(value)){out.push(normalizeCheck(value,target,combo,`check-${out.length+1}`));return}for(const key of['checks','codeChecks','designChecks','verificationResults','verifications','result','results','cases','items'])if(value[key]!=null)collectFrom(value[key],target,out,seen,combo)}
function collectChecks(project){const out=[],seen=new Set();for(const key of['codeChecks','designChecks','verificationResults','codeDesign','codeDesignResults','designResults'])collectFrom(project?.[key],null,out,seen,null);for(const e of project?.elements||[])for(const key of['codeChecks','designChecks','verificationResults','codeDesign','designResults'])collectFrom(e?.[key],String(e.id),out,seen,null);const dedup=new Map();for(const c of out){const k=[c.elementId||'',c.id,c.combinationId||'',c.category,c.status,c.utilization??''].join('|');if(!dedup.has(k))dedup.set(k,c)}return[...dedup.values()]}
function categorySummary(checks,category){const rows=checks.filter(c=>c.category===category),invalid=rows.filter(c=>c.status==='INVALID'),fail=rows.filter(c=>c.status==='FAIL'),pending=rows.filter(c=>c.status==='PENDING'),evaluated=rows.filter(c=>finite(c.utilization)!=null),governing=evaluated.length?evaluated.reduce((a,b)=>Math.abs(Number(b.utilization))>Math.abs(Number(a.utilization))?b:a):null;const status=invalid.length?'INVALID':fail.length?'FAIL':!rows.length||pending.length?'PENDING':'PASS';return{category,status,count:rows.length,pass:rows.filter(c=>c.status==='PASS').length,fail:fail.length,pending:pending.length,invalid:invalid.length,maxUtilization:governing?.utilization??null,governingCheckId:governing?.id??null,governingLimitState:governing?.limitState??null,checks:rows}}
function displacementRows(result){if(!result)return[];return result.totalDisplacements||result.displacements||result.combined?.displacements||result.peakDisplacements||[]}
function responseForElement(project,result,element){const nature=resultNature(result),ids=nodeIds(element).map(String),dmap=new Map(displacementRows(result).map(d=>[String(d.nodeId),d])),ds=ids.map(id=>dmap.get(id)).filter(Boolean),mag=d=>Math.hypot(Number(d?.ux)||0,Number(d?.uy)||0,Number(d?.uz)||0),uMax=ds.length?Math.max(...ds.map(mag))*1000:null;let relativeEnd=null;if(ids.length>=2){const a=dmap.get(ids[0]),b=dmap.get(ids.at(-1));if(a&&b)relativeEnd=1000*Math.hypot((Number(b.ux)||0)-(Number(a.ux)||0),(Number(b.uy)||0)-(Number(a.uy)||0),(Number(b.uz)||0)-(Number(a.uz)||0))}const forces=(result?.elementForces||[]).filter(f=>String(f.elementId)===String(element.id));const maxAbs=keys=>{let m=null;for(const f of forces)for(const key of keys){const parts=key.split('.');let v=f;for(const p of parts)v=v?.[p];const n=finite(v);if(n!=null)m=m==null?Math.abs(n):Math.max(m,Math.abs(n))}return m};const shell=String(element.type)==='shell4';const force=shell?{kind:'shell',membraneKNm:maxAbs(['membraneResultants.Nx','membraneResultants.Ny','membraneResultants.Nxy']),bendingKNmPerM:maxAbs(['bendingMoments.Mx','bendingMoments.My','bendingMoments.Mxy']),shearKNm:maxAbs(['transverseShear.Qx','transverseShear.Qy'])}:{kind:'bar',axialKN:maxAbs(['N1','N2','axialForce']),shearKN:maxAbs(['Vy1','Vy2','Vz1','Vz2']),momentKNm:maxAbs(['My1','My2','Mz1','Mz2']),torsionKNm:maxAbs(['T1','T2'])};const state=!result?'PENDING':nature==='eigen-shape'?'MODE_ONLY':ds.length?'READY':'PENDING';return{state,nature,analysisType:text(result?.analysisType||result?.type),uMaxMm:nature==='physical'?uMax:null,relativeEndMm:nature==='physical'?relativeEnd:null,nodeResponses:nature==='physical'?ds.length:0,force}}
function globalStability(project,result){const vals=[result?.buckling?.criticalFactor,result?.buckling?.lambdaCr,result?.stability?.criticalFactor,result?.criticalLoadFactor,result?.lambdaCr,project?.stabilityResults?.criticalFactor,project?.bucklingResult?.criticalFactor];let lambdaCr=null;for(const v of vals){const n=finite(v);if(n!=null){lambdaCr=n;break}}return{analysisType:text(result?.analysisType||project?.settings?.analysisType),secondOrder:/pdelta|corotational/.test(norm(result?.analysisType||project?.settings?.analysisType)),lambdaCr}}
function rowStatus(checks,elu,els,response){if(checks.some(c=>c.status==='FAIL'))return'FAIL';if(checks.some(c=>c.status==='INVALID')||elu.status==='INVALID'||els.status==='INVALID')return'INVALID';const unknownBlocking=checks.some(c=>c.category==='UNKNOWN'&&['PENDING','INVALID','FAIL'].includes(c.status));return elu.status==='PASS'&&els.status==='PASS'&&response.state==='READY'&&!unknownBlocking?'READY_FOR_REVIEW':'PENDING'}
function counts(rows){return{count:rows.length,fail:rows.filter(r=>r.status==='FAIL').length,invalid:rows.filter(r=>r.status==='INVALID').length,pending:rows.filter(r=>r.status==='PENDING').length,readyForReview:rows.filter(r=>r.status==='READY_FOR_REVIEW').length}}
function aggregateTree(rows,inventory,result){const levelMeta=new Map((inventory.levels||[]).map(l=>[String(l.id),l])),ids=[];for(const r of rows)if(!ids.includes(String(r.levelId)))ids.push(String(r.levelId));const tree=ids.map(id=>{const items=rows.filter(r=>String(r.levelId)===id),meta=levelMeta.get(id),groups=[...new Set(items.map(r=>r.group))].map(group=>{const rs=items.filter(r=>r.group===group),worst=rs.reduce((a,b)=>PRIORITY[b.status]<PRIORITY[a.status]?b:a,rs[0]);return{id:group,status:worst?.status||'PENDING',...counts(rs)}});const worst=items.reduce((a,b)=>PRIORITY[b.status]<PRIORITY[a.status]?b:a,items[0]);const drift=(result?.storyDrifts||[]).find(d=>String(d.levelId??d.storyId??d.id)===id||text(d.name)===text(meta?.name));return{id,name:id==='FOUNDATION'?'Fundações':text(meta?.name,items[0]?.levelLabel||id),elevation:id==='FOUNDATION'?null:finite(meta?.elevation),status:worst?.status||'PENDING',...counts(items),groups,drift:drift||null}});return tree.sort((a,b)=>a.id==='FOUNDATION'?-1:b.id==='FOUNDATION'?1:(a.elevation??1e9)-(b.elevation??1e9))}

export function buildingEluElsDashboard(project={},resultInput=null){const inventory=buildingLevelInventory(project),result=latestResult(project,resultInput),nature=resultNature(result),stability=globalStability(project,result),checks=collectChecks(project),checksByElement=new Map();for(const c of checks){if(!c.elementId)continue;const arr=checksByElement.get(String(c.elementId))||[];arr.push(c);checksByElement.set(String(c.elementId),arr)}const elementById=new Map((project.elements||[]).map(e=>[String(e.id),e]));const rows=[];for(const level of inventory.levels||[])for(const item of level.items||[]){const element=elementById.get(String(item.id));if(!element)continue;const mapped=checksByElement.get(String(item.id))||[],elu=categorySummary(mapped,'ELU'),els=categorySummary(mapped,'ELS'),response=responseForElement(project,result,element),unknown=mapped.filter(c=>c.category==='UNKNOWN'),governing=mapped.filter(c=>finite(c.utilization)!=null).sort((a,b)=>Math.abs(Number(b.utilization))-Math.abs(Number(a.utilization)))[0]||null,status=rowStatus(mapped,elu,els,response),issues=[];if(!elu.count)issues.push('Nenhuma verificação ELU explicitamente mapeada para o elemento.');if(!els.count)issues.push('Nenhuma verificação ELS explicitamente mapeada para o elemento.');if(elu.pending)issues.push('Há verificação ELU pendente.');if(els.pending)issues.push('Há verificação ELS pendente.');if(unknown.length)issues.push(`${unknown.length} verificação(ões) sem classificação ELU/ELS; permanecem fora dos subtotais.`);if(response.state==='PENDING')issues.push('Não há resposta física nodal corrente para este elemento.');if(response.state==='MODE_ONLY')issues.push('O resultado corrente é forma própria normalizada e não representa deformação física em mm.');rows.push({contract:'building-elu-els-row/v1',version:ELU_ELS_DASHBOARD_VERSION,rowId:`element:${item.id}`,entityKind:'element',entityId:String(item.id),label:text(element.label||element.name,item.id),type:text(element.type),group:item.group,levelId:String(item.levelId||level.id),levelLabel:item.levelLabel||level.name,status,elu,els,unknownChecks:unknown,checks:mapped,governing:governing?{id:governing.id,limitState:governing.limitState,category:governing.category,utilization:governing.utilization,combinationId:governing.combinationId}:null,response,stability,issues:unique(issues)})}
  let foundation={rows:[],summary:{count:0}},foundationError=null;try{foundation=foundationDecisionDashboard(project,result)}catch(e){foundationError=String(e?.message||e)}for(const f of foundation.rows||[]){const els={category:'ELS',status:'PENDING',count:0,pass:0,fail:0,pending:1,invalid:0,maxUtilization:null,governingCheckId:null,governingLimitState:null,checks:[]},elu={category:'ELU',status:f.normative.status,count:f.normative.pass+f.normative.fail+f.normative.pending,pass:f.normative.pass,fail:f.normative.fail,pending:f.normative.pending,invalid:0,maxUtilization:f.normative.maxUtilization,governingCheckId:null,governingLimitState:f.normative.governing,checks:[]},response={state:f.ssi.state==='READY'?'READY':f.ssi.state==='MODE_ONLY'?'MODE_ONLY':'PENDING',nature:f.ssi.state==='MODE_ONLY'?'eigen-shape':'physical',analysisType:stability.analysisType,uMaxMm:f.ssi.settlementMm==null?null:Math.abs(Number(f.ssi.settlementMm)),relativeEndMm:null,nodeResponses:f.ssi.settlementMm==null?0:1,force:{kind:'foundation',verticalReactionKN:f.ssi.verticalReactionKN,averageContactPressureKPa:f.ssi.averageContactPressureKPa}},issues=[...f.issues,'Critério ELS explícito de recalque/serviço ainda não foi cadastrado neste dashboard; resposta SSI isolada não equivale a PASS ELS.'];const status=f.status==='FAIL'?'FAIL':f.status==='INVALID'?'INVALID':'PENDING';rows.push({contract:'building-elu-els-row/v1',version:ELU_ELS_DASHBOARD_VERSION,rowId:`foundation:${f.foundationId}`,entityKind:f.nodeId?'node':'foundation',entityId:f.nodeId||f.foundationId,foundationId:f.foundationId,label:f.label,type:f.type,group:'foundation',levelId:'FOUNDATION',levelLabel:'Fundações',status,elu,els,unknownChecks:[],checks:[],governing:f.normative.governing?{id:null,limitState:f.normative.governing,category:'ELU',utilization:f.normative.maxUtilization,combinationId:null}:null,response,stability,foundationDecisionStatus:f.status,foundationEvidence:f,issues:unique(issues)})}
  rows.sort((a,b)=>PRIORITY[a.status]-PRIORITY[b.status]||String(a.levelLabel).localeCompare(String(b.levelLabel))||String(a.label).localeCompare(String(b.label)));const tree=aggregateTree(rows,inventory,result),summary={...counts(rows),elements:rows.filter(r=>r.group!=='foundation').length,foundations:rows.filter(r=>r.group==='foundation').length,eluPass:rows.filter(r=>r.elu.status==='PASS').length,elsPass:rows.filter(r=>r.els.status==='PASS').length,physicalResponseReady:rows.filter(r=>r.response.state==='READY').length,levels:tree.length,checkCount:checks.length,unmappedChecks:checks.filter(c=>!c.elementId).length};return{contract:ELU_ELS_DASHBOARD_CONTRACT,version:ELU_ELS_DASHBOARD_VERSION,rows,tree,summary,analysis:{available:!!result,nature,analysisType:text(result?.analysisType||result?.type||project?.settings?.analysisType),stability},foundationError,governance:{missingCheckNeverPasses:true,missingElsNeverPasses:true,eigenShapesAreNotPhysicalDeformations:true,limitStateClassification:'explicit metadata first; semantic classification only for known engineering terms; unknown checks remain unclassified',resistanceRecalculation:false,foundationSsiResponseIsNotElsApproval:true,integratedApproval:false}}}
