import{deriveLevels}from'../core/levels.js';
import{designBasisFromProject}from'./marketParity.js';

export const ENGINEERING_PROFILE_VERSION='0.53.2-exp';
export const DURABILITY_PROFILE_CONTRACT='durability-profile/v1';
export const DURABILITY_AUDIT_CONTRACT='durability-audit/v1';
export const WIND_PROFILE_CONTRACT='wind-method-profile/v1';
export const WIND_AUDIT_CONTRACT='wind-audit/v1';
export const WIND_GENERATION_CONTRACT='generated-wind-loads/v1';
const clone=v=>v==null?v:typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));
const finite=v=>v!==''&&v!==null&&v!==undefined&&Number.isFinite(Number(v))?Number(v):null;
const text=(v,f='')=>String(v??f);
const safe=s=>text(s,'ID').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').toUpperCase()||'ID';
const FAMILY_PATH={beam:'beamFckMpa',slab:'slabFckMpa',column:'columnFckMpa',wall:'wallFckMpa',foundation:'foundationFckMpa'};
export const STRUCTURAL_FAMILIES=Object.freeze([{id:'beam',label:'Vigas'},{id:'slab',label:'Lajes'},{id:'column',label:'Pilares'},{id:'wall',label:'Paredes'},{id:'foundation',label:'Fundações'}]);

export const DURABILITY_PROFILE_SKELETONS=Object.freeze([
 {id:'BR-NBR6118-2023',contract:DURABILITY_PROFILE_CONTRACT,version:ENGINEERING_PROFILE_VERSION,jurisdiction:'BR',standard:'ABNT NBR 6118',edition:'2023',label:'ABNT NBR 6118:2023 · perfil parametrizado pelo responsável',rules:[],provenance:{embeddedNormativeTables:false,requiresLicensedStandard:true}},
 {id:'US-ACI318-25',contract:DURABILITY_PROFILE_CONTRACT,version:ENGINEERING_PROFILE_VERSION,jurisdiction:'US',standard:'ACI CODE-318',edition:'2025',label:'ACI CODE-318-25 · perfil parametrizado pelo responsável',rules:[],provenance:{embeddedNormativeTables:false,requiresLicensedStandard:true}},
 {id:'EU-EN1992-1-1',contract:DURABILITY_PROFILE_CONTRACT,version:ENGINEERING_PROFILE_VERSION,jurisdiction:'EU',standard:'EN 1992-1-1 / National Annex',edition:null,label:'EN 1992-1-1 + Anexo Nacional · perfil parametrizado',rules:[],provenance:{embeddedNormativeTables:false,requiresLicensedStandard:true,nationalAnnexRequired:true}}
]);
export const WIND_PROFILE_SKELETONS=Object.freeze([
 {id:'BR-NBR6123-2023',contract:WIND_PROFILE_CONTRACT,version:ENGINEERING_PROFILE_VERSION,jurisdiction:'BR',standard:'ABNT NBR 6123',edition:'2023',label:'ABNT NBR 6123:2023 · fatores informados',method:'velocity-factor-force',required:['basicSpeedMS','s1','s2','s3','forceCoefficient'],provenance:{embeddedNormativeTables:false,requiresLicensedStandard:true}},
 {id:'US-ASCE7-22',contract:WIND_PROFILE_CONTRACT,version:ENGINEERING_PROFILE_VERSION,jurisdiction:'US',standard:'ASCE/SEI 7',edition:'2022',label:'ASCE/SEI 7-22 · pressão por nível informada',method:'direct-story-pressure',required:['pressureKPa','forceCoefficient'],provenance:{embeddedNormativeTables:false,requiresLicensedStandard:true}},
 {id:'EU-EN1991-1-4',contract:WIND_PROFILE_CONTRACT,version:ENGINEERING_PROFILE_VERSION,jurisdiction:'EU',standard:'EN 1991-1-4 / National Annex',edition:null,label:'EN 1991-1-4 + Anexo Nacional · pressão por nível informada',method:'direct-story-pressure',required:['pressureKPa','forceCoefficient'],provenance:{embeddedNormativeTables:false,requiresLicensedStandard:true,nationalAnnexRequired:true}}
]);
export function profileSkeleton(kind,id){const rows=kind==='wind'?WIND_PROFILE_SKELETONS:DURABILITY_PROFILE_SKELETONS;return clone(rows.find(x=>x.id===id)||rows[0]);}
export function engineeringProfilesFromProject(project={}){const stored=project.engineeringProfiles||{};return{durability:stored.durability?clone(stored.durability):profileSkeleton('durability','BR-NBR6118-2023'),wind:stored.wind?clone(stored.wind):profileSkeleton('wind','BR-NBR6123-2023'),windConfig:clone(stored.windConfig||defaultWindConfig())}}
export function withEngineeringProfiles(project,profiles){const p=clone(project||{});p.engineeringProfiles={durability:normalizeDurabilityProfile(profiles?.durability),wind:normalizeWindProfile(profiles?.wind),windConfig:normalizeWindConfig(profiles?.windConfig)};return p}
export function normalizeDurabilityProfile(profile={}){return{contract:DURABILITY_PROFILE_CONTRACT,version:ENGINEERING_PROFILE_VERSION,id:text(profile.id,'CUSTOM-DURABILITY'),jurisdiction:text(profile.jurisdiction),standard:text(profile.standard,'Norma definida pelo responsável'),edition:profile.edition==null?null:text(profile.edition),label:text(profile.label,profile.standard||'Perfil de durabilidade'),rules:Array.from(profile.rules||[],normalizeDurabilityRule),provenance:{embeddedNormativeTables:false,requiresLicensedStandard:true,...clone(profile.provenance||{})}}}
export function normalizeDurabilityRule(rule={},i=0){return{id:text(rule.id,`R${i+1}`),exposureClass:text(rule.exposureClass,'*'),family:STRUCTURAL_FAMILIES.some(x=>x.id===rule.family)?rule.family:'beam',minFckMpa:finite(rule.minFckMpa),nominalCoverMm:finite(rule.nominalCoverMm),note:text(rule.note),clause:rule.clause==null?null:text(rule.clause),source:'user-supplied-rule'}}
export function normalizeWindProfile(profile={}){const method=profile.method==='direct-story-pressure'?'direct-story-pressure':'velocity-factor-force';return{contract:WIND_PROFILE_CONTRACT,version:ENGINEERING_PROFILE_VERSION,id:text(profile.id,'CUSTOM-WIND'),jurisdiction:text(profile.jurisdiction),standard:text(profile.standard,'Norma de vento definida pelo responsável'),edition:profile.edition==null?null:text(profile.edition),label:text(profile.label,profile.standard||'Perfil de vento'),method,required:Array.from(profile.required||[],String),provenance:{embeddedNormativeTables:false,requiresLicensedStandard:true,...clone(profile.provenance||{})}}}
export function defaultWindConfig(){return{directions:['X+','X-','Y+','Y-'],airDensityKgM3:1.225,basicSpeedMS:null,s1:null,s2:null,s3:null,neighborhoodFactor:null,acceptBoundingBoxArea:false,forceCoefficients:{'X+':null,'X-':null,'Y+':null,'Y-':null},storyOverrides:{},notes:''}}
export function normalizeWindConfig(v={}){const d=defaultWindConfig();return{...d,...clone(v),directions:(Array.isArray(v.directions)?v.directions:d.directions).filter(x=>['X+','X-','Y+','Y-'].includes(x)),airDensityKgM3:finite(v.airDensityKgM3)??1.225,basicSpeedMS:finite(v.basicSpeedMS),s1:finite(v.s1),s2:finite(v.s2),s3:finite(v.s3),neighborhoodFactor:finite(v.neighborhoodFactor),acceptBoundingBoxArea:v.acceptBoundingBoxArea===true,forceCoefficients:{...d.forceCoefficients,...clone(v.forceCoefficients||{})},storyOverrides:clone(v.storyOverrides||{})}}
function matchRule(profile,exposure,family){const exact=profile.rules.find(r=>r.family===family&&String(r.exposureClass).toLowerCase()===String(exposure).toLowerCase()),wild=profile.rules.find(r=>r.family===family&&r.exposureClass==='*');return exact||wild||null}
export function evaluateDurabilityBasis(projectOrBasis={},profileInput=null){const basis=projectOrBasis?.contract==='building-design-basis/v1'?projectOrBasis:designBasisFromProject(projectOrBasis),profile=normalizeDurabilityProfile(profileInput||engineeringProfilesFromProject(projectOrBasis).durability),exposure=basis?.durability?.exposureClass,rows=STRUCTURAL_FAMILIES.map(f=>{const rule=matchRule(profile,exposure,f.id),fck=finite(basis?.durability?.concrete?.[FAMILY_PATH[f.id]]),cover=finite(basis?.durability?.coversMm?.[f.id]);if(!exposure)return{family:f.id,label:f.label,status:'PENDING',message:'Classe de exposição/agressividade não informada.',rule};if(!rule)return{family:f.id,label:f.label,status:'PENDING',message:'Nenhuma regra do perfil corresponde à exposição e família.',rule:null};const checks=[];if(rule.minFckMpa==null)checks.push({id:'fck',ok:null,message:'fck mínimo não parametrizado no perfil.'});else if(fck==null)checks.push({id:'fck',ok:null,message:'fck do projeto não informado.'});else checks.push({id:'fck',ok:fck>=rule.minFckMpa,demand:rule.minFckMpa,provided:fck,unit:'MPa'});if(rule.nominalCoverMm==null)checks.push({id:'cover',ok:null,message:'Cobrimento nominal não parametrizado no perfil.'});else if(cover==null)checks.push({id:'cover',ok:null,message:'Cobrimento do projeto não informado.'});else checks.push({id:'cover',ok:cover>=rule.nominalCoverMm,demand:rule.nominalCoverMm,provided:cover,unit:'mm'});return{family:f.id,label:f.label,status:checks.some(c=>c.ok===false)?'FAIL':checks.some(c=>c.ok===null)?'PENDING':'PASS',rule,checks}}),status=rows.some(r=>r.status==='FAIL')?'FAIL':rows.some(r=>r.status==='PENDING')?'PENDING':'PASS';return{contract:DURABILITY_AUDIT_CONTRACT,version:ENGINEERING_PROFILE_VERSION,profile,basisExposure:exposure||null,status,rows,summary:{pass:rows.filter(r=>r.status==='PASS').length,fail:rows.filter(r=>r.status==='FAIL').length,pending:rows.filter(r=>r.status==='PENDING').length},governance:{normativeTablesEmbedded:false,profileRulesUserSupplied:true}}}
function levelNodes(project,level){const tol=1e-5;return(project.nodes||[]).filter(n=>String(n.levelId||'')===String(level.id)||Math.abs((Number(n.z)||0)-Number(level.elevation))<=tol)}
function overallBounds(project){const ns=project.nodes||[],xs=ns.map(n=>Number(n.x)||0),ys=ns.map(n=>Number(n.y)||0);return{dx:Math.max(.001,Math.max(...xs,0)-Math.min(...xs,0)),dy:Math.max(.001,Math.max(...ys,0)-Math.min(...ys,0))}}
function storyRows(project){const levels=deriveLevels(project).sort((a,b)=>a.elevation-b.elevation),bounds=overallBounds(project);return levels.slice(1).map((l,i)=>{const lower=levels[i],height=Math.max(0,Number(l.elevation)-Number(lower.elevation));return{id:String(l.id),name:String(l.name),elevation:Number(l.elevation),heightM:height,nodes:levelNodes(project,l),autoWidthX:bounds.dy,autoWidthY:bounds.dx}})}
function overrideFor(config,levelId,direction){return config.storyOverrides?.[levelId]?.[direction]||{}}
function velocityPressureKPa(config){const vals=[config.basicSpeedMS,config.s1,config.s2,config.s3];if(vals.some(v=>finite(v)==null))return null;const fv=finite(config.neighborhoodFactor)??1,v=Number(config.basicSpeedMS)*Number(config.s1)*Number(config.s2)*Number(config.s3)*fv,rho=finite(config.airDensityKgM3)??1.225;return .5*rho*v*v/1000}
export function windAuditFromProject(project={},profileInput=null,configInput=null){const profiles=engineeringProfilesFromProject(project),profile=normalizeWindProfile(profileInput||profiles.wind),config=normalizeWindConfig(configInput||profiles.windConfig),stories=storyRows(project),rows=[];for(const direction of config.directions){for(const story of stories){const ov=overrideFor(config,story.id,direction),cf=finite(ov.forceCoefficient)??finite(config.forceCoefficients?.[direction]),pressure=profile.method==='velocity-factor-force'?velocityPressureKPa(config):finite(ov.pressureKPa),autoArea=(direction[0]==='X'?story.autoWidthX:story.autoWidthY)*story.heightM,explicitArea=finite(ov.projectedAreaM2),area=explicitArea??(config.acceptBoundingBoxArea?autoArea:null),missing=[];if(pressure==null)missing.push(profile.method==='velocity-factor-force'?'V0/S1/S2/S3':'pressão do nível');if(cf==null)missing.push('coeficiente de força/arrasto');if(area==null)missing.push('área projetada aceita ou informada');if(!story.nodes.length)missing.push('nós no pavimento');const ready=!missing.length,force=ready?pressure*cf*area:null;rows.push({id:`${direction}-${story.id}`,direction,levelId:story.id,levelName:story.name,elevation:story.elevation,heightM:story.heightM,pressureKPa:pressure,forceCoefficient:cf,projectedAreaM2:area,autoProjectedAreaM2:autoArea,areaSource:explicitArea!=null?'explicit':config.acceptBoundingBoxArea?'axis-aligned-bounds':'pending',nodeIds:story.nodes.map(n=>n.id),forceKN:force,status:ready?'READY':'PENDING',missing})}}const ready=rows.filter(r=>r.status==='READY').length;return{contract:WIND_AUDIT_CONTRACT,version:ENGINEERING_PROFILE_VERSION,profile,config,rows,summary:{rows:rows.length,ready,pending:rows.length-ready,totalForceByDirection:Object.fromEntries(config.directions.map(d=>[d,rows.filter(r=>r.direction===d&&r.forceKN!=null).reduce((s,r)=>s+r.forceKN,0)]))},governance:{normativeTablesEmbedded:false,automaticAreaRequiresExplicitAcceptance:true,irregularGeometryRequiresReview:true}}}
function directionVector(direction,force){const s=direction.endsWith('-')?-1:1;return direction[0]==='X'?{fx:s*force,fy:0,fz:0}:{fx:0,fy:s*force,fz:0}}
export function generateWindLoads(project={},auditInput=null,{replaceGenerated=true}={}){const audit=auditInput?.contract===WIND_AUDIT_CONTRACT?clone(auditInput):windAuditFromProject(project);if(audit.summary.pending)throw new Error(`Wind: ${audit.summary.pending} linha(s) pendente(s). Complete os dados e aceite/revise as áreas antes de gerar cargas.`);const p=clone(project),tag='astrastruct-wind-v0532';if(replaceGenerated){p.loads=(p.loads||[]).filter(l=>l?.metadata?.generator!==tag);p.loadCases=(p.loadCases||[]).filter(c=>c?.metadata?.generator!==tag)}const usedCase=new Set((p.loadCases||[]).map(c=>String(c.id))),usedLoad=new Set((p.loads||[]).map(l=>String(l.id))),cases=[];for(const direction of audit.config.directions){let id=`WIND-${safe(direction)}`,k=2;while(usedCase.has(id))id=`WIND-${safe(direction)}-${k++}`;usedCase.add(id);cases.push({id,name:`Vento ${direction} · ${audit.profile.standard} ${audit.profile.edition||''}`.trim(),type:'wind',metadata:{generator:tag,profileId:audit.profile.id,contract:WIND_GENERATION_CONTRACT,direction}})}p.loadCases=[...(p.loadCases||[]),...cases];const caseMap=new Map(cases.map(c=>[c.metadata.direction,c.id]));for(const row of audit.rows){const share=row.forceKN/row.nodeIds.length,v=directionVector(row.direction,share);for(const nodeId of row.nodeIds){let id=`W-${safe(row.direction)}-${safe(row.levelId)}-${safe(nodeId)}`,k=2;while(usedLoad.has(id))id=`${id}-${k++}`;usedLoad.add(id);p.loads.push({id,caseId:caseMap.get(row.direction),nodeId,...v,mx:0,my:0,mz:0,metadata:{generator:tag,contract:WIND_GENERATION_CONTRACT,profileId:audit.profile.id,direction:row.direction,levelId:row.levelId,storyForceKN:row.forceKN,distributedNodeCount:row.nodeIds.length,pressureKPa:row.pressureKPa,forceCoefficient:row.forceCoefficient,projectedAreaM2:row.projectedAreaM2,areaSource:row.areaSource}})}}p.windAudit={...audit,generatedAt:new Date().toISOString(),generatedCaseIds:cases.map(c=>c.id)};return p}
