import {registerIsolatedLab} from './labRegistry';
import {$,num,fmt,kpi} from './labUi';
// @ts-ignore
import {generateSlipBearingBoltGroup,solveSlipCriticalToBearing} from '../../web/src/solver/connectionSlipBearing2d.js';
// @ts-ignore
import {solveTStubPrying} from '../../web/src/solver/tstubPrying1d.js';
// @ts-ignore
import {makeSymmetricCyclicHistory,solveHoleBearingDamage} from '../../web/src/solver/holeBearingDamage1d.js';
// @ts-ignore
import {solveAnchorConcreteInteraction} from '../../web/src/solver/anchorConcreteInteraction.js';

function chart(points:any[],x:(p:any)=>number,y:(p:any)=>number,title:string,xLabel:string,yLabel:string,testId:string){const W=720,H=320,pad=48,xv=points.map(x),yv=points.map(y),xmin=Math.min(...xv),xmax=Math.max(...xv),ymin=Math.min(0,...yv),ymax=Math.max(...yv),sx=(v:number)=>pad+(v-xmin)/Math.max(1e-12,xmax-xmin)*(W-2*pad),sy=(v:number)=>H-pad-(v-ymin)/Math.max(1e-12,ymax-ymin)*(H-2*pad),pts=points.map(p=>`${sx(x(p)).toFixed(1)},${sy(y(p)).toFixed(1)}`).join(' ');return`<svg class="core-lab-chart react-chart" data-testid="${testId}" viewBox="0 0 ${W} ${H}" role="img"><rect width="${W}" height="${H}" fill="#fff"/><text x="${W/2}" y="22" text-anchor="middle" fill="#17202a" font-size="14" font-weight="700">${title}</text><line x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}" stroke="#657786"/><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${H-pad}" stroke="#657786"/><polyline points="${pts}" fill="none" stroke="#285f9d" stroke-width="2"/><text x="${W/2}" y="${H-9}" text-anchor="middle" fill="#333" font-size="11">${xLabel}</text><text x="14" y="${H/2}" transform="rotate(-90 14 ${H/2})" text-anchor="middle" fill="#333" font-size="11">${yLabel}</text></svg>`}

function openSlip(){const ui=(requireLab as any)({testId:'slip-bearing-lab',title:'Lab · Slip-critical → bearing',subtitle:'pré-tensão · atrito de interface · folga · bearing',warning:'Modelo mecânico. A pré-tensão e μ são entradas do usuário; nenhuma resistência normativa é inferida.',controlsHtml:`<div class="core-lab-form"><label>μ<input data-sb-mu value="0.30"></label><label>Pré-tensão/bolt [kN]<input data-sb-pre value="50"></label><label>Folga radial [mm]<input data-sb-gap value="1"></label><label>k bearing [kN/mm]<input data-sb-k value="200"></label><label>Fx [kN]<input data-sb-fx value="80"></label><label>Passos<input data-sb-steps value="20"></label></div><div class="core-lab-actions"><button class="primary" data-testid="run-slip-bearing" data-sb-run>Executar</button></div>`});$<HTMLButtonElement>('[data-sb-run]',ui.back)!.onclick=()=>{try{const mu=num($<HTMLInputElement>('[data-sb-mu]',ui.back)?.value,.3),pre=num($<HTMLInputElement>('[data-sb-pre]',ui.back)?.value,50),gap=num($<HTMLInputElement>('[data-sb-gap]',ui.back)?.value,1)/1000,k=num($<HTMLInputElement>('[data-sb-k]',ui.back)?.value,200)*1000,Fx=num($<HTMLInputElement>('[data-sb-fx]',ui.back)?.value,80),steps=num($<HTMLInputElement>('[data-sb-steps]',ui.back)?.value,20),bolts=generateSlipBearingBoltGroup({nx:2,ny:2,mu,preload:pre,gap,bearingStiffness:k}),r=solveSlipCriticalToBearing({bolts,loads:{fx:Fx},steps});ui.results.innerHTML=`<h3>Resposta</h3><div class="core-lab-summary">${kpi('ux',`${fmt(r.plateDisplacement.ux*1000,3)} mm`)}${kpi('1º slip',r.events.firstSlip?`λ=${fmt(r.events.firstSlip.lambda,2)}`:'—')}${kpi('1º bearing',r.events.firstBearing?`λ=${fmt(r.events.firstBearing.lambda,2)}`:'—')}${kpi('Resíduo',r.equilibrium.residualNorm.toExponential(2))}</div>${chart(r.history,p=>p.ux*1000,p=>p.maxForce,'Transição slip-critical → bearing','ux [mm]','Vmax por bolt [kN]','slip-bearing-chart')}<table class="core-lab-table" data-testid="slip-bearing-table"><thead><tr><th>Bolt</th><th>Estado</th><th>F atrito</th><th>F bearing</th><th>Total</th></tr></thead><tbody>${r.bolts.map((b:any)=>`<tr><td>${b.id}</td><td>${b.state}</td><td>${fmt(b.frictionForce,2)}</td><td>${fmt(b.bearingForce,2)}</td><td>${fmt(b.force.magnitude,2)}</td></tr>`).join('')}</tbody></table>`}catch(e:any){alert(e?.message||String(e))}}}

function openPrying(){const ui=(requireLab as any)({testId:'tstub-prying-lab',title:'Lab · T-stub / prying',subtitle:'flange fora do plano · parafuso axial · toe unilateral',warning:'Faixa de flange de Euler–Bernoulli com toe por penalidade. Use como modelo de componentes, não como substituto de verificação normativa.',controlsHtml:`<div class="core-lab-form"><label>t chapa [mm]<input data-pr-t value="10"></label><label>m [mm]<input data-pr-m value="60"></label><label>n [mm]<input data-pr-n value="120"></label><label>Uplift máx. [mm]<input data-pr-u value="3"></label><label>Fy bolt [kN]<input data-pr-fy value="100"></label><label>Passos<input data-pr-steps value="20"></label></div><div class="core-lab-actions"><button class="primary" data-testid="run-tstub-prying" data-pr-run>Executar</button></div>`});$<HTMLButtonElement>('[data-pr-run]',ui.back)!.onclick=()=>{try{const r=solveTStubPrying({thickness:num($<HTMLInputElement>('[data-pr-t]',ui.back)?.value,10)/1000,m:num($<HTMLInputElement>('[data-pr-m]',ui.back)?.value,60)/1000,n:num($<HTMLInputElement>('[data-pr-n]',ui.back)?.value,120)/1000,maxUplift:num($<HTMLInputElement>('[data-pr-u]',ui.back)?.value,3)/1000,boltYieldForce:num($<HTMLInputElement>('[data-pr-fy]',ui.back)?.value,100),steps:num($<HTMLInputElement>('[data-pr-steps]',ui.back)?.value,20)}),f=r.final;ui.results.innerHTML=`<h3>Resposta fora do plano</h3><div class="core-lab-summary">${kpi('T aplicada',`${fmt(f.appliedTension,2)} kN`)}${kpi('Tração bolt',`${fmt(f.boltTension,2)} kN`)}${kpi('Prying Q',`${fmt(f.pryingReaction,2)} kN`)}${kpi('Q/T',fmt(f.pryingRatio,3))}${kpi('Toe',f.toeActive?'contato':'aberto')}${kpi('Equilíbrio',f.equilibrium.relative.toExponential(2))}</div>${chart(r.curve,p=>p.upliftMm,p=>p.boltTension,'Prying / T-stub','uplift [mm]','tração no parafuso [kN]','tstub-prying-chart')}`}catch(e:any){alert(e?.message||String(e))}}}

function openDamage(){const ui=(requireLab as any)({testId:'hole-damage-lab',title:'Lab · Dano e ovalização do furo',subtitle:'bearing cíclico · memória plástica bilateral',warning:'Modelo reduzido 1D de dano local. A ovalização permanente é uma variável mecânica interna, não um limite normativo.',controlsHtml:`<div class="core-lab-form"><label>Folga [mm]<input data-dm-gap value="1"></label><label>Amplitude máx. [mm]<input data-dm-a value="3.5"></label><label>k bearing [kN/mm]<input data-dm-k value="200"></label><label>Fy bearing [kN]<input data-dm-fy value="40"></label></div><div class="core-lab-actions"><button class="primary" data-testid="run-hole-damage" data-dm-run>Executar</button></div>`});$<HTMLButtonElement>('[data-dm-run]',ui.back)!.onclick=()=>{try{const a=num($<HTMLInputElement>('[data-dm-a]',ui.back)?.value,3.5)/1000,h=makeSymmetricCyclicHistory({amplitudes:[.0005,.55*a,a]}),r=solveHoleBearingDamage({history:h,config:{gap:num($<HTMLInputElement>('[data-dm-gap]',ui.back)?.value,1)/1000,bearingStiffness:num($<HTMLInputElement>('[data-dm-k]',ui.back)?.value,200)*1000,yieldForce:num($<HTMLInputElement>('[data-dm-fy]',ui.back)?.value,40)}});ui.results.innerHTML=`<h3>Histórico local</h3><div class="core-lab-summary">${kpi('Ovalização permanente',`${fmt(r.permanentOvalizationMm,3)} mm`)}${kpi('Dano',fmt(r.damage,3))}${kpi('Energia dissipada',`${fmt(r.dissipatedEnergy,4)} kN·m`)}</div>${chart(r.path,p=>p.displacementMm,p=>p.force,'Histerese local de bearing','deslocamento [mm]','força [kN]','hole-damage-chart')}`}catch(e:any){alert(e?.message||String(e))}}}

function openAnchorInteraction(){const ui=(requireLab as any)({testId:'anchor-concrete-interaction-lab',title:'Lab · Interação aço–aderência–concreto',subtitle:'componentes em série · modo governante · pós-pico',warning:'As capacidades de aço, aderência e concreto são entradas mecânicas. O cálculo normativo dessas capacidades pertence aos plugins P4.',controlsHtml:`<div class="core-lab-form"><label>Aço [kN]<input data-ac-steel value="120"></label><label>Aderência [kN]<input data-ac-bond value="95"></label><label>Concreto [kN]<input data-ac-conc value="70"></label><label>Fator de borda<input data-ac-edge value="1.0"></label><label>δ máx. [mm]<input data-ac-d value="10"></label></div><div class="core-lab-actions"><button class="primary" data-testid="run-anchor-concrete-interaction" data-ac-run>Executar</button></div>`});$<HTMLButtonElement>('[data-ac-run]',ui.back)!.onclick=()=>{try{const r=solveAnchorConcreteInteraction({steelYield:num($<HTMLInputElement>('[data-ac-steel]',ui.back)?.value,120),steelUltimate:num($<HTMLInputElement>('[data-ac-steel]',ui.back)?.value,120)*1.25,bondPeak:num($<HTMLInputElement>('[data-ac-bond]',ui.back)?.value,95),concretePeak:num($<HTMLInputElement>('[data-ac-conc]',ui.back)?.value,70),edgeFactor:num($<HTMLInputElement>('[data-ac-edge]',ui.back)?.value,1),maxDisplacement:num($<HTMLInputElement>('[data-ac-d]',ui.back)?.value,10)/1000});ui.results.innerHTML=`<h3>Interação de componentes</h3><div class="core-lab-summary">${kpi('Modo governante',r.controllingMode)}${kpi('Pico',`${fmt(r.peakForce,2)} kN`)}${kpi('δ pico',`${fmt(r.peakDisplacement*1000,3)} mm`)}${kpi('K inicial',`${fmt(r.equivalentInitialStiffness/1000,1)} kN/mm`)}</div>${chart(r.curve,p=>p.displacementMm,p=>p.force,'Interação aço–aderência–concreto','deslocamento total [mm]','força [kN]','anchor-concrete-chart')}`}catch(e:any){alert(e?.message||String(e))}}}

import {openCoreLab as requireLab} from './labUi';
registerIsolatedLab({id:'slip-bearing',title:'Ligação · slip → bearing',description:'Pré-tensão, atrito de interface e transição para bearing após consumo da folga.',meta:'P3 · v0.31.0',order:80,testId:'open-slip-bearing-lab',open:openSlip});
registerIsolatedLab({id:'tstub-prying',title:'Ligação · T-stub / prying',description:'Flange fora do plano, parafuso axial e contato unilateral no toe.',meta:'P3 · v0.31.0',order:81,testId:'open-tstub-prying-lab',open:openPrying});
registerIsolatedLab({id:'hole-damage',title:'Furo · dano / ovalização',description:'Bearing cíclico com memória plástica bilateral e perda de rigidez.',meta:'P3 · v0.31.0',order:82,testId:'open-hole-damage-lab',open:openDamage});
registerIsolatedLab({id:'anchor-concrete-interaction',title:'Chumbador · interação concreto',description:'Componentes em série: aço, aderência e cone de concreto com pós-pico.',meta:'P3 · v0.31.0',order:83,testId:'open-anchor-concrete-interaction-lab',open:openAnchorInteraction});
export {};
