import React, { useMemo, useRef, useState } from 'react';
// The numerical engine remains framework-independent.
// @ts-ignore
import { emptyProject, normalizeProject, demoFrame, demoBeamUDL, demoTruss, demoMixed, demoLoadCases } from '../../web/src/core/model.js';
// @ts-ignore
import { solve } from '../../web/src/solver/index.js';
import { EngineeringPanels, type PanelKind } from './EngineeringPanels';

type AnyProject=any;type AnyResult=any;type Drawer='library'|'inspector'|'results'|'menu'|null;
const STORAGE_KEY='astrastruct.project';const VIEW={w:1000,h:680,p:90};

const ICONS:Record<string,React.ReactNode>={
  new:<><path d="M7 3.5h8l4 4V20.5H7z"/><path d="M15 3.5v4h4M13 11v6M10 14h6"/></>,frame:<><path d="M5 20V6h14v14M5 9h14"/><circle cx="5" cy="20" r="1.5"/><circle cx="19" cy="20" r="1.5"/></>,beam:<><path d="M4 16h16M6 19l-2 2M18 19l2 2"/><path d="M8 4v7m0 0-2-3m2 3 2-3M12 4v7m0 0-2-3m2 3 2-3M16 4v7m0 0-2-3m2 3 2-3"/></>,truss:<><path d="M4 19 12 5l8 14H4Z M4 19l8-6 8 6M12 5v8"/><circle cx="4" cy="19" r="1.2"/><circle cx="12" cy="5" r="1.2"/><circle cx="20" cy="19" r="1.2"/></>,mixed:<><path d="M5 20V5h14v15M5 9h14M5 20 19 9"/><circle cx="5" cy="20" r="1.3"/><circle cx="19" cy="20" r="1.3"/></>,cases:<><path d="M5 6h10l4 4v8H5z"/><path d="M8 3h8l4 4v8M8 10h7M8 14h7"/></>,play:<><path d="M8 5.5 18 12 8 18.5Z"/><path d="M4 4v16"/></>,import:<><path d="M5 4h9l4 4v12H5zM14 4v4h4"/><path d="M12 10v7m0-7-3 3m3-3 3 3"/></>,export:<><path d="M5 4h9l4 4v12H5zM14 4v4h4"/><path d="M12 17v-7m0 7-3-3m3 3 3-3"/></>,library:<path d="M4 5.5h5v13H4zM10 5.5h5v13h-5zM16 5.5h4v13h-4z"/>,inspector:<><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h5M8 16h7"/></>,results:<><path d="M4 19V9M9 19V5M14 19v-7M19 19V3"/><path d="M3 19h18"/></>,model:<><path d="M4 5h16v14H4z"/><path d="M8 9h8M8 13h5"/><circle cx="16.5" cy="15.5" r="1.5"/></>,more:<><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></>,close:<path d="M6 6l12 12M18 6 6 18"/>,
  chart:<><path d="M4 19h16M5 16c3-1 4-8 7-7s3 6 7 2"/><circle cx="12" cy="9" r="1.2"/></>,advanced:<><path d="M4 18h16M12 4v9m0 0-3-3m3 3 3-3"/><circle cx="12" cy="18" r="1.4"/></>,properties:<><path d="M5 6h14M5 12h14M5 18h14"/><circle cx="9" cy="6" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="11" cy="18" r="2"/></>,mechanics:<><path d="M4 12h3l1.5-4 3 8 3-8 1.5 4h4"/><path d="M18 4v5M18 15v5"/></>,connection:<><path d="M3 12h6M15 12h6"/><circle cx="11" cy="12" r="2"/><circle cx="13" cy="12" r="2"/></>,stress:<><path d="M5 7h14M5 17h14"/><path d="M8 3v7m0 0-2-3m2 3 2-3M16 21v-7m0 0-2 3m2-3 2 3"/></>,analysis:<><path d="M4 18h16M6 16V8M10 16v-5M14 16V5M18 16v-8"/><path d="M5 6c4 1 6-3 9-2s3 4 5 3"/></>,report:<><path d="M6 3.5h9l4 4V21H6zM15 3.5v4h4"/><path d="M9 17v-4m3 4V9m3 8v-6"/></>,vnl:<><rect x="3.5" y="5" width="6" height="5" rx="1"/><rect x="14.5" y="14" width="6" height="5" rx="1"/><path d="M9.5 7.5h4a4 4 0 0 1 4 4V14"/></>
};
function Glyph({name}:{name:string}){return <svg className="glyph" viewBox="0 0 24 24" aria-hidden="true">{ICONS[name]||ICONS.more}</svg>}
function IconButton({icon,label,onClick,active=false,disabled=false,testId}:{icon:string;label:string;onClick?:()=>void;active?:boolean;disabled?:boolean;testId?:string}){return <button data-testid={testId} className={`icon-btn ${active?'active':''}`} aria-label={label} title={label} onClick={onClick} disabled={disabled}><Glyph name={icon}/></button>}

function loadInitialProject():AnyProject{try{const raw=localStorage.getItem(STORAGE_KEY);return normalizeProject(raw?JSON.parse(raw):demoFrame())}catch{return normalizeProject(demoFrame())}}
function saveProject(project:AnyProject){localStorage.setItem(STORAGE_KEY,JSON.stringify(project))}
function getBounds(project:AnyProject){if(!project.nodes?.length)return{minX:0,maxX:10,minY:0,maxY:6};const xs=project.nodes.map((n:any)=>Number(n.x)||0),ys=project.nodes.map((n:any)=>Number(n.y)||0);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
function makeMapper(project:AnyProject){const b=getBounds(project),dx=Math.max(2,b.maxX-b.minX),dy=Math.max(2,b.maxY-b.minY),s=Math.min((VIEW.w-2*VIEW.p)/dx,(VIEW.h-2*VIEW.p)/dy);return(x:number,y:number):[number,number]=>[VIEW.p+(x-b.minX)*s,VIEW.h-VIEW.p-(y-b.minY)*s]}
function Support({node,project,map}:{node:any;project:any;map:(x:number,y:number)=>[number,number]}){const s=project.supports?.find((x:any)=>x.nodeId===node.id);if(!s||!(s.ux||s.uy||s.rz))return null;const[x,y]=map(node.x,node.y);if(s.ux&&s.uy&&s.rz)return <g className="support"><line x1={x-16} y1={y+14} x2={x+16} y2={y+14}/><line x1={x-13} y1={y+18} x2={x-5} y2={y+26}/><line x1={x-2} y1={y+18} x2={x+6} y2={y+26}/><line x1={x+9} y1={y+18} x2={x+17} y2={y+26}/></g>;return <g className="support"><path d={`M ${x-13} ${y+17} L ${x+13} ${y+17} L ${x} ${y+3} Z`}/><line x1={x-18} y1={y+22} x2={x+18} y2={y+22}/></g>}

function StructureCanvas({project,result,selectedId,onSelect}:{project:any;result:any;selectedId:string|null;onSelect:(id:string)=>void}){
  const map=useMemo(()=>makeMapper(project),[project]);const activeCase=project.settings?.activeLoadCaseId||project.loadCases?.[0]?.id;const displacements=new Map((result?.displacements||[]).map((d:any)=>[d.nodeId,d]));const maxDisp=Math.max(0,...(result?.displacements||[]).map((d:any)=>Math.hypot(d.ux||0,d.uy||0))),deformationScale=maxDisp>0?Math.min(80,Math.max(1,.8/maxDisp)):1;
  return <svg data-testid="model-canvas" className="model-canvas" viewBox={`0 0 ${VIEW.w} ${VIEW.h}`} role="img" aria-label="Modelo estrutural 2D"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3 z"/></marker></defs><g className="grid-lines">{Array.from({length:21},(_,i)=><line key={`v${i}`} x1={i*50} y1="0" x2={i*50} y2={VIEW.h}/>)}{Array.from({length:15},(_,i)=><line key={`h${i}`} x1="0" y1={i*50} x2={VIEW.w} y2={i*50}/>)}</g>{project.elements?.map((e:any)=>{const a=project.nodes.find((n:any)=>n.id===e.n1),b=project.nodes.find((n:any)=>n.id===e.n2);if(!a||!b)return null;const[x1,y1]=map(a.x,a.y),[x2,y2]=map(b.x,b.y);return <g key={e.id} onClick={()=>onSelect(e.id)} className="clickable"><line className={`member ${e.type==='truss2d'?'truss':''} ${selectedId===e.id?'selected':''}`} x1={x1} y1={y1} x2={x2} y2={y2}/><text className="element-label" x={(x1+x2)/2+8} y={(y1+y2)/2-8}>{e.id}</text></g>})}{result&&project.elements?.map((e:any)=>{const a=project.nodes.find((n:any)=>n.id===e.n1),b=project.nodes.find((n:any)=>n.id===e.n2),da:any=displacements.get(e.n1),db:any=displacements.get(e.n2);if(!a||!b||!da||!db)return null;const[x1,y1]=map(a.x+(da.ux||0)*deformationScale,a.y+(da.uy||0)*deformationScale),[x2,y2]=map(b.x+(db.ux||0)*deformationScale,b.y+(db.uy||0)*deformationScale);return <line key={`d-${e.id}`} className="deformed" x1={x1} y1={y1} x2={x2} y2={y2}/>})}{project.nodes?.map((n:any)=>{const[x,y]=map(n.x,n.y);return <g key={n.id}><Support node={n} project={project} map={map}/><circle className="node" cx={x} cy={y} r="6"/><text className="node-label" x={x+9} y={y-9}>{n.id}</text></g>})}{project.loads?.filter((l:any)=>l.caseId===activeCase).map((l:any)=>{const n=project.nodes.find((x:any)=>x.id===l.nodeId);if(!n)return null;const[x,y]=map(n.x,n.y);if(Math.abs(l.fy||0)>1e-9){const y0=y+(l.fy<0?-70:70);return <g key={l.id} className="load"><line x1={x} y1={y0} x2={x} y2={y} markerEnd="url(#arrow)"/><text x={x+10} y={y0}>{Number(l.fy).toFixed(1)} kN</text></g>}if(Math.abs(l.fx||0)>1e-9){const x0=x+(l.fx>0?-70:70);return <g key={l.id} className="load"><line x1={x0} y1={y} x2={x} y2={y} markerEnd="url(#arrow)"/><text x={x0} y={y-10}>{Number(l.fx).toFixed(1)} kN</text></g>}return null})}</svg>
}

function ResultsPanel({result}:{result:AnyResult}){if(!result)return <div className="empty-state">Execute a análise para visualizar deslocamentos, reações e esforços.</div>;const maxDisp=Math.max(0,...result.displacements.map((d:any)=>Math.hypot(d.ux||0,d.uy||0)))*1000;return <div className="results-content"><div className="metrics"><div><span>Cenário</span><strong>{result.scenario?.name||result.scenario?.id||'—'}</strong></div><div><span>Solver</span><strong>{result.type}</strong></div><div><span>Desl. máx.</span><strong>{maxDisp.toFixed(3)} mm</strong></div></div><div className="table-wrap"><table><thead><tr><th>Nó</th><th>Ux [mm]</th><th>Uy [mm]</th><th>Rz [rad]</th></tr></thead><tbody>{result.displacements.map((d:any)=><tr key={d.nodeId}><td>{d.nodeId}</td><td>{(d.ux*1000).toFixed(4)}</td><td>{(d.uy*1000).toFixed(4)}</td><td>{Number(d.rz||0).toExponential(3)}</td></tr>)}</tbody></table></div></div>}

export default function App(){
  const[project,setProjectState]=useState<AnyProject>(()=>loadInitialProject());const[result,setResult]=useState<AnyResult>(null);const[selectedId,setSelectedId]=useState<string|null>(null);const[drawer,setDrawer]=useState<Drawer>(null);const[panel,setPanel]=useState<PanelKind>(null);const[error,setError]=useState('');const inputRef=useRef<HTMLInputElement|null>(null);
  const setProject=(next:any)=>{const normalized=normalizeProject(typeof next==='function'?next(project):next);saveProject(normalized);setProjectState(normalized);setResult(null);setSelectedId(null)};const scenarios=[...(project.loadCases||[]),...(project.loadCombinations||[])];const selected=project.elements?.find((e:any)=>e.id===selectedId);
  const useDemo=(factory:()=>any)=>{setError('');setProject(factory());setDrawer(null);setPanel(null)};const analyze=()=>{try{setError('');const scenarioId=project.settings?.analysisScenarioId||project.loadCases?.[0]?.id;const r=solve(project,scenarioId);setResult(r);setDrawer('results')}catch(e:any){setError(e?.message||String(e))}};const changeScenario=(id:string)=>setProject({...project,settings:{...(project.settings||{}),analysisScenarioId:id}});const exportJson=()=>{const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='astrastruct-project.json';a.click();URL.revokeObjectURL(url)};const importJson=(file:File)=>{const reader=new FileReader();reader.onload=()=>{try{setProject(JSON.parse(String(reader.result)));setError('')}catch{setError('Arquivo JSON inválido.')}};reader.readAsText(file)};const openPanel=(p:PanelKind)=>{setDrawer(null);setPanel(p)};
  const panelButtons=[['cases','Casos/combinações','actions'],['chart','Diagramas/envelopes','postprocess'],['advanced','Cargas avançadas','advanced'],['properties','Materiais e seções','properties'],['mechanics','Molas e térmica','mechanics'],['connection','Ligações','connections'],['stress','Tensões','stress'],['analysis','Tipo de análise','analysis'],['report','Relatório técnico','report'],['vnl','VNL','vnl']] as const;

  return <div className="astra-app" data-testid="astra-app"><header className="topbar"><div className="brand"><span className="brand-mark">AS</span><div><strong>AstraStruct</strong><small>React/Vite · v1.1 migration</small></div></div><div className="top-actions"><IconButton icon="new" label="Novo projeto" onClick={()=>useDemo(emptyProject)}/><IconButton icon="frame" label="Pórtico demonstrativo" onClick={()=>useDemo(demoFrame)}/><IconButton icon="beam" label="Viga com carga distribuída" onClick={()=>useDemo(demoBeamUDL)}/><IconButton icon="truss" label="Treliça demonstrativa" onClick={()=>useDemo(demoTruss)}/><IconButton icon="mixed" label="Modelo misto" onClick={()=>useDemo(demoMixed)}/>{panelButtons.slice(0,5).map(([icon,label,p])=><IconButton key={p} icon={icon} label={label} onClick={()=>openPanel(p)}/>)}</div><div className="scenario-box"><select aria-label="Cenário de análise" value={project.settings?.analysisScenarioId||scenarios[0]?.id||''} onChange={e=>changeScenario(e.target.value)}>{scenarios.map((s:any)=><option key={s.id} value={s.id}>{s.name||s.id}</option>)}</select></div><IconButton testId="analyze-button" icon="play" label="Executar análise" onClick={analyze}/><input ref={inputRef} hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)importJson(f);e.currentTarget.value=''}}/></header>

    <main className="main-grid"><aside className={`sidebar library-panel ${drawer==='library'?'open':''}`}><div className="panel-head"><strong>Biblioteca</strong><button className="mobile-close" onClick={()=>setDrawer(null)}><Glyph name="close"/></button></div><div className="library-list"><button onClick={()=>useDemo(demoFrame)}><Glyph name="frame"/><span><b>Pórtico 2D</b><small>Euler–Bernoulli</small></span></button><button onClick={()=>useDemo(demoBeamUDL)}><Glyph name="beam"/><span><b>Viga</b><small>carga distribuída</small></span></button><button onClick={()=>useDemo(demoTruss)}><Glyph name="truss"/><span><b>Treliça 2D</b><small>barra axial</small></span></button><button onClick={()=>useDemo(demoMixed)}><Glyph name="mixed"/><span><b>Modelo misto</b><small>frame + truss</small></span></button></div><div className="library-tools"><b>Ferramentas migradas</b>{panelButtons.map(([icon,label,p])=><button key={p} onClick={()=>openPanel(p)}><Glyph name={icon}/><span>{label}</span></button>)}</div><div className="panel-note">Os painéis React usam o projeto em memória como fonte única de verdade. O frontend legado permanece apenas como referência histórica.</div></aside>
      <section className="workspace"><div className="workspace-bar"><div><b>{project.name}</b><span>{project.nodes?.length||0} nós · {project.elements?.length||0} elementos</span></div><div className="workspace-status"><span className="status-dot"></span>Engine 0.10 · React migration</div></div>{error&&<div className="error-banner" role="alert">{error}</div>}<div className="viewport"><StructureCanvas project={project} result={result} selectedId={selectedId} onSelect={setSelectedId}/></div><section className={`results-panel ${drawer==='results'?'open':''}`}><div className="panel-head"><strong>Resultados</strong><button className="mobile-close" onClick={()=>setDrawer(null)}><Glyph name="close"/></button></div><ResultsPanel result={result}/></section></section>
      <aside className={`sidebar inspector-panel ${drawer==='inspector'?'open':''}`}><div className="panel-head"><strong>Inspector</strong><button className="mobile-close" onClick={()=>setDrawer(null)}><Glyph name="close"/></button></div>{selected?<div className="inspector-card"><label>ID<strong>{selected.id}</strong></label><label>Tipo<strong>{selected.type}</strong></label><label>Nós<strong>{selected.n1} → {selected.n2}</strong></label><label>Área A<strong>{Number(selected.A||0).toExponential(4)} m²</strong></label><label>Inércia I<strong>{Number(selected.I||0).toExponential(4)} m⁴</strong></label></div>:<div className="empty-state">Selecione uma barra no modelo.</div>}<div className="inspector-card"><label>Análise<strong>{project.settings?.analysisType==='pdelta'?'P-Delta':'Linear'}</strong></label><label>Unidades<strong>{project.units||'kN-m-MPa'}</strong></label><label>Schema<strong>v{project.version}</strong></label></div></aside></main>

    <nav className="mobile-dock" aria-label="Navegação móvel"><IconButton icon="library" label="Biblioteca" active={drawer==='library'} onClick={()=>setDrawer(drawer==='library'?null:'library')}/><IconButton icon="model" label="Modelo" onClick={()=>setDrawer(null)}/><IconButton icon="inspector" label="Inspector" active={drawer==='inspector'} onClick={()=>setDrawer(drawer==='inspector'?null:'inspector')}/><IconButton icon="results" label="Resultados" active={drawer==='results'} onClick={()=>setDrawer(drawer==='results'?null:'results')}/><IconButton icon="more" label="Mais comandos" active={drawer==='menu'} onClick={()=>setDrawer(drawer==='menu'?null:'menu')}/></nav>
    {drawer==='menu'&&<div className="command-sheet"><div className="panel-head"><strong>Comandos</strong><button className="mobile-close" onClick={()=>setDrawer(null)}><Glyph name="close"/></button></div><div className="command-grid"><IconButton icon="new" label="Novo" onClick={()=>useDemo(emptyProject)}/><IconButton icon="frame" label="Pórtico" onClick={()=>useDemo(demoFrame)}/><IconButton icon="beam" label="Viga" onClick={()=>useDemo(demoBeamUDL)}/><IconButton icon="truss" label="Treliça" onClick={()=>useDemo(demoTruss)}/><IconButton icon="mixed" label="Misto" onClick={()=>useDemo(demoMixed)}/>{panelButtons.map(([icon,label,p])=><IconButton key={p} icon={icon} label={label} onClick={()=>openPanel(p)}/>) }<IconButton icon="import" label="Importar" onClick={()=>inputRef.current?.click()}/><IconButton icon="export" label="Exportar" onClick={exportJson}/><IconButton icon="play" label="Analisar" onClick={analyze}/></div></div>}
    {drawer&&drawer!=='results'&&<button className="scrim" aria-label="Fechar painel" onClick={()=>setDrawer(null)}/>}<EngineeringPanels panel={panel} project={project} result={result} onClose={()=>setPanel(null)} onCommit={setProject}/>
  </div>
}
