import React, { useRef, useState } from 'react';
// @ts-ignore
import { emptyProject, normalizeProject, demoFrame, demoBeamUDL, demoTruss, demoMixed, demoSpatialFrame, demoLoadCases } from '../../web/src/core/model.js';
// @ts-ignore
import { solve } from '../../web/src/solver/index.js';
import { EngineeringPanels, type PanelKind } from './EngineeringPanels';
import { AnalysisPanelV13 } from './AnalysisPanelV13';
import { NonlinearPostprocessPanel } from './NonlinearPostprocessPanel';
import { NonlinearReportPanel } from './NonlinearReportPanel';
import { DynamicsPostprocessPanel } from './DynamicsPostprocessPanel';
import { BucklingPanel } from './BucklingPanel';
import { Glyph, IconButton } from './AstraIcons';
import { ModelingCanvas, type ModelTool, type Selection } from './ModelingCanvas';
import { SpatialCanvas3D } from './SpatialCanvas3D';
// @ts-ignore
import { inferProjectDimension } from '../../web/src/core/elementRegistry.js';
import { InspectorPanel } from './InspectorPanel';
import { useProjectHistory } from './useProjectHistory';

type Drawer='library'|'inspector'|'results'|'menu'|null;
const STORAGE_KEY='astrastruct.project';
function loadInitial(){try{const raw=localStorage.getItem(STORAGE_KEY);return normalizeProject(raw?JSON.parse(raw):demoFrame())}catch{return normalizeProject(demoFrame())}}
function ResultsPanel({result}:{result:any}){
  if(!result)return <div className="empty-state">Execute a análise para visualizar deslocamentos, reações e esforços.</div>;
  if(result.dimension==='3d'&&result.analysisType!=='modal'){const disps=result.displacements||[],forces=result.elementForces||[],maxT=Math.max(0,...disps.map((d:any)=>Math.hypot(Number(d.ux)||0,Number(d.uy)||0,Number(d.uz)||0)))*1000;return <div className="results-content" data-testid="spatial3d-results"><div className="metrics"><div><span>Solver</span><strong>{result.type}</strong></div><div><span>Dimensão</span><strong>3D · 6 DOFs/nó</strong></div><div><span>|u| máx.</span><strong>{maxT.toFixed(4)} mm</strong></div><div><span>Kernel</span><strong>{result.solverVersion}</strong></div></div><div className="panel-note">{result.analysisType==='corotational'?'Co-rotacional 3D experimental v0.29: grandes deslocamentos/rotações com recuperação N/V/M/T na configuração corrente.':result.analysisType==='pdelta'?'P-Delta espacial 3D v0.28: segunda ordem elástica com rigidez geométrica biaxial.':'Fundação 3D linear v0.26 com visualização espacial interativa v0.26.1.'} Use o Canvas 3D para orbitar, inspecionar a deformada e mapear N/V/M/T.</div><div className="table-wrap"><table><thead><tr><th>Nó</th><th>Ux [mm]</th><th>Uy [mm]</th><th>Uz [mm]</th><th>Rx</th><th>Ry</th><th>Rz</th></tr></thead><tbody>{disps.map((d:any)=><tr key={d.nodeId}><td>{d.nodeId}</td><td>{(1000*Number(d.ux||0)).toFixed(4)}</td><td>{(1000*Number(d.uy||0)).toFixed(4)}</td><td>{(1000*Number(d.uz||0)).toFixed(4)}</td><td>{Number(d.rx||0).toExponential(3)}</td><td>{Number(d.ry||0).toExponential(3)}</td><td>{Number(d.rz||0).toExponential(3)}</td></tr>)}</tbody></table></div><div className="table-wrap" data-testid="spatial3d-forces"><table><thead><tr><th>Elemento</th><th>N1</th><th>Vy1</th><th>Vz1</th><th>T1</th><th>My1</th><th>Mz1</th></tr></thead><tbody>{forces.map((f:any)=><tr key={f.elementId}><td>{f.elementId}</td><td>{Number(f.N1 ?? (f.axialForce!=null ? -f.axialForce : 0)).toFixed(3)}</td><td>{Number(f.Vy1||0).toFixed(3)}</td><td>{Number(f.Vz1||0).toFixed(3)}</td><td>{Number(f.T1||0).toFixed(3)}</td><td>{Number(f.My1||0).toFixed(3)}</td><td>{Number(f.Mz1||0).toFixed(3)}</td></tr>)}</tbody></table></div></div>}
  if(result.analysisType==='modal'){const modes=result.modal?.modes||result.modes||[],m=modes[0];return <div className="results-content" data-testid="dynamic-results-modal"><div className="metrics"><div><span>Solver</span><strong>{result.type}</strong></div><div><span>f₁</span><strong>{m?Number(m.frequencyHz).toFixed(4):'—'} Hz</strong></div><div><span>T₁</span><strong>{m?Number(m.period).toFixed(5):'—'} s</strong></div><div><span>Massa</span><strong>{result.massFormulation}</strong></div></div><div className="panel-note">Forma exibida no canvas é normalizada para visualização; não representa deslocamento físico em metros.</div><div className="table-wrap"><table><thead><tr><th>Modo</th><th>f [Hz]</th><th>T [s]</th><th>ΣMef,X</th><th>ΣMef,Y</th>{result.dimension==='3d'&&<th>ΣMef,Z</th>}</tr></thead><tbody>{modes.map((x:any)=><tr key={x.mode}><td>{x.mode}</td><td>{Number(x.frequencyHz).toFixed(5)}</td><td>{Number(x.period).toFixed(5)}</td><td>{(100*Number(x.participation?.cumulativeMassRatioX||0)).toFixed(2)}%</td><td>{(100*Number(x.participation?.cumulativeMassRatioY||0)).toFixed(2)}%</td>{result.dimension==='3d'&&<td>{(100*Number(x.participation?.cumulativeMassRatioZ||0)).toFixed(2)}%</td>}</tr>)}</tbody></table></div></div>}
  if(result.analysisType==='time-history'){return <div className="results-content" data-testid="dynamic-results-time"><div className="metrics"><div><span>Solver</span><strong>{result.type}</strong></div><div><span>Monitor</span><strong>{result.monitor?.nodeId}/{String(result.monitor?.dof||'').toUpperCase()}</strong></div><div><span>|u| pico</span><strong>{(1000*Number(result.peakResponse?.absDisplacement||0)).toFixed(4)} mm</strong></div><div><span>Δt</span><strong>{Number(result.newmark?.timeStep||0).toFixed(5)} s</strong></div></div><div className="panel-note">História temporal linear por Newmark average-acceleration com amortecimento de Rayleigh. Abra Diagramas/envelopes para o gráfico completo.</div></div>}
  if(result.analysisType==='response-spectrum'){return <div className="results-content" data-testid="dynamic-results-spectrum"><div className="metrics"><div><span>Solver</span><strong>{result.type}</strong></div><div><span>Direção</span><strong>{String(result.direction||'x').toUpperCase()}</strong></div><div><span>Combinação</span><strong>{String(result.combination||'cqc').toUpperCase()}</strong></div><div><span>PGA</span><strong>{Number(result.spectrum?.pgaG||0).toFixed(4)} g</strong></div><div><span>|u| comb.</span><strong>{(1000*Number(result.combined?.peakTranslationalDisplacement||0)).toFixed(4)} mm</strong></div></div><div className="panel-note">Pseudo-espectros Sa/Sv/Sd derivados do acelerograma, com pré-processamento v0.25 e resposta modal/direcional combinada. Abra Diagramas/envelopes para a curva espectral e contribuições modais.</div></div>}
  const total=result.totalDisplacements||result.displacements,initial=result.initialDisplacements||[],incremental=result.displacements||[],initialMap=new Map(initial.map((d:any)=>[d.nodeId,d])),incrementalMap=new Map(incremental.map((d:any)=>[d.nodeId,d])),hasImperfection=!!result.pDelta?.imperfection?.enabled,isCorotational=result.analysisType==='corotational'||result.nonlinear?.formulation?.includes('co-rotational'),maxDisp=Math.max(0,...total.map((d:any)=>Math.hypot(d.ux||0,d.uy||0)))*1000;
  const lastStep=isCorotational?result.nonlinear?.history?.[result.nonlinear.history.length-1]:null;
  return <div className="results-content"><div className="metrics"><div><span>Cenário</span><strong>{result.scenario?.name||result.scenario?.id||'—'}</strong></div><div><span>Solver</span><strong>{result.type}</strong></div><div><span>{hasImperfection?'Desl. total máx.':'Desl. máx.'}</span><strong>{maxDisp.toFixed(3)} mm</strong></div>{hasImperfection&&<div data-testid="imperfection-result-metric"><span>Imperfeição</span><strong>Modo {result.pDelta.imperfection.mode} · {Number(result.pDelta.imperfection.amplitudeMm).toFixed(2)} mm</strong></div>}{isCorotational&&<><div data-testid="nonlinear-result-metric"><span>Não linear</span><strong>{result.nonlinear?.steps} incrementos · convergiu</strong></div><div><span>Newton final</span><strong>{lastStep?.iterations??'—'} it. · ‖r‖∞ {Number(lastStep?.residualNorm||0).toExponential(2)}</strong></div></>}</div>{hasImperfection&&<div className="panel-note">P‑Delta com imperfeição modal: <b>u₀</b> = forma inicial prescrita, <b>Δu</b> = incremento devido às ações e <b>u</b> = u₀ + Δu. λcr,ref = {Number(result.pDelta.imperfection.criticalFactor).toFixed(4)}.</div>}{isCorotational&&<div data-testid="nonlinear-result-note" className="panel-note"><b>Geom. não linear experimental:</b> formulação co‑rotacional Euler–Bernoulli com Newton–Raphson incremental{result.nonlinear?.lineSearch?' + line search':''}. A geometria exibida corresponde à configuração corrente para escala de deformada ×1.</div>}<div className="table-wrap"><table><thead>{hasImperfection?<tr><th>Nó</th><th>u₀x [mm]</th><th>ΔUx [mm]</th><th>Ux total [mm]</th><th>u₀y [mm]</th><th>ΔUy [mm]</th><th>Uy total [mm]</th><th>Rz total [rad]</th></tr>:<tr><th>Nó</th><th>Ux [mm]</th><th>Uy [mm]</th><th>Rz [rad]</th></tr>}</thead><tbody>{total.map((d:any)=>{const d0:any=initialMap.get(d.nodeId)||{ux:0,uy:0,rz:0},di:any=incrementalMap.get(d.nodeId)||{ux:0,uy:0,rz:0};return hasImperfection?<tr key={d.nodeId}><td>{d.nodeId}</td><td>{(d0.ux*1000).toFixed(4)}</td><td>{(di.ux*1000).toFixed(4)}</td><td>{(d.ux*1000).toFixed(4)}</td><td>{(d0.uy*1000).toFixed(4)}</td><td>{(di.uy*1000).toFixed(4)}</td><td>{(d.uy*1000).toFixed(4)}</td><td>{Number(d.rz||0).toExponential(3)}</td></tr>:<tr key={d.nodeId}><td>{d.nodeId}</td><td>{(d.ux*1000).toFixed(4)}</td><td>{(d.uy*1000).toFixed(4)}</td><td>{Number(d.rz||0).toExponential(3)}</td></tr>})}</tbody></table></div></div>
}

export default function App(){
  const store=useProjectHistory(loadInitial());const project=store.project;const[result,setResult]=useState<any>(null);const[selection,setSelection]=useState<Selection>(null);const[tool,setTool]=useState<ModelTool>('select');const[drawer,setDrawer]=useState<Drawer>(null);const[panel,setPanel]=useState<PanelKind>(null);const[bucklingOpen,setBucklingOpen]=useState(false);const[bucklingView,setBucklingView]=useState<any>(null);const[error,setError]=useState('');const inputRef=useRef<HTMLInputElement|null>(null);
  const commitProject=(next:any,record=true)=>{store.commit(normalizeProject(next),{record});setResult(null);setBucklingView(null)};
  const useDemo=(factory:()=>any)=>{setError('');commitProject(factory());setSelection(null);setTool('select');setDrawer(null);setPanel(null);setBucklingOpen(false)};
  const scenarios=[...(project.loadCases||[]),...(project.loadCombinations||[])];const projectDimension=inferProjectDimension(project);const activeScenario=project.settings?.analysisScenarioId||project.loadCases?.[0]?.id;
  const analyze=()=>{try{setError('');const r=solve(project,activeScenario);setResult(r);setDrawer('results')}catch(e:any){setError(e?.message||String(e))}};
  const changeScenario=(id:string)=>commitProject({...project,settings:{...(project.settings||{}),analysisScenarioId:id}},false);
  const exportJson=()=>{const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='astrastruct-project.json';a.click();URL.revokeObjectURL(url)};
  const importJson=(file:File)=>{const reader=new FileReader();reader.onload=()=>{try{commitProject(JSON.parse(String(reader.result)));setSelection(null);setError('')}catch{setError('Arquivo JSON inválido.')}};reader.readAsText(file)};
  const openPanel=(p:PanelKind)=>{setDrawer(null);setBucklingOpen(false);setPanel(p)};
  const openBuckling=()=>{setDrawer(null);setPanel(null);setBucklingOpen(true)};
  const undo=()=>{store.undo();setResult(null);setBucklingView(null);setSelection(null)};const redo=()=>{store.redo();setResult(null);setBucklingView(null);setSelection(null)};
  const panelButtons=[['cases','Casos/combinações','actions'],['chart','Diagramas/envelopes','postprocess'],['advanced','Cargas avançadas','advanced'],['properties','Materiais e seções','properties'],['mechanics','Molas e térmica','mechanics'],['connection','Ligações','connections'],['stress','Tensões','stress'],['analysis','Tipo de análise','analysis'],['report','Relatório técnico','report'],['vnl','VNL','vnl']] as const;
  const tools:[ModelTool,string,string][]=[['select','select','Selecionar/mover'],['node','node','Criar nó'],['frame2d','frame','Desenhar pórtico/viga'],['truss2d','truss','Desenhar treliça']];
  return <div className="astra-app" data-testid="astra-app">
    <header className="topbar"><div className="brand"><span className="brand-mark">AS</span><div><strong>AstraStruct</strong><small>v0.29 · co-rotacional 3D</small></div></div><div className="top-actions"><IconButton icon="new" label="Novo projeto" onClick={()=>useDemo(emptyProject)}/><IconButton icon="undo" label="Desfazer" disabled={!store.canUndo} onClick={undo}/><IconButton icon="redo" label="Refazer" disabled={!store.canRedo} onClick={redo}/><IconButton icon="frame" label="Pórtico demonstrativo" onClick={()=>useDemo(demoFrame)}/><IconButton icon="beam" label="Viga com carga distribuída" onClick={()=>useDemo(demoBeamUDL)}/><IconButton icon="truss" label="Treliça demonstrativa" onClick={()=>useDemo(demoTruss)}/><IconButton icon="mixed" label="Modelo misto" onClick={()=>useDemo(demoMixed)}/><IconButton icon="frame" label="Pórtico 3D demonstrativo" onClick={()=>useDemo(demoSpatialFrame)}/>{panelButtons.slice(0,4).map(([icon,label,p])=><IconButton key={p} icon={icon} label={label} onClick={()=>openPanel(p)}/>)}<IconButton icon="stability" label="Estabilidade" onClick={openBuckling}/></div><div className="scenario-box"><select aria-label="Cenário de análise" value={activeScenario||''} onChange={e=>changeScenario(e.target.value)}>{scenarios.map((s:any)=><option key={s.id} value={s.id}>{s.name||s.id}</option>)}</select></div><IconButton testId="analyze-button" icon="play" label="Executar análise" onClick={analyze}/><input ref={inputRef} hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)importJson(f);e.currentTarget.value=''}}/></header>
    <main className="main-grid">
      <aside className={`sidebar library-panel ${drawer==='library'?'open':''}`}><div className="panel-head"><strong>Biblioteca</strong><button className="mobile-close" onClick={()=>setDrawer(null)}><Glyph name="close"/></button></div><div className="library-list"><button onClick={()=>setTool('frame2d')}><Glyph name="frame"/><span><b>Viga / pórtico</b><small>dois cliques/toques</small></span></button><button onClick={()=>setTool('truss2d')}><Glyph name="truss"/><span><b>Barra de treliça</b><small>dois cliques/toques</small></span></button><button onClick={()=>setTool('node')}><Glyph name="node"/><span><b>Nó</b><small>snap na malha</small></span></button><button onClick={()=>useDemo(demoLoadCases)}><Glyph name="cases"/><span><b>Exemplo de ações</b><small>casos + combinação</small></span></button><button onClick={()=>useDemo(demoSpatialFrame)}><Glyph name="frame"/><span><b>Pórtico espacial 3D</b><small>v0.26.1 · Canvas 3D</small></span></button></div><div className="library-tools"><b>Ferramentas migradas</b>{panelButtons.map(([icon,label,p])=><button key={p} onClick={()=>openPanel(p)}><Glyph name={icon}/><span>{label}</span></button>)}<button onClick={openBuckling}><Glyph name="stability"/><span>Estabilidade</span></button></div><div className="panel-note">Modelagem, Inspector e painéis avançados usam estado React. O diretório web/ é mantido apenas como engine/legado durante a migração.</div></aside>
      <section className="workspace"><div className="workspace-bar modeling-bar"><div className="model-tools">{projectDimension==='2d'?tools.map(([t,icon,label])=><IconButton key={t} icon={icon} label={label} active={tool===t} onClick={()=>setTool(t)}/>):<span className="spatial3d-mode-label">Canvas 3D · visualização</span>}<span className="tool-sep"/><IconButton icon="undo" label="Desfazer" disabled={!store.canUndo} onClick={undo}/><IconButton icon="redo" label="Refazer" disabled={!store.canRedo} onClick={redo}/></div><div className="workspace-title"><b>{project.name}</b><span>{project.nodes?.length||0} nós · {project.elements?.length||0} elementos · grade {project.settings?.grid||.25} m</span></div><div className="workspace-status"><span className="status-dot"></span>{projectDimension==='3d'?'Canvas 3D':tool==='select'?'Seleção':tool==='node'?'Criar nó':tool==='frame2d'?'Pórtico 2D':'Treliça 2D'}</div></div>{error&&<div className="error-banner" role="alert">{error}</div>}<div className="viewport">{projectDimension==='3d'?<SpatialCanvas3D project={project} result={result} bucklingView={bucklingView} selection={selection} onSelection={setSelection}/>:<ModelingCanvas project={project} result={result} bucklingView={bucklingView} onClearBuckling={()=>setBucklingView(null)} tool={tool} selection={selection} onSelection={setSelection} onCommit={commitProject}/>}</div><section className={`results-panel ${drawer==='results'?'open':''}`}><div className="panel-head"><strong>Resultados</strong><button className="mobile-close" onClick={()=>setDrawer(null)}><Glyph name="close"/></button></div><ResultsPanel result={result}/></section></section>
      <aside className={`sidebar inspector-panel ${drawer==='inspector'?'open':''}`}><div className="panel-head"><strong>Inspector</strong><button className="mobile-close" onClick={()=>setDrawer(null)}><Glyph name="close"/></button></div><InspectorPanel project={project} selection={selection} onCommit={commitProject}/></aside>
    </main>
    <nav className="mobile-dock" aria-label="Navegação móvel"><IconButton icon="library" label="Biblioteca" active={drawer==='library'} onClick={()=>setDrawer(drawer==='library'?null:'library')}/><IconButton icon="model" label="Modelo" onClick={()=>setDrawer(null)}/><IconButton icon="inspector" label="Inspector" active={drawer==='inspector'} onClick={()=>setDrawer(drawer==='inspector'?null:'inspector')}/><IconButton icon="results" label="Resultados" active={drawer==='results'} onClick={()=>setDrawer(drawer==='results'?null:'results')}/><IconButton icon="more" label="Mais comandos" active={drawer==='menu'} onClick={()=>setDrawer(drawer==='menu'?null:'menu')}/></nav>
    {drawer==='menu'&&<div className="command-sheet"><div className="panel-head"><strong>Comandos</strong><button className="mobile-close" onClick={()=>setDrawer(null)}><Glyph name="close"/></button></div><div className="command-grid"><IconButton icon="new" label="Novo" onClick={()=>useDemo(emptyProject)}/><IconButton icon="undo" label="Desfazer" disabled={!store.canUndo} onClick={()=>{undo();setDrawer(null)}}/><IconButton icon="redo" label="Refazer" disabled={!store.canRedo} onClick={()=>{redo();setDrawer(null)}}/>{tools.map(([t,icon,label])=><IconButton key={t} icon={icon} label={label} active={tool===t} onClick={()=>{setTool(t);setDrawer(null)}}/>)}{panelButtons.map(([icon,label,p])=><IconButton key={p} icon={icon} label={label} onClick={()=>openPanel(p)}/>) }<IconButton icon="stability" label="Estabilidade" onClick={openBuckling}/><IconButton icon="import" label="Importar" onClick={()=>{setDrawer(null);inputRef.current?.click()}}/><IconButton icon="export" label="Exportar" onClick={()=>{exportJson();setDrawer(null)}}/><IconButton icon="play" label="Analisar" onClick={()=>{setDrawer(null);analyze()}}/></div></div>}
    {drawer&&drawer!=='results'&&<button className="scrim" aria-label="Fechar painel" onClick={()=>setDrawer(null)}/>} {panel==='analysis'?<AnalysisPanelV13 project={project} onClose={()=>setPanel(null)} onCommit={commitProject}/>:panel==='postprocess'&&project.settings?.analysisType==='corotational'?<NonlinearPostprocessPanel project={project} result={result} onClose={()=>setPanel(null)}/>:panel==='postprocess'&&['modal','time-history','response-spectrum'].includes(project.settings?.analysisType)?<DynamicsPostprocessPanel result={result} onClose={()=>setPanel(null)}/>:panel==='report'&&project.settings?.analysisType==='corotational'?<NonlinearReportPanel project={project} result={result} onClose={()=>setPanel(null)}/>:<EngineeringPanels panel={panel} project={project} result={result} onClose={()=>setPanel(null)} onCommit={commitProject}/>} {bucklingOpen&&<BucklingPanel project={project} onClose={()=>setBucklingOpen(false)} onVisualize={setBucklingView} onCommit={commitProject}/>} 
  </div>
}
