import {registerIsolatedLab} from './labRegistry';
import {$,fmt,esc,downloadText,openCoreLab} from './labUi';
// @ts-ignore
import {evaluateRuleSet,listRuleSets} from '../../web/src/rules/registerStructuralCodePlugins.js';

const presets:Record<string,any>={
  'aisc-360-22-connections':{bolt:{Vu:45,Tu:30,Fnv:372,Fnt:621,Ab:245,At:245,planes:1,phi:.75},bearing:{Vu:45,Fu:450,t:10,d:20,Lc:35,phi:.75},netSection:{Tu:120,Fu:450,An:700,U:1,phi:.75},blockShear:{demand:300,Fy:345,Fu:450,Agv:1800,Anv:1200,Ant:400,Ubs:1,phi:.75}},
  'en-1993-1-8-2024-connections':{bolt:{VEd:45,TEd:30,fub:800,A:245,As:245,planes:1,alphaV:.6,k2:.9,gammaM2:1.25},bearing:{VEd:45,fu:430,d:20,t:10,k1:2.2,alphaB:.60,gammaM2:1.25}},
  'aci-318-25-punching-anchors':{punching:{Vu:1000,fc:25,b0:3468,d:417,beta:1,alphaS:40,lambda:1,lambdaS:1,phi:.75},anchorTension:{Nu:80,fc:27.6,hef:170,anchorType:'cast-in',edgeDistance:255,phi:.70}},
  'nbr-8800-2024vc2025-connections':{boltShear:{demand:90,designResistance:120},bearing:{demand:80,designResistance:135}},
  'nbr-6118-2026-punching':{punching:{Vu:500,designPunchingResistanceMPa:1.2,b0:3000,d:200}}
};
function csv(result:any){const rows=['id,limit_state,demand,resistance,unit,utilization,status,clause'];for(const c of result.checks||[])rows.push([c.id,JSON.stringify(c.limitState),c.demand??'',c.resistance??'',c.unit,c.utilization??'',c.ok===null?'pending':c.ok?'pass':'fail',JSON.stringify(c.clause||'')].join(','));return rows.join('\n')}
function options(){return listRuleSets().filter((r:any)=>presets[r.id]).map((r:any)=>`<option value="${esc(r.id)}">${esc(r.code)} · ${esc(r.edition)}</option>`).join('')}
function openCodeChecks(){
  const ui=openCoreLab({testId:'code-checks-lab',title:'Verificações normativas · RuleEngine',subtitle:'AISC · Eurocode · ACI · ABNT NBR com provenance por edição',warning:'O RuleEngine é separado dos solvers mecânicos. Para ABNT, parâmetros não verificáveis publicamente são fornecidos pelo usuário/perfil licenciado; ausência de parâmetro gera estado PENDENTE, nunca aprovação automática.',controlsHtml:`<div class="core-lab-form"><label style="grid-column:1/-1">Pacote normativo<select data-code-ruleset>${options()}</select></label></div><label class="core-lab-note" style="display:grid;gap:5px">Entrada JSON editável<textarea data-code-json spellcheck="false" style="min-height:310px;width:100%;box-sizing:border-box;background:#0b131d;color:#eef4ff;border:1px solid #334a63;border-radius:7px;padding:9px;font:11px/1.4 ui-monospace,monospace"></textarea></label><div class="core-lab-actions"><button class="primary" data-testid="run-code-checks" data-code-run>Verificar</button><button data-code-reset>Restaurar exemplo</button><button data-code-csv disabled>Exportar CSV</button></div>`});
  const sel=$<HTMLSelectElement>('[data-code-ruleset]',ui.back)!,editor=$<HTMLTextAreaElement>('[data-code-json]',ui.back)!,run=$<HTMLButtonElement>('[data-code-run]',ui.back)!,reset=$<HTMLButtonElement>('[data-code-reset]',ui.back)!,csvBtn=$<HTMLButtonElement>('[data-code-csv]',ui.back)!;let last:any=null;
  const load=()=>{editor.value=JSON.stringify(presets[sel.value]||{},null,2)};sel.onchange=load;reset.onclick=load;load();
  run.onclick=()=>{try{const input=JSON.parse(editor.value||'{}'),r=evaluateRuleSet(sel.value,input);last=r;csvBtn.disabled=false;const prov=r.provenance||{},rows=r.checks.map((c:any)=>`<tr><td>${esc(c.limitState)}</td><td>${c.demand===null?'—':fmt(c.demand,3)}</td><td>${c.resistance===null?'—':fmt(c.resistance,3)}</td><td>${c.utilization===null?'—':fmt(c.utilization,3)}</td><td>${c.ok===null?'PENDENTE':c.ok?'OK':'NÃO OK'}</td><td>${esc(c.unit)}</td></tr>`).join('');ui.results.innerHTML=`<h3>Resultado normativo</h3><div class="core-lab-summary"><div class="core-lab-kpi"><span>Norma</span><strong>${esc(r.code)}</strong></div><div class="core-lab-kpi"><span>Edição</span><strong>${esc(r.edition)}</strong></div><div class="core-lab-kpi"><span>η máximo</span><strong>${fmt(r.summary.maxUtilization,3)}</strong></div><div class="core-lab-kpi"><span>Checks</span><strong>${r.summary.count}</strong></div><div class="core-lab-kpi"><span>Falhas</span><strong>${r.summary.fail}</strong></div><div class="core-lab-kpi"><span>Pendentes</span><strong>${r.summary.pending}</strong></div></div><div class="core-lab-note" data-testid="code-provenance"><b>Provenance:</b> ${esc(prov.standard||r.code)} · ${prov.requiresLicensedParameters?'parâmetros licenciados requeridos quando indicado':'fórmulas/coeficientes explícitos no perfil'} · ${esc(prov.sourceStatus||prov.policy||'')}</div><table class="core-lab-table" data-testid="code-checks-table"><thead><tr><th>Estado limite</th><th>Demanda</th><th>Resistência</th><th>η</th><th>Status</th><th>Un.</th></tr></thead><tbody>${rows}</tbody></table>`}catch(e:any){alert(e?.message||String(e))}};
  csvBtn.onclick=()=>last&&downloadText(`astrastruct-${last.ruleSetId}-checks.csv`,csv(last),'text/csv;charset=utf-8');
}
registerIsolatedLab({id:'code-checks',title:'Verificações normativas · RuleEngine',description:'Plugins independentes para AISC, Eurocode, ACI e integrações ABNT versionadas com provenance.',meta:'P4 · v0.31.1',order:90,testId:'open-code-checks-lab',open:openCodeChecks});
export {};
