import React,{useEffect,useMemo,useState}from'react';
import{createPortal}from'react-dom';
// @ts-ignore
import{normalizeProject}from'../../web/src/core/model.js';
// @ts-ignore
import{solve}from'../../web/src/solver/index.js';
// @ts-ignore
import{buildCombinationEnvelopeExplorer,combinationDescriptors}from'../../web/src/projectWorkflow/combinationEnvelopeExplorer.js';
// @ts-ignore
import{buildEnvelopeVisualization}from'../../web/src/projectWorkflow/envelopeVisualization.js';
import'./combination-envelope.css';

const STORAGE_KEY='astrastruct.project';
const readProject=()=>{try{return normalizeProject(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'));}catch{return normalizeProject({});}};
const fmt=(v:any,d=3)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);
const pct=(v:any)=>v==null||!Number.isFinite(Number(v))?'—':`${(100*Number(v)).toFixed(3)}%`;
const cls=(s:string)=>String(s||'PENDING').toLowerCase().replaceAll('_','-');
type Tab='combinations'|'envelopes'|'drift';
type EnvelopeField='N'|'V'|'M'|'T';
type SolvedEntry={combinationId:string;result?:any;error?:string};

export function CombinationEnvelopeExplorer(){
  const[open,setOpen]=useState(false),[project,setProject]=useState<any>(()=>readProject()),[entries,setEntries]=useState<SolvedEntry[]>([]),[running,setRunning]=useState(false),[progress,setProgress]=useState({done:0,total:0,label:''}),[tab,setTab]=useState<Tab>('combinations'),[category,setCategory]=useState('ALL'),[selectedCombination,setSelectedCombination]=useState(''),[envelopeField,setEnvelopeField]=useState<EnvelopeField>('M');
  const descriptors=useMemo(()=>combinationDescriptors(project),[project]);
  const explorer=useMemo(()=>buildCombinationEnvelopeExplorer(project,entries),[project,entries]);
  const envelopeView=useMemo(()=>buildEnvelopeVisualization(explorer,envelopeField),[explorer,envelopeField]);
  useEffect(()=>{const fn=(ev:Event)=>{const d=(ev as CustomEvent)?.detail||{};setProject(readProject());if(d.combinationId){setSelectedCombination(String(d.combinationId));setTab('combinations')}if(d.tab==='envelopes')setTab('envelopes');setOpen(true)};const sync=(ev:Event)=>{const q=(ev as CustomEvent)?.detail?.project;if(q)setProject(normalizeProject(q))};window.addEventListener('astrastruct:combination-envelope-open',fn);window.addEventListener('astrastruct:project-external-commit',sync);return()=>{window.removeEventListener('astrastruct:combination-envelope-open',fn);window.removeEventListener('astrastruct:project-external-commit',sync)}},[]);
  useEffect(()=>{if(selectedCombination&&!entries.some(e=>e.combinationId===selectedCombination))setSelectedCombination('')},[entries,selectedCombination]);
  const calculateAll=async()=>{if(running||!descriptors.length)return;setRunning(true);setEntries([]);setProgress({done:0,total:descriptors.length,label:''});const out:SolvedEntry[]=[];for(let i=0;i<descriptors.length;i++){const d=descriptors[i];setProgress({done:i,total:descriptors.length,label:d.name});await new Promise(r=>setTimeout(r,0));try{out.push({combinationId:d.id,result:solve(project,d.id)})}catch(e:any){out.push({combinationId:d.id,error:String(e?.message||e)})}setEntries([...out]);setProgress({done:i+1,total:descriptors.length,label:d.name})}setRunning(false)};
  const visibleCombos=explorer.combinations.filter((c:any)=>category==='ALL'||c.category===category),selected=explorer.combinations.find((c:any)=>c.combinationId===selectedCombination)||visibleCombos[0]||null;
  const preview=(combo:any)=>{if(!combo?.result)return;window.dispatchEvent(new CustomEvent('astrastruct:result-preview',{detail:{result:combo.result,label:`${combo.name} · ${combo.category}`,combinationId:combo.combinationId,source:'combination-envelope'}}));setOpen(false)};
  const clearPreview=()=>window.dispatchEvent(new CustomEvent('astrastruct:result-preview',{detail:{clear:true,source:'combination-envelope'}}));
  const showEnvelope3D=()=>{if(!envelopeView.items.length)return;window.dispatchEvent(new CustomEvent('astrastruct:envelope-3d',{detail:envelopeView}));setOpen(false)};
  const clearEnvelope3D=()=>window.dispatchEvent(new CustomEvent('astrastruct:envelope-3d',{detail:{clear:true,source:'combination-envelope'}}));
  const exportCsv=()=>{const h=['elementId','label','kind','N_abs','N_comb','V_abs','V_comb','M_abs','M_comb','T_abs','T_comb'];const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;const lines=[h.join(','),...explorer.elementEnvelopes.map((e:any)=>[e.elementId,e.label,e.kind,e.N.absMax,e.N.governingCombinationId,e.V.absMax,e.V.governingCombinationId,e.M.absMax,e.M.governingCombinationId,e.T.absMax,e.T.governingCombinationId].map(esc).join(','))];const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='astrastruct-combination-envelopes.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),0)};
  if(!open)return null;
  return createPortal(<div className="ce-backdrop" data-testid="combination-envelope-explorer"><section className="ce-shell" role="dialog" aria-modal="true" aria-label="Explorador de combinações e envoltórias"><header><div><h2>Combinações & envoltórias · v0.53.9</h2><p>Mesmo solver do modelo · ELU/ELS por combinação · N/V/M/T · drift por pavimento · mapas 3D com combinação governante</p></div><button aria-label="Fechar explorador" onClick={()=>setOpen(false)}>×</button></header>
    <div className="ce-metrics"><div><b>{explorer.summary.defined}</b><span>definidas</span></div><div><b>{explorer.summary.ready}</b><span>resolvidas</span></div><div><b>{explorer.summary.elu}</b><span>ELU</span></div><div><b>{explorer.summary.els}</b><span>ELS</span></div><div className={explorer.summary.unknown?'warn':''}><b>{explorer.summary.unknown}</b><span>sem classe</span></div><div className={explorer.summary.error?'fail':''}><b>{explorer.summary.error}</b><span>erros</span></div><div><b>{explorer.summary.elements}</b><span>elementos c/ envelope</span></div><div><b>{explorer.summary.stories}</b><span>drifts</span></div></div>
    <div className="ce-toolbar"><button className="primary" data-testid="combination-calculate" disabled={running||!descriptors.length} onClick={calculateAll}>{running?'Calculando…':'Calcular combinações'}</button>{running&&<span className="ce-progress">{progress.done}/{progress.total} · {progress.label}</span>}<select aria-label="Filtrar categoria de combinação" value={category} onChange={e=>setCategory(e.target.value)}><option value="ALL">Todas</option><option value="ELU">ELU</option><option value="ELS">ELS</option><option value="UNKNOWN">Sem classificação</option></select><button onClick={exportCsv} disabled={!explorer.elementEnvelopes.length}>Exportar envoltórias CSV</button><button onClick={clearPreview}>Limpar prévia 3D</button></div>
    <nav className="ce-tabs"><button className={tab==='combinations'?'active':''} onClick={()=>setTab('combinations')}>Combinações</button><button className={tab==='envelopes'?'active':''} onClick={()=>setTab('envelopes')}>Envoltórias N/V/M/T</button><button className={tab==='drift'?'active':''} onClick={()=>setTab('drift')}>Drift & deslocamentos</button></nav>
    <main>{tab==='combinations'&&<div className="ce-split"><div className="ce-table-wrap"><table><thead><tr><th>Combinação</th><th>Classe</th><th>Estado</th><th>u máx. [mm]</th><th>Nó</th><th>Termos</th></tr></thead><tbody>{visibleCombos.map((c:any)=><tr key={c.combinationId} data-testid={`combination-row-${c.combinationId}`} className={selected?.combinationId===c.combinationId?'selected':''} onClick={()=>setSelectedCombination(c.combinationId)}><td><b>{c.name}</b><small>{c.combinationId}</small></td><td><span className={`ce-pill ${cls(c.category)}`}>{c.category}</span></td><td><span className={`ce-pill ${cls(c.status)}`}>{c.status}</span></td><td>{fmt(c.displacement.magnitudeMm)}</td><td>{c.displacement.nodeId||'—'}</td><td>{(c.terms||[]).map((t:any)=>`${fmt(t.factor,2)}·${t.caseId}`).join(' + ')||'—'}</td></tr>)}{!visibleCombos.length&&<tr><td colSpan={6} className="ce-empty">Nenhuma combinação calculada neste filtro.</td></tr>}</tbody></table></div>{selected&&<aside className="ce-detail"><h3>{selected.name}</h3><p><span className={`ce-pill ${cls(selected.category)}`}>{selected.category}</span> <span className={`ce-pill ${cls(selected.status)}`}>{selected.status}</span></p><dl><dt>Origem da classe</dt><dd>{selected.categorySource}</dd><dt>Deslocamento máximo</dt><dd>{fmt(selected.displacement.magnitudeMm)} mm · {selected.displacement.nodeId||'—'}</dd><dt>Drifts calculáveis</dt><dd>{selected.storyDrifts.length}</dd></dl>{selected.error&&<p className="ce-error">{selected.error}</p>}<button className="primary" data-testid="combination-preview-3d" disabled={!selected.result||selected.status!=='READY'} onClick={()=>preview(selected)}>Pré-visualizar no Canvas 3D</button><small>A prévia não substitui o resultado principal salvo no projeto.</small></aside>}</div>}
      {tab==='envelopes'&&<div className="ce-envelope-view"><div className="ce-envelope-tools"><label>Mapa 3D <select data-testid="envelope-field-select" aria-label="Campo da envoltória 3D" value={envelopeField} onChange={e=>setEnvelopeField(e.target.value as EnvelopeField)}><option value="N">N · esforço normal</option><option value="V">V · cortante</option><option value="M">M · momento fletor</option><option value="T">T · torção</option></select></label><button className="primary" data-testid="envelope-show-3d" disabled={!envelopeView.items.length} onClick={showEnvelope3D}>Visualizar mapa no Canvas 3D</button><button onClick={clearEnvelope3D}>Limpar mapa 3D</button><span>{envelopeView.summary.bars} barras · {envelopeView.summary.shells} shells · escalas independentes</span></div><div className="ce-table-wrap"><table><thead><tr><th>Elemento</th><th>Tipo</th><th>|N| máx.</th><th>Comb. N</th><th>|V| máx.</th><th>Comb. V</th><th>|M| máx.</th><th>Comb. M</th><th>|T| máx.</th><th>Comb. T</th></tr></thead><tbody>{explorer.elementEnvelopes.map((e:any)=><tr key={e.elementId} data-testid={`envelope-row-${e.elementId}`}><td><b>{e.label}</b><small>{e.elementId}</small></td><td>{e.kind}</td><td>{fmt(e.N.absMax)}</td><td>{e.N.governingCombinationId||'—'}</td><td>{fmt(e.V.absMax)}</td><td>{e.V.governingCombinationId||'—'}</td><td>{fmt(e.M.absMax)}</td><td>{e.M.governingCombinationId||'—'}</td><td>{fmt(e.T.absMax)}</td><td>{e.T.governingCombinationId||'—'}</td></tr>)}{!explorer.elementEnvelopes.length&&<tr><td colSpan={10} className="ce-empty">Calcule as combinações para formar as envoltórias.</td></tr>}</tbody></table><p className="ce-note">Barras: N [kN], V [kN], M/T [kN·m]. Shells: N [kN/m], V [kN/m], M [kN·m/m]. O mapa 3D usa escalas separadas para barras e shells; unidades incompatíveis nunca são normalizadas em conjunto.</p></div></div>}
      {tab==='drift'&&<div className="ce-drift"><section className="ce-displacement-card"><span>Envelope global de deslocamento</span><b>{fmt(explorer.displacementEnvelope.magnitudeMm)} mm</b><small>{explorer.displacementEnvelope.nodeId||'—'} · {explorer.displacementEnvelope.governingCombinationId||'—'}</small></section><div className="ce-table-wrap"><table><thead><tr><th>Pavimento</th><th>Altura [m]</th><th>Drift máx.</th><th>Δ horiz. [mm]</th><th>Drift X</th><th>Drift Y</th><th>Combinação governante</th></tr></thead><tbody>{explorer.storyDriftEnvelopes.map((d:any)=><tr key={d.levelId}><td><b>{d.levelLabel}</b><small>{d.fromLevelId} → {d.levelId}</small></td><td>{fmt(d.heightM)}</td><td>{pct(d.maxDriftRatio)}</td><td>{fmt(d.maxDriftMm)}</td><td>{pct(d.driftX)}</td><td>{pct(d.driftY)}</td><td>{d.governingCombinationId||'—'}</td></tr>)}{!explorer.storyDriftEnvelopes.length&&<tr><td colSpan={7} className="ce-empty">Sem pares de pavimentos com deslocamentos físicos suficientes.</td></tr>}</tbody></table></div><p className="ce-note"><b>Importante:</b> drift é apresentado como grandeza de pós-processamento. Nenhum limite normativo é presumido e nenhum PASS/FAIL é emitido sem um critério ELS explícito.</p></div>}</main>
    <footer><span><b>Governança:</b> somente resultados realmente resolvidos entram nas envoltórias. Combinações sem classificação explícita/semântica permanecem UNKNOWN. Formas modais e de flambagem não entram em deslocamentos ou drifts físicos.</span><button onClick={()=>setOpen(false)}>Fechar</button></footer>
  </section></div>,document.body);
}
