import React,{useMemo}from'react';
// @ts-ignore
import{characteristicLength3D,clamp,nodePoint,projectPoint3D}from'../../web/src/view/spatialView3d.js';

type Selection={kind:'node'|'element';id:string}|null;
type Viewport={left:number;top:number;width:number;height:number};
type Props={project:any;view:any;camera:any;viewport:Viewport;selection:Selection;onSelection:(s:Selection)=>void;onClear:()=>void};
const points=(v:any[])=>v.map(p=>`${Number(p.x).toFixed(2)},${Number(p.y).toFixed(2)}`).join(' ');
const fmt=(v:any,d=2)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);
const pct=(v:any)=>v==null||!Number.isFinite(Number(v))?'—':`${(100*Number(v)).toFixed(3)}%`;
const magnitudeColor=(ratio:any,domain:string)=>{const t=clamp(Number(ratio)||0,0,1),neutral=[220,230,236],target=domain==='drift'?[116,82,151]:[47,112,173],c=neutral.map((v,i)=>Math.round(v+(target[i]-v)*t));return`rgb(${c[0]},${c[1]},${c[2]})`};
const levelElevation=(project:any,id:string)=>{const l=(project?.levels||[]).find((x:any)=>String(x.id)===String(id));return Number.isFinite(Number(l?.elevation))?Number(l.elevation):null};

export function CombinationKinematicOverlay({project,view,camera,viewport,selection,onSelection,onClear}:Props){
  const domain=String(view?.domain||''),charL=useMemo(()=>characteristicLength3D(project),[project]);
  const displacementScene=useMemo(()=>{if(domain!=='displacement')return[];const nodeById=new Map((project?.nodes||[]).map((n:any)=>[String(n.id),n])),criticalId=String(view?.criticalByKind?.node?.nodeId||''),out:any[]=[];for(const item of view?.items||[]){const n:any=nodeById.get(String(item.nodeId));if(!n)continue;const a=projectPoint3D(nodePoint(n),camera,{width:viewport.width,height:viewport.height});if(!a.visible)continue;const vx=Number(item.uxMm)||0,vy=Number(item.uyMm)||0,vz=Number(item.uzMm)||0,vm=Math.hypot(vx,vy,vz),ratio=clamp(Number(item.ratio)||0,0,1),len=charL*(.035+.14*ratio),q=vm>1e-12?{x:Number(n.x||0)+vx/vm*len,y:Number(n.y||0)+vy/vm*len,z:Number(n.z||0)+vz/vm*len}:nodePoint(n),b=projectPoint3D(q,camera,{width:viewport.width,height:viewport.height});out.push({kind:'node',id:String(item.nodeId),source:item,a,b,color:magnitudeColor(ratio,domain),critical:String(item.nodeId)===criticalId})}return out},[domain,project,view,camera,viewport.width,viewport.height,charL]);
  const driftScene=useMemo(()=>{if(domain!=='drift')return[];const criticalId=String(view?.criticalByKind?.story?.levelId||''),allNodes=project?.nodes||[],out:any[]=[];for(const item of view?.items||[]){const levelId=String(item.levelId),z=levelElevation(project,levelId);if(z==null)continue;const tol=Math.max(1e-7,charL*1e-7),levelNodes=allNodes.filter((n:any)=>String(n.levelId||'')===levelId||(!n.levelId&&Number.isFinite(Number(n.z))&&Math.abs(Number(n.z)-z)<=tol));if(!levelNodes.length)continue;let minX=Math.min(...levelNodes.map((n:any)=>Number(n.x)||0)),maxX=Math.max(...levelNodes.map((n:any)=>Number(n.x)||0)),minY=Math.min(...levelNodes.map((n:any)=>Number(n.y)||0)),maxY=Math.max(...levelNodes.map((n:any)=>Number(n.y)||0));const pad=Math.max(charL*.025,1e-4);if(maxX-minX<pad){minX-=pad;maxX+=pad}if(maxY-minY<pad){minY-=pad;maxY+=pad}const corners=[{x:minX,y:minY,z},{x:maxX,y:minY,z},{x:maxX,y:maxY,z},{x:minX,y:maxY,z}],pp=corners.map(p=>projectPoint3D(p,camera,{width:viewport.width,height:viewport.height}));if(pp.some((p:any)=>!p.visible))continue;const ratio=clamp(Number(item.ratio)||0,0,1);out.push({kind:'story',id:levelId,source:item,points:pp,color:magnitudeColor(ratio,domain),critical:levelId===criticalId,cx:pp.reduce((s:number,p:any)=>s+p.x,0)/pp.length,cy:pp.reduce((s:number,p:any)=>s+p.y,0)/pp.length})}return out},[domain,project,view,camera,viewport.width,viewport.height,charL]);
  if(domain!=='displacement'&&domain!=='drift')return null;
  const selected=domain==='displacement'&&selection?.kind==='node'?(view?.items||[]).find((x:any)=>String(x.nodeId)===String(selection.id))||null:null,criticalNode=view?.criticalByKind?.node||null,criticalStory=view?.criticalByKind?.story||null,focus=selected||criticalNode;
  const openCombination=(id:any)=>id&&window.dispatchEvent(new CustomEvent('astrastruct:combination-envelope-open',{detail:{combinationId:String(id),source:'kinematic-map'}}));
  return <>
    {(displacementScene.length>0||driftScene.length>0)&&<svg data-testid="spatial3d-envelope-overlay" className="spatial3d-envelope-overlay" aria-label={domain==='displacement'?'Mapa 3D de deslocamentos nodais':'Mapa 3D de drift por pavimento'} viewBox={`0 0 ${viewport.width} ${viewport.height}`} style={{left:viewport.left,top:viewport.top,width:viewport.width,height:viewport.height}}><defs><marker id="kinematic-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#2f70ad"/></marker></defs>{domain==='displacement'&&displacementScene.map((it:any)=><g key={it.id} data-envelope-node-id={it.id} data-envelope-critical={it.critical?'true':'false'}>{Math.hypot(it.source.uxMm||0,it.source.uyMm||0,it.source.uzMm||0)>1e-12&&<line className="spatial3d-envelope-vector" x1={it.a.x} y1={it.a.y} x2={it.b.x} y2={it.b.y} stroke={it.color} strokeWidth={it.critical?4:2.4} markerEnd="url(#kinematic-arrow)"/>}<circle className={`spatial3d-envelope-node ${it.critical?'spatial3d-envelope-critical':''}`} cx={it.a.x} cy={it.a.y} r={it.critical?6.5:4.5} fill={it.color} stroke="#fff" strokeWidth="1.7"/>{it.critical&&<text className="spatial3d-envelope-label" x={it.a.x+8} y={it.a.y-8}>{it.id} · u máx.</text>}</g>)}{domain==='drift'&&driftScene.map((it:any)=><g key={it.id} data-envelope-story-id={it.id} data-envelope-critical={it.critical?'true':'false'}><polygon className={`spatial3d-envelope-story ${it.critical?'spatial3d-envelope-critical':''}`} points={points(it.points)} fill={it.color} fillOpacity={it.critical ? .48 : .30} stroke={it.color} strokeWidth={it.critical?4:2}/><text className="spatial3d-envelope-label" x={it.cx+7} y={it.cy-7}>{it.source.levelLabel} · {pct(it.source.value)}</text></g>)}</svg>}
    <div className="spatial3d-envelope-status" data-testid="spatial3d-envelope-status" data-envelope-domain={domain}><header><b>{domain==='displacement'?'Deslocamento governante 3D':'Drift por pavimento 3D'}</b><span className="env-field">{domain==='displacement'?'U':'Δ/h'}</span></header><div className="spatial3d-envelope-gradient kinematic"/><div className="spatial3d-envelope-scales">{domain==='displacement'?<span>Nós: máx. {fmt(view?.scales?.node?.maxAbs,3)} mm</span>:<span>Pavimentos: máx. {pct(view?.scales?.story?.maxAbs)}</span>}<span>cores = magnitude relativa</span></div>{domain==='displacement'?<div className="spatial3d-envelope-selected" data-testid="spatial3d-envelope-selected"><b>{focus?`${focus.label} · ${focus.nodeId}`:'Sem nó disponível'}</b>{focus&&<><span>|u| {fmt(focus.value,3)} mm · ux {fmt(focus.uxMm,3)} · uy {fmt(focus.uyMm,3)} · uz {fmt(focus.uzMm,3)}</span><span>Combinação governante: {focus.governingCombinationId||'—'}</span></>}<div className="spatial3d-envelope-actions">{!selected&&criticalNode&&<button data-testid="kinematic-select-critical-node" type="button" onClick={()=>onSelection({kind:'node',id:String(criticalNode.nodeId)})}>Selecionar nó crítico</button>}{focus?.governingCombinationId&&<button className="primary" data-testid="kinematic-open-governing-combination" type="button" onClick={()=>openCombination(focus.governingCombinationId)}>Abrir combinação governante</button>}<button type="button" onClick={onClear}>Limpar mapa</button></div></div>:<div className="spatial3d-envelope-selected" data-testid="spatial3d-envelope-selected">{criticalStory?<><b>{criticalStory.levelLabel}</b><span>Drift {pct(criticalStory.value)} · Δ horiz. {fmt(criticalStory.driftMm,3)} mm</span><span>Combinação governante: {criticalStory.governingCombinationId||'—'}</span></>:<span>Sem pavimento com drift físico disponível.</span>}<div className="spatial3d-envelope-actions">{criticalStory?.governingCombinationId&&<button className="primary" data-testid="kinematic-open-governing-combination" type="button" onClick={()=>openCombination(criticalStory.governingCombinationId)}>Abrir combinação governante</button>}<button type="button" onClick={onClear}>Limpar mapa</button></div></div>}<small className="spatial3d-envelope-governance">Escala gráfica relativa. Nenhum limite normativo ou PASS/FAIL é inferido deste mapa.</small></div>
  </>;
}
