import React from 'react';

type Props={result:any;onClose:()=>void};
const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const fmt=(v:any,d=4)=>{const n=Number(v);if(!Number.isFinite(n))return'—';return Math.abs(n)>=1e4||(Math.abs(n)>0&&Math.abs(n)<1e-3)?n.toExponential(3):n.toFixed(d)};

function TimeChart({rows}:{rows:any[]}){
  if(!rows?.length)return <div className="empty-state">Sem histórico temporal.</div>;
  const W=720,H=270,L=58,R=18,T=28,B=38,xs=rows.map(r=>num(r.t)),ys=rows.map(r=>num(r.displacement)*1000),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys,0),ymax=Math.max(...ys,0),dx=Math.max(xmax-xmin,1e-12),dy=Math.max(ymax-ymin,1e-12),xlo=xmin,xhi=xmax,ylo=ymin-.08*dy,yhi=ymax+.08*dy,sx=(x:number)=>L+(x-xlo)/Math.max(xhi-xlo,1e-12)*(W-L-R),sy=(y:number)=>T+(yhi-y)/Math.max(yhi-ylo,1e-12)*(H-T-B),path=rows.map((r,i)=>`${i?'L':'M'} ${sx(num(r.t)).toFixed(1)} ${sy(num(r.displacement)*1000).toFixed(1)}`).join(' ');
  return <div className="chart-card" data-testid="dynamic-time-chart"><div className="chart-title"><b>Resposta temporal · deslocamento monitorado</b><span>{fmt(xmin,3)} … {fmt(xmax,3)} s · {fmt(ymin,3)} … {fmt(ymax,3)} mm</span></div><svg viewBox={`0 0 ${W} ${H}`} className="react-chart"><line x1={L} y1={T} x2={L} y2={H-B}/><line x1={L} y1={H-B} x2={W-R} y2={H-B}/>{ylo<=0&&yhi>=0&&<line className="zero" x1={L} y1={sy(0)} x2={W-R} y2={sy(0)}/>}<path className="line" d={path}/></svg></div>;
}

export function DynamicsPostprocessPanel({result,onClose}:Props){
  const modal=result?.analysisType==='modal'?result:null,time=result?.analysisType==='time-history'?result:null,modes=(result?.modal?.modes||result?.modes||[]) as any[];
  return <div className="react-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section data-testid="panel-dynamics-postprocess" className="react-modal wide" role="dialog" aria-modal="true" aria-label="Dinâmica estrutural"><header className="react-modal-head"><div><h2>Dinâmica estrutural · v0.23</h2><p>Análise modal e integração temporal linear-elástica.</p></div><button className="plain-icon" aria-label="Fechar" onClick={onClose}>×</button></header>{!result||(!modal&&!time)?<div className="empty-state">Execute uma análise Modal ou História temporal para visualizar estes resultados.</div>:<>
    <div className="metrics"><div><span>Solver</span><strong>{result.type}</strong></div><div><span>Massa</span><strong>{result.massFormulation}</strong></div><div><span>DOFs livres</span><strong>{result.freeDofs}</strong></div>{modal&&modes[0]&&<><div data-testid="dynamic-first-frequency"><span>f₁</span><strong>{fmt(modes[0].frequencyHz,4)} Hz</strong></div><div><span>T₁</span><strong>{fmt(modes[0].period,5)} s</strong></div></>}{time&&<><div data-testid="dynamic-peak-displacement"><span>|u| pico</span><strong>{fmt(num(time.peakResponse?.absDisplacement)*1000,4)} mm</strong></div><div><span>Δt</span><strong>{fmt(time.newmark?.timeStep,5)} s</strong></div></>}</div>
    <div className="panel-note"><b>Convenção de massa:</b> `material.density` é interpretado como peso específico em kN/m³ e convertido por ρm=γ/g. A v0.23 é linear-elástica; não mistura história temporal com as leis plásticas cíclicas quase-estáticas.</div>
    <section className="react-card" data-testid="dynamic-modal-table"><div className="section-title"><h3>Modos próprios</h3><span className="chip">Kφ = ω²Mφ</span></div><div className="table-wrap"><table><thead><tr><th>Modo</th><th>f [Hz]</th><th>T [s]</th><th>ω [rad/s]</th><th>Mef,X</th><th>ΣMef,X</th><th>Mef,Y</th><th>ΣMef,Y</th></tr></thead><tbody>{modes.map((m:any)=><tr key={m.mode}><td>{m.mode}</td><td>{fmt(m.frequencyHz,5)}</td><td>{fmt(m.period,5)}</td><td>{fmt(m.omega,4)}</td><td>{fmt(100*num(m.participation?.effectiveMassRatioX),2)}%</td><td>{fmt(100*num(m.participation?.cumulativeMassRatioX),2)}%</td><td>{fmt(100*num(m.participation?.effectiveMassRatioY),2)}%</td><td>{fmt(100*num(m.participation?.cumulativeMassRatioY),2)}%</td></tr>)}</tbody></table></div></section>
    {time&&<><TimeChart rows={time.history||[]}/><section className="react-card" data-testid="dynamic-time-summary"><div className="section-title"><h3>Newmark-β</h3><span className="chip">β={fmt(time.newmark?.beta,2)} · γ={fmt(time.newmark?.gamma,2)}</span></div><div className="metrics"><div><span>Monitor</span><strong>{time.monitor?.nodeId}/{String(time.monitor?.dof||'').toUpperCase()}</strong></div><div><span>Duração</span><strong>{fmt(time.newmark?.duration,4)} s</strong></div><div><span>Passos</span><strong>{time.newmark?.steps}</strong></div><div><span>Amortecimento alvo</span><strong>{fmt(100*num(time.rayleigh?.dampingRatio),2)}%</strong></div><div><span>αM</span><strong>{fmt(time.rayleigh?.alphaM,6)}</strong></div><div><span>βK</span><strong>{fmt(time.rayleigh?.betaK,8)}</strong></div></div><div className="panel-note">Excitação v0.23: o vetor de cargas do cenário é multiplicado pela história escalar definida pelo usuário. <b>Aceleração de base ainda não está implementada</b>.</div></section></>}
    <section className="react-card"><h3>Limitações v0.23</h3><p>Formulação linear-elástica em frame2d/truss2d com extremidades rígidas. Sem não linearidade geométrica/material, sem contato, sem amortecimento histerético, sem análise espectral e sem excitação sísmica por aceleração de base nesta versão.</p></section>
  </>}</section></div>;
}
