import React,{useEffect,useMemo,useState}from'react';
import{createPortal}from'react-dom';
// @ts-ignore
import{normalizeProject}from'../../web/src/core/model.js';
// @ts-ignore
import{buildingEluElsDashboard}from'../../web/src/projectWorkflow/eluElsDashboard.js';
import{currentAnalysisResult,subscribeAnalysisResult}from'./analysisResultBridge';
import'./elu-els-dashboard.css';

const STORAGE_KEY='astrastruct.project';
const readProject=()=>{try{return normalizeProject(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'));}catch{return normalizeProject({});}};
const fmt=(v:any,d=2)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);
const statusClass=(s:string)=>String(s||'PENDING').toLowerCase().replaceAll('_','-');
const statusLabel=(s:string)=>({FAIL:'FAIL',INVALID:'INVALID',PENDING:'PENDING',READY_FOR_REVIEW:'READY FOR REVIEW'} as Record<string,string>)[s]||s;
const groupLabel=(g:string)=>({beam:'Vigas',column:'Pilares',slab:'Lajes',wall:'Paredes',brace:'Contraventamentos',foundation:'Fundações',other:'Outros'} as Record<string,string>)[g]||g;
const forceText=(f:any)=>{if(!f)return'—';if(f.kind==='shell')return`N ${fmt(f.membraneKNm)} kN/m · M ${fmt(f.bendingKNmPerM)} kN·m/m · Q ${fmt(f.shearKNm)} kN/m`;if(f.kind==='foundation')return`Rz ${fmt(f.verticalReactionKN)} kN · q̄ ${fmt(f.averageContactPressureKPa)} kPa`;return`N ${fmt(f.axialKN)} kN · V ${fmt(f.shearKN)} kN · M ${fmt(f.momentKNm)} kN·m · T ${fmt(f.torsionKNm)} kN·m`};

type Filter={level:string;group:string;status:string};
type RequestedEntity={kind?:string;id:string;combinationId?:string|null}|null;
export function EluElsDashboard(){
  const[open,setOpen]=useState(false),[project,setProject]=useState<any>(()=>readProject()),[analysisResult,setAnalysisResult]=useState<any>(()=>currentAnalysisResult()),[filter,setFilter]=useState<Filter>({level:'ALL',group:'ALL',status:'ALL'}),[query,setQuery]=useState(''),[selectedKey,setSelectedKey]=useState(''),[requestedEntity,setRequestedEntity]=useState<RequestedEntity>(null);
  const refresh=()=>setProject(readProject());
  useEffect(()=>subscribeAnalysisResult(setAnalysisResult),[]);
  useEffect(()=>{const fn=(ev:Event)=>{const d=(ev as CustomEvent)?.detail||{};refresh();if(d.id!=null||d.elementId!=null||d.entityId!=null){setRequestedEntity({kind:d.kind||'element',id:String(d.id??d.elementId??d.entityId),combinationId:d.combinationId??null});setFilter({level:'ALL',group:'ALL',status:'ALL'});setQuery('')}else setRequestedEntity(null);setOpen(true)};const sync=(ev:Event)=>{if(!open)return;const q=(ev as CustomEvent)?.detail?.project;setProject(q?normalizeProject(q):readProject())};window.addEventListener('astrastruct:elu-els-dashboard-open',fn);window.addEventListener('astrastruct:project-external-commit',sync);return()=>{window.removeEventListener('astrastruct:elu-els-dashboard-open',fn);window.removeEventListener('astrastruct:project-external-commit',sync)}},[open]);
  const dashboard=useMemo(()=>buildingEluElsDashboard(project,analysisResult),[project,analysisResult]);
  useEffect(()=>{if(requestedEntity){const hit=dashboard.rows.find((r:any)=>(!requestedEntity.kind||r.entityKind===requestedEntity.kind)&&String(r.entityId)===requestedEntity.id);if(hit){setSelectedKey(hit.rowId);setRequestedEntity(null);return}}if(!selectedKey&&dashboard.rows[0])setSelectedKey(dashboard.rows[0].rowId);else if(selectedKey&&!dashboard.rows.some((r:any)=>r.rowId===selectedKey))setSelectedKey(dashboard.rows[0]?.rowId||'')},[dashboard,selectedKey,requestedEntity]);
  useEffect(()=>{const fn=(ev:Event)=>{const s=(ev as CustomEvent)?.detail?.selection;if(!s)return;const hit=dashboard.rows.find((r:any)=>r.entityKind===s.kind&&String(r.entityId)===String(s.id));if(hit)setSelectedKey(hit.rowId)};window.addEventListener('astrastruct:selection-changed',fn);return()=>window.removeEventListener('astrastruct:selection-changed',fn)},[dashboard]);
  const rows=useMemo(()=>dashboard.rows.filter((r:any)=>(filter.level==='ALL'||r.levelId===filter.level)&&(filter.group==='ALL'||r.group===filter.group)&&(filter.status==='ALL'||r.status===filter.status)&&(!query.trim()||`${r.label} ${r.entityId} ${r.type} ${r.levelLabel} ${groupLabel(r.group)} ${r.governing?.limitState||''}`.toLowerCase().includes(query.trim().toLowerCase()))),[dashboard,filter,query]);
  const selected=dashboard.rows.find((r:any)=>r.rowId===selectedKey)||rows[0]||null;
  const chooseTree=(level:string,group='ALL')=>setFilter(f=>({...f,level,group}));
  const selectCanvas=()=>{if(!selected||!['element','node'].includes(selected.entityKind))return;window.dispatchEvent(new CustomEvent('astrastruct:select-entity',{detail:{kind:selected.entityKind,id:selected.entityId,source:'elu-els-dashboard'}}));setOpen(false)};
  const exportCsv=()=>{const h=['id','label','level','group','status','ELU','ELS','etaMax','governing','uMax_mm','deltaEnds_mm','response','analysisType','lambdaCr','issues'];const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;const lines=[h.join(','),...dashboard.rows.map((r:any)=>[r.entityId,r.label,r.levelLabel,groupLabel(r.group),r.status,r.elu.status,r.els.status,r.governing?.utilization,r.governing?.limitState,r.response.uMaxMm,r.response.relativeEndMm,r.response.state,r.response.analysisType,r.stability?.lambdaCr,r.issues.join(' | ')].map(esc).join(','))];const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='astrastruct-elu-els-building-dashboard.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),0)};
  if(!open)return null;
  const s=dashboard.summary;
  const shell=<div className="be-backdrop" data-testid="elu-els-dashboard"><section className="be-shell" role="dialog" aria-modal="true" aria-label="Dashboard ELU ELS do edifício"><header><div><h2>Edifício · ELU/ELS · v0.53.7</h2><p>Elementos por pavimento e categoria · verificações governantes · deformações · estabilidade · navegação 3D</p></div><button aria-label="Fechar dashboard ELU ELS" onClick={()=>setOpen(false)}>×</button></header>
    <div className="be-metrics"><button onClick={()=>setFilter({level:'ALL',group:'ALL',status:'ALL'})}><b>{s.count}</b><span>itens</span></button><button className="fail" onClick={()=>setFilter(f=>({...f,status:'FAIL'}))}><b>{s.fail}</b><span>FAIL</span></button><button className="invalid" onClick={()=>setFilter(f=>({...f,status:'INVALID'}))}><b>{s.invalid}</b><span>INVALID</span></button><button className="pending" onClick={()=>setFilter(f=>({...f,status:'PENDING'}))}><b>{s.pending}</b><span>PENDING</span></button><button className="ready" onClick={()=>setFilter(f=>({...f,status:'READY_FOR_REVIEW'}))}><b>{s.readyForReview}</b><span>ready for review</span></button><div><b>{s.eluPass}</b><span>ELU PASS</span></div><div><b>{s.elsPass}</b><span>ELS PASS</span></div><div><b>{s.physicalResponseReady}</b><span>resposta física</span></div></div>
    <div className="be-toolbar"><input aria-label="Buscar elemento" placeholder="Buscar elemento, nível, categoria ou governante…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filtrar estado ELU ELS" value={filter.status} onChange={e=>setFilter(f=>({...f,status:e.target.value}))}><option value="ALL">Todos os estados</option><option value="FAIL">FAIL</option><option value="INVALID">INVALID</option><option value="PENDING">PENDING</option><option value="READY_FOR_REVIEW">READY FOR REVIEW</option></select><button onClick={()=>setFilter({level:'ALL',group:'ALL',status:'ALL'})}>Limpar filtros</button><button onClick={exportCsv}>Exportar CSV</button></div>
    <div className="be-layout"><aside className="be-tree"><div className="be-tree-title"><b>Edifício</b><span>{dashboard.tree.length} nível(is)</span></div><button className={filter.level==='ALL'?'active':''} onClick={()=>chooseTree('ALL')}>Todos <small>{s.count}</small></button>{dashboard.tree.map((l:any)=><section key={l.id}><button className={`${filter.level===l.id&&filter.group==='ALL'?'active':''} ${statusClass(l.status)}`} onClick={()=>chooseTree(l.id)}><span>{l.name}</span><small>{l.count} · {statusLabel(l.status)}</small></button><div>{l.groups.map((g:any)=><button key={g.id} className={`${filter.level===l.id&&filter.group===g.id?'active':''} ${statusClass(g.status)}`} onClick={()=>chooseTree(l.id,g.id)}><span>{groupLabel(g.id)}</span><small>{g.count}</small></button>)}</div></section>)}</aside>
      <main className="be-main"><div className="be-table-wrap"><table className="be-table"><thead><tr><th>Elemento</th><th>Nível</th><th>Categoria</th><th>ELU</th><th>ELS</th><th>η máx.</th><th>Governante</th><th>u máx. [mm]</th><th>Δ extremos [mm]</th><th>Resposta</th><th>Integrado</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.rowId} data-testid={`elu-els-row-${r.entityId}`} className={`${selectedKey===r.rowId?'selected':''} ${statusClass(r.status)}`} onClick={()=>setSelectedKey(r.rowId)}><td><b>{r.label}</b><small>{r.entityId} · {r.type}</small></td><td>{r.levelLabel}</td><td>{groupLabel(r.group)}</td><td><span className={`be-pill ${statusClass(r.elu.status)}`}>{r.elu.status}</span></td><td><span className={`be-pill ${statusClass(r.els.status)}`}>{r.els.status}</span></td><td>{fmt(r.governing?.utilization,3)}</td><td>{r.governing?.limitState||'—'}</td><td>{fmt(r.response.uMaxMm,3)}</td><td>{fmt(r.response.relativeEndMm,3)}</td><td>{r.response.state}</td><td><span className={`be-pill ${statusClass(r.status)}`}>{statusLabel(r.status)}</span></td></tr>)}{!rows.length&&<tr><td colSpan={11} className="be-empty">Nenhum item corresponde aos filtros atuais.</td></tr>}</tbody></table></div>
      {selected&&<section className="be-detail" data-testid="elu-els-detail"><header><div><h3>{selected.label}</h3><p>{selected.levelLabel} · {groupLabel(selected.group)} · {selected.type}</p></div><span className={`be-pill ${statusClass(selected.status)}`}>{statusLabel(selected.status)}</span></header><div className="be-detail-grid"><article><h4>ELU</h4><b>{selected.elu.status}</b><p>{selected.elu.count} verificação(ões) · η máx. {fmt(selected.elu.maxUtilization,3)}</p><small>{selected.elu.governingLimitState||'Sem governante ELU explícito'}</small></article><article><h4>ELS</h4><b>{selected.els.status}</b><p>{selected.els.count} verificação(ões) · η máx. {fmt(selected.els.maxUtilization,3)}</p><small>{selected.els.governingLimitState||'Sem governante ELS explícito'}</small></article><article><h4>Deformação</h4><b>{selected.response.state}</b><p>u nodal máx. {fmt(selected.response.uMaxMm,3)} mm</p><small>Δ entre extremos {fmt(selected.response.relativeEndMm,3)} mm</small></article><article><h4>Estabilidade</h4><b>{selected.stability?.secondOrder?'2ª ordem ativa':'evidência global'}</b><p>λcr {fmt(selected.stability?.lambdaCr,3)}</p><small>{selected.stability?.analysisType||'—'}</small></article></div><div className="be-evidence"><section><h4>Esforços/resultantes correntes</h4><p>{forceText(selected.response.force)}</p><small>Valores apenas do resultado carregado; a combinação aberta a partir da envoltória serve como referência governante, mas só aparece aqui como resposta física se estiver realmente carregada no resultado corrente.</small></section><section><h4>Pendências</h4>{selected.issues.length?selected.issues.map((x:string,i:number)=><p key={i}>{x}</p>):<p>Nenhuma pendência automática neste escopo.</p>}</section></div><div className="be-checks"><h4>Verificações explicitamente associadas</h4>{selected.checks.length?<div className="be-check-list">{selected.checks.map((c:any,i:number)=><div key={`${c.id}-${i}`}><span className={`be-pill ${statusClass(c.status)}`}>{c.status}</span><b>{c.category}</b><span>{c.limitState}</span><small>{c.combinationId||'—'} · η {fmt(c.utilization,3)} · {c.code||c.profileId||'fonte normativa não identificada'}</small></div>)}</div>:<p className="be-empty-note">Nenhum <code>code-design-check/v1</code> ou verificação compatível foi explicitamente associado a este elemento.</p>}</div><div className="be-detail-actions">{['element','node'].includes(selected.entityKind)&&<button className="primary" data-testid="elu-els-select-canvas" onClick={selectCanvas}>Selecionar no Canvas 3D</button>}{selected.group==='foundation'&&<button onClick={()=>{setOpen(false);window.dispatchEvent(new CustomEvent('astrastruct:foundation-dashboard-open'))}}>Abrir dashboard de fundações</button>}<button onClick={()=>setOpen(false)}>Fechar e retornar ao modelo</button></div></section>}
      </main></div>
    <footer><span><b>Governança:</b> ausência de ELU, ELS ou resposta física permanece PENDING. Formas modais/flambagem não são tratadas como deformações em mm. READY FOR REVIEW ≠ aprovação do projeto.</span><button onClick={refresh}>Recarregar projeto</button></footer>
  </section></div>;
  return createPortal(shell,document.body);
}
