import React,{useMemo,useState}from'react';
// @ts-ignore
import{buildEngineeringDesktopResults}from'../../web/src/solver/engineeringDesktopResults.js';

type Tab='overview'|'reactions'|'forces'|'nodes'|'rebar';
const fmt=(v:any,d=3)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);
const pct=(v:any)=>v==null||!Number.isFinite(Number(v))?'—':fmt(100*Number(v),3);

function Empty({children}:{children:React.ReactNode}){return <div className="eng-result-empty">{children}</div>}

export function EngineeringResultsWorkbench({project,result}:{project:any;result:any}){
  const[tab,setTab]=useState<Tab>('overview');
  const data=useMemo(()=>buildEngineeringDesktopResults(project,result||{}),[project,result]);
  const vis=result?.engineeringVisualization,overview=vis?.floors?.levels||data.overview||[];
  const tabButton=(id:Tab,label:string)=><button data-testid={`engineering-result-tab-${id}`} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>;
  return <div className="eng-results-strip eng-results-workbench" data-testid="engineering-results-strip" data-result-tab={tab} data-result-contract={data.contract}>
    <div className="eng-result-tabs">{tabButton('overview','Resultados')}{tabButton('reactions','Reações de apoio')}{tabButton('forces','Esforços em elementos')}{tabButton('nodes','Deslocamentos em nós')}{tabButton('rebar','Armaduras (Resumo)')}</div>
    <div className="eng-result-table" data-testid={`engineering-result-panel-${tab}`}>
      {tab==='overview'&&(overview.length?<table><thead><tr><th>Pavimento</th><th>Desloc. X [mm]</th><th>Desloc. Y [mm]</th><th>Desloc. Z [mm]</th><th>|u| [mm]</th><th>Drift X [%]</th><th>Drift Y [%]</th></tr></thead><tbody>{overview.slice().reverse().map((r:any)=>{const drift=(vis?.floors?.storyDrifts||[]).find((d:any)=>String(d.levelId)===String(r.id));return <tr key={r.id}><td>{r.label||r.id}</td><td>{fmt(r.uxMm)}</td><td>{fmt(r.uyMm)}</td><td>{fmt(r.uzMm)}</td><td>{fmt(r.resultantMm)}</td><td>{pct(drift?.driftX)}</td><td>{pct(drift?.driftY)}</td></tr>})}</tbody></table>:<Empty>Execute uma análise 3D para preencher deslocamentos e drifts por pavimento.</Empty>)}
      {tab==='reactions'&&(data.reactions.length?<table data-testid="engineering-reaction-table"><thead><tr><th>Apoio</th><th>Fx [kN]</th><th>Fy [kN]</th><th>Fz [kN]</th><th>|R| [kN]</th><th>Mx [kN·m]</th><th>My [kN·m]</th><th>Mz [kN·m]</th><th>|M| [kN·m]</th></tr></thead><tbody>{data.reactions.map((r:any)=><tr key={r.nodeId} data-testid={`engineering-reaction-${r.nodeId}`}><td>{r.label}<small>{r.nodeId}</small></td><td>{fmt(r.Fx)}</td><td>{fmt(r.Fy)}</td><td>{fmt(r.Fz)}</td><td>{fmt(r.resultantKN)}</td><td>{fmt(r.Mx)}</td><td>{fmt(r.My)}</td><td>{fmt(r.Mz)}</td><td>{fmt(r.resultantMomentKNm)}</td></tr>)}</tbody></table>:<Empty>Sem reações físicas de apoio no resultado corrente. Apenas nós explicitamente restringidos são apresentados.</Empty>)}
      {tab==='forces'&&<div className="eng-force-tables">{data.barForces.length?<><div className="eng-table-caption">Barras · forças em kN; momentos/torção em kN·m</div><table data-testid="engineering-bar-force-table"><thead><tr><th>Elemento</th><th>Tipo</th><th>N1</th><th>Vy1</th><th>Vz1</th><th>T1</th><th>My1</th><th>Mz1</th><th>N2</th><th>Vy2</th><th>Vz2</th><th>T2</th><th>My2</th><th>Mz2</th></tr></thead><tbody>{data.barForces.map((r:any)=><tr key={r.elementId}><td>{r.label}<small>{r.elementId}</small></td><td>{r.type}</td>{['N1','Vy1','Vz1','T1','My1','Mz1','N2','Vy2','Vz2','T2','My2','Mz2'].map(k=><td key={k}>{fmt(r[k])}</td>)}</tr>)}</tbody></table></>:null}{data.shellForces.length?<><div className="eng-table-caption">Cascas · N/Q em kN/m; M em kN·m/m</div><table data-testid="engineering-shell-force-table"><thead><tr><th>Elemento</th><th>Nx</th><th>Ny</th><th>Nxy</th><th>Mx</th><th>My</th><th>Mxy</th><th>Qx</th><th>Qy</th></tr></thead><tbody>{data.shellForces.map((r:any)=><tr key={r.elementId}><td>{r.label}<small>{r.elementId}</small></td>{['Nx','Ny','Nxy','Mx','My','Mxy','Qx','Qy'].map(k=><td key={k}>{fmt(r[k])}</td>)}</tr>)}</tbody></table></>:null}{!data.barForces.length&&!data.shellForces.length?<Empty>Sem esforços de elementos no resultado corrente.</Empty>:null}</div>}
      {tab==='nodes'&&(data.displacements.length?<table data-testid="engineering-node-displacement-table"><thead><tr><th>Nó</th><th>Ux [mm]</th><th>Uy [mm]</th><th>Uz [mm]</th><th>|u| [mm]</th><th>Rx [rad]</th><th>Ry [rad]</th><th>Rz [rad]</th></tr></thead><tbody>{data.displacements.map((r:any)=><tr key={r.nodeId} data-testid={`engineering-displacement-${r.nodeId}`}><td>{r.label}<small>{r.nodeId}</small></td><td>{fmt(r.uxMm)}</td><td>{fmt(r.uyMm)}</td><td>{fmt(r.uzMm)}</td><td>{fmt(r.resultantMm)}</td><td>{fmt(r.rx,6)}</td><td>{fmt(r.ry,6)}</td><td>{fmt(r.rz,6)}</td></tr>)}</tbody></table>:<Empty>Sem deslocamentos físicos nodais no resultado corrente.</Empty>)}
      {tab==='rebar'&&(data.rebar.rows.length?<><div className="eng-result-summary" data-testid="engineering-rebar-summary"><span>{data.rebar.summary.marks} marca(s)</span><span>Comprimento total: {fmt(data.rebar.summary.totalLengthM,2)} m</span><span>Massa total: {fmt(data.rebar.summary.totalMassKg,2)} kg</span></div><table data-testid="engineering-rebar-table"><thead><tr><th>Marca</th><th>Localização</th><th>Aço</th><th>Ø [mm]</th><th>Qtd.</th><th>Corte [mm]</th><th>Comprimento [m]</th><th>Massa [kg]</th></tr></thead><tbody>{data.rebar.rows.map((r:any)=><tr key={r.id}><td>{r.id}</td><td>{r.location}</td><td>{r.grade}</td><td>{fmt(r.diameterMm,1)}</td><td>{fmt(r.quantity,0)}</td><td>{fmt(r.cutLengthMm,0)}</td><td>{fmt(r.totalLengthM,2)}</td><td>{fmt(r.totalMassKg,2)}</td></tr>)}</tbody></table></>:<Empty><span>Nenhum <code>rebar-schedule/v1</code> está associado ao projeto.</span><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('astrastruct:engineering-review-open',{detail:{tab:'sheets',source:'engineering-results'}}))}>Abrir detalhamento de armaduras</button></Empty>)}
    </div>
  </div>;
}
