import React,{useEffect,useMemo,useState}from'react';
import{createPortal}from'react-dom';
// @ts-ignore
import{normalizeProject}from'../../web/src/core/model.js';
// @ts-ignore
import{foundationDecisionDashboard}from'../../web/src/foundation/dashboard.js';
// @ts-ignore
import{foundationReactionLink}from'../../web/src/foundation/reactionLink.js';
import{currentAnalysisResult,subscribeAnalysisResult}from'./analysisResultBridge';
import'./foundation-dashboard.css';

const STORAGE_KEY='astrastruct.project';
const readProject=()=>{try{return normalizeProject(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'));}catch{return normalizeProject({});}};
const fmt=(v:any,d=2)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);
const statusLabel:{[key:string]:string}={FAIL:'FAIL',INVALID:'INVALID',PENDING:'PENDING',READY_FOR_REVIEW:'READY FOR REVIEW'};
const statusClass=(s:string)=>String(s||'PENDING').toLowerCase().replaceAll('_','-');
const reactionStatusText=(link:any)=>link?.status==='LINKED'?`Fundação vinculada: ${link.foundations?.[0]?.label||link.foundationId} (${link.foundationId})`:link?.status==='AMBIGUOUS'?`Vínculo ambíguo: ${link.foundations?.length||0} fundações usam o nó ${link.nodeId}.`:link?.status==='UNLINKED'?`Nenhuma fundação está explicitamente vinculada ao nó ${link.nodeId}.`:'Contexto de reação sem nó válido.';
const reactionVectorText=(link:any)=>{const r=link?.reaction;if(!Array.isArray(r?.vector))return null;const labels=r.quantity==='moment'?['Mx','My','Mz']:['Fx','Fy','Fz'];return r.vector.map((v:any,i:number)=>`${labels[i]} ${fmt(v,2)}`).join(' · ')};

export function FoundationDecisionDashboard(){
  const[open,setOpen]=useState(false),[project,setProject]=useState<any>(()=>readProject()),[analysisResult,setAnalysisResult]=useState<any>(()=>currentAnalysisResult()),[statusFilter,setStatusFilter]=useState('ALL'),[query,setQuery]=useState(''),[reactionSource,setReactionSource]=useState<any>(null);
  const refresh=()=>setProject(readProject());
  useEffect(()=>subscribeAnalysisResult(setAnalysisResult),[]);
  useEffect(()=>{const fn=(ev:Event)=>{const detail=(ev as CustomEvent)?.detail||{},p=readProject();setProject(p);setStatusFilter('ALL');if(detail?.source==='reaction-map'&&detail?.reaction){setReactionSource(detail.reaction);setQuery(detail.nodeId?String(detail.nodeId):'')}else{setReactionSource(null);setQuery('')}setOpen(true)};const sync=(ev:Event)=>{if(!open)return;const q=(ev as CustomEvent)?.detail?.project;setProject(q?normalizeProject(q):readProject())};window.addEventListener('astrastruct:foundation-dashboard-open',fn);window.addEventListener('astrastruct:project-external-commit',sync);return()=>{window.removeEventListener('astrastruct:foundation-dashboard-open',fn);window.removeEventListener('astrastruct:project-external-commit',sync)}},[open]);
  const dashboard=useMemo(()=>foundationDecisionDashboard(project,analysisResult),[project,analysisResult]),reactionLink=useMemo(()=>reactionSource?foundationReactionLink(project,reactionSource):null,[project,reactionSource]),rows=useMemo(()=>dashboard.rows.filter((r:any)=>(statusFilter==='ALL'||r.status===statusFilter)&&(!query.trim()||`${r.foundationId} ${r.label} ${r.type} ${r.nodeId||''} ${r.geotechnical.profileLabel||''}`.toLowerCase().includes(query.trim().toLowerCase()))),[dashboard,statusFilter,query]);
  const openFoundation=()=>{setOpen(false);window.dispatchEvent(new CustomEvent('astrastruct:engineering-review-open',{detail:{tab:'foundation',foundationId:reactionLink?.foundationId||null,nodeId:reactionLink?.nodeId||null,source:reactionLink?'reaction-foundation-link':'foundation-dashboard'}}))};
  const openSSI=()=>{setOpen(false);window.dispatchEvent(new CustomEvent('astrastruct:ssi-open'))};
  const openGeo=()=>{setOpen(false);window.dispatchEvent(new CustomEvent('astrastruct:geotechnical-open'))};
  const exportCsv=()=>{const h=['foundationId','label','type','status','normative','etaMax','ssi','uz_mm','Rz_kN','qbar_kPa','geo','profile','layers','geoParameters','issues'];const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;const lines=[h.join(','),...dashboard.rows.map((r:any)=>[r.foundationId,r.label,r.type,r.status,r.normative.status,r.normative.maxUtilization,r.ssi.state,r.ssi.settlementMm,r.ssi.verticalReactionKN,r.ssi.averageContactPressureKPa,r.geotechnical.state,r.geotechnical.profileLabel||r.geotechnical.profileId||'',r.geotechnical.layers,r.geotechnical.explicitParameters,r.issues.join(' | ')].map(esc).join(','))];const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='astrastruct-foundation-decision-dashboard.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),0)};
  if(!open)return null;
  const s=dashboard.summary,rv=reactionLink?.reaction,vectorText=reactionVectorText(reactionLink);
  const shell=<div className="fd-backdrop" data-testid="foundation-decision-dashboard"><section className="fd-shell" role="dialog" aria-modal="true" aria-label="Dashboard integrado de fundações"><header><div><h2>Fundação · SSI · Geotecnia · v0.53.12</h2><p>Decisão integrada por fundação, sem transformar dado ausente ou reação estrutural em aprovação</p></div><button aria-label="Fechar dashboard de fundações" onClick={()=>setOpen(false)}>×</button></header>
    <div className="fd-toolbar"><div className="fd-filters"><input aria-label="Buscar fundação" placeholder="Buscar fundação, nó, tipo ou perfil…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filtrar estado" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">Todos os estados</option><option value="FAIL">FAIL</option><option value="INVALID">INVALID</option><option value="PENDING">PENDING</option><option value="READY_FOR_REVIEW">READY FOR REVIEW</option></select></div><div className="fd-actions"><button onClick={openFoundation}>Dimensionamento/fundação</button><button onClick={openSSI}>SSI</button><button onClick={openGeo}>Geotecnia</button><button onClick={exportCsv}>Exportar CSV</button></div></div>
    {reactionLink&&<section className={`fd-reaction-context ${String(reactionLink.status||'').toLowerCase()}`} data-testid="foundation-reaction-context" data-reaction-link-status={reactionLink.status} data-reaction-node-id={reactionLink.nodeId||''} data-reaction-foundation-id={reactionLink.foundationId||''}><div><b>Demanda estrutural por combinação · somente leitura</b><span>Apoio {reactionLink.nodeId||'—'} · {rv?.field||'reação'} {fmt(rv?.value,3)} {rv?.unit||''} · combinação {rv?.governingCombinationId||'—'}</span>{vectorText&&<small>{vectorText}</small>}</div><div><b data-testid="foundation-reaction-link-status">{reactionStatusText(reactionLink)}</b><small>Nenhum campo N/H/M, capacidade, punção, cisalhamento ou flexão da fundação foi alterado automaticamente.</small></div><div className="fd-actions">{reactionLink.status==='LINKED'&&<button data-testid="foundation-reaction-open-review" onClick={openFoundation}>Abrir fundação vinculada</button>}<button data-testid="foundation-reaction-clear" onClick={()=>{setReactionSource(null);setQuery('')}}>Limpar contexto</button></div></section>}
    <div className="fd-metrics"><button onClick={()=>setStatusFilter('ALL')}><b>{s.count}</b><span>fundações</span></button><button className="fail" onClick={()=>setStatusFilter('FAIL')}><b>{s.fail}</b><span>FAIL</span></button><button className="invalid" onClick={()=>setStatusFilter('INVALID')}><b>{s.invalid}</b><span>INVALID</span></button><button className="pending" onClick={()=>setStatusFilter('PENDING')}><b>{s.pending}</b><span>PENDING</span></button><button className="ready" onClick={()=>setStatusFilter('READY_FOR_REVIEW')}><b>{s.readyForReview}</b><span>ready for review</span></button><div><b>{s.normativePass}</b><span>normativo PASS</span></div><div><b>{s.ssiPhysicalReady}</b><span>SSI física pronta</span></div><div><b>{s.geotechnicalReady}</b><span>geotecnia pronta</span></div></div>
    <main className="fd-content">{rows.map((r:any)=>{const reactionLinked=reactionLink?.foundationId===r.foundationId;return <article key={r.foundationId} className={`fd-row ${statusClass(r.status)}${reactionLinked?' reaction-linked':''}`} data-testid={`foundation-decision-${r.foundationId}`} data-reaction-linked={reactionLinked?'true':'false'}><div className="fd-row-main"><div className="fd-id"><b>{r.label}</b><span>{r.foundationId} · {r.type} · nó {r.nodeId||'—'}</span>{reactionLinked&&<small>Reação governante em contexto · {rv?.governingCombinationId||'—'} · somente leitura</small>}</div><span className={`fd-status ${statusClass(r.status)}`}>{statusLabel[r.status]||r.status}</span><div className="fd-cell"><span>Normativo</span><b>{r.normative.status}</b><small>{r.normative.governing||'sem governante'}{r.normative.maxUtilization!=null?` · η ${fmt(r.normative.maxUtilization,2)}`:''}</small></div><div className="fd-cell"><span>SSI</span><b>{r.ssi.globalEnabled?r.ssi.state:'DESATIVADA'}</b><small>uz {fmt(r.ssi.settlementMm,2)} mm · Rz {fmt(r.ssi.verticalReactionKN,2)} kN</small></div><div className="fd-cell"><span>Contato</span><b>{r.ssi.averageContactPressureKPa==null?'—':`${fmt(r.ssi.averageContactPressureKPa,2)} kPa`}</b><small>q̄ discreta · sem superfície interpolada</small></div><div className="fd-cell"><span>Geotecnia</span><b>{r.geotechnical.state}</b><small>{r.geotechnical.profileLabel||r.geotechnical.profileId||'sem perfil'} · {r.geotechnical.layers} camada(s)</small></div></div><details><summary>Diagnóstico e recomendações</summary><div className="fd-details"><section><h4>Evidências</h4><p>Verificações: {r.normative.pass} PASS · {r.normative.fail} FAIL · {r.normative.pending} PENDING.</p><p>SSI: {r.ssi.stiffnessDefined}/6 rigidezes positivas explicitamente informadas{r.ssi.source?` · fonte: ${r.ssi.source}`:''}.</p><p>Perfil: {r.geotechnical.profileLabel||'—'} · método {r.geotechnical.method||'—'} · {r.geotechnical.explicitParameters} parâmetro(s) geotécnico(s) explícito(s){r.geotechnical.profileSource?` · fonte: ${r.geotechnical.profileSource}`:''}.</p><p>Estacas: {r.ssi.pileReactionState}.</p>{reactionLinked&&<p><b>Reação transitória:</b> {rv?.field||'—'} {fmt(rv?.value,3)} {rv?.unit||''} · combinação {rv?.governingCombinationId||'—'}; não persistida como demanda da fundação.</p>}</section><section><h4>Pendências</h4>{r.issues.length?r.issues.map((x:string,i:number)=><p key={i}>{x}</p>):<p>Nenhuma pendência automática neste escopo.</p>}</section><section><h4>Sugestões</h4>{r.suggestions.length?r.suggestions.map((x:any,i:number)=><p key={i}><b>{x.discipline}</b> · {x.message}</p>):<p>Sem sugestão automática. Prosseguir para revisão humana da solução.</p>}</section></div></details></article>})}{!rows.length&&<div className="fd-empty">{reactionLink?.status==='UNLINKED'?'Nenhuma fundação explicitamente vinculada ao apoio selecionado.':'Nenhuma fundação corresponde ao filtro atual.'}</div>}</main>
    <footer><span><b>Governança:</b> READY FOR REVIEW ≠ aprovação. Reações por combinação são contexto transitório; o vínculo usa somente nodeId explícito e não infere convenção de sinais, ações de dimensionamento ou capacidades.</span><button onClick={refresh}>Recarregar projeto</button></footer>
  </section></div>;
  return createPortal(shell,document.body);
}
