// Shared presentation layer for inspection-field/v1. Keeps solver data, legends,
// CSV and SVG rendering independent from each local mechanics Lab.
// @ts-ignore
import {inspectionFieldCsv,inspectionFieldRange,validateInspectionField} from '../../web/src/core/inspectionField.js';
import {esc,fmt} from './labUi';

function divergingColor(value:number,maxAbs:number){const t=Math.max(-1,Math.min(1,maxAbs>1e-14?value/maxAbs:0)),a=Math.abs(t);return t>=0?`rgb(${Math.round(238-65*a)},${Math.round(241-120*a)},${Math.round(244-86*a)})`:`rgb(${Math.round(238-122*a)},${Math.round(241-72*a)},${Math.round(244-24*a)})`}
function sequentialColor(value:number,min:number,max:number){const q=Math.max(0,Math.min(1,(value-min)/Math.max(1e-14,max-min)));return`rgb(${Math.round(224-105*q)},${Math.round(235-125*q)},${Math.round(244-65*q)})`}
export function fieldColor(field:any,value:number){const r=inspectionFieldRange(field);return field.scale?.symmetric?divergingColor(value,r.maxAbs):sequentialColor(value,r.min,r.max)}
export function fieldCsv(field:any){validateInspectionField(field);return inspectionFieldCsv(field)}
export function fieldLegendHtml(field:any){validateInspectionField(field);const r=inspectionFieldRange(field);return`<div class="core-lab-field-legend" title="${esc(field.contract)} · ${esc(field.provenance?.solverVersion||'')}"><span>${esc(field.label)}</span><i></i><span>${fmt(r.min,3)}…${fmt(r.max,3)} ${esc(field.unit)}</span></div>`}

export function pathFieldSvg(field:any,{testId='inspection-field',title=field?.label||'Campo',xLabel='Coordenada',width=760,height=300,className='core-lab-chart'}:any={}){
  validateInspectionField(field);const s=field.samples,w=width,h=height,p={x:62,y:34,w:width-112,h:height-84};
  const xs=s.map((q:any)=>Number.isFinite(q.s)?q.s:Number.isFinite(q.depth)?q.depth:q.index),ys=s.map((q:any)=>q.value),xmin=Math.min(...xs),xmax=Math.max(...xs),r=inspectionFieldRange(field),spanY=Math.max(1e-12,r.max-r.min),sx=(x:number)=>p.x+(x-xmin)/Math.max(1e-12,xmax-xmin)*p.w,sy=(y:number)=>p.y+p.h-(y-r.min)/spanY*p.h,path=s.map((q:any,i:number)=>`${i?'L':'M'} ${sx(xs[i]).toFixed(2)} ${sy(q.value).toFixed(2)}`).join(' '),dots=s.map((q:any,i:number)=>`<circle cx="${sx(xs[i])}" cy="${sy(q.value)}" r="2.2" fill="${fieldColor(field,q.value)}"><title>${esc(q.entityId||i)} · ${fmt(q.value,4)} ${esc(field.unit)}</title></circle>`).join('');
  return`<svg class="${className}" data-testid="${esc(testId)}" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}"><rect width="${w}" height="${h}" fill="#fff"/><text x="${p.x}" y="21" fill="#253744" font-size="12" font-weight="700">${esc(title)}</text><line x1="${p.x}" y1="${p.y+p.h}" x2="${p.x+p.w}" y2="${p.y+p.h}" stroke="#9daab4"/><line x1="${p.x}" y1="${p.y}" x2="${p.x}" y2="${p.y+p.h}" stroke="#9daab4"/><path d="${path}" fill="none" stroke="#326f9e" stroke-width="2.2"/>${dots}<text x="${p.x+p.w/2}" y="${h-17}" text-anchor="middle" fill="#344753" font-size="11">${esc(xLabel)}</text><text x="18" y="${p.y+p.h/2}" transform="rotate(-90 18 ${p.y+p.h/2})" text-anchor="middle" fill="#344753" font-size="11">${esc(field.label)} [${esc(field.unit)}]</text><text x="${p.x+p.w}" y="21" text-anchor="end" fill="#687986" font-size="9">${esc(field.contract)} · solver ${esc(field.provenance?.solverVersion||'—')}</text></svg>`;
}

export function pointFieldSvg(field:any,{testId='inspection-map',title=field?.label||'Campo',width=760,height=430,className='core-lab-chart'}:any={}){
  validateInspectionField(field);const pts=field.samples.filter((q:any)=>Number.isFinite(q.x)&&Number.isFinite(q.y));if(!pts.length)return pathFieldSvg(field,{testId,title,width,height,className});
  const xs=pts.map((q:any)=>q.x),ys=pts.map((q:any)=>q.y),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),span=Math.max(1e-6,xmax-xmin,ymax-ymin),p={x:58,y:40,w:width-150,h:height-82},sx=(x:number)=>p.x+(x-(xmin-.08*span))/(Math.max(1e-12,xmax-xmin+.16*span))*p.w,sy=(y:number)=>p.y+p.h-(y-(ymin-.08*span))/(Math.max(1e-12,ymax-ymin+.16*span))*p.h,maxAbs=Math.max(1e-12,...pts.map((q:any)=>Math.abs(q.value))),marks=pts.map((q:any)=>{const rad=3+5*Math.abs(q.value)/maxAbs;return`<circle cx="${sx(q.x)}" cy="${sy(q.y)}" r="${rad}" fill="${fieldColor(field,q.value)}" fill-opacity=".88"><title>${esc(q.entityId||'')} · ${fmt(q.value,4)} ${esc(field.unit)}</title></circle>`}).join('');
  return`<svg class="${className}" data-testid="${esc(testId)}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(title)}"><rect width="${width}" height="${height}" fill="#fff"/><text x="${p.x}" y="23" fill="#253744" font-size="12" font-weight="700">${esc(title)}</text><rect x="${p.x}" y="${p.y}" width="${p.w}" height="${p.h}" fill="#f7f9fa" stroke="#bac4cb"/>${marks}<text x="${width-82}" y="70" text-anchor="middle" fill="#344753" font-size="10">${esc(field.label)}</text>${Array.from({length:16},(_,i)=>`<rect x="${width-96}" y="${85+i*13}" width="28" height="14" fill="${fieldColor(field,-maxAbs+2*maxAbs*i/15)}"/>`).join('')}<text x="${width-62}" y="95" fill="#53646f" font-size="9">${fmt(maxAbs,2)}</text><text x="${width-62}" y="${85+15*13+10}" fill="#53646f" font-size="9">${fmt(-maxAbs,2)} ${esc(field.unit)}</text><text x="${p.x}" y="${height-12}" fill="#6a7984" font-size="9">${esc(field.contract)} · provenance ${esc(field.provenance?.sourceType||'')} / ${esc(field.provenance?.solverVersion||'')}</text></svg>`;
}
