import {registerIsolatedLab} from './labRegistry';
import {$,num,fmt,esc,downloadText,openCoreLab,kpi} from './labUi';
// @ts-ignore
import {generateExplicitHoleBoltGroup} from '../../web/src/solver/connectionPlateHoleContact2d.js';
// @ts-ignore
import {runHoleContactVerification,verificationSummaryCsv} from '../../web/src/solver/localVerification.js';

function openVerification(){
  const ui=openCoreLab({testId:'local-verification-lab',title:'Lab · Verificação numérica local',subtitle:'malha · cut-cell · contorno · kₙ · equilíbrio',warning:'Este módulo mede sensibilidade numérica do modelo de furo explícito; não aumenta artificialmente a precisão do solver. Avisos permanecem visíveis quando os critérios não são atendidos.',controlsHtml:`<h3>Referência</h3><div class="core-lab-form"><label>Malha X<input data-ver-mx value="6" type="number"></label><label>Malha Y<input data-ver-my value="4" type="number"></label><label>Quadratura<input data-ver-cut value="8" type="number"></label><label>Segmentos contorno<input data-ver-seg value="48" type="number"></label><label>kₙ [MPa/mm]<input data-ver-kn value="300" type="number"></label><label>Deslocamento [mm]<input data-ver-disp value="2.5" type="number"></label></div><div class="core-lab-actions"><button class="primary" data-testid="run-local-verification" data-ver-run>Executar estudos</button><button data-ver-csv disabled>Exportar verificação CSV</button></div><p class="core-lab-note">Critérios padrão: malha 5%, quadratura 2,5%, contorno 2,5%, sensibilidade kₙ 15%, equilíbrio 0,2%, área vazada 5%.</p>`});
  const run=$<HTMLButtonElement>('[data-ver-run]',ui.back)!,csv=$<HTMLButtonElement>('[data-ver-csv]',ui.back)!;let last:any=null;
  run.onclick=()=>{const old=run.textContent;try{run.disabled=true;run.textContent='Executando estudos…';const mx=Math.max(4,Math.round(num($<HTMLInputElement>('[data-ver-mx]',ui.back)?.value,6))),my=Math.max(4,Math.round(num($<HTMLInputElement>('[data-ver-my]',ui.back)?.value,4))),cut=Math.max(4,Math.round(num($<HTMLInputElement>('[data-ver-cut]',ui.back)?.value,8))),seg=Math.max(24,Math.round(num($<HTMLInputElement>('[data-ver-seg]',ui.back)?.value,48))),kn=num($<HTMLInputElement>('[data-ver-kn]',ui.back)?.value,300)*1e6,disp=num($<HTMLInputElement>('[data-ver-disp]',ui.back)?.value,2.5)/1000,bolts=generateExplicitHoleBoltGroup({nx:1,ny:1,centerX:.25,boltDiameter:.020,gap:.0005,contactNormalStiffness:kn}),input={length:.50,width:.30,thickness:.012,E:200e6,nu:.3,fy:355e3,meshX:mx,meshY:my,cutIntegrationOrder:cut,boundarySegments:seg,contactNormalStiffness:kn,edgeDisplacementMax:disp,steps:5,bolts},r=runHoleContactVerification(input,{meshLevels:[[Math.max(3,mx-2),my],[mx,my],[Math.min(28,mx+2),Math.min(22,my+2)]],quadratureOrders:[Math.max(4,cut-4),cut,Math.min(18,cut+4)],boundarySegments:[Math.max(24,Math.round(seg/2)),seg,Math.min(180,seg*2)],knFactors:[.5,1,2]});last=r;csv.disabled=false;const pct=(v:number)=>`${fmt(100*v,2)}%`,warnings=r.warnings.length?r.warnings.map((w:string)=>`<li>${esc(w)}</li>`).join(''):'<li>Nenhum aviso pelos critérios configurados.</li>',studyRows=Object.entries(r.studies).flatMap(([name,series]:any)=>series.map((p:any)=>`<tr><td>${esc(name)}</td><td>${esc(Array.isArray(p.parameter)?p.parameter.join('×'):p.parameter)}</td><td>${p.converged?'sim':'não'}</td><td>${fmt(p.load,2)}</td><td>${fmt(p.peakPressureMPa,1)}</td><td>${pct(p.forceResidual)}</td></tr>`)).join('');ui.results.innerHTML=`<h3>Diagnóstico</h3><div class="core-lab-summary">${kpi('Malha Δ',pct(r.indicators.meshDelta),'verification-kpi')}${kpi('Cut-cell Δ',pct(r.indicators.quadratureDelta),'verification-kpi')}${kpi('Contorno Δ',pct(r.indicators.angularDelta),'verification-kpi')}${kpi('kₙ sens.',pct(r.indicators.knSpread),'verification-kpi')}${kpi('Equilíbrio',pct(r.indicators.forceResidual),'verification-kpi')}${kpi('Área vazada',pct(r.indicators.areaError),'verification-kpi')}</div><div class="core-lab-warning" data-testid="verification-warnings"><b>${r.adequate?'Discretização adequada pelos critérios':'Refinamento recomendado'}</b><ul>${warnings}</ul></div><table class="core-lab-table" data-testid="verification-table"><thead><tr><th>Estudo</th><th>Parâmetro</th><th>Conv.</th><th>F [kN]</th><th>pmax [MPa]</th><th>Resíduo</th></tr></thead><tbody>${studyRows}</tbody></table><p class="core-lab-note">Trabalho externo = ${fmt(r.energyAccounting.externalWork,5)} kN·m · energia elástica de contato = ${fmt(r.energyAccounting.contactSpringEnergy,5)} kN·m. ${esc(r.energyAccounting.note)}</p>`}catch(e:any){alert(e?.message||String(e))}finally{run.disabled=false;run.textContent=old||'Executar estudos'}};
  csv.onclick=()=>last&&downloadText('local-verification.csv',verificationSummaryCsv(last),'text/csv;charset=utf-8');
}
registerIsolatedLab({id:'local-verification',title:'Verificação numérica · contato',description:'Convergência de malha/cut-cell/contorno, sensibilidade a kₙ, equilíbrio e contabilidade energética.',meta:'v0.30.9 · quality gate P2',order:70,testId:'open-local-verification-lab',open:openVerification});
export {};
