import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import { ErrorBoundary } from './ErrorBoundary';
import { IfcExchangeShell } from './IfcExchangeShell';
import { VnlWorkbench } from './VnlWorkbench';
import { ReliabilityWorkbench } from './ReliabilityWorkbench';
import { OptimizationWorkbench } from './OptimizationWorkbench';
import { AutomationWorkbench } from './AutomationWorkbench';
import { EngineeringReviewWorkbench } from './EngineeringReviewWorkbench';
import { MarketParityWorkbench } from './MarketParityWorkbench';
import { MarketParityAdvancedWorkbench } from './MarketParityAdvancedWorkbench';
import { WindDurabilityWorkbench } from './WindDurabilityWorkbench';
import { FoundationSSIWorkbench } from './FoundationSSIWorkbench';
import { GeotechnicalWorkbench } from './GeotechnicalWorkbench';
import { FoundationDecisionDashboard } from './FoundationDecisionDashboard';
import { EluElsDashboard } from './EluElsDashboard';
import { CombinationEnvelopeExplorer } from './CombinationEnvelopeExplorer';
import './styles.css';import './panels.css';import './analysis-v13.css';import './modeling.css';import './results.css';import './buckling.css';import './modern.css';import './modern-layout-fix.css';import './unified-toolbar.css';import './scientific-export.css';import './workspaceChrome.css';import './group-appearance.css';import './context-toolbar.css';import './spatial-inspector.css';import './spatial-contours.css';import './market-parity.css';import './market-parity-advanced.css';import './wind-durability.css';import './foundation-dashboard.css';import './elu-els-dashboard.css';
import './modernShell';import './scientificExportPanel';import './workspaceChrome';import './groupAppearanceWorkspace';import './marketParityBootstrap';import './marketParityAdvancedBootstrap';import './windDurabilityBootstrap';import './ssiBootstrap';import './geotechnicalBootstrap';import './foundationDashboardBootstrap';import './eluElsDashboardBootstrap';import './combinationEnvelopeBootstrap';import './contextToolbar';import './modelLabBootstrap';import './labRegistryBootstrap';import './advancedExamplesBootstrap';import './coreLocalLabsBootstrap';import './connectionPlateHoleContactLabBootstrap';import './localVerificationBootstrap';import './advancedConnectionLabsBootstrap';import './codeChecksLabBootstrap';import './dxfPlanBootstrap';import './levelsBootstrap';import './shellLabBootstrap';import './shellMeshBootstrap';import './shellRefinementBootstrap';import './shellAdaptiveBootstrap';import './shellQualityBootstrap';import './shellConvergenceBootstrap';import './shellQualityResultsBootstrap';import './vnlLegacyBridge';
const root=document.getElementById('root');if(!root)throw new Error('AstraStruct: elemento #root não encontrado.');
createRoot(root).render(<React.StrictMode><ErrorBoundary><IfcExchangeShell><><App/><VnlWorkbench/><ReliabilityWorkbench/><OptimizationWorkbench/><AutomationWorkbench/><EngineeringReviewWorkbench/><MarketParityWorkbench/><MarketParityAdvancedWorkbench/><WindDurabilityWorkbench/><FoundationSSIWorkbench/><GeotechnicalWorkbench/><FoundationDecisionDashboard/><EluElsDashboard/><CombinationEnvelopeExplorer/></></IfcExchangeShell></ErrorBoundary></React.StrictMode>);
requestAnimationFrame(()=>{document.documentElement.dataset.astraReady='true';(window as any).__ASTRA_BOOT_OK__?.();});
