import React, { useEffect, useMemo, useRef, useState } from 'react';
// @ts-ignore
import { makeFrameElement, makeTrussElement, uid } from '../../web/src/core/model.js';

export type ModelTool='select'|'node'|'frame2d'|'truss2d';
export type Selection={kind:'node'|'element';id:string}|null;
const VIEW={w:1000,h:680,p:90};
const clone=(v:any)=>JSON.parse(JSON.stringify(v));
const makeFrame:any=makeFrameElement;
const makeTruss:any=makeTrussElement;

function bounds(project:any){if(!project.nodes?.length)return{minX:0,maxX:10,minY:0,maxY:6};const xs=project.nodes.map((n:any)=>Number(n.x)||0),ys=project.nodes.map((n:any)=>Number(n.y)||0);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
function transform(project:any){const b=bounds(project),dx=Math.max(2,b.maxX-b.minX),dy=Math.max(2,b.maxY-b.minY),s=Math.min((VIEW.w-2*VIEW.p)/dx,(VIEW.h-2*VIEW.p)/dy);return{to:(x:number,y:number):[number,number]=>[VIEW.p+(x-b.minX)*s,VIEW.h-VIEW.p-(y-b.minY)*s],from:(X:number,Y:number):[number,number]=>[(X-VIEW.p)/s+b.minX,(VIEW.h-VIEW.p-Y)/s+b.minY],scale:s}}
function snap(project:any,v:number){const g=Number(project.settings?.grid)||.25;return project.settings?.snap===false?v:Math.round(v/g)*g}
function nearest(project:any,x:number,y:number,t=.28){return project.nodes.find((n:any)=>Math.hypot(n.x-x,n.y-y)<=t)}
function nextNodeId(project:any){let i=1;while(project.nodes.some((n:any)=>n.id===`N${i}`))i++;return`N${i}`}
function Support({node,project,to}:{node:any;project:any;to:(x:number,y:number)=>[number,number]}){const s=project.supports?.find((x:any)=>x.nodeId===node.id);if(!s||!(s.ux||s.uy||s.rz))return null;const[x,y]=to(node.x,node.y);if(s.ux&&s.uy&&s.rz)return <g className="support"><line x1={x-16} y1={y+14} x2={x+16} y2={y+14}/><line x1={x-13} y1={y+18} x2={x-5} y2={y+26}/><line x1={x-2} y1={y+18} x2={x+6} y2={y+26}/><line x1={x+9} y1={y+18} x2={x+17} y2={y+26}/></g>;if(s.uy)return <g className="support"><path d={`M ${x-13} ${y+17} L ${x+13} ${y+17} L ${x} ${y+3} Z`}/><circle cx={x-7} cy={y+22} r="3"/><circle cx={x+7} cy={y+22} r="3"/></g>;return <g className="support"><path d={`M ${x-13} ${y+17} L ${x+13} ${y+17} L ${x} ${y+3} Z`}/><line x1={x-18} y1={y+22} x2={x+18} y2={y+22}/></g>}

export function ModelingCanvas({project,result,tool,selection,onSelection,onCommit}:{project:any;result:any;tool:ModelTool;selection:Selection;onSelection:(s:Selection)=>void;onCommit:(p:any)=>void}){
  const svgRef=useRef<SVGSVGElement|null>(null);const [draft,setDraft]=useState<{x:number;y:number;nodeId?:string}|null>(null);const [cursor,setCursor]=useState<{x:number;y:number}|null>(null);const [drag,setDrag]=useState<{id:string;startX:number;startY:number}|null>(null);const [dragPoint,setDragPoint]=useState<{x:number;y:number}|null>(null);
  useEffect(()=>{setDraft(null);setCursor(null);setDrag(null);setDragPoint(null)},[tool]);
  const tf=useMemo(()=>transform(project),[project]);
  const displayProject=useMemo(()=>{if(!drag||!dragPoint)return project;const p=clone(project),n=p.nodes.find((x:any)=>x.id===drag.id);if(n){n.x=dragPoint.x;n.y=dragPoint.y}return p},[project,drag,dragPoint]);
  const activeCase=project.settings?.activeLoadCaseId||project.loadCases?.[0]?.id;const disp=new Map((result?.displacements||[]).map((d:any)=>[d.nodeId,d]));const maxDisp=Math.max(0,...(result?.displacements||[]).map((d:any)=>Math.hypot(d.ux||0,d.uy||0))),defScale=maxDisp>0?Math.min(80,Math.max(1,.8/maxDisp)):1;
  const eventWorld=(e:React.PointerEvent<SVGSVGElement>)=>{const svg=svgRef.current;if(!svg)return[0,0] as [number,number];const r=svg.getBoundingClientRect(),X=(e.clientX-r.left)*VIEW.w/r.width,Y=(e.clientY-r.top)*VIEW.h/r.height,[x,y]=tf.from(X,Y);return[snap(project,x),snap(project,y)] as [number,number]};
  const ensureNode=(p:any,x:number,y:number,nodeId?:string)=>{const existing=nodeId?p.nodes.find((n:any)=>n.id===nodeId):nearest(p,x,y);if(existing)return existing;const n={id:nextNodeId(p),x:+x.toFixed(5),y:+y.toFixed(5)};p.nodes.push(n);return n};
  const finishMember=(x:number,y:number,nodeId?:string)=>{if(!draft)return;const startNode=draft.nodeId?project.nodes.find((n:any)=>n.id===draft.nodeId):nearest(project,draft.x,draft.y),endNode=nodeId?project.nodes.find((n:any)=>n.id===nodeId):nearest(project,x,y);const sx=startNode?.x??draft.x,sy=startNode?.y??draft.y,ex=endNode?.x??x,ey=endNode?.y??y;if(Math.hypot(ex-sx,ey-sy)<1e-8){setDraft(null);return}const p=clone(project),n1=ensureNode(p,sx,sy,startNode?.id),n2=ensureNode(p,ex,ey,endNode?.id);if(tool==='truss2d')p.elements.push(makeTruss({id:uid('E'),n1:n1.id,n2:n2.id,label:'Treliça 2D'}));else p.elements.push(makeFrame({id:uid('E'),n1:n1.id,n2:n2.id,label:'Pórtico 2D'}));onCommit(p);setDraft(null);onSelection({kind:'element',id:p.elements[p.elements.length-1].id})};
  const backgroundPointer=(e:React.PointerEvent<SVGSVGElement>)=>{if((e.target as Element).closest?.('[data-entity]'))return;const[x,y]=eventWorld(e);if(tool==='select'){onSelection(null);return}if(tool==='node'){if(nearest(project,x,y))return;const p=clone(project),n=ensureNode(p,x,y);onCommit(p);onSelection({kind:'node',id:n.id});return}if(tool==='frame2d'||tool==='truss2d'){if(!draft)setDraft({x,y});else finishMember(x,y)}};
  const nodePointerDown=(e:React.PointerEvent,id:string)=>{e.stopPropagation();const n=project.nodes.find((x:any)=>x.id===id);if(tool==='select'){onSelection({kind:'node',id});if(n){setDrag({id,startX:n.x,startY:n.y});setDragPoint({x:n.x,y:n.y});(e.currentTarget as Element).setPointerCapture?.(e.pointerId)}}else if(tool==='frame2d'||tool==='truss2d'){if(!draft)setDraft({x:n.x,y:n.y,nodeId:id});else finishMember(n.x,n.y,id)}};
  const pointerMove=(e:React.PointerEvent<SVGSVGElement>)=>{const[x,y]=eventWorld(e);setCursor({x,y});if(drag)setDragPoint({x,y})};const pointerUp=()=>{if(drag&&dragPoint&&(Math.abs(dragPoint.x-drag.startX)>1e-12||Math.abs(dragPoint.y-drag.startY)>1e-12)){const p=clone(project),n=p.nodes.find((x:any)=>x.id===drag.id);if(n){n.x=dragPoint.x;n.y=dragPoint.y;onCommit(p)}}setDrag(null);setDragPoint(null)};
  const draftEnd=cursor&&draft?tf.to(cursor.x,cursor.y):null,draftStart=draft?tf.to(draft.x,draft.y):null;
  return <svg ref={svgRef} data-testid="model-canvas" className={`model-canvas modeling tool-${tool}`} viewBox={`0 0 ${VIEW.w} ${VIEW.h}`} role="img" aria-label="Modelo estrutural 2D" onPointerDown={backgroundPointer} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerLeave={pointerUp}>
    <defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3 z"/></marker></defs><g className="grid-lines">{Array.from({length:21},(_,i)=><line key={`v${i}`} x1={i*50} y1="0" x2={i*50} y2={VIEW.h}/>)}{Array.from({length:15},(_,i)=><line key={`h${i}`} x1="0" y1={i*50} x2={VIEW.w} y2={i*50}/>)}</g>
    {displayProject.elements?.map((e:any)=>{const a=displayProject.nodes.find((n:any)=>n.id===e.n1),b=displayProject.nodes.find((n:any)=>n.id===e.n2);if(!a||!b)return null;const[x1,y1]=tf.to(a.x,a.y),[x2,y2]=tf.to(b.x,b.y);return <g data-entity="element" key={e.id} className="clickable" onPointerDown={ev=>{ev.stopPropagation();if(tool==='select')onSelection({kind:'element',id:e.id})}}><line className={`member ${e.type==='truss2d'?'truss':''} ${selection?.kind==='element'&&selection.id===e.id?'selected':''}`} x1={x1} y1={y1} x2={x2} y2={y2}/><text className="element-label" x={(x1+x2)/2+8} y={(y1+y2)/2-8}>{e.id}</text></g>})}
    {result&&displayProject.elements?.map((e:any)=>{const a=displayProject.nodes.find((n:any)=>n.id===e.n1),b=displayProject.nodes.find((n:any)=>n.id===e.n2),da:any=disp.get(e.n1),db:any=disp.get(e.n2);if(!a||!b||!da||!db)return null;const[x1,y1]=tf.to(a.x+(da.ux||0)*defScale,a.y+(da.uy||0)*defScale),[x2,y2]=tf.to(b.x+(db.ux||0)*defScale,b.y+(db.uy||0)*defScale);return <line key={`d-${e.id}`} className="deformed" x1={x1} y1={y1} x2={x2} y2={y2}/>})}
    {displayProject.nodes?.map((n:any)=>{const[x,y]=tf.to(n.x,n.y);return <g data-entity="node" key={n.id} className="clickable" onPointerDown={e=>nodePointerDown(e,n.id)}><Support node={n} project={displayProject} to={tf.to}/><circle className={`node ${selection?.kind==='node'&&selection.id===n.id?'selected':''}`} cx={x} cy={y} r={selection?.kind==='node'&&selection.id===n.id?9:6}/><text className="node-label" x={x+10} y={y-10}>{n.id}</text></g>})}
    {project.loads?.filter((l:any)=>l.caseId===activeCase).map((l:any)=>{const n=displayProject.nodes.find((x:any)=>x.id===l.nodeId);if(!n)return null;const[x,y]=tf.to(n.x,n.y);if(Math.abs(l.fy||0)>1e-9){const y0=y+(l.fy<0?-70:70);return <g key={l.id} className="load"><line x1={x} y1={y0} x2={x} y2={y} markerEnd="url(#arrow)"/><text x={x+10} y={y0}>{Number(l.fy).toFixed(1)} kN</text></g>}if(Math.abs(l.fx||0)>1e-9){const x0=x+(l.fx>0?-70:70);return <g key={l.id} className="load"><line x1={x0} y1={y} x2={x} y2={y} markerEnd="url(#arrow)"/><text x={x0} y={y-10}>{Number(l.fx).toFixed(1)} kN</text></g>}return null})}
    {draftStart&&draftEnd&&<line className="draft-member" x1={draftStart[0]} y1={draftStart[1]} x2={draftEnd[0]} y2={draftEnd[1]}/>} {cursor&&tool!=='select'&&<circle className="cursor-snap" cx={tf.to(cursor.x,cursor.y)[0]} cy={tf.to(cursor.x,cursor.y)[1]} r="5"/>}
  </svg>
}
