import React, { useMemo } from 'react';
// @ts-ignore
import { solve } from '../../web/src/solver/index.js';

type Props={project:any;result:any;onClose:()=>void};
const fmt=(v:any,d=4)=>{const n=Number(v);if(!Number.isFinite(n))return'—';const a=Math.abs(n);return a>=1e4||(a>0&&a<1e-4)?n.toExponential(3):n.toFixed(d)};
function extrema(stations:any[],field:string){const values=stations.map(s=>Number(s[field])).filter(Number.isFinite);return values.length?{min:Math.min(...values),max:Math.max(...values),abs:Math.max(...values.map(Math.abs))}:{min:NaN,max:NaN,abs:NaN}}
function pointSummary(e:any){const pts=e.referenceLoad?.points||[];return pts.length?pts.map((p:any)=>`x/L=${fmt(p.xi,3)}: (${fmt(p.px,2)}, ${fmt(p.py,2)}) kN`).join('; '):'—'}
function hasThermal(e:any){const t=e?.thermal||{};return Math.abs(Number(t.dT)||0)+Math.abs(Number(t.dTGradient)||0)>1e-12}
function followerSummary(e:any){const a=e.followerEnds||[];return a.map((f:any)=>`ext.${f.end}: local (${fmt(f.px,3)}, ${fmt(f.py,3)}) kN → global (${fmt(f.currentGlobal?.fx,3)}, ${fmt(f.currentGlobal?.fy,3)}) kN`).join('; ')}

export function NonlinearReportPanel({project,result,onClose}:Props){
  const solved=useMemo(()=>{try{if(result?.analysisType==='corotational'&&result?.elementResponses?.length)return{value:result,error:''};const id=project.settings?.analysisScenarioId||project.loadCases?.[0]?.id;return{value:solve(project,id),error:''}}catch(e:any){return{value:null,error:e?.message||String(e)}}},[project,result]);
  const r=solved.value,history=r?.nonlinear?.history||[],last=history.at(-1),maxDisp=Math.max(0,...(r?.displacements||[]).map((d:any)=>Math.hypot(Number(d.ux)||0,Number(d.uy)||0)))*1000;
  const loaded=(r?.elementResponses||[]).filter((e:any)=>{const u=e.referenceLoad?.uniform||{},pts=e.referenceLoad?.points||[];return Math.abs(Number(u.qx)||0)+Math.abs(Number(u.qy)||0)+Math.abs(Number(e.referenceLoad?.selfWeight)||0)>1e-12||pts.length>0});
  const thermal=(r?.elementResponses||[]).filter((e:any)=>hasThermal(e)),followers=(r?.elementResponses||[]).filter((e:any)=>(e.followerEnds||[]).length),maxRecovery=Math.max(0,...(r?.elementResponses||[]).map((e:any)=>Number(e.loadRecovery?.equilibriumResidualAbs)||0));
  return <div className="react-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section data-testid="panel-nonlinear-report" className="react-modal wide" role="dialog" aria-modal="true" aria-label="Relatório técnico geometricamente não linear">
    <header className="react-modal-head"><div><h2>Relatório técnico · geom. não linear</h2><p>Registro do cenário resolvido pelo kernel co‑rotacional experimental v0.13.4.</p></div><button className="plain-icon" aria-label="Fechar" onClick={onClose}>×</button></header>
    {solved.error?<div className="panel-warning">{solved.error}</div>:<article className="report-preview" data-testid="nonlinear-report-preview"><header><div><b>AstraStruct</b><span>Relatório de análise geometricamente não linear</span></div><div><strong>{project.name}</strong><span>{new Date().toLocaleString('pt-BR')}</span></div></header>
      <h3>1. Identificação e escopo</h3><p><b>Cenário:</b> {r?.scenario?.name||r?.scenario?.id}. <b>Solver:</b> {r?.type}. <b>Versão:</b> {r?.solverVersion}. Formulação: pórtico plano Euler–Bernoulli co‑rotacional com equilíbrio incremental por Newton–Raphson{r?.nonlinear?.lineSearch?' e line search':''}.</p>
      <div className="metrics-row"><div><small>Nós</small><b>{project.nodes?.length||0}</b></div><div><small>Elementos</small><b>{project.elements?.length||0}</b></div><div><small>DOFs ativos</small><b>{r?.activeDofs??'—'}</b></div><div><small>Deslocamento máx.</small><b>{fmt(maxDisp,3)} mm</b></div></div>
      <h3>2. Controle incremental e convergência</h3><div className="metrics-row"><div><small>Incrementos</small><b>{r?.nonlinear?.steps}</b></div><div><small>Máx. iterações/passo</small><b>{r?.nonlinear?.maxIterations}</b></div><div><small>Tolerância</small><b>{Number(r?.nonlinear?.tolerance).toExponential(2)}</b></div><div><small>Último passo</small><b>{last?.iterations??'—'} it. · ‖r‖∞ {Number(last?.residualNorm||0).toExponential(2)}</b></div></div>
      <div className="table-scroll"><table><thead><tr><th>Passo</th><th>Fator de carga</th><th>Iterações</th><th>‖r‖∞</th></tr></thead><tbody>{history.map((h:any)=><tr key={h.step}><td>{h.step}</td><td>{fmt(h.loadFactor,4)}</td><td>{h.iterations}</td><td>{Number(h.residualNorm).toExponential(3)}</td></tr>)}</tbody></table></div>
      <h3>3. Cargas mecânicas mortas da referência</h3><p data-testid="nonlinear-load-model">Cargas nodais permanecem em eixos globais. Carga uniforme, peso próprio e carga pontual em barra são tratados como <b>dead loads da configuração inicial</b>: o vetor equivalente é calculado em L₀, α₀ e congelado durante Newton–Raphson. Essas ações não recebem tangente externa.</p>{loaded.length>0&&<><div className="metrics-row"><div><small>Elementos com carga de referência</small><b>{loaded.length}</b></div><div><small>Resíduo máx. recuperação N/V/M</small><b>{maxRecovery.toExponential(3)}</b></div></div><div className="table-scroll"><table><thead><tr><th>Elemento</th><th>qx₀ [kN/m]</th><th>qy₀ [kN/m]</th><th>Peso próprio [kN/m]</th><th>Cargas pontuais Px₀, Py₀</th><th>Resíduo rec.</th></tr></thead><tbody>{loaded.map((e:any)=>{const u=e.referenceLoad?.uniform||{};return <tr key={e.elementId}><td>{e.elementId}</td><td>{fmt(u.qx,4)}</td><td>{fmt(u.qy,4)}</td><td>{fmt(e.referenceLoad?.selfWeight,4)}</td><td>{pointSummary(e)}</td><td>{Number(e.loadRecovery?.equilibriumResidualAbs||0).toExponential(3)}</td></tr>})}</tbody></table></div></>}
      <h3>4. Estado térmico inicial</h3><p data-testid="nonlinear-thermal-model">A temperatura entra como <b>deformação axial e curvatura iniciais</b>: εT = α·ΔT e κT = −α·ΔTg/h. O estado térmico é incrementado com λ e as forças constitutivas resultam de kb(db − db,T).</p>{thermal.length>0?<div className="table-scroll"><table><thead><tr><th>Elemento</th><th>ΔT [°C]</th><th>ΔTg [°C]</th><th>α [1/°C]</th><th>h [m]</th><th>εT</th><th>κT [1/m]</th></tr></thead><tbody>{thermal.map((e:any)=>{const t=e.thermal||{};return <tr key={e.elementId}><td>{e.elementId}</td><td>{fmt(t.dT,3)}</td><td>{fmt(t.dTGradient,3)}</td><td>{Number(t.alpha||0).toExponential(3)}</td><td>{fmt(t.sectionHeight,4)}</td><td>{Number(t.eps0||0).toExponential(3)}</td><td>{Number(t.kappa0||0).toExponential(3)}</td></tr>})}</tbody></table></div>:<p>Não há ação térmica ativa no cenário atual.</p>}
      <h3>5. Forças seguidoras</h3><p data-testid="nonlinear-follower-model">Na v0.13.4, a ação follower disponível é uma força concentrada na <b>extremidade 2</b> do elemento. Suas componentes Px/Py são constantes nos eixos locais da corda corrente e, por isso, Fx/Fy globais dependem de α(q). A derivada <b>Kext=dP/dq</b> é montada explicitamente e Newton usa <b>(Kint − λKext)Δq = R</b>. A matriz externa é em geral não simétrica, compatível com a natureza não conservativa da carga.</p>{followers.length>0?<div className="table-scroll"><table><thead><tr><th>Elemento</th><th>Força local → global atual</th><th>max|Kext|</th><th>Tangente</th></tr></thead><tbody>{followers.map((e:any)=><tr key={e.elementId}><td>{e.elementId}</td><td>{followerSummary(e)}</td><td>{Math.max(...e.followerEnds.map((f:any)=>Number(f.tangentMaxAbs)||0)).toExponential(3)}</td><td>consistente</td></tr>)}</tbody></table></div>:<p>Não há força seguidora ativa no cenário atual.</p>}
      <h3>6. Deslocamentos nodais</h3><div className="table-scroll"><table><thead><tr><th>Nó</th><th>Ux [mm]</th><th>Uy [mm]</th><th>Rz [rad]</th></tr></thead><tbody>{(r?.displacements||[]).map((d:any)=><tr key={d.nodeId}><td>{d.nodeId}</td><td>{fmt((Number(d.ux)||0)*1000,4)}</td><td>{fmt((Number(d.uy)||0)*1000,4)}</td><td>{fmt(d.rz,6)}</td></tr>)}</tbody></table></div>
      <h3>7. Extremos por elemento na configuração corrente</h3><div className="table-scroll"><table><thead><tr><th>Elemento</th><th>L₀ [m]</th><th>L atual [m]</th><th>|N|max [kN]</th><th>|V|max [kN]</th><th>|M|max [kN·m]</th><th>|σ|max [MPa]</th></tr></thead><tbody>{(r?.elementResponses||[]).map((e:any)=>{const N=extrema(e.stations||[],'N'),V=extrema(e.stations||[],'V'),M=extrema(e.stations||[],'M'),S=extrema(e.stations||[],'sigmaAbs');return <tr key={e.elementId}><td>{e.elementId}</td><td>{fmt(e.L,4)}</td><td>{fmt(e.currentLength,4)}</td><td>{fmt(N.abs,3)}</td><td>{fmt(V.abs,3)}</td><td>{fmt(M.abs,3)}</td><td>{fmt(S.abs,3)}</td></tr>})}</tbody></table></div>
      <h3>8. Hipóteses e limitações</h3><p data-testid="nonlinear-report-limitations">Esta versão é <b>experimental e não normativa</b>. Escopo: frame2d Euler–Bernoulli, material elástico linear, extremidades rígidas, cargas nodais, UDL/peso próprio/carga pontual como dead loads de referência, temperatura como estado inicial e força seguidora concentrada apenas na extremidade 2 com tangente externa consistente. Não estão incluídos: follower distribuída ou em ponto interior da barra, follower moment, não linearidade material, contato, molas nodais, recalques, ligações semirrígidas, releases, imperfeição geométrica inicial no kernel co‑rotacional ou envelopes não lineares. Resultados profissionais exigem verificação independente adequada ao problema.</p>
    </article>}
    <div className="commit-bar"><span>Relatório do cenário atual; não representa verificação normativa automática.</span><div className="commit-actions"><button onClick={onClose}>Fechar</button><button className="primary" onClick={()=>window.print()}>Imprimir / PDF</button></div></div>
  </section></div>;
}
