import React, { useMemo, useState } from 'react';
// @ts-ignore
import { solve } from '../../web/src/solver/index.js';

type Props={project:any;result:any;onClose:()=>void};
const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const fmt=(v:any,d=3)=>{const n=Number(v);if(!Number.isFinite(n))return'—';const a=Math.abs(n);return a>=1e4||(a>0&&a<1e-3)?n.toExponential(3):n.toFixed(d)};

function MiniChart({points,field,label,unit,factor=1}:{points:any[];field:string;label:string;unit:string;factor?:number}){
  if(!points?.length)return <div className="chart-card empty-state">Sem dados.</div>;
  const W=560,H=190,L=48,R=14,T=22,B=30,xs=points.map(p=>num(p.x)),values=points.map(p=>num(p[field])*factor),min=Math.min(...values,0),max=Math.max(...values,0),span=Math.max(max-min,1e-9),lo=min-.1*span,hi=max+.1*span,x0=Math.min(...xs),x1=Math.max(...xs),sx=(x:number)=>L+(x-x0)/Math.max(x1-x0,1e-12)*(W-L-R),sy=(y:number)=>T+(hi-y)/Math.max(hi-lo,1e-12)*(H-T-B),path=points.map((p,i)=>`${i?'L':'M'} ${sx(num(p.x)).toFixed(1)} ${sy(num(p[field])*factor).toFixed(1)}`).join(' ');
  return <div className="chart-card"><div className="chart-title"><b>{label}</b><span>{fmt(min)} … {fmt(max)} {unit}</span></div><svg viewBox={`0 0 ${W} ${H}`} className="react-chart"><line x1={L} y1={T} x2={L} y2={H-B}/><line x1={L} y1={H-B} x2={W-R} y2={H-B}/>{lo<=0&&hi>=0&&<line className="zero" x1={L} y1={sy(0)} x2={W-R} y2={sy(0)}/>}<path className="line" d={path}/></svg></div>;
}

function extrema(points:any[],field:string){const a=points.map(p=>Number(p[field])).filter(Number.isFinite);return a.length?{min:Math.min(...a),max:Math.max(...a),abs:Math.max(...a.map(Math.abs))}:{min:NaN,max:NaN,abs:NaN}}

export function NonlinearPostprocessPanel({project,result,onClose}:Props){
  const solved=useMemo(()=>{try{if(result?.analysisType==='corotational'&&result?.elementResponses?.length)return{value:result,error:''};const id=project.settings?.analysisScenarioId||project.loadCases?.[0]?.id;return{value:solve(project,id),error:''}}catch(e:any){return{value:null,error:e?.message||String(e)}}},[project,result]);
  const responses=solved.value?.elementResponses||[], [elementId,setElementId]=useState(()=>responses[0]?.elementId||'');
  const response=responses.find((r:any)=>r.elementId===elementId)||responses[0],force=(solved.value?.elementForces||[]).find((f:any)=>f.elementId===response?.elementId),connections=force?.connectionRotations||[],points=response?.stations||[],history=solved.value?.nonlinear?.history||[],M=extrema(points,'M'),N=extrema(points,'N'),S=extrema(points,'sigmaAbs'),last=history.at(-1),uniform=response?.referenceLoad?.uniform||{},pointLoads=response?.referenceLoad?.points||[],currentPoints=response?.referenceLoad?.currentPoints||[],thermal=response?.thermal||{},followers=response?.followerEnds||[],hasReferenceLoad=Math.abs(num(uniform.qx))+Math.abs(num(uniform.qy))+Math.abs(num(response?.referenceLoad?.selfWeight))>1e-12||pointLoads.length>0,hasThermal=Math.abs(num(thermal.dT))+Math.abs(num(thermal.dTGradient))>1e-12,hasFollower=followers.length>0,hasConnections=connections.length>0,recovery=num(response?.loadRecovery?.equilibriumResidualAbs),connectionResidual=num(force?.connectionCondensation?.internalResidual);
  const pointText=pointLoads.map((p:any,i:number)=>{const current=currentPoints[i]||{};return `P${i+1}(x/L=${fmt(p.xi,3)}): Px₀=${fmt(p.px)} kN, Py₀=${fmt(p.py)} kN${Number.isFinite(Number(current.py))?`, Py atual=${fmt(current.py)} kN`:''}`}).join('; ');
  const followerText=followers.map((f:any,i:number)=>`F${i+1}@ext.${f.end}: Px=${fmt(f.px)} kN, Py=${fmt(f.py)} kN → Fx=${fmt(f.currentGlobal?.fx)} kN, Fy=${fmt(f.currentGlobal?.fy)} kN; max|Kext|=${Number(f.tangentMaxAbs||0).toExponential(3)}`).join('; ');
  const connectionText=connections.map((c:any)=>`ext.${c.end} ${c.type==='release'?'rótula':'semirrígida'}: kθ=${fmt(c.k)} kN·m/rad, θn=${fmt(c.nodeRotation,6)}, θe=${fmt(c.elementRotation,6)}, Δθ=${fmt(c.relativeRotation,6)} rad, M=${fmt(c.moment)} kN·m`).join('; ');
  return <div className="react-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section data-testid="panel-nonlinear-postprocess" className="react-modal wide" role="dialog" aria-modal="true" aria-label="Resultados geometricamente não lineares">
    <header className="react-modal-head"><div><h2>Resultados geometricamente não lineares</h2><p>Configuração corrente · cenário único · formulação co‑rotacional v0.13.5.</p></div><button className="plain-icon" aria-label="Fechar" onClick={onClose}>×</button></header>
    {solved.error?<div className="panel-warning">{solved.error}</div>:<>{response&&<div className="modal-toolbar"><label>Elemento<select data-testid="nonlinear-element-select" value={response.elementId} onChange={e=>setElementId(e.target.value)}>{responses.map((r:any)=><option key={r.elementId} value={r.elementId}>{r.elementId}</option>)}</select></label><span className="chip">{solved.value?.scenario?.name||solved.value?.scenario?.id}</span><span className="chip">{history.length} incrementos</span>{hasConnections&&<span className="chip">ligação flexível</span>}{hasReferenceLoad&&<span className="chip">carga morta de referência</span>}{hasThermal&&<span className="chip">estado térmico inicial</span>}{hasFollower&&<span className="chip">carga seguidora</span>}</div>}
    <div className="panel-warning" data-testid="nonlinear-envelope-note"><b>Envelope não linear desabilitado nesta versão.</b> Os gráficos abaixo pertencem somente ao cenário resolvido. A combinação de respostas de caminhos de equilíbrio distintos exige tratamento próprio e não é inferida automaticamente.</div>
    {hasConnections&&<div data-testid="connection-postprocess-note" className="panel-note"><b>Ligações de extremidade · condensação de Schur:</b> {connectionText}. A mola segue M=kθ(θn−θe); kθ=0 representa rótula. Resíduo máximo do equilíbrio interno das rotações condensadas: {connectionResidual.toExponential(3)}.</div>}
    {hasReferenceLoad&&<div data-testid="reference-load-postprocess-note" className="panel-note"><b>Modelo mecânico de referência:</b> carga uniforme/peso próprio e/ou carga pontual em barra convertidos em vetor nodal equivalente e congelados na configuração inicial. Não é carga seguidora. Para o elemento selecionado: qx₀={fmt(uniform.qx)} kN/m, qy₀={fmt(uniform.qy)} kN/m, peso próprio={fmt(response?.referenceLoad?.selfWeight)} kN/m{pointLoads.length?`. ${pointText}`:''}. Resíduo máximo de recuperação N/V/M: {recovery.toExponential(2)}.</div>}
    {hasThermal&&<div data-testid="thermal-postprocess-note" className="panel-note"><b>Estado térmico inicial:</b> ΔT={fmt(thermal.dT)} °C, ΔTg={fmt(thermal.dTGradient)} °C, α={Number(thermal.alpha||0).toExponential(3)} 1/°C, εT={Number(thermal.eps0||0).toExponential(3)}, κT={Number(thermal.kappa0||0).toExponential(3)} 1/m. A ação térmica entra em <b>db−db,T</b>; não é vetor de força externo.</div>}
    {hasFollower&&<div data-testid="follower-postprocess-note" className="panel-note"><b>Força seguidora não conservativa:</b> {followerText}. As componentes Px/Py permanecem constantes no sistema local da corda corrente; as componentes globais giram com α. Newton usa <b>Kint − λKext</b>, com Kext=dP/dq consistente e em geral não simétrica.</div>}
    {response&&<><div className="metrics-row"><div><small>Comprimento inicial</small><b>{fmt(response.L)} m</b></div><div><small>Comprimento corrente</small><b>{fmt(response.currentLength)} m</b></div><div><small>|N|max</small><b>{fmt(N.abs)} kN</b></div><div><small>|M|max</small><b>{fmt(M.abs)} kN·m</b></div><div><small>|σ|max</small><b>{fmt(S.abs)} MPa</b></div><div><small>Newton final</small><b>{last?.iterations??'—'} it.</b></div><div><small>Resíduo final</small><b>{Number.isFinite(Number(last?.residualNorm))?Number(last.residualNorm).toExponential(2):'—'}</b></div><div><small>Equilíbrio conexão</small><b>{hasConnections?connectionResidual.toExponential(2):'—'}</b></div></div>
    <div className="charts-grid"><MiniChart points={points} field="N" label="N(x)" unit="kN"/><MiniChart points={points} field="V" label="V(x)" unit="kN"/><MiniChart points={points} field="M" label="M(x)" unit="kN·m"/><MiniChart points={points} field="vLocal" label="v co‑rotante(x)" unit="mm" factor={1000}/><MiniChart points={points} field="sigmaTop" label="σ superior(x)" unit="MPa"/><MiniChart points={points} field="sigmaBottom" label="σ inferior(x)" unit="MPa"/></div></>}</>}
    <div className="commit-bar"><span>Grandezas na geometria corrente. N positivo = tração; M positivo = sagente conforme convenção do pós-processador.</span><div className="commit-actions"><button className="primary" onClick={onClose}>Fechar</button></div></div>
  </section></div>;
}
