import React, { useMemo, useState } from 'react';
// @ts-ignore
import { solve } from '../../web/src/solver/index.js';

type Props={project:any;result:any;onClose:()=>void};
const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const fmt=(v:any,d=3)=>{const n=Number(v);if(!Number.isFinite(n))return'—';const a=Math.abs(n);return a>=1e4||(a>0&&a<1e-3)?n.toExponential(3):n.toFixed(d)};
const fmtStiffness=(v:any)=>{const n=Number(v);if(!Number.isFinite(n))return'—';return Math.abs(n)<1e7?n.toLocaleString('en-US',{useGrouping:false,maximumFractionDigits:3}):n.toExponential(3)};
const maxTranslation=(rows:any[]|null|undefined)=>Math.max(0,...(Array.isArray(rows)?rows:[]).map(d=>Math.hypot(num(d.ux),num(d.uy))))*1000;

function MiniChart({points,field,label,unit,factor=1}:{points:any[];field:string;label:string;unit:string;factor?:number}){
  if(!points?.length)return <div className="chart-card empty-state">Sem dados.</div>;
  const W=560,H=190,L=48,R=14,T=22,B=30,xs=points.map(p=>num(p.x)),values=points.map(p=>num(p[field])*factor),min=Math.min(...values,0),max=Math.max(...values,0),span=Math.max(max-min,1e-9),lo=min-.1*span,hi=max+.1*span,x0=Math.min(...xs),x1=Math.max(...xs),sx=(x:number)=>L+(x-x0)/Math.max(x1-x0,1e-12)*(W-L-R),sy=(y:number)=>T+(hi-y)/Math.max(hi-lo,1e-12)*(H-T-B),path=points.map((p,i)=>`${i?'L':'M'} ${sx(num(p.x)).toFixed(1)} ${sy(num(p[field])*factor).toFixed(1)}`).join(' ');
  return <div className="chart-card"><div className="chart-title"><b>{label}</b><span>{fmt(min)} … {fmt(max)} {unit}</span></div><svg viewBox={`0 0 ${W} ${H}`} className="react-chart"><line x1={L} y1={T} x2={L} y2={H-B}/><line x1={L} y1={H-B} x2={W-R} y2={H-B}/>{lo<=0&&hi>=0&&<line className="zero" x1={L} y1={sy(0)} x2={W-R} y2={sy(0)}/>}<path className="line" d={path}/></svg></div>;
}

function PushoverChart({pushover}:{pushover:any}){
  const rows=pushover?.curve||[];if(!rows.length)return null;
  const rotational=pushover?.control?.dof==='rz',factor=rotational?1:1000,unit=rotational?'rad':'mm',W=650,H=250,L=58,R=18,T=28,B=38,xs=rows.map((r:any)=>num(r.controlledDisplacement)*factor),ys=rows.map((r:any)=>num(r.loadFactor)),xmin=Math.min(...xs,0),xmax=Math.max(...xs,0),ymin=Math.min(...ys,0),ymax=Math.max(...ys,0),dx=Math.max(xmax-xmin,1e-12),dy=Math.max(ymax-ymin,1e-12),xlo=xmin-.06*dx,xhi=xmax+.06*dx,ylo=ymin-.08*dy,yhi=ymax+.08*dy,sx=(x:number)=>L+(x-xlo)/Math.max(xhi-xlo,1e-12)*(W-L-R),sy=(y:number)=>T+(yhi-y)/Math.max(yhi-ylo,1e-12)*(H-T-B),path=rows.map((r:any,i:number)=>`${i?'L':'M'} ${sx(num(r.controlledDisplacement)*factor).toFixed(1)} ${sy(num(r.loadFactor)).toFixed(1)}`).join(' '),peak=rows.reduce((a:any,b:any)=>!a||Math.abs(num(b.loadFactor))>Math.abs(num(a.loadFactor))?b:a,null);
  return <div className="chart-card" data-testid="pushover-capacity-chart"><div className="chart-title"><b>Curva de capacidade · λ × {pushover.control?.nodeId}/{String(pushover.control?.dof||'').toUpperCase()}</b><span>u: {fmt(xmin,3)} … {fmt(xmax,3)} {unit} · λpico={fmt(peak?.loadFactor,4)}</span></div><svg viewBox={`0 0 ${W} ${H}`} className="react-chart"><line x1={L} y1={T} x2={L} y2={H-B}/><line x1={L} y1={H-B} x2={W-R} y2={H-B}/>{xlo<=0&&xhi>=0&&<line className="zero" x1={sx(0)} y1={T} x2={sx(0)} y2={H-B}/>} {ylo<=0&&yhi>=0&&<line className="zero" x1={L} y1={sy(0)} x2={W-R} y2={sy(0)}/>}<path className="line" d={path}/>{rows.filter((r:any)=>r.newlyYieldedHinges?.length).map((r:any)=><circle key={`yield-${r.step}`} cx={sx(num(r.controlledDisplacement)*factor)} cy={sy(num(r.loadFactor))} r="4"><title>{`Passo ${r.step}: nova plastificação · λ=${fmt(r.loadFactor,4)} · u=${fmt(num(r.controlledDisplacement)*factor,3)} ${unit}`}</title></circle>)}{peak&&<circle data-testid="pushover-peak-marker" cx={sx(num(peak.controlledDisplacement)*factor)} cy={sy(num(peak.loadFactor))} r="5"><title>{`Pico |λ| · passo ${peak.step}`}</title></circle>}</svg><div className="panel-note">Marcadores indicam início de plastificação de novas rótulas; o marcador de pico identifica o maior |λ| calculado no caminho.</div></div>;
}

function extrema(points:any[],field:string){const a=points.map(p=>Number(p[field])).filter(Number.isFinite);return a.length?{min:Math.min(...a),max:Math.max(...a),abs:Math.max(...a.map(Math.abs))}:{min:NaN,max:NaN,abs:NaN}}
function connectionLabel(c:any){return c?.type==='release'?'rótula ideal':c?.type==='fiber-hinge'?'rótula de fibras':'semirrígida'}

export function NonlinearPostprocessPanel({project,result,onClose}:Props){
  const solved=useMemo(()=>{try{if(result?.analysisType==='corotational'&&result?.elementResponses?.length)return{value:result,error:''};const id=project.settings?.analysisScenarioId||project.loadCases?.[0]?.id;return{value:solve(project,id),error:''}}catch(e:any){return{value:null,error:e?.message||String(e)}}},[project,result]);
  const responses=solved.value?.elementResponses||[], [elementId,setElementId]=useState(()=>responses[0]?.elementId||'');
  const response=responses.find((r:any)=>r.elementId===elementId)||responses[0],force=(solved.value?.elementForces||[]).find((f:any)=>f.elementId===response?.elementId),connections=force?.connectionRotations||[],points=response?.stations||[],history=solved.value?.nonlinear?.history||[],M=extrema(points,'M'),N=extrema(points,'N'),S=extrema(points,'sigmaAbs'),last=history.at(-1),uniform=response?.referenceLoad?.uniform||{},pointLoads=response?.referenceLoad?.points||[],currentPoints=response?.referenceLoad?.currentPoints||[],thermal=response?.thermal||{},followers=response?.followerEnds||[],hasReferenceLoad=Math.abs(num(uniform.qx))+Math.abs(num(uniform.qy))+Math.abs(num(response?.referenceLoad?.selfWeight))>1e-12||pointLoads.length>0,hasThermal=Math.abs(num(thermal.dT))+Math.abs(num(thermal.dTGradient))>1e-12,hasFollower=followers.length>0,hasConnections=connections.length>0,recovery=num(response?.loadRecovery?.equilibriumResidualAbs),connectionResidual=num(force?.connectionCondensation?.internalResidual),imperfection=solved.value?.imperfection,hasImperfection=!!imperfection?.enabled,initialMax=maxTranslation(solved.value?.initialDisplacements),incrementalMax=maxTranslation(solved.value?.displacements),totalMax=maxTranslation(solved.value?.totalDisplacements||solved.value?.displacements),material=solved.value?.materialNonlinearity,hasMaterial=!!material?.enabled,materialRecords=(material?.records||[]).filter((r:any)=>r.elementId===response?.elementId),pushover=solved.value?.pushover,hasPushover=!!pushover?.enabled,firstYield=pushover?.firstYield,controlUnit=pushover?.control?.dof==='rz'?'rad':'mm',controlFactor=pushover?.control?.dof==='rz'?1:1000;
  const pointText=pointLoads.map((p:any,i:number)=>{const current=currentPoints[i]||{};return `P${i+1}(x/L=${fmt(p.xi,3)}): Px₀=${fmt(p.px)} kN, Py₀=${fmt(p.py)} kN${Number.isFinite(Number(current.py))?`, Py atual=${fmt(current.py)} kN`:''}`}).join('; ');
  const followerText=followers.map((f:any,i:number)=>`F${i+1}@ext.${f.end}: Px=${fmt(f.px)} kN, Py=${fmt(f.py)} kN → Fx=${fmt(f.currentGlobal?.fx)} kN, Fy=${fmt(f.currentGlobal?.fy)} kN; max|Kext|=${Number(f.tangentMaxAbs||0).toExponential(3)}`).join('; ');
  const connectionText=connections.map((c:any)=>`ext.${c.end} ${connectionLabel(c)}: kθ=${fmtStiffness(c.k)} kN·m/rad, θn=${fmt(c.nodeRotation,6)}, θe=${fmt(c.elementRotation,6)}, Δθ=${fmt(c.relativeRotation,6)} rad, M=${fmt(c.moment)} kN·m`).join('; ');
  const materialText=materialRecords.map((r:any)=>`ext.${r.end}: Lp=${fmt(r.hingeLength,3)} m, Δθ=${fmt(r.rotation,6)} rad, N=${fmt(r.targetAxialForce)} kN, M=${fmt(r.constitutiveMoment)} kN·m, kt=${fmtStiffness(r.tangent)} kN·m/rad, ksec=${fmtStiffness(r.secantStiffness)} kN·m/rad, fibras escoadas=${r.yieldedFibers}/${r.fiberCount}, rM=${Number(r.momentResidual||0).toExponential(2)}, rN=${Number(r.axialResidual||0).toExponential(2)} kN`).join('; ');
  const solverLabel=solved.value?.solverVersion||'0.13.6-exp';
  return <div className="react-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section data-testid="panel-nonlinear-postprocess" className="react-modal wide" role="dialog" aria-modal="true" aria-label="Resultados geometricamente não lineares">
    <header className="react-modal-head"><div><h2>Resultados não lineares</h2><p>Configuração corrente · cenário único · solver {solverLabel}{hasMaterial?' · rótulas concentradas de fibras':''}.</p></div><button className="plain-icon" aria-label="Fechar" onClick={onClose}>×</button></header>
    {solved.error?<div className="panel-warning">{solved.error}</div>:<>{response&&<div className="modal-toolbar"><label>Elemento<select data-testid="nonlinear-element-select" value={response.elementId} onChange={e=>setElementId(e.target.value)}>{responses.map((r:any)=><option key={r.elementId} value={r.elementId}>{r.elementId}</option>)}</select></label><span className="chip">{solved.value?.scenario?.name||solved.value?.scenario?.id}</span><span className="chip">{history.length} incrementos</span>{hasPushover&&<span className="chip">pushover · deslocamento controlado</span>}{hasImperfection&&<span className="chip">geometria imperfeita</span>}{hasMaterial&&<span className="chip">material não linear</span>}{materialRecords.length>0&&<span className="chip">rótula de fibras</span>}{hasConnections&&<span className="chip">ligação flexível</span>}{hasReferenceLoad&&<span className="chip">carga morta de referência</span>}{hasThermal&&<span className="chip">estado térmico inicial</span>}{hasFollower&&<span className="chip">carga seguidora</span>}</div>}
    <div className="panel-warning" data-testid="nonlinear-envelope-note"><b>Envelope não linear desabilitado nesta versão.</b> Os gráficos abaixo pertencem somente ao cenário resolvido. A combinação de respostas de caminhos de equilíbrio distintos exige tratamento próprio e não é inferida automaticamente.</div>
    {hasPushover&&<div data-testid="pushover-summary" className="panel-note"><b>Pushover v0.16 · controle de deslocamento:</b> {pushover.control?.nodeId}/{String(pushover.control?.dof||'').toUpperCase()} → alvo {fmt(num(pushover.control?.targetDisplacement)*controlFactor,3)} {controlUnit}; λ final={fmt(pushover.finalLoadFactor,5)}, λ pico={fmt(pushover.peakLoadFactor,5)} em u={fmt(num(pushover.peakControlledDisplacement)*controlFactor,3)} {controlUnit}. {firstYield?<>Primeira plastificação no passo <b>{firstYield.step}</b>, λ={fmt(firstYield.loadFactor,5)}, u={fmt(num(firstYield.controlledDisplacement)*controlFactor,3)} {controlUnit}, em {(firstYield.hinges||[]).map((h:any)=>`${h.elementId}/ext.${h.end}`).join(', ')}.</>:<>Nenhuma rótula de fibras plastificou no caminho calculado.</>} Derivada de carga: {pushover.loadFactorDerivative}. Arc-length: não ativo.</div>}
    {hasImperfection&&<div data-testid="corotational-imperfection-note" className="panel-note"><b>Imperfeição geométrica modal:</b> modo {imperfection.mode}, e₀,max={fmt(imperfection.amplitudeMm,3)} mm, referência {imperfection.referenceScenarioId||'cenário atual'}, λcr={fmt(imperfection.criticalFactor,5)}. A sequência cinemática é <b>nominal → referência imperfeita sem tensões → equilíbrio corrente</b>. O solver mantém u₀, Δu e u total separados.</div>}
    {hasMaterial&&<div data-testid="material-postprocess-note" className="panel-note"><b>Não linearidade material v0.16:</b> rótulas concentradas de seção de fibras com aço bilinear monotônico e equilíbrio local N–M. Estratégia global: {material.globalStrategy||'iteração secante externa'}; acoplamento {material.coupling||'—'}, Newton local máx. {material.maxLocalIterations??'—'} it., iterações externas {material.outerIterations??0}, resíduo máximo de momento {Number(material.maxMomentResidual||0).toExponential(2)} kN·m. {materialRecords.length?materialText:'O elemento selecionado não possui rótula de fibras.'} <b>Importante:</b> os diagramas σ superior/inferior abaixo pertencem ao trecho elástico do frame e não substituem as tensões fibra a fibra da rótula plastificada.</div>}
    {hasConnections&&<div data-testid="connection-postprocess-note" className="panel-note"><b>Ligações de extremidade · condensação de Schur:</b> {connectionText}. Para ligações lineares, M=kθ(θn−θe); kθ=0 representa rótula ideal. Na rótula de fibras v0.16, a tangente constitutiva e o termo afim M0 são atualizados pelo Newton local e condensados por Schur. Resíduo máximo do equilíbrio interno das rotações condensadas: {connectionResidual.toExponential(3)}.</div>}
    {hasReferenceLoad&&<div data-testid="reference-load-postprocess-note" className="panel-note"><b>Modelo mecânico de referência:</b> carga uniforme/peso próprio e/ou carga pontual em barra convertidos em vetor nodal equivalente e congelados na configuração inicial. Não é carga seguidora. Para o elemento selecionado: qx₀={fmt(uniform.qx)} kN/m, qy₀={fmt(uniform.qy)} kN/m, peso próprio={fmt(response?.referenceLoad?.selfWeight)} kN/m{pointLoads.length?`. ${pointText}`:''}. Resíduo máximo de recuperação N/V/M: {recovery.toExponential(2)}.</div>}
    {hasThermal&&<div data-testid="thermal-postprocess-note" className="panel-note"><b>Estado térmico inicial:</b> ΔT={fmt(thermal.dT)} °C, ΔTg={fmt(thermal.dTGradient)} °C, α={Number(thermal.alpha||0).toExponential(3)} 1/°C, εT={Number(thermal.eps0||0).toExponential(3)}, κT={Number(thermal.kappa0||0).toExponential(3)} 1/m. A ação térmica entra em <b>db−db,T</b>; não é vetor de força externo.</div>}
    {hasFollower&&<div data-testid="follower-postprocess-note" className="panel-note"><b>Força seguidora não conservativa:</b> {followerText}. As componentes Px/Py permanecem constantes no sistema local da corda corrente; as componentes globais giram com α. Newton usa <b>Kint − λKext</b>, com Kext=dP/dq consistente e em geral não simétrica.</div>}
    {response&&<><div className="metrics-row"><div><small>{hasImperfection?'L referência':'Comprimento inicial'}</small><b>{fmt(response.L)} m</b></div>{hasImperfection&&<div><small>L nominal</small><b>{fmt(response.nominalLength)} m</b></div>}<div><small>Comprimento corrente</small><b>{fmt(response.currentLength)} m</b></div>{hasImperfection&&<><div><small>e₀,max</small><b>{fmt(initialMax,3)} mm</b></div><div><small>|Δu|max</small><b>{fmt(incrementalMax,3)} mm</b></div><div><small>|u total|max</small><b>{fmt(totalMax,3)} mm</b></div></>}<div><small>|N|max</small><b>{fmt(N.abs)} kN</b></div><div><small>|M|max</small><b>{fmt(M.abs)} kN·m</b></div><div><small>|σ| elástico máx.</small><b>{fmt(S.abs)} MPa</b></div>{hasPushover&&<><div><small>λ final</small><b>{fmt(pushover.finalLoadFactor,5)}</b></div><div><small>λ pico</small><b>{fmt(pushover.peakLoadFactor,5)}</b></div><div><small>u controlado final</small><b>{fmt(num(pushover.curve?.at(-1)?.controlledDisplacement)*controlFactor,3)} {controlUnit}</b></div></>}<div><small>Newton final</small><b>{last?.iterations??'—'} it.</b></div><div><small>Resíduo final</small><b>{Number.isFinite(Number(last?.residualNorm))?Number(last.residualNorm).toExponential(2):'—'}</b></div><div><small>Equilíbrio conexão</small><b>{hasConnections?connectionResidual.toExponential(2):'—'}</b></div>{hasMaterial&&<><div><small>Newton material local</small><b>{material.maxLocalIterations??material.outerIterations??'—'}</b></div><div><small>Resíduo M material</small><b>{Number(material.maxMomentResidual||0).toExponential(2)}</b></div></>}</div>
    {hasPushover&&<PushoverChart pushover={pushover}/>}<div className="charts-grid"><MiniChart points={points} field="N" label="N(x)" unit="kN"/><MiniChart points={points} field="V" label="V(x)" unit="kN"/><MiniChart points={points} field="M" label="M(x)" unit="kN·m"/><MiniChart points={points} field="vLocal" label="v co‑rotante(x)" unit="mm" factor={1000}/><MiniChart points={points} field="sigmaTop" label="σ elástica superior(x)" unit="MPa"/><MiniChart points={points} field="sigmaBottom" label="σ elástica inferior(x)" unit="MPa"/></div></>}</>}
    <div className="commit-bar"><span>Grandezas na geometria corrente. N positivo = tração; M positivo = sagente conforme convenção do pós-processador.</span><div className="commit-actions"><button className="primary" onClick={onClose}>Fechar</button></div></div>
  </section></div>;
}
