// Shell4 mesh-quality panel for Lab & Modelos.
// @ts-ignore
import {evaluateShellMeshQuality} from '../../web/src/core/shellQuality.js';

const STORAGE_KEY='astrastruct.project';
const $=<T extends Element=HTMLElement>(sel:string,root:ParentNode=document)=>root.querySelector(sel) as T|null;
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch));
const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function current(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}}
function shellIds(e:any){return(Array.isArray(e?.nodeIds)&&e.nodeIds.length===4?e.nodeIds:[e?.n1,e?.n2,e?.n3,e?.n4]).filter(Boolean)}
function statusLabel(s:string){return s==='good'?'Boa':s==='warning'?'Atenção':'Inválida'}
function statusClass(s:string){return s==='good'?'quality-good':s==='warning'?'quality-warning':'quality-invalid'}
function levelProject(project:any,levelId:string|null){if(!levelId)return project;const nodes:any[]=project.nodes||[],nodeMap=new Map<string,any>(nodes.map((n:any)=>[String(n.id),n])),elements=(project.elements||[]).filter((e:any)=>{if(e.type!=='shell4')return false;const first:any=nodeMap.get(String(shellIds(e)[0]));return String(e.levelId??first?.levelId??'')===String(levelId)});return{...project,elements}}
function fmt(v:any,d=3){return Number.isFinite(Number(v))?Number(v).toFixed(d):'—'}

function installStyle(){if(document.getElementById('astra-shell-quality-style'))return;const s=document.createElement('style');s.id='astra-shell-quality-style';s.textContent=`
.astra-shell-quality{margin-top:14px}.astra-shell-quality-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:7px;margin:10px 0}.astra-shell-quality-metrics>div{border:1px solid #2b4057;background:#0f1925;border-radius:8px;padding:8px}.astra-shell-quality-metrics span{display:block;color:#8ea2ba;font-size:10px}.astra-shell-quality-metrics b{font-size:13px;color:#edf4fd}.quality-good{color:#85d2a1!important}.quality-warning{color:#f0c36d!important}.quality-invalid{color:#ff8e98!important}.astra-shell-quality table{width:100%;border-collapse:collapse}.astra-shell-quality th,.astra-shell-quality td{font-size:11px;padding:6px 7px;border-bottom:1px solid #27384a;text-align:right;font-variant-numeric:tabular-nums}.astra-shell-quality th:first-child,.astra-shell-quality td:first-child,.astra-shell-quality th:nth-child(2),.astra-shell-quality td:nth-child(2){text-align:left}.astra-shell-quality-details{max-height:230px;overflow:auto;border:1px solid #293b50;border-radius:8px}.astra-shell-quality-note{color:#8fa2ba;font-size:11px;margin-top:7px}
`;document.head.appendChild(s)}

function render(panel:HTMLElement,body:HTMLElement){const project=current();if(!project){panel.innerHTML='<p>Projeto não carregado.</p>';return}const levelId=$<HTMLSelectElement>('[data-shell-level]',body)?.value||null,q=evaluateShellMeshQuality(levelProject(project,levelId)),w=q.worst;
  panel.innerHTML=`<h3>Qualidade da malha Q4</h3><p>Diagnóstico geométrico antes da montagem: Jacobiano, distorção, proporção, ângulos internos e coplanaridade.</p><div class="astra-shell-quality-metrics"><div><span>Boa</span><b class="quality-good">${q.counts.good}</b></div><div><span>Atenção</span><b class="quality-warning">${q.counts.warning}</b></div><div><span>Inválida</span><b class="quality-invalid">${q.counts.invalid}</b></div><div><span>J escalado mín.</span><b>${fmt(w.minScaledJacobian)}</b></div><div><span>Jmin/Jmax mín.</span><b>${fmt(w.jacobianRatio)}</b></div><div><span>Aspect máx.</span><b>${fmt(w.aspectRatio,2)}</b></div></div>${q.total?`<div class="astra-shell-quality-details"><table><thead><tr><th>Shell</th><th>Estado</th><th>Aspect</th><th>θ mín.</th><th>θ máx.</th><th>Jesc mín.</th><th>Jmin/Jmax</th></tr></thead><tbody>${q.items.map((x:any)=>`<tr title="${esc((x.issues||[]).join(' · ')||'Sem alertas geométricos')}"><td>${esc(x.id)}</td><td class="${statusClass(x.status)}">${statusLabel(x.status)}</td><td>${fmt(x.aspectRatio,2)}</td><td>${fmt(x.minAngle,1)}°</td><td>${fmt(x.maxAngle,1)}°</td><td>${fmt(x.minScaledJacobian)}</td><td>${fmt(x.jacobianRatio)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="astra-lab-note">Nenhum shell4 no nível selecionado.</div>'}<div class="astra-shell-quality-note">Critérios de atenção: aspect ratio &gt; 4, ângulo &lt; 30° ou &gt; 150°, Jacobiano escalado &lt; 0,35 ou Jmin/Jmax &lt; 0,25. Elementos com Jacobiano não positivo ou fora da tolerância de planicidade são inválidos.</div>`;
}

function patch(){installStyle();document.querySelectorAll<HTMLElement>('[data-testid="model-lab-overlay"]').forEach(overlay=>{const body=$<HTMLElement>('[data-lab-body]',overlay);if(!body||!body.querySelector('[data-shell-create]')||body.querySelector('[data-shell-quality-panel]'))return;const panel=document.createElement('section');panel.className='astra-model-card astra-shell-quality';panel.setAttribute('data-shell-quality-panel','');panel.setAttribute('data-testid','shell4-quality-panel');const refinement=$<HTMLElement>('[data-shell-refinement]',body),anchor=refinement||body.querySelector<HTMLElement>('.astra-shell-list');(anchor||body).insertAdjacentElement('afterend',panel);const level=$<HTMLSelectElement>('[data-shell-level]',body);level?.addEventListener('change',()=>render(panel,body));render(panel,body)})}
const observer=new MutationObserver(patch);observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch,{once:true});else patch();
