// Shell4 slab launcher injected into Lab & Modelos.
// It uses the persisted project contract so the generated slab reopens directly in React.
// @ts-ignore
import { assignLevels, deriveLevels } from '../../web/src/core/levels.js';
// @ts-ignore
import { uid } from '../../web/src/core/model.js';

const STORAGE_KEY='astrastruct.project';
const $=<T extends Element=HTMLElement>(sel:string,root:ParentNode=document)=>root.querySelector(sel) as T|null;
const clone=(v:any)=>JSON.parse(JSON.stringify(v));
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch));
const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function current(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}}
function save(p:any){p.meta={...(p.meta||{}),shell4UpdatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(p));location.reload()}
function shellNodes(e:any){return(Array.isArray(e?.nodeIds)&&e.nodeIds.length===4?e.nodeIds:[e?.n1,e?.n2,e?.n3,e?.n4]).filter(Boolean)}

function installStyle(){if(document.getElementById('astra-shell-lab-style'))return;const s=document.createElement('style');s.id='astra-shell-lab-style';s.textContent=`
.astra-shell-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;margin:12px 0}.astra-shell-metric{border:1px solid #2b4057;background:#111d2b;border-radius:9px;padding:9px 10px}.astra-shell-metric span{display:block;color:#8ea2ba;font-size:11px}.astra-shell-metric b{display:block;margin-top:2px;color:#edf4fd;font-size:13px}.astra-shell-list{margin-top:15px;max-height:240px;overflow:auto}.astra-shell-list table{width:100%;border-collapse:collapse}.astra-shell-list th,.astra-shell-list td{padding:7px 8px;border-bottom:1px solid #26374a;text-align:left;font-size:12px}.astra-shell-list th{color:#9fb1c5;position:sticky;top:0;background:#101822}.astra-shell-list button{padding:4px 7px;border:1px solid #5b3940;background:#28171b;color:#ffb6bd;border-radius:6px;cursor:pointer}.astra-shell-node-order{display:grid;grid-template-columns:repeat(4,minmax(110px,1fr));gap:8px}.astra-shell-node-order label{display:grid;gap:4px;color:#aab9cc}.astra-shell-node-order select,.astra-shell-select{width:100%;box-sizing:border-box;border:1px solid #334961;background:#0c131d;color:#eef4ff;border-radius:8px;padding:9px}@media(max-width:720px){.astra-shell-node-order{grid-template-columns:repeat(2,minmax(110px,1fr))}}
`;document.head.appendChild(s)}

function renderShells(body:HTMLElement){
  const raw=current();if(!raw){body.innerHTML='<p class="astra-lab-note">Nenhum projeto carregado.</p>';return}const p=assignLevels(raw),levels=deriveLevels(p),shells=(p.elements||[]).filter((e:any)=>e.type==='shell4'),activeCase=p.settings?.activeLoadCaseId||p.loadCases?.[0]?.id||'LC1';
  const levelOptions=levels.map((l:any)=>`<option value="${esc(l.id)}">${esc(l.name)} · Z=${num(l.elevation).toFixed(3)} m</option>`).join(''),materialOptions=(p.materials||[]).map((m:any)=>`<option value="${esc(m.id)}" ${String(m.type).toLowerCase()==='concrete'?'selected':''}>${esc(m.name||m.id)}</option>`).join('');
  body.innerHTML=`<p class="astra-lab-note"><b>Lajes / Shell4:</b> crie uma casca plana Q4 Mindlin–Reissner escolhendo quatro nós de um mesmo nível. O recurso está habilitado somente para análise linear 3D nesta etapa.</p>
  <div class="astra-shell-summary"><div class="astra-shell-metric"><span>Níveis</span><b>${levels.length}</b></div><div class="astra-shell-metric"><span>Shells existentes</span><b>${shells.length}</b></div><div class="astra-shell-metric"><span>Caso ativo</span><b>${esc(activeCase)}</b></div><div class="astra-shell-metric"><span>Formulação</span><b>Q4 Mindlin–Reissner</b></div></div>
  <div class="astra-form-grid"><label>Nível<select class="astra-shell-select" data-shell-level>${levelOptions}</select></label><label>Material<select class="astra-shell-select" data-shell-material>${materialOptions}</select></label><label>Nome<input data-shell-name value="Laje shell4"></label><label>Espessura t [m]<input data-shell-t type="number" min="0.00001" step="0.01" value="0.18"></label><label>Pressão local +z [kN/m²]<input data-shell-p type="number" step="1" value="-5"></label><label>κ cisalhamento<input data-shell-kappa type="number" min="0.05" max="1" step="0.01" value="0.833333"></label></div>
  <h4 style="margin:14px 0 8px">Vértices em ordem de contorno</h4><div class="astra-shell-node-order" data-shell-nodes></div><p class="astra-plan-help">Selecione os quatro cantos percorrendo a face sem cruzar diagonais. Para uma laje horizontal vista de cima, uma ordem anti-horária produz normal local +z para cima.</p>
  <div class="astra-form-actions"><button class="astra-lab-btn primary" data-testid="create-shell4" data-shell-create>Criar shell4</button><button class="astra-lab-btn" data-shell-refresh>Recarregar níveis</button></div>
  <div class="astra-shell-list"><table><thead><tr><th>Shell</th><th>Nível</th><th>Nós</th><th>t [m]</th><th>Pressão</th><th></th></tr></thead><tbody>${shells.length?shells.map((e:any)=>{const ids=shellNodes(e),level=p.nodes.find((n:any)=>String(n.id)===String(ids[0]))?.levelId||'—',load=(p.elementLoads||[]).find((l:any)=>l.elementId===e.id&&(l.kind==='surface'||l.kind==='pressure'));return`<tr><td>${esc(e.id)}</td><td>${esc(level)}</td><td>${esc(ids.join(' · '))}</td><td>${num(e.thickness??e.t).toFixed(3)}</td><td>${num(load?.pressure??load?.pz??load?.qz).toFixed(2)}</td><td><button data-shell-delete="${esc(e.id)}">Excluir</button></td></tr>`}).join(''):'<tr><td colspan="6">Nenhum shell4 no projeto.</td></tr>'}</tbody></table></div>`;
  const levelSel=$<HTMLSelectElement>('[data-shell-level]',body)!,nodesHost=$<HTMLElement>('[data-shell-nodes]',body)!;
  const renderNodes=()=>{const level=levels.find((l:any)=>String(l.id)===String(levelSel.value)),candidates=(p.nodes||[]).filter((n:any)=>String(n.levelId)===String(level?.id)||Math.abs(num(n.z)-num(level?.elevation))<=1e-5);const opts=candidates.map((n:any)=>`<option value="${esc(n.id)}">${esc(n.id)} · (${num(n.x).toFixed(2)}, ${num(n.y).toFixed(2)})</option>`).join('');nodesHost.innerHTML=[0,1,2,3].map(i=>`<label>Nó ${i+1}<select data-shell-node="${i}" ${candidates.length<4?'disabled':''}>${opts}</select></label>`).join('');const sels=[...nodesHost.querySelectorAll<HTMLSelectElement>('select[data-shell-node]')];sels.forEach((s,i)=>{if(candidates[i])s.value=String(candidates[i].id)})};
  levelSel.onchange=renderNodes;renderNodes();
  ($<HTMLButtonElement>('[data-shell-refresh]',body)!).onclick=()=>renderShells(body);
  ($<HTMLButtonElement>('[data-shell-create]',body)!).onclick=()=>{try{const level=levels.find((l:any)=>String(l.id)===String(levelSel.value)),ids=[...nodesHost.querySelectorAll<HTMLSelectElement>('select[data-shell-node]')].map(s=>s.value);if(ids.length!==4||new Set(ids).size!==4)throw new Error('Selecione quatro nós distintos.');const levelIds=new Set((p.nodes||[]).filter((n:any)=>String(n.levelId)===String(level?.id)||Math.abs(num(n.z)-num(level?.elevation))<=1e-5).map((n:any)=>String(n.id)));if(ids.some(id=>!levelIds.has(String(id))))throw new Error('Todos os nós do shell devem pertencer ao nível selecionado.');const used=new Set((p.elements||[]).map((e:any)=>String(e.id)));let id=`SHELL_${shells.length+1}`,i=2;while(used.has(id))id=`SHELL_${shells.length+1}_${i++}`;const t=Math.max(1e-5,num(($<HTMLInputElement>('[data-shell-t]',body)!).value,.18)),pressure=num(($<HTMLInputElement>('[data-shell-p]',body)!).value),materialId=($<HTMLSelectElement>('[data-shell-material]',body)!).value,kappa=Math.max(.05,Math.min(1,num(($<HTMLInputElement>('[data-shell-kappa]',body)!).value,5/6))),label=($<HTMLInputElement>('[data-shell-name]',body)!).value||id,e={id,type:'shell4',nodeIds:ids,n1:ids[0],n2:ids[1],n3:ids[2],n4:ids[3],materialId,thickness:t,shearCorrection:kappa,drillingFactor:1e-6,label,levelId:level?.id};p.elements=[...(p.elements||[]),e];if(Math.abs(pressure)>1e-12)p.elementLoads=[...(p.elementLoads||[]),{id:uid('SURF'),caseId:activeCase,elementId:id,kind:'surface',pressure}];p.settings={...(p.settings||{}),analysisType:'linear'};save(p)}catch(err:any){alert(err?.message||String(err))}};
  body.querySelectorAll<HTMLButtonElement>('[data-shell-delete]').forEach(b=>b.onclick=()=>{const id=String(b.dataset.shellDelete);if(!confirm(`Excluir ${id}?`))return;const next=clone(p);next.elements=(next.elements||[]).filter((e:any)=>String(e.id)!==id);next.elementLoads=(next.elementLoads||[]).filter((l:any)=>String(l.elementId)!==id);save(next)});
}

function patch(){installStyle();document.querySelectorAll<HTMLElement>('[data-testid="model-lab-overlay"]').forEach(overlay=>{const tabs=$<HTMLElement>('.astra-lab-tabs',overlay),body=$<HTMLElement>('[data-lab-body]',overlay);if(!tabs||!body||tabs.querySelector('[data-tab="shells"]'))return;const b=document.createElement('button');b.textContent='Lajes / Shell4';b.dataset.tab='shells';b.setAttribute('data-testid','shell4-lab-tab');b.onclick=()=>{tabs.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderShells(body)};tabs.appendChild(b)})}
const observer=new MutationObserver(patch);observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch,{once:true});else patch();
