// Shell4 mesh convergence study for Lab & Modelos.
// @ts-ignore
import {runShellMeshConvergence} from '../../web/src/core/shellConvergence.js';
// @ts-ignore
import {solve} from '../../web/src/solver/index.js';

const STORAGE_KEY='astrastruct.project';
const $=<T extends Element=HTMLElement>(sel:string,root:ParentNode=document)=>root.querySelector(sel) as T|null;
const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const studies=new WeakMap<HTMLElement,any>();
const runConvergence:any=runShellMeshConvergence;
function current(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}}
function save(p:any){localStorage.setItem(STORAGE_KEY,JSON.stringify(p));location.reload()}
function fmt(v:any,d=4){return Number.isFinite(Number(v))?Number(v).toFixed(d):'—'}
function metricLabel(metric:string){return({maxAbsUz:'|Uz| máx. [m]',maxAbsU:'|u| máx. [m]',maxAbsMx:'|Mx| máx.',maxAbsMy:'|My| máx.',maxAbsMxy:'|Mxy| máx.',maxAbsQx:'|Qx| máx.',maxAbsQy:'|Qy| máx.'} as any)[metric]||metric}
function installStyle(){if(document.getElementById('astra-shell-convergence-style'))return;const s=document.createElement('style');s.id='astra-shell-convergence-style';s.textContent=`.astra-shell-convergence table{width:100%;border-collapse:collapse;margin-top:8px}.astra-shell-convergence th,.astra-shell-convergence td{font-size:11px;padding:6px 7px;border-bottom:1px solid #2d4054;text-align:right;font-variant-numeric:tabular-nums}.astra-shell-convergence th:first-child,.astra-shell-convergence td:first-child{text-align:left}.astra-shell-convergence .conv-ok{color:#85d2a1}.astra-shell-convergence .conv-pending{color:#f0c36d}.astra-shell-convergence [data-conv-result]{margin-top:9px}.astra-shell-convergence .conv-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}`;document.head.appendChild(s)}
function renderResult(host:HTMLElement,out:any){const r=out?.report;if(!r)return;const rows=(r.steps||[]).map((x:any)=>`<tr><td>${x.divisions}×${x.divisions}</td><td>${x.shells}</td><td>${x.nodes}</td><td>${fmt(x.value,6)}</td><td>${x.relativeChange==null?'—':`${fmt(100*x.relativeChange,2)}%`}</td><td>${fmt(x.quality?.worst?.minScaledJacobian,3)}</td></tr>`).join(''),result=$<HTMLElement>('[data-conv-result]',host);if(!result)return;result.innerHTML=`<div class="${r.converged?'conv-ok':'conv-pending'}"><b>${r.converged?'Convergência atingida':'Limite de refinamento atingido'}</b> · malha recomendada ${r.recommendedDivisions}×${r.recommendedDivisions} · critério ${metricLabel(r.metric)} · tolerância ${(100*r.tolerance).toFixed(2)}%</div><div class="table-wrap"><table><thead><tr><th>Malha</th><th>Shells</th><th>Nós</th><th>Métrica</th><th>Δ relativo</th><th>Jesc mín.</th></tr></thead><tbody>${rows}</tbody></table></div>`;const apply=$<HTMLButtonElement>('[data-conv-apply]',host);if(apply)apply.disabled=false}
function patch(){installStyle();document.querySelectorAll<HTMLElement>('[data-testid="model-lab-overlay"]').forEach(overlay=>{const body=$<HTMLElement>('[data-lab-body]',overlay);if(!body||!body.querySelector('[data-shell-create]')||body.querySelector('[data-shell-convergence]'))return;const host=document.createElement('section');host.className='astra-model-card astra-shell-convergence';host.setAttribute('data-shell-convergence','');host.setAttribute('data-testid','shell4-convergence-controls');host.innerHTML=`<h3>Convergência de malha shell4</h3><p>Executa a análise linear em malhas progressivamente refinadas e compara a resposta até atingir a tolerância escolhida. O estudo não altera o modelo até confirmar a malha recomendada.</p><div class="astra-form-grid"><label>Métrica<select data-conv-metric><option value="maxAbsUz">|Uz| máximo</option><option value="maxAbsU">|u| máximo</option><option value="maxAbsMx">|Mx| máximo</option><option value="maxAbsMy">|My| máximo</option><option value="maxAbsMxy">|Mxy| máximo</option><option value="maxAbsQx">|Qx| máximo</option><option value="maxAbsQy">|Qy| máximo</option></select></label><label>Tolerância [%]<input data-conv-tol type="number" min="0.1" max="20" step="0.1" value="3"></label><label>Refinamento máximo<input data-conv-max type="number" min="2" max="6" step="1" value="4"></label></div><div class="conv-actions"><button class="astra-lab-btn primary" data-testid="run-shell4-convergence" data-conv-run>Estudar convergência</button><button class="astra-lab-btn" data-testid="apply-shell4-convergence" data-conv-apply disabled>Aplicar malha recomendada</button></div><div data-conv-result><small>Sequência padrão: 1×1, 2×2, … até o limite definido. Elementos geometricamente inválidos interrompem o estudo.</small></div>`;const quality=$<HTMLElement>('[data-shell-quality-panel]',body),refinement=$<HTMLElement>('[data-shell-refinement]',body),anchor=quality||refinement||body.querySelector<HTMLElement>('.astra-shell-list');(anchor||body).insertAdjacentElement('afterend',host);
    const run=$<HTMLButtonElement>('[data-conv-run]',host)!,apply=$<HTMLButtonElement>('[data-conv-apply]',host)!;run.onclick=()=>{const old=run.textContent;try{const p=current();if(!p)throw new Error('Projeto não carregado.');if(String(p.settings?.analysisType||'linear')!=='linear')throw new Error('O estudo de convergência shell4 requer análise Linear.');const levelId=$<HTMLSelectElement>('[data-shell-level]',body)?.value||null,metric=$<HTMLSelectElement>('[data-conv-metric]',host)?.value||'maxAbsUz',tol=Math.max(.001,Math.min(.2,num($<HTMLInputElement>('[data-conv-tol]',host)?.value,3)/100)),maxDiv=Math.max(2,Math.min(6,Math.round(num($<HTMLInputElement>('[data-conv-max]',host)?.value,4)))),divisions=Array.from({length:maxDiv},(_,i)=>i+1);run.disabled=true;run.textContent='Calculando…';const out=runConvergence(p,{solveModel:solve,scenarioId:p.settings?.analysisScenarioId||p.settings?.activeLoadCaseId||p.loadCases?.[0]?.id,levelId,divisions,tolerance:tol,maxDivisions:maxDiv});studies.set(host,out);renderResult(host,out)}catch(err:any){alert(err?.message||String(err))}finally{run.disabled=false;run.textContent=old||'Estudar convergência'}};apply.onclick=()=>{const out=studies.get(host);if(!out?.project)return;save(out.project)};
  })}
const observer=new MutationObserver(()=>patch());observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch,{once:true});else patch();
