// Recovery-based adaptive shell4 refinement controls for Lab & Modelos.
// @ts-ignore
import {planAdaptiveShellRefinement,applyAdaptiveShellRefinement} from '../../web/src/core/shellAdaptiveRefinement.js';
// @ts-ignore
import {solve} from '../../web/src/solver/index.js';

const STORAGE_KEY='astrastruct.project';
const $=<T extends Element=HTMLElement>(sel:string,root:ParentNode=document)=>root.querySelector(sel) as T|null;
const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const plans=new WeakMap<HTMLElement,any>();
function current(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}}
function save(p:any){localStorage.setItem(STORAGE_KEY,JSON.stringify(p));location.reload()}
function fmt(v:any,d=2){return Number.isFinite(Number(v))?Number(v).toFixed(d):'—'}
function fieldLabel(v:string){return({Mx:'Mx',My:'My',Mxy:'Mxy',Qx:'Qx',Qy:'Qy',Nx:'Nx',Ny:'Ny',Nxy:'Nxy'} as any)[v]||v}
function render(host:HTMLElement,out:any){
  const result=$<HTMLElement>('[data-adaptive-result]',host),apply=$<HTMLButtonElement>('[data-adaptive-apply]',host);if(!result||!apply)return;const e=out?.estimate,sp=out?.splitPlan;if(!e||!sp)return;
  const rows=(e.items||[]).slice(0,10).map((x:any)=>`<tr class="${x.marked?'adaptive-marked':''}"><td>${x.elementId}</td><td>${fmt(100*x.relativeError,2)}%</td><td>${fmt(x.rmsError,4)}</td><td>${x.marked?'refinar':'—'}</td></tr>`).join('');
  const nonManifold=(sp.nonManifoldEdges||[]).length,canApply=sp.refinedCount>0&&!nonManifold;apply.disabled=!canApply;
  result.innerHTML=`<div class="${canApply?'conv-pending':sp.refinedCount?'adaptive-warning':'conv-ok'}"><b>${sp.markedIds.length} hotspot(s)</b> · ${sp.transitionIds.length} transição(ões) · 2×2: ${sp.full.length} · 2×1: ${sp.xOnly.length} · 1×2: ${sp.yOnly.length} · malha prevista: ${sp.predictedShellCount} shells</div><small>Indicador global de recuperação: ${fmt(100*e.globalRelativeError,2)}% · campo ${fieldLabel(e.field)} · Gauss 2×2 × nodal suavizado.</small>${nonManifold?`<div class="adaptive-warning">${nonManifold} aresta(s) não-manifold detectada(s). Corrija a topologia antes de aplicar.</div>`:''}<div class="table-wrap"><table><thead><tr><th>Elemento</th><th>η recuperação</th><th>RMS erro</th><th>Ação</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Nenhum shell com resposta disponível.</td></tr>'}</tbody></table></div>`;
}
function installStyle(){if(document.getElementById('astra-shell-adaptive-style'))return;const s=document.createElement('style');s.id='astra-shell-adaptive-style';s.textContent=`.astra-shell-adaptive table{width:100%;border-collapse:collapse;margin-top:8px}.astra-shell-adaptive th,.astra-shell-adaptive td{font-size:11px;padding:6px 7px;border-bottom:1px solid #2d4054;text-align:right;font-variant-numeric:tabular-nums}.astra-shell-adaptive th:first-child,.astra-shell-adaptive td:first-child{text-align:left}.astra-shell-adaptive .adaptive-marked td{font-weight:650}.astra-shell-adaptive .adaptive-warning{color:#e6a45e;margin-top:7px}.astra-shell-adaptive [data-adaptive-result]{margin-top:9px}.astra-shell-adaptive .adaptive-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}`;document.head.appendChild(s)}
function patch(){installStyle();document.querySelectorAll<HTMLElement>('[data-testid="model-lab-overlay"]').forEach(overlay=>{
  const body=$<HTMLElement>('[data-lab-body]',overlay);if(!body||!body.querySelector('[data-shell-create]')||body.querySelector('[data-shell-adaptive]'))return;
  const host=document.createElement('section');host.className='astra-model-card astra-shell-adaptive';host.setAttribute('data-shell-adaptive','');host.setAttribute('data-testid','shell4-adaptive-controls');host.innerHTML=`<h3>Refinamento adaptativo shell4</h3><p>Estima o erro local comparando a resposta nos pontos de Gauss com o campo nodal suavizado. Hotspots recebem 2×2 e apenas faixas de transição 2×1/1×2 são propagadas para manter a malha conforme.</p><div class="astra-form-grid"><label>Campo<select data-adaptive-field><option value="Mx">Mx</option><option value="My">My</option><option value="Mxy">Mxy</option><option value="Qx">Qx</option><option value="Qy">Qy</option><option value="Nx">Nx</option><option value="Ny">Ny</option><option value="Nxy">Nxy</option></select></label><label>Tolerância η [%]<input data-adaptive-tol type="number" min="1" max="200" step="1" value="15"></label><label>Forçar pior fração [%]<input data-adaptive-fraction type="number" min="0" max="100" step="5" value="0"></label></div><div class="adaptive-actions"><button class="astra-lab-btn primary" data-testid="estimate-shell4-adaptive" data-adaptive-estimate>Estimar erro local</button><button class="astra-lab-btn" data-testid="apply-shell4-adaptive" data-adaptive-apply disabled>Aplicar refinamento adaptativo</button></div><div data-adaptive-result><small>η é um indicador de recuperação para refinamento de malha; não é um limite formal de erro em norma de energia. A estimativa não altera o modelo.</small></div>`;
  const convergence=$<HTMLElement>('[data-shell-convergence]',body),refinement=$<HTMLElement>('[data-shell-refinement]',body),anchor=convergence||refinement||body.querySelector<HTMLElement>('[data-shell-quality-panel]')||body.querySelector<HTMLElement>('.astra-shell-list');(anchor||body).insertAdjacentElement('afterend',host);
  const estimate=$<HTMLButtonElement>('[data-adaptive-estimate]',host)!,apply=$<HTMLButtonElement>('[data-adaptive-apply]',host)!;
  estimate.onclick=()=>{const old=estimate.textContent;try{const p=current();if(!p)throw new Error('Projeto não carregado.');if(String(p.settings?.analysisType||'linear')!=='linear')throw new Error('Refinamento adaptativo shell4: use análise Linear.');const levelId=$<HTMLSelectElement>('[data-shell-level]',body)?.value||null,field=$<HTMLSelectElement>('[data-adaptive-field]',host)?.value||'Mx',tol=Math.max(.01,Math.min(2,num($<HTMLInputElement>('[data-adaptive-tol]',host)?.value,15)/100)),fraction=Math.max(0,Math.min(1,num($<HTMLInputElement>('[data-adaptive-fraction]',host)?.value,0)/100)),scenarioId=p.settings?.analysisScenarioId||p.settings?.activeLoadCaseId||p.loadCases?.[0]?.id;estimate.disabled=true;estimate.textContent='Calculando…';const result=solve(p,scenarioId),out=planAdaptiveShellRefinement(p,result,{field,levelId,tolerance:tol,markFraction:fraction});plans.set(host,{...out,projectId:p.id,sourceShellCount:(p.elements||[]).filter((e:any)=>e.type==='shell4').length});render(host,out)}catch(err:any){alert(err?.message||String(err))}finally{estimate.disabled=false;estimate.textContent=old||'Estimar erro local'}};
  apply.onclick=()=>{try{const state=plans.get(host),p=current();if(!state||!p)throw new Error('Execute a estimativa antes de aplicar.');const shellCount=(p.elements||[]).filter((e:any)=>e.type==='shell4').length;if(String(p.id)!==String(state.projectId)||shellCount!==state.sourceShellCount)throw new Error('O modelo mudou após a estimativa. Recalcule o refinamento adaptativo.');if((state.splitPlan?.nonManifoldEdges||[]).length)throw new Error('A malha contém arestas não-manifold; corrija a topologia antes de refinar.');const out=applyAdaptiveShellRefinement(p,state);save(out.project)}catch(err:any){alert(err?.message||String(err))}};
 })}
let queued=false;const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;patch()})};const observer=new MutationObserver(schedule);observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch,{once:true});else patch();

export {};
