import React,{useEffect,useMemo,useRef,useState}from'react';
import{SpatialCanvas3D as SpatialCanvas3DCore}from'./SpatialCanvas3DCore';
// @ts-ignore
import{applyCameraPreset3D,characteristicLength3D,clamp,fitCamera3D,orbitCamera3D,panCamera3D}from'../../web/src/view/spatialView3d.js';
// @ts-ignore
import{foundationSSIOverlayScene}from'../../web/src/view/foundationSsiView3d.js';
// @ts-ignore
import{foundationGeotechnicalOverlayScene}from'../../web/src/view/geotechnicalView3d.js';
import{publishAnalysisResult}from'./analysisResultBridge';
import'./spatial-ssi-overlay.css';
import'./spatial-geotechnical-overlay.css';

type Selection={kind:'node'|'element';id:string}|null;
type Props={project:any;result:any;bucklingView?:any;selection:Selection;onSelection:(s:Selection)=>void};
type Drag={pointerId:number;x:number;y:number;mode:'orbit'|'pan'}|null;
type Viewport={left:number;top:number;width:number;height:number};
type GeoField='profiles'|'settlement'|'pressure';
const points=(v:any[])=>v.map(p=>`${Number(p.x).toFixed(2)},${Number(p.y).toFixed(2)}`).join(' ');
const fmt=(v:any,d=2)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);

export function SpatialCanvas3D(props:Props){
  const hostRef=useRef<HTMLDivElement|null>(null),dragRef=useRef<Drag>(null),[projection,setProjection]=useState<'perspective'|'orthographic'>('perspective'),[camera,setCamera]=useState<any>(()=>fitCamera3D(props.project,'iso','perspective')),[viewport,setViewport]=useState<Viewport>({left:0,top:0,width:1000,height:680}),[showSSI,setShowSSI]=useState(true),[showSSIResults,setShowSSIResults]=useState(true),[showGeo,setShowGeo]=useState(true),[geoField,setGeoField]=useState<GeoField>('profiles');
  const charL=useMemo(()=>characteristicLength3D(props.project),[props.project]),scene=useMemo(()=>foundationSSIOverlayScene(props.project,props.result,camera,{width:viewport.width,height:viewport.height},charL),[props.project,props.result,camera,viewport.width,viewport.height,charL]),geoScene=useMemo(()=>foundationGeotechnicalOverlayScene(props.project,props.result,camera,{width:viewport.width,height:viewport.height},charL),[props.project,props.result,camera,viewport.width,viewport.height,charL]);
  useEffect(()=>publishAnalysisResult(props.result),[props.result]);
  useEffect(()=>{const fn=(ev:Event)=>{const d=(ev as CustomEvent)?.detail,kind=d?.kind,id=d?.id;if((kind!=='element'&&kind!=='node')||id==null)return;const exists=kind==='element'?(props.project?.elements||[]).some((x:any)=>String(x.id)===String(id)):(props.project?.nodes||[]).some((x:any)=>String(x.id)===String(id));if(exists)props.onSelection({kind,id:String(id)})};window.addEventListener('astrastruct:select-entity',fn);return()=>window.removeEventListener('astrastruct:select-entity',fn)},[props.project,props.onSelection]);
  useEffect(()=>{window.dispatchEvent(new CustomEvent('astrastruct:selection-changed',{detail:{selection:props.selection}}))},[props.selection]);
  useEffect(()=>{setProjection('perspective');setCamera(fitCamera3D(props.project,'iso','perspective'))},[props.project?.id]);
  useEffect(()=>{const host=hostRef.current;if(!host)return;const canvas=host.querySelector<HTMLCanvasElement>('.spatial3d-canvas');if(!canvas)return;const sync=()=>{if(!host)return;const a=canvas.getBoundingClientRect(),b=host.getBoundingClientRect();setViewport({left:a.left-b.left,top:a.top-b.top,width:Math.max(1,a.width),height:Math.max(1,a.height)})};sync();const ro=new ResizeObserver(sync);ro.observe(canvas);window.addEventListener('resize',sync);return()=>{ro.disconnect();window.removeEventListener('resize',sync)}},[props.project?.id]);
  useEffect(()=>{const host=hostRef.current;if(!host)return;const isCanvas=(t:EventTarget|null)=>t instanceof HTMLCanvasElement&&t.classList.contains('spatial3d-canvas');
    const down=(e:PointerEvent)=>{if(!isCanvas(e.target))return;dragRef.current={pointerId:e.pointerId,x:e.clientX,y:e.clientY,mode:e.button===1||e.button===2||e.shiftKey?'pan':'orbit'}};
    const move=(e:PointerEvent)=>{const d=dragRef.current;if(!d||d.pointerId!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;d.x=e.clientX;d.y=e.clientY;setCamera((c:any)=>d.mode==='pan'?panCamera3D(c,dx,dy,{width:viewport.width,height:viewport.height}):orbitCamera3D(c,dx,dy))};
    const up=(e:PointerEvent)=>{if(dragRef.current?.pointerId===e.pointerId)dragRef.current=null};
    const wheel=(e:WheelEvent)=>{if(!isCanvas(e.target))return;setCamera((c:any)=>({...c,zoom:clamp(c.zoom*Math.exp(-e.deltaY*.0012),.15,8),preset:'custom'}))};
    const click=(e:MouseEvent)=>{const el=(e.target as HTMLElement)?.closest<HTMLElement>('[data-testid]');if(!el)return;const id=el.dataset.testid;if(id==='view-3d-iso'||id==='view-3d-xy'||id==='view-3d-xz'||id==='view-3d-yz'){const name=id.replace('view-3d-','');setCamera((c:any)=>applyCameraPreset3D(c,props.project,name));return}if(id==='view-3d-fit'){setCamera((c:any)=>fitCamera3D(props.project,c.preset==='custom'?'iso':c.preset||'iso',projection));return}if(id==='spatial3d-zoom-in'){setCamera((c:any)=>({...c,zoom:clamp(c.zoom*1.25,.15,8)}));return}if(id==='spatial3d-zoom-out'){setCamera((c:any)=>({...c,zoom:clamp(c.zoom/1.25,.15,8)}));return}if(id==='spatial3d-projection'){setProjection(p=>{const next=p==='perspective'?'orthographic':'perspective';setCamera((c:any)=>({...c,projection:next}));return next})}};
    host.addEventListener('pointerdown',down,true);host.addEventListener('pointermove',move,true);host.addEventListener('pointerup',up,true);host.addEventListener('pointercancel',up,true);host.addEventListener('wheel',wheel,true);host.addEventListener('click',click,true);return()=>{host.removeEventListener('pointerdown',down,true);host.removeEventListener('pointermove',move,true);host.removeEventListener('pointerup',up,true);host.removeEventListener('pointercancel',up,true);host.removeEventListener('wheel',wheel,true);host.removeEventListener('click',click,true)}},[props.project,projection,viewport.width,viewport.height]);
  const visible=scene.enabled&&scene.items.length>0,geoVisible=geoScene.profiles.length>0||geoScene.samples.length>0;
  const geoSampleCount=geoField==='settlement'?geoScene.summary.settlementSamples:geoField==='pressure'?geoScene.summary.pressureSamples:geoScene.summary.profiles;
  return <div ref={hostRef} className="spatial3d-ssi-host" data-ssi-count={scene.summary.count} data-ssi-ready-count={scene.summary.ready} data-ssi-result-nature={scene.resultNature} data-geotechnical-profile-count={geoScene.summary.profiles} data-geotechnical-field={geoField} data-geotechnical-interpolation="none">
    <SpatialCanvas3DCore {...props}/>
    {geoVisible&&showGeo&&<svg data-testid="spatial3d-geotechnical-overlay" className="spatial3d-ssi-overlay spatial3d-geotechnical-overlay" aria-label="Perfis e resultados geotécnicos no Canvas 3D" viewBox={`0 0 ${viewport.width} ${viewport.height}`} style={{left:viewport.left,top:viewport.top,width:viewport.width,height:viewport.height}}>
      {geoField==='profiles'&&geoScene.profiles.map((p:any)=>p.visible?<g key={p.id} data-geotechnical-profile-id={p.id} data-geotechnical-state={p.state}><circle cx={p.anchor.x} cy={p.anchor.y} r="5" fill="#fff" stroke={p.state==='READY'?'#4e6f5d':p.state==='INVALID'?'#c84d55':'#c79237'} strokeWidth="2"/><text x={p.anchor.x+9} y={p.anchor.y-8} className="geo3d-profile-label">{p.label} · {p.state}</text>{p.segments.map((s:any)=><g key={s.layerId} data-geotechnical-layer-id={s.layerId}><line x1={s.a.x} y1={s.a.y} x2={s.b.x} y2={s.b.y} stroke="#fff" strokeWidth="13" strokeLinecap="round" opacity=".92"/><line x1={s.a.x} y1={s.a.y} x2={s.b.x} y2={s.b.y} stroke={s.color} strokeWidth="9" strokeLinecap="round"/><text x={(s.a.x+s.b.x)/2+8} y={(s.a.y+s.b.y)/2} className="geo3d-layer-label">{s.soilClass||s.label} · {fmt(s.topDepthM,1)}–{fmt(s.bottomDepthM,1)} m</text></g>)}</g>:null)}
      {geoField!=='profiles'&&geoScene.samples.map((s:any)=>{const value=geoField==='settlement'?s.settlementMm:s.pressureKPa,color=geoField==='settlement'?s.settlementColor:s.pressureColor;if(value==null)return null;return <g key={`${geoField}-${s.foundationId}`} data-geotechnical-foundation-id={s.foundationId} data-geotechnical-result-kind={geoField}>{s.footprint&&<polygon points={points(s.footprint)} fill={color||'#75899b'} fillOpacity=".42" stroke={color||'#75899b'} strokeWidth="2"/>}<circle cx={s.anchor.x} cy={s.anchor.y} r="4" fill="#fff" stroke={color||'#75899b'} strokeWidth="2"/><text x={s.anchor.x+8} y={s.anchor.y-7} className="geo3d-result-label">{s.label}</text><text x={s.anchor.x+8} y={s.anchor.y+8} className="geo3d-result-value">{geoField==='settlement'?`uz ${fmt(value,2)} mm`:`q̄ ${fmt(value,2)} kPa`}</text></g>})}
    </svg>}
    {visible&&showSSI&&<svg data-testid="spatial3d-ssi-overlay" className="spatial3d-ssi-overlay" aria-label="Interação solo estrutura no Canvas 3D" viewBox={`0 0 ${viewport.width} ${viewport.height}`} style={{left:viewport.left,top:viewport.top,width:viewport.width,height:viewport.height}}><defs><marker id="ssi-arrow-d" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#218d78"/></marker><marker id="ssi-arrow-r" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#b84550"/></marker></defs>{scene.items.map((it:any)=><g key={it.foundationId} data-foundation-id={it.foundationId} data-ssi-state={it.state}>{it.footprint&&<polygon points={points(it.footprint)} fill={it.color} fillOpacity=".13" stroke={it.color} strokeWidth="1.7" strokeDasharray={it.state==='READY'?undefined:'5 3'}/>}<polyline points={points(it.spring)} fill="none" stroke={it.color} strokeWidth="2.2"/><circle cx={it.anchor.x} cy={it.anchor.y} r="4.5" fill="#fff" stroke={it.color} strokeWidth="2"/>{showSSIResults&&it.displacement&&<line x1={it.displacement.a.x} y1={it.displacement.a.y} x2={it.displacement.b.x} y2={it.displacement.b.y} stroke="#218d78" strokeWidth="2.3" markerEnd="url(#ssi-arrow-d)"/>}{showSSIResults&&it.reaction&&<line x1={it.reaction.a.x} y1={it.reaction.a.y} x2={it.reaction.b.x} y2={it.reaction.b.y} stroke="#b84550" strokeWidth="2.3" markerEnd="url(#ssi-arrow-r)"/>}<text x={it.anchor.x+9} y={it.anchor.y-11} className="ssi3d-label">{it.label}</text>{showSSIResults&&it.settlementMm!=null&&<text x={it.anchor.x+9} y={it.anchor.y+5} className="ssi3d-value">uz {fmt(it.settlementMm,2)} mm</text>}{showSSIResults&&it.averageContactPressureKPa!=null&&<text x={it.anchor.x+9} y={it.anchor.y+19} className="ssi3d-value">q̄ {fmt(it.averageContactPressureKPa,2)} kPa</text>}{it.state==='MODE_ONLY'&&<text x={it.anchor.x+9} y={it.anchor.y+5} className="ssi3d-mode">forma própria · sem reação física</text>}</g>)}</svg>}
    {visible&&<div className="spatial3d-ssi-controls" data-testid="spatial3d-ssi-controls"><label><input data-testid="spatial3d-ssi-toggle" type="checkbox" checked={showSSI} onChange={e=>setShowSSI(e.target.checked)}/> SSI</label><label><input data-testid="spatial3d-ssi-results-toggle" type="checkbox" checked={showSSIResults} disabled={!showSSI||scene.resultNature==='eigen-shape'} onChange={e=>setShowSSIResults(e.target.checked)}/> Reações/recalques</label><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('astrastruct:ssi-open'))}>Configurar</button></div>}
    {geoVisible&&<div className="spatial3d-geo-controls" data-testid="spatial3d-geotechnical-controls"><label><input data-testid="spatial3d-geotechnical-toggle" type="checkbox" checked={showGeo} onChange={e=>setShowGeo(e.target.checked)}/> Geotecnia</label><label>Campo <select aria-label="Campo geotécnico 3D" value={geoField} onChange={e=>setGeoField(e.target.value as GeoField)}><option value="profiles">Perfis</option><option value="settlement">Recalque uz</option><option value="pressure">Pressão q̄</option></select></label><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('astrastruct:geotechnical-open'))}>Perfis/camadas</button></div>}
    {geoVisible&&showGeo&&<div className="spatial3d-geo-status" data-testid="spatial3d-geotechnical-status"><b>Geotecnia</b>{geoField==='profiles'?<><span>{geoScene.summary.profiles} perfil(is)</span><span>{geoScene.summary.readyProfiles} READY</span><span>perfil pontual · sem extrapolação lateral</span></>:<><span>{geoSampleCount} amostra(s)</span><span>{geoField==='settlement'?'recalque vertical':'pressão média q̄'}</span><span>sem interpolação espacial</span></>}</div>}
    {visible&&showSSI&&<div className="spatial3d-ssi-status" data-testid="spatial3d-ssi-status"><b>SSI 3D</b><span>{scene.summary.count} fundação(ões)</span><span>{scene.summary.ready} resposta(s) física(s)</span>{scene.resultNature==='eigen-shape'?<span className="mode">forma própria · sem reação/recalque físico</span>:<><span className="disp">↗ deslocamento</span><span className="react">↗ reação da mola</span></>}</div>}
  </div>;
}
