import React,{useEffect,useMemo,useRef,useState}from'react';
import{SpatialCanvas3D as SpatialCanvas3DCore}from'./SpatialCanvas3DCore';
import{CombinationKinematicOverlay}from'./CombinationKinematicOverlay';
// @ts-ignore
import{applyCameraPreset3D,characteristicLength3D,clamp,fitCamera3D,nodePoint,orbitCamera3D,panCamera3D,projectPoint3D}from'../../web/src/view/spatialView3d.js';
// @ts-ignore
import{foundationSSIOverlayScene}from'../../web/src/view/foundationSsiView3d.js';
// @ts-ignore
import{foundationGeotechnicalOverlayScene}from'../../web/src/view/geotechnicalView3d.js';
import{publishAnalysisResult}from'./analysisResultBridge';
import'./spatial-ssi-overlay.css';
import'./spatial-geotechnical-overlay.css';
import'./spatial-result-preview.css';
import'./spatial-envelope-overlay.css';

type Selection={kind:'node'|'element';id:string}|null;
type Props={project:any;result:any;bucklingView?:any;selection:Selection;onSelection:(s:Selection)=>void};
type Drag={pointerId:number;x:number;y:number;mode:'orbit'|'pan'}|null;
type Viewport={left:number;top:number;width:number;height:number};
type GeoField='profiles'|'settlement'|'pressure';
const points=(v:any[])=>v.map(p=>`${Number(p.x).toFixed(2)},${Number(p.y).toFixed(2)}`).join(' ');
const fmt=(v:any,d=2)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);
const scaleRows=(rows:any[],phase:number)=>Array.isArray(rows)?rows.map(d=>({...d,ux:(Number(d.ux)||0)*phase,uy:(Number(d.uy)||0)*phase,uz:(Number(d.uz)||0)*phase,rx:(Number(d.rx)||0)*phase,ry:(Number(d.ry)||0)*phase,rz:(Number(d.rz)||0)*phase})):rows;
const shellIds=(e:any)=>Array.isArray(e?.nodeIds)&&e.nodeIds.length?e.nodeIds:[e?.n1,e?.n2,e?.n3,e?.n4].filter(Boolean);
const envColor=(value:any,ratio:any)=>{const t=clamp(Number(ratio)||0,0,1),neutral=[231,236,239],target=Number(value)<0?[71,127,182]:[183,71,84],c=neutral.map((v,i)=>Math.round(v+(target[i]-v)*t));return`rgb(${c[0]},${c[1]},${c[2]})`};
function visualPhaseResult(result:any,phase:number){if(!result||phase>=.999999)return result;const out={...result};if(Array.isArray(result.displacements))out.displacements=scaleRows(result.displacements,phase);if(Array.isArray(result.totalDisplacements))out.totalDisplacements=scaleRows(result.totalDisplacements,phase);if(result.combined&&Array.isArray(result.combined.displacements))out.combined={...result.combined,displacements:scaleRows(result.combined.displacements,phase)};return out}

export function SpatialCanvas3D(props:Props){
  const hostRef=useRef<HTMLDivElement|null>(null),dragRef=useRef<Drag>(null),[projection,setProjection]=useState<'perspective'|'orthographic'>('perspective'),[camera,setCamera]=useState<any>(()=>fitCamera3D(props.project,'iso','perspective')),[viewport,setViewport]=useState<Viewport>({left:0,top:0,width:1000,height:680}),[showSSI,setShowSSI]=useState(true),[showSSIResults,setShowSSIResults]=useState(true),[showGeo,setShowGeo]=useState(true),[geoField,setGeoField]=useState<GeoField>('profiles'),[preview,setPreview]=useState<any>(null),[previewPlaying,setPreviewPlaying]=useState(false),[previewPhase,setPreviewPhase]=useState(1),[envelopeView,setEnvelopeView]=useState<any>(null);
  const displayResult=useMemo(()=>preview?visualPhaseResult(preview.result,previewPlaying?previewPhase:1):props.result,[preview,previewPlaying,previewPhase,props.result]),charL=useMemo(()=>characteristicLength3D(props.project),[props.project]),scene=useMemo(()=>foundationSSIOverlayScene(props.project,displayResult,camera,{width:viewport.width,height:viewport.height},charL),[props.project,displayResult,camera,viewport.width,viewport.height,charL]),geoScene=useMemo(()=>foundationGeotechnicalOverlayScene(props.project,displayResult,camera,{width:viewport.width,height:viewport.height},charL),[props.project,displayResult,camera,viewport.width,viewport.height,charL]);
  const forceEnvelopeActive=envelopeView&&(!envelopeView.domain||envelopeView.domain==='force');
  const envelopeScene=useMemo(()=>{if(!forceEnvelopeActive||!envelopeView?.items?.length)return[];const byId=new Map((envelopeView.items||[]).map((x:any)=>[String(x.elementId),x])),nodeById=new Map((props.project?.nodes||[]).map((n:any)=>[String(n.id),n])),criticalIds=new Set(Object.values(envelopeView.criticalByKind||{}).filter(Boolean).map((x:any)=>String(x.elementId))),out:any[]=[];for(const e of props.project?.elements||[]){const env:any=byId.get(String(e.id));if(!env)continue;if(e.type==='shell4'){const ns=shellIds(e).map((id:any)=>nodeById.get(String(id))).filter(Boolean);if(ns.length<3)continue;const pp=ns.map((n:any)=>projectPoint3D(nodePoint(n),camera,{width:viewport.width,height:viewport.height}));if(pp.some((p:any)=>!p.visible))continue;out.push({kind:'shell',elementId:String(e.id),env,points:pp,color:envColor(env.value,env.ratio),critical:criticalIds.has(String(e.id)),cx:pp.reduce((s:number,p:any)=>s+p.x,0)/pp.length,cy:pp.reduce((s:number,p:any)=>s+p.y,0)/pp.length})}else if(['frame3d','truss3d'].includes(e.type)){const a:any=nodeById.get(String(e.n1)),b:any=nodeById.get(String(e.n2));if(!a||!b)continue;const pa=projectPoint3D(nodePoint(a),camera,{width:viewport.width,height:viewport.height}),pb=projectPoint3D(nodePoint(b),camera,{width:viewport.width,height:viewport.height});if(!pa.visible||!pb.visible)continue;out.push({kind:'bar',elementId:String(e.id),env,a:pa,b:pb,color:envColor(env.value,env.ratio),critical:criticalIds.has(String(e.id)),cx:(pa.x+pb.x)/2,cy:(pa.y+pb.y)/2})}}return out},[forceEnvelopeActive,envelopeView,props.project,camera,viewport.width,viewport.height]);
  const selectedEnvelope=useMemo(()=>forceEnvelopeActive&&props.selection?.kind==='element'&&envelopeView?.items?.length?(envelopeView.items||[]).find((x:any)=>String(x.elementId)===String(props.selection?.id))||null:null,[forceEnvelopeActive,props.selection,envelopeView]);
  useEffect(()=>publishAnalysisResult(props.result),[props.result]);
  useEffect(()=>{const fn=(ev:Event)=>{const detail=(ev as CustomEvent)?.detail||{};if(typeof detail.show==='boolean')setShowSSI(detail.show);if(typeof detail.results==='boolean')setShowSSIResults(detail.results)};window.addEventListener('astrastruct:ssi-visibility',fn);return()=>window.removeEventListener('astrastruct:ssi-visibility',fn)},[]);
  useEffect(()=>{if(!previewPlaying||!preview){setPreviewPhase(1);return}let raf=0;const t0=performance.now(),tick=(t:number)=>{setPreviewPhase(.5-.5*Math.cos((t-t0)/900*Math.PI*2));raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[previewPlaying,preview]);
  useEffect(()=>{const fn=(ev:Event)=>{const d=(ev as CustomEvent)?.detail;if(d?.clear){setPreviewPlaying(false);setPreview(null);return}if(d?.result){setPreviewPlaying(false);setPreviewPhase(1);setPreview({result:d.result,label:d.label||d.combinationId||'Resultado temporário',combinationId:d.combinationId||d.result?.scenario?.id||null,source:d.source||'preview'})}};window.addEventListener('astrastruct:result-preview',fn);return()=>window.removeEventListener('astrastruct:result-preview',fn)},[]);
  useEffect(()=>{const fn=(ev:Event)=>{const d=(ev as CustomEvent)?.detail;if(d?.clear){setEnvelopeView(null);return}if(d?.contract==='combination-envelope-visualization/v1'&&Array.isArray(d.items))setEnvelopeView(d)};window.addEventListener('astrastruct:envelope-3d',fn);return()=>window.removeEventListener('astrastruct:envelope-3d',fn)},[]);
  useEffect(()=>{const fn=(ev:Event)=>{const d=(ev as CustomEvent)?.detail,kind=d?.kind,id=d?.id;if((kind!=='element'&&kind!=='node')||id==null)return;const exists=kind==='element'?(props.project?.elements||[]).some((x:any)=>String(x.id)===String(id)):(props.project?.nodes||[]).some((x:any)=>String(x.id)===String(id));if(exists)props.onSelection({kind,id:String(id)})};window.addEventListener('astrastruct:select-entity',fn);return()=>window.removeEventListener('astrastruct:select-entity',fn)},[props.project,props.onSelection]);
  useEffect(()=>{window.dispatchEvent(new CustomEvent('astrastruct:selection-changed',{detail:{selection:props.selection}}))},[props.selection]);
  useEffect(()=>{setProjection('perspective');setCamera(fitCamera3D(props.project,'iso','perspective'));setPreviewPlaying(false);setPreview(null);setEnvelopeView(null)},[props.project?.id]);
  useEffect(()=>{const host=hostRef.current;if(!host)return;const canvas=host.querySelector<HTMLCanvasElement>('.spatial3d-canvas');if(!canvas)return;const sync=()=>{if(!host)return;const a=canvas.getBoundingClientRect(),b=host.getBoundingClientRect();setViewport({left:a.left-b.left,top:a.top-b.top,width:Math.max(1,a.width),height:Math.max(1,a.height)})};sync();const ro=new ResizeObserver(sync);ro.observe(canvas);window.addEventListener('resize',sync);return()=>{ro.disconnect();window.removeEventListener('resize',sync)}},[props.project?.id]);
  useEffect(()=>{const host=hostRef.current;if(!host)return;const isCanvas=(t:EventTarget|null)=>t instanceof HTMLCanvasElement&&t.classList.contains('spatial3d-canvas');
    const down=(e:PointerEvent)=>{if(!isCanvas(e.target))return;dragRef.current={pointerId:e.pointerId,x:e.clientX,y:e.clientY,mode:e.button===1||e.button===2||e.shiftKey?'pan':'orbit'}};
    const move=(e:PointerEvent)=>{const d=dragRef.current;if(!d||d.pointerId!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;d.x=e.clientX;d.y=e.clientY;setCamera((c:any)=>d.mode==='pan'?panCamera3D(c,dx,dy,{width:viewport.width,height:viewport.height}):orbitCamera3D(c,dx,dy))};
    const up=(e:PointerEvent)=>{if(dragRef.current?.pointerId===e.pointerId)dragRef.current=null};
    const wheel=(e:WheelEvent)=>{if(!isCanvas(e.target))return;setCamera((c:any)=>({...c,zoom:clamp(c.zoom*Math.exp(-e.deltaY*.0012),.15,8),preset:'custom'}))};
    const click=(e:MouseEvent)=>{const el=(e.target as HTMLElement)?.closest<HTMLElement>('[data-testid]');if(!el)return;const id=el.dataset.testid;if(id==='view-3d-iso'||id==='view-3d-xy'||id==='view-3d-xz'||id==='view-3d-yz'){const name=id.replace('view-3d-','');setCamera((c:any)=>applyCameraPreset3D(c,props.project,name));return}if(id==='view-3d-fit'){setCamera((c:any)=>fitCamera3D(props.project,c.preset==='custom'?'iso':c.preset||'iso',projection));return}if(id==='spatial3d-zoom-in'){setCamera((c:any)=>({...c,zoom:clamp(c.zoom*1.25,.15,8)}));return}if(id==='spatial3d-zoom-out'){setCamera((c:any)=>({...c,zoom:clamp(c.zoom/1.25,.15,8)}));return}if(id==='spatial3d-projection'){setProjection(p=>{const next=p==='perspective'?'orthographic':'perspective';setCamera((c:any)=>({...c,projection:next}));return next})}};
    host.addEventListener('pointerdown',down,true);host.addEventListener('pointermove',move,true);host.addEventListener('pointerup',up,true);host.addEventListener('pointercancel',up,true);host.addEventListener('wheel',wheel,true);host.addEventListener('click',click,true);return()=>{host.removeEventListener('pointerdown',down,true);host.removeEventListener('pointermove',move,true);host.removeEventListener('pointerup',up,true);host.removeEventListener('pointercancel',up,true);host.removeEventListener('wheel',wheel,true);host.removeEventListener('click',click,true)}},[props.project,projection,viewport.width,viewport.height]);
  const visible=scene.enabled&&scene.items.length>0,geoVisible=geoScene.profiles.length>0||geoScene.samples.length>0;
  const geoSampleCount=geoField==='settlement'?geoScene.summary.settlementSamples:geoField==='pressure'?geoScene.summary.pressureSamples:geoScene.summary.profiles;
  const criticalBar=forceEnvelopeActive?envelopeView?.criticalByKind?.bar||null:null,criticalShell=forceEnvelopeActive?envelopeView?.criticalByKind?.shell||null:null;
  return <div ref={hostRef} className="spatial3d-ssi-host" data-result-preview={preview?'true':'false'} data-result-preview-combination={preview?.combinationId||''} data-result-preview-phase={previewPlaying?previewPhase.toFixed(3):'1.000'} data-envelope-domain={envelopeView?.domain||''} data-envelope-field={envelopeView?.field||''} data-envelope-items={envelopeView?.items?.length||0} data-ssi-count={scene.summary.count} data-ssi-ready-count={scene.summary.ready} data-ssi-result-nature={scene.resultNature} data-geotechnical-profile-count={geoScene.summary.profiles} data-geotechnical-field={geoField} data-geotechnical-interpolation="none">
    <SpatialCanvas3DCore {...props} result={displayResult}/>
    {preview&&<div className="spatial3d-preview-status" data-testid="spatial3d-result-preview"><b>Prévia de combinação</b><span>{preview.label}</span><button data-testid="spatial3d-preview-animate" type="button" className={previewPlaying?'active':''} onClick={()=>setPreviewPlaying(x=>!x)}>{previewPlaying?'Parar animação':'Animar deformada'}</button><button type="button" onClick={()=>{setPreviewPlaying(false);setPreview(null)}}>Voltar ao resultado principal</button></div>}
    {forceEnvelopeActive&&envelopeScene.length>0&&<svg data-testid="spatial3d-envelope-overlay" className="spatial3d-envelope-overlay" aria-label={`Mapa 3D da envoltória ${envelopeView.field}`} viewBox={`0 0 ${viewport.width} ${viewport.height}`} style={{left:viewport.left,top:viewport.top,width:viewport.width,height:viewport.height}}>{envelopeScene.map((it:any)=>it.kind==='bar'?<g key={it.elementId} data-envelope-element-id={it.elementId} data-envelope-critical={it.critical?'true':'false'}><line className={it.critical?'spatial3d-envelope-critical':''} x1={it.a.x} y1={it.a.y} x2={it.b.x} y2={it.b.y} stroke={it.color} strokeWidth={it.critical?7:5} strokeLinecap="round" opacity=".92"/>{it.critical&&<text className="spatial3d-envelope-label" x={it.cx+7} y={it.cy-7}>{it.elementId} · crítico</text>}</g>:<g key={it.elementId} data-envelope-element-id={it.elementId} data-envelope-critical={it.critical?'true':'false'}><polygon className={it.critical?'spatial3d-envelope-critical':''} points={points(it.points)} fill={it.color} fillOpacity={it.critical?.58:.42} stroke={it.color} strokeWidth={it.critical?4:2}/>{it.critical&&<text className="spatial3d-envelope-label" x={it.cx+7} y={it.cy-7}>{it.elementId} · crítico</text>}</g>)}</svg>}
    {forceEnvelopeActive&&<div className="spatial3d-envelope-status" data-testid="spatial3d-envelope-status"><header><b>Envoltória governante 3D</b><span className="env-field">{envelopeView.field}</span></header><div className="spatial3d-envelope-gradient"/><div className="spatial3d-envelope-scales">{envelopeView.scales?.bar?.count>0&&<span>Barras: |máx.| {fmt(envelopeView.scales.bar.maxAbs)} {envelopeView.scales.bar.unit}</span>}{envelopeView.scales?.shell?.count>0&&<span>Shells: |máx.| {fmt(envelopeView.scales.shell.maxAbs)} {envelopeView.scales.shell.unit}</span>}</div>{selectedEnvelope?<div className="spatial3d-envelope-selected" data-testid="spatial3d-envelope-selected"><b>{selectedEnvelope.label} · {selectedEnvelope.elementId}</b><span>{selectedEnvelope.governingComponent||envelopeView.field}: {fmt(selectedEnvelope.value)} {selectedEnvelope.unit}</span><span>Combinação governante: {selectedEnvelope.governingCombinationId||'—'}</span><div className="spatial3d-envelope-actions">{selectedEnvelope.governingCombinationId&&<button className="primary" data-testid="envelope-open-governing-combination" type="button" onClick={()=>window.dispatchEvent(new CustomEvent('astrastruct:combination-envelope-open',{detail:{combinationId:selectedEnvelope.governingCombinationId}}))}>Abrir combinação governante</button>}<button data-testid="envelope-open-elu-els" type="button" onClick={()=>window.dispatchEvent(new CustomEvent('astrastruct:elu-els-dashboard-open',{detail:{kind:'element',id:selectedEnvelope.elementId,combinationId:selectedEnvelope.governingCombinationId||null,source:'combination-envelope'}}))}>Verificações ELU/ELS do elemento</button><button type="button" onClick={()=>setEnvelopeView(null)}>Limpar mapa</button></div></div>:<div className="spatial3d-envelope-selected"><span>Selecione um elemento no Canvas para consultar valor, componente e combinação governante.</span><div className="spatial3d-envelope-actions">{criticalBar&&<button data-testid="envelope-select-critical-bar" type="button" onClick={()=>props.onSelection({kind:'element',id:String(criticalBar.elementId)})}>Selecionar barra crítica</button>}{criticalShell&&<button data-testid="envelope-select-critical-shell" type="button" onClick={()=>props.onSelection({kind:'element',id:String(criticalShell.elementId)})}>Selecionar shell crítico</button>}<button type="button" onClick={()=>setEnvelopeView(null)}>Limpar mapa</button></div></div>}</div>}
    {envelopeView&&(envelopeView.domain==='displacement'||envelopeView.domain==='drift'||envelopeView.domain==='reaction')&&<CombinationKinematicOverlay project={props.project} view={envelopeView} camera={camera} viewport={viewport} selection={props.selection} onSelection={props.onSelection} onClear={()=>setEnvelopeView(null)}/>} 
    {geoVisible&&showGeo&&<svg data-testid="spatial3d-geotechnical-overlay" className="spatial3d-ssi-overlay spatial3d-geotechnical-overlay" aria-label="Perfis e resultados geotécnicos no Canvas 3D" viewBox={`0 0 ${viewport.width} ${viewport.height}`} style={{left:viewport.left,top:viewport.top,width:viewport.width,height:viewport.height}}>
      {geoField==='profiles'&&geoScene.profiles.map((p:any)=>p.visible?<g key={p.id} data-geotechnical-profile-id={p.id} data-geotechnical-state={p.state}><circle cx={p.anchor.x} cy={p.anchor.y} r="5" fill="#fff" stroke={p.state==='READY'?'#4e6f5d':p.state==='INVALID'?'#c84d55':'#c79237'} strokeWidth="2"/><text x={p.anchor.x+9} y={p.anchor.y-8} className="geo3d-profile-label">{p.label} · {p.state}</text>{p.segments.map((s:any)=><g key={s.layerId} data-geotechnical-layer-id={s.layerId}><line x1={s.a.x} y1={s.a.y} x2={s.b.x} y2={s.b.y} stroke="#fff" strokeWidth="13" strokeLinecap="round" opacity=".92"/><line x1={s.a.x} y1={s.a.y} x2={s.b.x} y2={s.b.y} stroke={s.color} strokeWidth="9" strokeLinecap="round"/><text x={(s.a.x+s.b.x)/2+8} y={(s.a.y+s.b.y)/2} className="geo3d-layer-label">{s.soilClass||s.label} · {fmt(s.topDepthM,1)}–{fmt(s.bottomDepthM,1)} m</text></g>)}</g>:null)}
      {geoField!=='profiles'&&geoScene.samples.map((s:any)=>{const value=geoField==='settlement'?s.settlementMm:s.pressureKPa,color=geoField==='settlement'?s.settlementColor:s.pressureColor;if(value==null)return null;return <g key={`${geoField}-${s.foundationId}`} data-geotechnical-foundation-id={s.foundationId} data-geotechnical-result-kind={geoField}>{s.footprint&&<polygon points={points(s.footprint)} fill={color||'#75899b'} fillOpacity=".42" stroke={color||'#75899b'} strokeWidth="2"/>}<circle cx={s.anchor.x} cy={s.anchor.y} r="4" fill="#fff" stroke={color||'#75899b'} strokeWidth="2"/><text x={s.anchor.x+8} y={s.anchor.y-7} className="geo3d-result-label">{s.label}</text><text x={s.anchor.x+8} y={s.anchor.y+8} className="geo3d-result-value">{geoField==='settlement'?`uz ${fmt(value,2)} mm`:`q̄ ${fmt(value,2)} kPa`}</text></g>})}
    </svg>}
    {visible&&showSSI&&<svg data-testid="spatial3d-ssi-overlay" className="spatial3d-ssi-overlay" aria-label="Interação solo estrutura no Canvas 3D" viewBox={`0 0 ${viewport.width} ${viewport.height}`} style={{left:viewport.left,top:viewport.top,width:viewport.width,height:viewport.height}}><defs><marker id="ssi-arrow-d" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#218d78"/></marker><marker id="ssi-arrow-r" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#b84550"/></marker></defs>{scene.items.map((it:any)=><g key={it.foundationId} data-foundation-id={it.foundationId} data-ssi-state={it.state}>{it.footprint&&<polygon points={points(it.footprint)} fill={it.color} fillOpacity=".13" stroke={it.color} strokeWidth="1.7" strokeDasharray={it.state==='READY'?undefined:'5 3'}/>}<polyline points={points(it.spring)} fill="none" stroke={it.color} strokeWidth="2.2"/><circle cx={it.anchor.x} cy={it.anchor.y} r="4.5" fill="#fff" stroke={it.color} strokeWidth="2"/>{showSSIResults&&it.displacement&&<line x1={it.displacement.a.x} y1={it.displacement.a.y} x2={it.displacement.b.x} y2={it.displacement.b.y} stroke="#218d78" strokeWidth="2.3" markerEnd="url(#ssi-arrow-d)"/>}{showSSIResults&&it.reaction&&<line x1={it.reaction.a.x} y1={it.reaction.a.y} x2={it.reaction.b.x} y2={it.reaction.b.y} stroke="#b84550" strokeWidth="2.3" markerEnd="url(#ssi-arrow-r)"/>}<text x={it.anchor.x+9} y={it.anchor.y-11} className="ssi3d-label">{it.label}</text>{showSSIResults&&it.settlementMm!=null&&<text x={it.anchor.x+9} y={it.anchor.y+5} className="ssi3d-value">uz {fmt(it.settlementMm,2)} mm</text>}{showSSIResults&&it.averageContactPressureKPa!=null&&<text x={it.anchor.x+9} y={it.anchor.y+19} className="ssi3d-value">q̄ {fmt(it.averageContactPressureKPa,2)} kPa</text>}{it.state==='MODE_ONLY'&&<text x={it.anchor.x+9} y={it.anchor.y+5} className="ssi3d-mode">forma própria · sem reação física</text>}</g>)}</svg>}
    {geoVisible&&<div className="spatial3d-geo-controls" data-testid="spatial3d-geotechnical-controls"><label><input data-testid="spatial3d-geotechnical-toggle" type="checkbox" checked={showGeo} onChange={e=>setShowGeo(e.target.checked)}/> Geotecnia</label><label>Campo <select aria-label="Campo geotécnico 3D" value={geoField} onChange={e=>setGeoField(e.target.value as GeoField)}><option value="profiles">Perfis</option><option value="settlement">Recalque uz</option><option value="pressure">Pressão q̄</option></select></label><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('astrastruct:geotechnical-open'))}>Perfis/camadas</button></div>}
    {geoVisible&&showGeo&&<div className="spatial3d-geo-status" data-testid="spatial3d-geotechnical-status"><b>Geotecnia</b>{geoField==='profiles'?<><span>{geoScene.summary.profiles} perfil(is)</span><span>{geoScene.summary.readyProfiles} READY</span><span>perfil pontual · sem extrapolação lateral</span></>:<><span>{geoSampleCount} amostra(s)</span><span>{geoField==='settlement'?'recalque vertical':'pressão média q̄'}</span><span>sem interpolação espacial</span></>}</div>}
  </div>;
}
