from pathlib import Path

# Inspector
p=Path('app/src/InspectorPanel.tsx'); s=p.read_text()
s=s.replace("const defaultDistributedPlasticity={enabled:false,integrationPoints:5,nFibers:80,hardeningRatio:.01};","const defaultDistributedPlasticity={enabled:false,integrationPoints:5,nFibers:80,hardeningRatio:.01,cyclic:false,kinematicFraction:1};")
s=s.replace("const normalizedDistributed=(raw:any)=>({enabled:!!raw?.enabled,integrationPoints:[3,5].includes(Math.round(num(raw?.integrationPoints,5)))?Math.round(num(raw?.integrationPoints,5)):5,nFibers:Math.max(8,Math.min(400,Math.round(num(raw?.nFibers,80)))),hardeningRatio:Math.max(1e-6,Math.min(.25,Math.abs(num(raw?.hardeningRatio,.01))))});","const normalizedDistributed=(raw:any)=>({enabled:!!raw?.enabled,integrationPoints:[3,5].includes(Math.round(num(raw?.integrationPoints,5)))?Math.round(num(raw?.integrationPoints,5)):5,nFibers:Math.max(8,Math.min(400,Math.round(num(raw?.nFibers,80)))),hardeningRatio:Math.max(1e-6,Math.min(.25,Math.abs(num(raw?.hardeningRatio,.01)))),cyclic:!!raw?.cyclic,kinematicFraction:Math.max(0,Math.min(1,num(raw?.kinematicFraction,1)))});")
s=s.replace("if(fiberHinges.rz1.enabled||fiberHinges.rz2.enabled||distributedPlasticity.enabled)p.settings={...(p.settings||{}),analysisType:'corotational'};","if(fiberHinges.rz1.enabled||fiberHinges.rz2.enabled||distributedPlasticity.enabled)p.settings={...(p.settings||{}),analysisType:'corotational'};if(distributedPlasticity.cyclic)p.settings={...(p.settings||{}),analysisType:'corotational',nonlinearControlMode:'displacement',cyclicProtocolEnabled:true};")
s=s.replace("<h4>Plasticidade distribuída · v0.20</h4>","<h4>Plasticidade distribuída · v0.21</h4>")
old="<label>Et/E<input data-testid={`distributed-plasticity-hardening`} type=\"number\" min=\"0.000001\" max=\"0.25\" step=\"0.005\" value={draft.distributedPlasticity.hardeningRatio} onChange={e=>patchDistributed({hardeningRatio:e.target.value})}/></label></div>}"
# actual JSX has literal data-testid, no template
old="<label>Et/E<input data-testid=\"distributed-plasticity-hardening\" type=\"number\" min=\"0.000001\" max=\"0.25\" step=\"0.005\" value={draft.distributedPlasticity.hardeningRatio} onChange={e=>patchDistributed({hardeningRatio:e.target.value})}/></label></div>}"
new="<label>Et/E<input data-testid=\"distributed-plasticity-hardening\" type=\"number\" min=\"0.000001\" max=\"0.25\" step=\"0.005\" value={draft.distributedPlasticity.hardeningRatio} onChange={e=>patchDistributed({hardeningRatio:e.target.value})}/></label><label className=\"checkbox-line\"><input data-testid=\"distributed-plasticity-cyclic\" type=\"checkbox\" checked={!!draft.distributedPlasticity.cyclic} onChange={e=>patchDistributed({cyclic:e.target.checked})}/><span>História cíclica</span></label>{draft.distributedPlasticity.cyclic&&<label>Fração cinemática η<input data-testid=\"distributed-plasticity-kinematic\" type=\"number\" min=\"0\" max=\"1\" step=\"0.05\" value={draft.distributedPlasticity.kinematicFraction} onChange={e=>patchDistributed({kinematicFraction:e.target.value})}/></label>}</div>}"
if old not in s: raise SystemExit('Inspector DP controls anchor missing')
s=s.replace(old,new)
s=s.replace("A v0.20 integra seções de fibras por Gauss–Lobatto ao longo do elemento e permite espalhamento da plastificação. Nesta versão usa extremidades rígidas e é mutuamente exclusiva com rótulas concentradas/releases/molas rotacionais. Lei de aço bilinear monotônica, sem histerese.","A v0.21 mantém Gauss–Lobatto e acrescenta história constitutiva opcional por fibra. No modo cíclico, o aço usa retorno plástico com endurecimento combinado; η=1 corresponde ao endurecimento cinemático linear e representa efeito Bauschinger. O estado material só é comprometido após um passo global convergido, preservando rollback em Newton/line search.")
p.write_text(s)

# Analysis panel
p=Path('app/src/AnalysisPanelV13.tsx'); s=p.read_text()
anchor="const [controlTolerance,setControlTolerance]=useState(project.settings?.displacementControlTolerance??1e-7);"
s=s.replace(anchor,anchor+"\n  const [cyclicProtocolEnabled,setCyclicProtocolEnabled]=useState(!!project.settings?.cyclicProtocolEnabled);\n  const [cyclicTargets,setCyclicTargets]=useState((project.settings?.cyclicProtocolTargets||[-.02,.02,-.04,.04,0]).map((v:any)=>String((project.settings?.displacementControlDof||'uy')==='rz'?num(v):num(v)*1000)).join(', '));\n  const [cyclicStepsPerSegment,setCyclicStepsPerSegment]=useState(project.settings?.cyclicStepsPerSegment??6);")
apply_anchor="p.settings.nonlinearControlMode=controlMode==='arc-length'?'arc-length':(controlMode==='displacement'?'displacement':'load');p.settings.displacementControlNodeId=controlNodeId||null;p.settings.displacementControlDof=['ux','uy','rz'].includes(controlDof)?controlDof:'uy';p.settings.displacementControlTarget=Number.isFinite(Number(controlTarget))&&Math.abs(Number(controlTarget))>1e-12?Number(controlTarget):-0.05;p.settings.displacementControlTolerance=Math.max(1e-10,num(controlTolerance,1e-7));"
replace=apply_anchor+"\n    const parsedTargets=String(cyclicTargets).split(/[;,\\s]+/).map(Number).filter(Number.isFinite).map(v=>controlDof==='rz'?v:v/1000);p.settings.cyclicProtocolEnabled=controlMode==='displacement'&&!!cyclicProtocolEnabled;p.settings.cyclicProtocolTargets=parsedTargets.length?parsedTargets:[-.02,.02,-.04,.04,0];p.settings.cyclicStepsPerSegment=Math.max(2,Math.min(60,Math.round(num(cyclicStepsPerSegment,6))));"
if apply_anchor not in s: raise SystemExit('Analysis apply anchor missing')
s=s.replace(apply_anchor,replace)
jsx_anchor="<div data-testid=\"pushover-control-note\" className=\"panel-note\">O padrão do cenário é escalado pelo fator <b>λ</b>, que passa a ser incógnita do sistema aumentado. Em cada incremento o solver impõe o deslocamento-alvo em {controlNodeId||'—'}/{controlDof.toUpperCase()} e resolve simultaneamente o equilíbrio global. Para rótulas de fibras, o acoplamento material embutido é obrigatório. Arc-length/Riks é uma alternativa separada quando o caminho possui ponto-limite.</div>"
cyclic_ui="<div className=\"react-card\" data-testid=\"cyclic-protocol-controls\"><label className=\"checkbox-line\"><input data-testid=\"cyclic-protocol-enabled\" type=\"checkbox\" checked={cyclicProtocolEnabled} onChange={e=>setCyclicProtocolEnabled(e.target.checked)}/><span><b>Protocolo cíclico · v0.21</b></span></label>{cyclicProtocolEnabled&&<div className=\"geometry-grid\"><label>{controlDof==='rz'?'Alvos [rad]':'Alvos [mm]'}<input data-testid=\"cyclic-protocol-targets\" value={cyclicTargets} onChange={e=>setCyclicTargets(e.target.value)}/></label><label>Passos por trecho<input data-testid=\"cyclic-steps-per-segment\" type=\"number\" min=\"2\" max=\"60\" value={cyclicStepsPerSegment} onChange={e=>setCyclicStepsPerSegment(num(e.target.value,6))}/></label></div>}<div className=\"panel-note\">Os alvos são percorridos em sequência por controle de deslocamento. Para elementos com história cíclica ativa, as variáveis internas das fibras são comprometidas somente após convergência global; tentativas rejeitadas são descartadas.</div></div>"
if jsx_anchor not in s: raise SystemExit('Analysis pushover note anchor missing')
s=s.replace(jsx_anchor,jsx_anchor+cyclic_ui)
s=s.replace("Newton–Raphson incremental · v0.19","Newton–Raphson incremental · v0.21")
s=s.replace("Continuam fora do escopo: plasticidade distribuída/cíclica, concreto não linear, contato, follower distribuída, molas nodais e recalques.","A v0.21 acrescenta plasticidade distribuída cíclica de aço por histórico incremental, Bauschinger linear e protocolos de deslocamento reversível. Continuam fora do escopo: concreto não linear, dano/fadiga, flambagem local, contato, follower distribuída, molas nodais e recalques.")
p.write_text(s)

# Postprocess
p=Path('app/src/NonlinearPostprocessPanel.tsx'); s=p.read_text()
s=s.replace("<b>Curva de capacidade · λ × {pushover.control?.nodeId}/{String(pushover.control?.dof||'').toUpperCase()}</b>","<b>{pushover.cyclicProtocol?.enabled?'Laço histerético global':'Curva de capacidade'} · λ × {pushover.control?.nodeId}/{String(pushover.control?.dof||'').toUpperCase()}</b>")
s=s.replace("<div className=\"panel-note\">Marcadores indicam início de plastificação de novas rótulas; o marcador de pico identifica o maior |λ| calculado no caminho.</div>","<div className=\"panel-note\">{pushover.cyclicProtocol?.enabled?<>v0.21: caminho reversível por controle de deslocamento; a área do laço λ–u evidencia a resposta histerética global. Energia material dissipada acumulada={fmt(pushover.cumulativeDissipatedEnergy,4)} kN·m.</>:<>Marcadores indicam início de plastificação de novas rótulas; o marcador de pico identifica o maior |λ| calculado no caminho.</>}</div>")
old="{hasDistributed&&<div data-testid=\"distributed-plasticity-note\" className=\"panel-note\"><b>Plasticidade distribuída v0.20:</b> integração Gauss–Lobatto with"
# direct replace opening + scope fragments, safer small replacements
s=s.replace("<b>Plasticidade distribuída v0.20:</b>","<b>Plasticidade distribuída {distributed?.cyclicHistory?'cíclica v0.21':'v0.20'}:</b>")
s=s.replace("<b>Escopo:</b> aço bilinear monotônico; sem descarga/recarga ou histerese.","<b>História:</b> {distributed?.cyclicHistory?<>retorno plástico incremental com endurecimento combinado, η={fmt(distributedRecord?.kinematicFraction,2)}, energia dissipada acumulada={fmt(distributed?.cumulativeDissipatedEnergy,4)} kN·m. Máx. εp,eq={Number(Math.max(0,...(distributedRecord?.sections||[]).map((q:any)=>num(q.maxEquivalentPlasticStrain)))).toExponential(2)}.</>:<>envelope bilinear monotônico.</>}")
s=s.replace("{hasPushover&&<span className=\"chip\">pushover · deslocamento controlado</span>}","{hasPushover&&<span className=\"chip\">{pushover?.cyclicProtocol?.enabled?'histerese · deslocamento cíclico':'pushover · deslocamento controlado'}</span>}")
p.write_text(s)

# Report
p=Path('app/src/NonlinearReportPanel.tsx'); s=p.read_text()
s=s.replace("{hasDistributed?' com plasticidade distribuída v0.20':''}","{hasDistributed?` com plasticidade distribuída ${distributed?.cyclicHistory?'cíclica v0.21':'v0.20'}`:''}")
s=s.replace("<h3>2.1. Pushover por controle de deslocamento</h3>","<h3>2.1. {pushover?.cyclicProtocol?.enabled?'Resposta cíclica por controle de deslocamento':'Pushover por controle de deslocamento'}</h3>")
needle="O caminho calculado possui {pushover.curve?.length||0} pontos. Arc-length não está ativo nesta versão."
s=s.replace(needle,needle+" {pushover?.cyclicProtocol?.enabled&&<>Protocolo v0.21: {(pushover.cyclicProtocol.targets||[]).map((v:any)=>fmt(Number(v)*controlFactor,3)).join(' → ')} {controlUnit}, {pushover.cyclicProtocol.stepsPerSegment} passos/trecho. <b>Commit/rollback:</b> {pushover.cyclicProtocol.commitRollback}. Energia dissipada acumulada={fmt(pushover.cumulativeDissipatedEnergy,5)} kN·m.</>}")
s=s.replace("<h3>3. Plasticidade distribuída · v0.20</h3>","<h3>3. Plasticidade distribuída · {distributed?.cyclicHistory?'v0.21 cíclica':'v0.20'}</h3>")
s=s.replace("aço bilinear monotônico","{distributed?.cyclicHistory?'aço bilinear incremental com endurecimento combinado e efeito Bauschinger':'aço bilinear monotônico'}")
p.write_text(s)
