from pathlib import Path

def rep(s,old,new,label):
    if new in s:return s
    if old not in s:raise SystemExit(f'{label}: anchor missing')
    return s.replace(old,new)

# Inspector: added nodal masses.
p=Path('app/src/InspectorPanel.tsx');s=p.read_text()
s=rep(s,
"      const load=project.loads.find((l:any)=>l.caseId===activeCase&&l.nodeId===entity.id)||{id:null,caseId:activeCase,nodeId:entity.id,fx:0,fy:0,mz:0};\n      setDraft({x:entity.x,y:entity.y,support:clone(support),load:clone(load)});",
"      const load=project.loads.find((l:any)=>l.caseId===activeCase&&l.nodeId===entity.id)||{id:null,caseId:activeCase,nodeId:entity.id,fx:0,fy:0,mz:0};\n      const nodalMass=(project.nodalMasses||[]).find((m:any)=>m.nodeId===entity.id)||{id:null,nodeId:entity.id,mx:0,my:0,mr:0};\n      setDraft({x:entity.x,y:entity.y,support:clone(support),load:clone(load),nodalMass:clone(nodalMass)});",
'inspector load mass draft')
old_apply="const applyNode=()=>{const p=clone(project),n=p.nodes.find((x:any)=>x.id===entity.id);n.x=num(draft.x);n.y=num(draft.y);p.supports=p.supports.filter((s:any)=>s.nodeId!==entity.id);if(draft.support.ux||draft.support.uy||draft.support.rz)p.supports.push({...draft.support,nodeId:entity.id});p.loads=p.loads.filter((l:any)=>!(l.caseId===activeCase&&l.nodeId===entity.id));if(Math.abs(num(draft.load.fx))+Math.abs(num(draft.load.fy))+Math.abs(num(draft.load.mz))>1e-12)p.loads.push({...draft.load,id:draft.load.id||uid('L'),caseId:activeCase,nodeId:entity.id,fx:num(draft.load.fx),fy:num(draft.load.fy),mz:num(draft.load.mz)});onCommit(normalizeProject(p))};"
new_apply="const applyNode=()=>{const p=clone(project),n=p.nodes.find((x:any)=>x.id===entity.id);n.x=num(draft.x);n.y=num(draft.y);p.supports=p.supports.filter((s:any)=>s.nodeId!==entity.id);if(draft.support.ux||draft.support.uy||draft.support.rz)p.supports.push({...draft.support,nodeId:entity.id});p.loads=p.loads.filter((l:any)=>!(l.caseId===activeCase&&l.nodeId===entity.id));if(Math.abs(num(draft.load.fx))+Math.abs(num(draft.load.fy))+Math.abs(num(draft.load.mz))>1e-12)p.loads.push({...draft.load,id:draft.load.id||uid('L'),caseId:activeCase,nodeId:entity.id,fx:num(draft.load.fx),fy:num(draft.load.fy),mz:num(draft.load.mz)});p.nodalMasses=(p.nodalMasses||[]).filter((m:any)=>m.nodeId!==entity.id);const mx=Math.max(0,num(draft.nodalMass?.mx)),my=Math.max(0,num(draft.nodalMass?.my)),mr=Math.max(0,num(draft.nodalMass?.mr));if(mx>0||my>0||mr>0)p.nodalMasses.push({...draft.nodalMass,id:draft.nodalMass?.id||uid('MASS'),nodeId:entity.id,mx,my,mr});onCommit(normalizeProject(p))};"
s=rep(s,old_apply,new_apply,'inspector apply node')
old_node="<h4>Carga nodal · {activeCase}</h4><div className=\"inspector-grid\"><label>Fx [kN]<input type=\"number\" value={draft.load.fx} onChange={e=>setDraft({...draft,load:{...draft.load,fx:e.target.value}})}/></label><label>Fy [kN]<input type=\"number\" value={draft.load.fy} onChange={e=>setDraft({...draft,load:{...draft.load,fy:e.target.value}})}/></label><label>Mz [kN·m]<input type=\"number\" value={draft.load.mz} onChange={e=>setDraft({...draft,load:{...draft.load,mz:e.target.value}})}/></label></div><button className=\"inspector-apply\" onClick={applyNode}>Aplicar alterações</button>"
new_node="<h4>Carga nodal · {activeCase}</h4><div className=\"inspector-grid\"><label>Fx [kN]<input type=\"number\" value={draft.load.fx} onChange={e=>setDraft({...draft,load:{...draft.load,fx:e.target.value}})}/></label><label>Fy [kN]<input type=\"number\" value={draft.load.fy} onChange={e=>setDraft({...draft,load:{...draft.load,fy:e.target.value}})}/></label><label>Mz [kN·m]<input type=\"number\" value={draft.load.mz} onChange={e=>setDraft({...draft,load:{...draft.load,mz:e.target.value}})}/></label></div><h4>Massa nodal adicional · v0.23</h4><div className=\"inspector-grid\"><label>mx [t]<input data-testid=\"nodal-mass-x\" type=\"number\" min=\"0\" step=\"0.1\" value={draft.nodalMass?.mx??0} onChange={e=>setDraft({...draft,nodalMass:{...draft.nodalMass,mx:e.target.value}})}/></label><label>my [t]<input data-testid=\"nodal-mass-y\" type=\"number\" min=\"0\" step=\"0.1\" value={draft.nodalMass?.my??0} onChange={e=>setDraft({...draft,nodalMass:{...draft.nodalMass,my:e.target.value}})}/></label><label>Jz [t·m²]<input data-testid=\"nodal-mass-rz\" type=\"number\" min=\"0\" step=\"0.1\" value={draft.nodalMass?.mr??0} onChange={e=>setDraft({...draft,nodalMass:{...draft.nodalMass,mr:e.target.value}})}/></label></div><div className=\"panel-note\">1 t = 1 kN·s²/m. A massa dos elementos é obtida do peso específico do material por ρm=γ/g.</div><button className=\"inspector-apply\" onClick={applyNode}>Aplicar alterações</button>"
s=rep(s,old_node,new_node,'inspector node mass UI')
p.write_text(s)

# Analysis panel: dynamic modes and settings.
p=Path('app/src/AnalysisPanelV13.tsx');s=p.read_text()
insert_after="""function incompatibilities(project:any){
"""
# Add helper before export, after incompatibilities function closing by targeting return issues block.
anchor="""  return issues;
}

export function AnalysisPanelV13"""
helper="""  return issues;
}

function dynamicIncompatibilities(project:any,timeHistory=false){
  const issues:string[]=[];
  if(!project.elements?.length)issues.push('O modelo não possui elementos.');
  for(const e of project.elements||[]){
    if(!['frame2d','truss2d'].includes(e.type))issues.push(`Elemento ${e.id}: tipo não suportado na dinâmica v0.23.`);
    if(e.type==='frame2d'&&(e.releases?.rz1||e.releases?.rz2||explicitSpring(e.rotationalSprings?.rz1)||explicitSpring(e.rotationalSprings?.rz2)))issues.push(`Elemento ${e.id}: dinâmica v0.23 requer extremidades rígidas.`);
    if(e.distributedPlasticity?.enabled||e.fiberHinges?.rz1?.enabled||e.fiberHinges?.rz2?.enabled)issues.push(`Elemento ${e.id}: desative a não linearidade material para dinâmica linear.`);
    const m=(project.materials||[]).find((x:any)=>x.id===e.materialId);if(!(num(m?.density)>0))issues.push(`Elemento ${e.id}: material deve possuir peso específico density > 0 kN/m³.`);
  }
  if((project.settlements||[]).length)issues.push('Recalques/deslocamentos impostos ainda não são suportados na dinâmica v0.23.');
  if((project.supports||[]).some((x:any)=>[x.uxValue,x.uyValue,x.rzValue,x.baseUxValue,x.baseUyValue,x.baseRzValue].some(v=>Math.abs(num(v))>1e-12)))issues.push('Apoios dinâmicos devem possuir deslocamentos prescritos nulos.');
  if(timeHistory){const allowed=new Set(['uniform','selfWeight','point']);const bad=(project.elementLoads||[]).filter((l:any)=>!allowed.has(l.kind));if(bad.length)issues.push(`História temporal não aceita neste estágio: ${[...new Set(bad.map((x:any)=>x.kind))].join(', ')}.`)}
  return [...new Set(issues)];
}

export function AnalysisPanelV13"""
s=rep(s,anchor,helper,'analysis dynamic helper')
state_anchor="  const [materialCoupling,setMaterialCoupling]=useState(project.settings?.materialCoupling||'embedded');"
state_new=state_anchor+"\n  const [dynamicMassFormulation,setDynamicMassFormulation]=useState(project.settings?.dynamicMassFormulation==='lumped'?'lumped':'consistent');\n  const [modalModes,setModalModes]=useState(project.settings?.modalModes??6);\n  const [dynamicDampingRatio,setDynamicDampingRatio]=useState(project.settings?.dynamicDampingRatio??.02);\n  const [dynamicRayleighMode1,setDynamicRayleighMode1]=useState(project.settings?.dynamicRayleighMode1??1);\n  const [dynamicRayleighMode2,setDynamicRayleighMode2]=useState(project.settings?.dynamicRayleighMode2??2);\n  const [dynamicTimeStep,setDynamicTimeStep]=useState(project.settings?.dynamicTimeStep??.01);\n  const [dynamicDuration,setDynamicDuration]=useState(project.settings?.dynamicDuration??1);\n  const [dynamicMonitorNodeId,setDynamicMonitorNodeId]=useState(project.settings?.dynamicMonitorNodeId||project.nodes?.[project.nodes.length-1]?.id||'');\n  const [dynamicMonitorDof,setDynamicMonitorDof]=useState(project.settings?.dynamicMonitorDof||'uy');\n  const [dynamicHistoryText,setDynamicHistoryText]=useState((project.settings?.dynamicHistoryPoints||[{t:0,scale:0},{t:.1,scale:1},{t:1,scale:0}]).map((x:any)=>`${num(x.t)}:${num(x.scale)}`).join(', '));"
s=rep(s,state_anchor,state_new,'analysis dynamic states')
logic_anchor="  const materialRequiresCorotational=mode!=='corotational'&&hasFiberHinges;"
logic_new="  const dynamicMode=mode==='modal'||mode==='time-history',dynamicIssues=useMemo(()=>dynamicIncompatibilities(effectiveProject,mode==='time-history'),[effectiveProject,mode]);\n  const materialRequiresCorotational=mode!=='corotational'&&hasFiberHinges;"
s=rep(s,logic_anchor,logic_new,'analysis dynamic logic')
s=s.replace("const followerRequiresCorotational=mode!=='corotational'&&followerLoads.length>0;","const followerRequiresCorotational=!['corotational','modal'].includes(mode)&&followerLoads.length>0;")
apply_anchor="    p.settings.materialMaxIterations=Math.max(3,Math.min(80,Math.round(num(materialMaxIt,30))));p.settings.materialTolerance=Math.max(1e-10,num(materialTol,1e-6));p.settings.materialRelaxation=Math.max(.2,Math.min(1,num(materialRelaxation,1)));p.settings.materialCoupling=controlMode!=='load'?'embedded':(materialCoupling==='outer'?'outer':'embedded');"
apply_new=apply_anchor+"\n    p.settings.dynamicMassFormulation=dynamicMassFormulation==='lumped'?'lumped':'consistent';p.settings.modalModes=Math.max(1,Math.min(20,Math.round(num(modalModes,6))));p.settings.dynamicDampingRatio=Math.max(0,Math.min(.30,num(dynamicDampingRatio,.02)));p.settings.dynamicRayleighMode1=Math.max(1,Math.min(20,Math.round(num(dynamicRayleighMode1,1))));p.settings.dynamicRayleighMode2=Math.max(1,Math.min(20,Math.round(num(dynamicRayleighMode2,2))));p.settings.dynamicTimeStep=Math.max(1e-5,num(dynamicTimeStep,.01));p.settings.dynamicDuration=Math.max(p.settings.dynamicTimeStep,num(dynamicDuration,1));p.settings.dynamicMonitorNodeId=dynamicMonitorNodeId||null;p.settings.dynamicMonitorDof=['ux','uy','rz'].includes(dynamicMonitorDof)?dynamicMonitorDof:'uy';const parsedDynamic=String(dynamicHistoryText).split(/[,;]+/).map(x=>x.trim()).filter(Boolean).map(x=>{const [t,scale]=x.split(':').map(Number);return{t,scale}}).filter(x=>Number.isFinite(x.t)&&Number.isFinite(x.scale)).sort((a,b)=>a.t-b.t);p.settings.dynamicHistoryPoints=parsedDynamic.length>=2?parsedDynamic:[{t:0,scale:0},{t:.1,scale:1},{t:1,scale:0}];"
s=rep(s,apply_anchor,apply_new,'analysis dynamic apply')
choice_anchor='<button data-testid="analysis-corotational" disabled={!nonlinearOk} className={mode===\'corotational\'?\'active\':\'\'} onClick={()=>setMode(\'corotational\')}><b>Geom. não linear</b><span>Co‑rotacional + Newton–Raphson</span><small>Núcleo geom. v0.13.6 · estabilidade multimodal v0.19.</small></button>'
choice_new=choice_anchor+'<button data-testid="analysis-modal" className={mode===\'modal\'?\'active\':\'\'} onClick={()=>setMode(\'modal\')}><b>Modal · v0.23</b><span>Kφ = ω²Mφ</span><small>Frequências, períodos e massas efetivas.</small></button><button data-testid="analysis-time-history" className={mode===\'time-history\'?\'active\':\'\'} onClick={()=>setMode(\'time-history\')}><b>Hist. temporal · v0.23</b><span>Mü + Ců + Ku = p(t)</span><small>Newmark-β + Rayleigh.</small></button>'
s=rep(s,choice_anchor,choice_new,'analysis choices')
warning_anchor="      {materialRequiresCorotational&&<div data-testid=\"material-mode-warning\""
warning_insert="      {dynamicMode&&dynamicIssues.length>0&&<div data-testid=\"dynamic-incompatibilities\" className=\"panel-warning\"><b>Dinâmica v0.23 indisponível neste modelo:</b><ul>{dynamicIssues.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}\n"+warning_anchor
s=rep(s,warning_anchor,warning_insert,'analysis dynamic warning')
pdelta_anchor="      {mode==='pdelta'&&<section className=\"react-card\"><h3>Controle P‑Delta</h3>"
dynamic_section="""      {dynamicMode&&<section className=\"react-card\" data-testid=\"dynamic-controls\"><div className=\"section-title\"><h3>Dinâmica linear · v0.23</h3><span className=\"chip\">M + C + K</span></div><div className=\"geometry-grid\"><label>Matriz de massa<select data-testid=\"dynamic-mass-formulation\" value={dynamicMassFormulation} onChange={e=>setDynamicMassFormulation(e.target.value)}><option value=\"consistent\">Consistente</option><option value=\"lumped\">Concentrada</option></select></label><label>Nº de modos<input data-testid=\"modal-mode-count\" type=\"number\" min=\"1\" max=\"20\" value={modalModes} onChange={e=>setModalModes(num(e.target.value,6))}/></label></div><div className=\"panel-note\">`density` é peso específico [kN/m³]; a massa volumétrica é calculada por ρm=γ/g. Massas nodais adicionais podem ser definidas no Inspector em toneladas.</div>{mode==='time-history'&&<><h3>Integração temporal</h3><div className=\"geometry-grid\"><label>Amortecimento ζ<input data-testid=\"dynamic-damping-ratio\" type=\"number\" min=\"0\" max=\"0.30\" step=\"0.005\" value={dynamicDampingRatio} onChange={e=>setDynamicDampingRatio(num(e.target.value,.02))}/></label><label>Modo Rayleigh 1<input data-testid=\"dynamic-rayleigh-mode-1\" type=\"number\" min=\"1\" max=\"20\" value={dynamicRayleighMode1} onChange={e=>setDynamicRayleighMode1(num(e.target.value,1))}/></label><label>Modo Rayleigh 2<input data-testid=\"dynamic-rayleigh-mode-2\" type=\"number\" min=\"1\" max=\"20\" value={dynamicRayleighMode2} onChange={e=>setDynamicRayleighMode2(num(e.target.value,2))}/></label><label>Δt [s]<input data-testid=\"dynamic-time-step\" type=\"number\" min=\"0.00001\" step=\"0.001\" value={dynamicTimeStep} onChange={e=>setDynamicTimeStep(num(e.target.value,.01))}/></label><label>Duração [s]<input data-testid=\"dynamic-duration\" type=\"number\" min=\"0.00001\" step=\"0.1\" value={dynamicDuration} onChange={e=>setDynamicDuration(num(e.target.value,1))}/></label><label>Nó monitor<select data-testid=\"dynamic-monitor-node\" value={dynamicMonitorNodeId} onChange={e=>setDynamicMonitorNodeId(e.target.value)}>{(project.nodes||[]).map((n:any)=><option key={n.id} value={n.id}>{n.id}</option>)}</select></label><label>DOF monitor<select data-testid=\"dynamic-monitor-dof\" value={dynamicMonitorDof} onChange={e=>setDynamicMonitorDof(e.target.value)}><option value=\"ux\">Ux</option><option value=\"uy\">Uy</option><option value=\"rz\">Rz</option></select></label><label>História t:escala<input data-testid=\"dynamic-history-points\" value={dynamicHistoryText} onChange={e=>setDynamicHistoryText(e.target.value)}/></label></div><div className=\"panel-note\">Formato: <b>0:0, 0.10:1, 1.00:0</b>. O vetor de cargas do cenário é escalado no tempo. A v0.23 ainda não usa aceleração de base.</div></>}</section>}\n"""+pdelta_anchor
s=rep(s,pdelta_anchor,dynamic_section,'analysis dynamic controls')
old_commit="<div className=\"commit-bar\"><span>{mode==='corotational'?'Modo experimental: valide independentemente antes de uso profissional.':'Linear permanece o padrão; P‑Delta não substitui análise de flambagem/autovalores.'}</span><div className=\"commit-actions\"><button onClick={onClose}>Cancelar</button><button data-testid=\"analysis-apply\" className=\"primary\" disabled={(mode==='corotational'&&!nonlinearOk)||followerRequiresCorotational||materialRequiresCorotational} onClick={apply}>Aplicar</button></div></div>"
new_commit="<div className=\"commit-bar\"><span>{mode==='corotational'?'Modo experimental: valide independentemente antes de uso profissional.':dynamicMode?'Dinâmica v0.23: linear-elástica; análise cíclica quase-estática permanece separada.':'Linear permanece o padrão; P‑Delta não substitui análise de flambagem/autovalores.'}</span><div className=\"commit-actions\"><button onClick={onClose}>Cancelar</button><button data-testid=\"analysis-apply\" className=\"primary\" disabled={(mode==='corotational'&&!nonlinearOk)||(dynamicMode&&dynamicIssues.length>0)||followerRequiresCorotational||materialRequiresCorotational} onClick={apply}>Aplicar</button></div></div>"
s=rep(s,old_commit,new_commit,'analysis commit bar')
p.write_text(s)

# App dynamic result summaries and postprocess routing.
p=Path('app/src/App.tsx');s=p.read_text()
s=rep(s,
"import { NonlinearReportPanel } from './NonlinearReportPanel';",
"import { NonlinearReportPanel } from './NonlinearReportPanel';\nimport { DynamicsPostprocessPanel } from './DynamicsPostprocessPanel';",
'app dynamic import')
results_anchor="function ResultsPanel({result}:{result:any}){\n  if(!result)return <div className=\"empty-state\">Execute a análise para visualizar deslocamentos, reações e esforços.</div>;"
results_new=results_anchor+"\n  if(result.analysisType==='modal'){const modes=result.modal?.modes||result.modes||[],m=modes[0];return <div className=\"results-content\" data-testid=\"dynamic-results-modal\"><div className=\"metrics\"><div><span>Solver</span><strong>{result.type}</strong></div><div><span>f₁</span><strong>{m?Number(m.frequencyHz).toFixed(4):'—'} Hz</strong></div><div><span>T₁</span><strong>{m?Number(m.period).toFixed(5):'—'} s</strong></div><div><span>Massa</span><strong>{result.massFormulation}</strong></div></div><div className=\"panel-note\">Forma exibida no canvas é normalizada para visualização; não representa deslocamento físico em metros.</div><div className=\"table-wrap\"><table><thead><tr><th>Modo</th><th>f [Hz]</th><th>T [s]</th><th>ΣMef,X</th><th>ΣMef,Y</th></tr></thead><tbody>{modes.map((x:any)=><tr key={x.mode}><td>{x.mode}</td><td>{Number(x.frequencyHz).toFixed(5)}</td><td>{Number(x.period).toFixed(5)}</td><td>{(100*Number(x.participation?.cumulativeMassRatioX||0)).toFixed(2)}%</td><td>{(100*Number(x.participation?.cumulativeMassRatioY||0)).toFixed(2)}%</td></tr>)}</tbody></table></div></div>}\n  if(result.analysisType==='time-history'){return <div className=\"results-content\" data-testid=\"dynamic-results-time\"><div className=\"metrics\"><div><span>Solver</span><strong>{result.type}</strong></div><div><span>Monitor</span><strong>{result.monitor?.nodeId}/{String(result.monitor?.dof||'').toUpperCase()}</strong></div><div><span>|u| pico</span><strong>{(1000*Number(result.peakResponse?.absDisplacement||0)).toFixed(4)} mm</strong></div><div><span>Δt</span><strong>{Number(result.newmark?.timeStep||0).toFixed(5)} s</strong></div></div><div className=\"panel-note\">História temporal linear por Newmark average-acceleration com amortecimento de Rayleigh. Abra Diagramas/envelopes para o gráfico completo.</div></div>}"
s=rep(s,results_anchor,results_new,'app dynamic results')
route_old="panel==='postprocess'&&project.settings?.analysisType==='corotational'?<NonlinearPostprocessPanel project={project} result={result} onClose={()=>setPanel(null)}/>:panel==='report'&&project.settings?.analysisType==='corotational'?<NonlinearReportPanel project={project} result={result} onClose={()=>setPanel(null)}/>:<EngineeringPanels"
route_new="panel==='postprocess'&&project.settings?.analysisType==='corotational'?<NonlinearPostprocessPanel project={project} result={result} onClose={()=>setPanel(null)}/>:panel==='postprocess'&&['modal','time-history'].includes(project.settings?.analysisType)?<DynamicsPostprocessPanel result={result} onClose={()=>setPanel(null)}/>:panel==='report'&&project.settings?.analysisType==='corotational'?<NonlinearReportPanel project={project} result={result} onClose={()=>setPanel(null)}/>:<EngineeringPanels"
s=rep(s,route_old,route_new,'app dynamic route')
p.write_text(s)

# README and documentation.
p=Path('README.md');s=p.read_text()
s=s.replace('> **v0.22 experimental:** história constitutiva cíclica agora também nas rótulas concentradas de fibras de aço, com retorno plástico, endurecimento combinado, efeito Bauschinger, commit/rollback e demanda plástica acumulada.','> **v0.23 experimental:** fundação de dinâmica estrutural linear com massas consistente/concentrada, análise modal, participação de massa, amortecimento de Rayleigh e integração temporal Newmark-β.')
s=s.replace('> **Estado atual — v0.22.0 experimental:**','> **Estado atual — v0.23.0 experimental:**')
marker='- documentação das rótulas concentradas cíclicas e demanda acumulada em `docs/cyclic-hinges-v022.md`;'
if '- **dinâmica estrutural linear v0.23' not in s:
    s=s.replace(marker,marker+'\n- **dinâmica estrutural linear v0.23 com Kφ=ω²Mφ, massas modais efetivas, Rayleigh e Newmark average-acceleration**;\n- documentação do núcleo dinâmico em `docs/structural-dynamics-v023.md`;')
p.write_text(s)

doc=Path('docs/structural-dynamics-v023.md')
if not doc.exists():doc.write_text('''# AstraStruct v0.23 — dinâmica estrutural linear\n\n## Escopo\n\nA v0.23 introduz a primeira fundação dinâmica do AstraStruct sem reutilizar indevidamente a análise cíclica quase-estática. O núcleo aceita modelos 2D formados por `frame2d` e `truss2d`, com comportamento linear-elástico e extremidades rígidas nos elementos de pórtico.\n\n## Massa\n\n`material.density` mantém a convenção existente do projeto: peso específico `gamma` em kN/m³. A densidade de massa usada na equação dinâmica é `rho_m = gamma/g`, com `g = 9.80665 m/s²`. Massas nodais adicionais usam kN·s²/m, numericamente equivalentes a toneladas para translação, e kN·s²·m para inércia rotacional.\n\nA formulação consistente usa a matriz clássica Euler–Bernoulli para `frame2d` e a matriz consistente translacional para `truss2d`. A opção lumped concentra metade da massa do elemento em cada nó translacional; DOFs rotacionais podem permanecer sem massa, pois o problema modal é resolvido pela transformação baseada em Cholesky de K, sem exigir M positiva definida.\n\n## Análise modal\n\nO problema `K phi = omega² M phi` é transformado em um problema simétrico para `mu = 1/omega²`. Os modos são normalizados por massa, e são calculados frequência, período, fatores de participação e massas modais efetivas nas direções globais X e Y, incluindo somatórios acumulados.\n\n## Amortecimento de Rayleigh\n\n`C = alpha_M M + beta_K K`. Para um amortecimento alvo `zeta`, os coeficientes são calibrados em dois modos escolhidos. Se ambos coincidirem, a implementação usa apenas a parcela proporcional à massa.\n\n## História temporal\n\nA v0.23 usa Newmark average-acceleration (`beta=1/4`, `gamma=1/2`) para `M u_ddot + C u_dot + K u = p(t)`. O vetor do cenário selecionado é tratado como padrão espacial e multiplicado por uma história escalar linearmente interpolada. A integração parte do repouso e a escala deve ser zero em `t=0`.\n\nA implementação foi validada contra: (1) autovalor fechado do modelo discreto axial de uma barra, com massa consistente e concentrada; (2) solução discreta exata do Newmark para vibração livre SDOF; (3) conservação de energia sem amortecimento; e (4) calibração exata do amortecimento de Rayleigh nos modos-alvo.\n\n## Limitações\n\nAinda não há aceleração de base, espectro de resposta, combinação modal SRSS/CQC, dinâmica não linear, amortecimento histerético, releases/semirrigidez dinâmica, contato, integração constitutiva cíclica no tempo ou análise sísmica normativa. A história cíclica v0.21/v0.22 permanece uma análise quase-estática separada.\n''')
