from pathlib import Path


def rep(s, old, new, label):
    if new in s:
        return s
    if old not in s:
        raise SystemExit(f'{label}: anchor missing')
    return s.replace(old, new)

# -----------------------------------------------------------------------------
# Project model: v0.25 seismic preprocessing, XY records and local record library
# -----------------------------------------------------------------------------
p=Path('web/src/core/model.js');s=p.read_text()
old="dynamicExcitationType: 'load-pattern', dynamicGroundMotionDirection: 'x', dynamicGroundMotionPoints: [{t:0,accelG:0},{t:0.05,accelG:0.15},{t:0.10,accelG:0},{t:0.15,accelG:-0.10},{t:0.20,accelG:0}], responseSpectrumCombination: 'cqc', responseSpectrumPeriodMin: 0.02, responseSpectrumPeriodMax: 4, responseSpectrumPeriodPoints: 80,"
new="dynamicExcitationType: 'load-pattern', dynamicGroundMotionDirection: 'x', dynamicGroundMotionPoints: [{t:0,accelG:0},{t:0.05,accelG:0.15},{t:0.10,accelG:0},{t:0.15,accelG:-0.10},{t:0.20,accelG:0}], dynamicGroundMotionPointsY: [{t:0,accelG:0},{t:0.05,accelG:0.10},{t:0.10,accelG:0},{t:0.15,accelG:-0.06},{t:0.20,accelG:0}], groundMotionBaselineCorrection: 'linear', groundMotionTaperRatio: 0.02, groundMotionHighPassHz: 0, groundMotionLowPassHz: 0, groundMotionResampleDt: 0, groundMotionScaleFactor: 1, dynamicGroundMotionLibrary: [], responseSpectrumCombination: 'cqc', responseSpectrumDirectionalCombination: 'srss', responseSpectrumPeriodMin: 0.02, responseSpectrumPeriodMax: 4, responseSpectrumPeriodPoints: 80, responseSpectrumTargetPoints: [],"
s=rep(s,old,new,'model defaults')
old="  p.settings.dynamicGroundMotionDirection = p.settings.dynamicGroundMotionDirection === 'y' ? 'y' : 'x';\n  p.settings.dynamicGroundMotionPoints = (Array.isArray(p.settings.dynamicGroundMotionPoints)?p.settings.dynamicGroundMotionPoints:[]).map(x=>({t:Number(x?.t),accelG:Number(x?.accelG??x?.accelerationG??x?.scale)})).filter(x=>Number.isFinite(x.t)&&Number.isFinite(x.accelG)).sort((a,b)=>a.t-b.t).slice(0,5000);\n  if(p.settings.dynamicGroundMotionPoints.length<2)p.settings.dynamicGroundMotionPoints=[{t:0,accelG:0},{t:.05,accelG:.15},{t:.10,accelG:0},{t:.15,accelG:-.10},{t:.20,accelG:0}];\n  p.settings.responseSpectrumCombination = p.settings.responseSpectrumCombination === 'srss' ? 'srss' : 'cqc';\n  p.settings.responseSpectrumPeriodMin = Math.max(0.001, Number(p.settings.responseSpectrumPeriodMin) || .02);\n  p.settings.responseSpectrumPeriodMax = Math.max(p.settings.responseSpectrumPeriodMin, Number(p.settings.responseSpectrumPeriodMax) || 4);\n  p.settings.responseSpectrumPeriodPoints = Math.max(10, Math.min(300, Math.round(Number(p.settings.responseSpectrumPeriodPoints) || 80)));"
new="  p.settings.dynamicGroundMotionDirection = ['x','y','xy'].includes(p.settings.dynamicGroundMotionDirection) ? p.settings.dynamicGroundMotionDirection : 'x';\n  const normGround=raw=>(Array.isArray(raw)?raw:[]).map(x=>({t:Number(x?.t),accelG:Number(x?.accelG??x?.accelerationG??x?.scale)})).filter(x=>Number.isFinite(x.t)&&Number.isFinite(x.accelG)).sort((a,b)=>a.t-b.t).slice(0,10000);\n  p.settings.dynamicGroundMotionPoints = normGround(p.settings.dynamicGroundMotionPoints);\n  if(p.settings.dynamicGroundMotionPoints.length<2)p.settings.dynamicGroundMotionPoints=[{t:0,accelG:0},{t:.05,accelG:.15},{t:.10,accelG:0},{t:.15,accelG:-.10},{t:.20,accelG:0}];\n  p.settings.dynamicGroundMotionPointsY = normGround(p.settings.dynamicGroundMotionPointsY);\n  if(p.settings.dynamicGroundMotionPointsY.length<2)p.settings.dynamicGroundMotionPointsY=[{t:0,accelG:0},{t:.05,accelG:.10},{t:.10,accelG:0},{t:.15,accelG:-.06},{t:.20,accelG:0}];\n  p.settings.groundMotionBaselineCorrection = ['none','mean','linear'].includes(p.settings.groundMotionBaselineCorrection) ? p.settings.groundMotionBaselineCorrection : 'linear';\n  p.settings.groundMotionTaperRatio = Math.max(0,Math.min(.25,Number(p.settings.groundMotionTaperRatio) || 0));\n  p.settings.groundMotionHighPassHz = Math.max(0,Number(p.settings.groundMotionHighPassHz) || 0);\n  p.settings.groundMotionLowPassHz = Math.max(0,Number(p.settings.groundMotionLowPassHz) || 0);\n  p.settings.groundMotionResampleDt = Math.max(0,Number(p.settings.groundMotionResampleDt) || 0);\n  p.settings.groundMotionScaleFactor = Number.isFinite(Number(p.settings.groundMotionScaleFactor)) ? Number(p.settings.groundMotionScaleFactor) : 1;\n  p.settings.dynamicGroundMotionLibrary = (Array.isArray(p.settings.dynamicGroundMotionLibrary)?p.settings.dynamicGroundMotionLibrary:[]).slice(0,12).map((r,i)=>({id:String(r?.id||`GM${i+1}`),name:String(r?.name||`Registro ${i+1}`),x:normGround(r?.x),y:normGround(r?.y)})).filter(r=>r.x.length>=2);\n  p.settings.responseSpectrumCombination = p.settings.responseSpectrumCombination === 'srss' ? 'srss' : 'cqc';\n  p.settings.responseSpectrumDirectionalCombination = p.settings.responseSpectrumDirectionalCombination === '100-30' ? '100-30' : 'srss';\n  p.settings.responseSpectrumPeriodMin = Math.max(0.001, Number(p.settings.responseSpectrumPeriodMin) || .02);\n  p.settings.responseSpectrumPeriodMax = Math.max(p.settings.responseSpectrumPeriodMin, Number(p.settings.responseSpectrumPeriodMax) || 4);\n  p.settings.responseSpectrumPeriodPoints = Math.max(10, Math.min(300, Math.round(Number(p.settings.responseSpectrumPeriodPoints) || 80)));\n  p.settings.responseSpectrumTargetPoints = (Array.isArray(p.settings.responseSpectrumTargetPoints)?p.settings.responseSpectrumTargetPoints:[]).map(x=>({period:Number(x?.period??x?.t),saG:Number(x?.saG??x?.sa)})).filter(x=>Number.isFinite(x.period)&&x.period>0&&Number.isFinite(x.saG)&&x.saG>0).sort((a,b)=>a.period-b.period).slice(0,500);"
s=rep(s,old,new,'model normalization')
p.write_text(s)

# -----------------------------------------------------------------------------
# Dynamic solver v0.25. Keep assembly/modal/Newmark foundation, replace seismic tail.
# -----------------------------------------------------------------------------
p=Path('web/src/solver/dynamics2d.js');s=p.read_text().replace('v0.24','v0.25').replace("'0.24.0-exp'","'0.25.0-exp'")
start=s.index('function normalizeGroundMotion(raw){')
new_tail=r'''function sanitizeGroundMotion(raw,label='Acelerograma'){
  const points=(Array.isArray(raw)?raw:[]).map(x=>({t:Number(x?.t),accelG:Number(x?.accelG??x?.accelerationG??x?.scale)})).filter(x=>Number.isFinite(x.t)&&Number.isFinite(x.accelG)).sort((a,b)=>a.t-b.t);
  if(points.length<2)throw new Error(`${label} v0.25 requer ao menos dois pontos {t, accelG}.`);
  if(Math.abs(points[0].t)>1e-12)throw new Error(`${label} v0.25 deve iniciar em t=0.`);
  for(let i=1;i<points.length;i++)if(!(points[i].t>points[i-1].t))throw new Error(`${label}: tempos devem ser estritamente crescentes.`);
  return points;
}
function groundAcceleration(points,t){return interpolateHistory(points.map(x=>({t:x.t,scale:x.accelG*G0})),t)}
function groundAccelerationG(points,t){return interpolateHistory(points.map(x=>({t:x.t,scale:x.accelG})),t)}
function minGroundStep(points){let h=Infinity;for(let i=1;i<points.length;i++)h=Math.min(h,points[i].t-points[i-1].t);return Number.isFinite(h)?h:.01}
function medianGroundStep(points){const ds=[];for(let i=1;i<points.length;i++)ds.push(points[i].t-points[i-1].t);ds.sort((a,b)=>a-b);return ds.length?ds[Math.floor(ds.length/2)]:.01}
function groundStats(points){let mean=0,pgaG=0;for(const p of points){mean+=p.accelG;pgaG=Math.max(pgaG,Math.abs(p.accelG))}mean/=points.length;let v=0,d=0;for(let i=1;i<points.length;i++){const dt=points[i].t-points[i-1].t,a0=points[i-1].accelG*G0,a1=points[i].accelG*G0,vn=v+.5*(a0+a1)*dt;d+=.5*(v+vn)*dt;v=vn}const dts=points.slice(1).map((p,i)=>p.t-points[i].t),dtMin=Math.min(...dts),dtMax=Math.max(...dts),dtMedian=medianGroundStep(points);return{samples:points.length,duration:points.at(-1).t,pgaG,meanAccelG:mean,dtMin,dtMax,dtMedian,samplingVariation:dtMedian>0?(dtMax-dtMin)/dtMedian:0,finalVelocity:v,finalDisplacement:d}}
function removeBaseline(points,mode){
  const kind=['mean','linear'].includes(mode)?mode:'none';if(kind==='none')return points.map(x=>({...x}));const n=points.length,mt=points.reduce((q,x)=>q+x.t,0)/n,ma=points.reduce((q,x)=>q+x.accelG,0)/n;if(kind==='mean')return points.map(x=>({t:x.t,accelG:x.accelG-ma}));let num=0,den=0;for(const x of points){num+=(x.t-mt)*(x.accelG-ma);den+=(x.t-mt)**2}const b=den>EPS?num/den:0,a=ma-b*mt;return points.map(x=>({t:x.t,accelG:x.accelG-(a+b*x.t)}));
}
function taperGround(points,ratio){const r=clamp(Number(ratio)||0,0,.25);if(!(r>0))return points.map(x=>({...x}));const T=points.at(-1).t,wT=Math.max(EPS,r*T);return points.map(x=>{const edge=Math.min(x.t,T-x.t),q=clamp(edge/wT,0,1),w=q>=1?1:.5*(1-Math.cos(Math.PI*q));return{t:x.t,accelG:x.accelG*w}})}
function resampleGround(points,dt){const h=Number(dt);if(!(h>0))return points.map(x=>({...x}));const T=points.at(-1).t,n=Math.max(1,Math.round(T/h)),step=T/n,src=points.map(x=>({t:x.t,scale:x.accelG}));return Array.from({length:n+1},(_,i)=>({t:i===n?T:i*step,accelG:interpolateHistory(src,i===n?T:i*step)}))}
function rcPass(values,dt,cutoff,type){const fc=Number(cutoff);if(!(fc>0))return [...values];const rc=1/(2*Math.PI*fc),out=Array(values.length).fill(0);if(type==='low'){const a=dt/(rc+dt);out[0]=values[0];for(let i=1;i<values.length;i++)out[i]=out[i-1]+a*(values[i]-out[i-1])}else{const a=rc/(rc+dt);out[0]=0;for(let i=1;i<values.length;i++)out[i]=a*(out[i-1]+values[i]-values[i-1])}return out}
function zeroPhaseRc(values,dt,cutoff,type){const f=rcPass(values,dt,cutoff,type),b=rcPass([...f].reverse(),dt,cutoff,type);return b.reverse()}
export function preprocessGroundMotion(raw,options={}){
  const input=sanitizeGroundMotion(raw),baselineCorrection=['mean','linear'].includes(options.baselineCorrection)?options.baselineCorrection:'none',taperRatio=clamp(Number(options.taperRatio)||0,0,.25),resampleDt=Math.max(0,Number(options.resampleDt)||0),highPassHz=Math.max(0,Number(options.highPassHz)||0),lowPassHz=Math.max(0,Number(options.lowPassHz)||0),scaleFactor=Number.isFinite(Number(options.scaleFactor))?Number(options.scaleFactor):1,rawStats=groundStats(input);let points=removeBaseline(input,baselineCorrection);points=taperGround(points,taperRatio);points=resampleGround(points,resampleDt);const dt=medianGroundStep(points),nyq=.5/dt;if(highPassHz>0&&highPassHz>=nyq)throw new Error(`Pré-processamento: high-pass ${highPassHz} Hz excede Nyquist ${nyq.toFixed(3)} Hz.`);if(lowPassHz>0&&lowPassHz>=nyq)throw new Error(`Pré-processamento: low-pass ${lowPassHz} Hz excede Nyquist ${nyq.toFixed(3)} Hz.`);if(highPassHz>0&&lowPassHz>0&&highPassHz>=lowPassHz)throw new Error('Pré-processamento: frequência high-pass deve ser menor que low-pass.');let values=points.map(x=>x.accelG);if(highPassHz>0)values=zeroPhaseRc(values,dt,highPassHz,'high');if(lowPassHz>0)values=zeroPhaseRc(values,dt,lowPassHz,'low');points=points.map((x,i)=>({t:x.t,accelG:values[i]*scaleFactor}));const processedStats=groundStats(points);return{points,options:{baselineCorrection,taperRatio,resampleDt,highPassHz,lowPassHz,scaleFactor},rawStats,processedStats,filter:{type:'first-order-zero-phase-RC',effectiveDt:dt,nyquistHz:nyq}};
}
function preprocessOptions(options){return{baselineCorrection:options?.baselineCorrection??'none',taperRatio:options?.taperRatio??0,highPassHz:options?.highPassHz??0,lowPassHz:options?.lowPassHz??0,resampleDt:options?.resampleDt??0,scaleFactor:options?.scaleFactor??1}}
function vectorPgaG(x,y){const tx=x||[],ty=y||[],times=[...new Set([...tx.map(p=>p.t),...ty.map(p=>p.t)])].sort((a,b)=>a-b);let peak=0;for(const t of times)peak=Math.max(peak,Math.hypot(tx.length?groundAccelerationG(tx,t):0,ty.length?groundAccelerationG(ty,t):0));return peak}

export function cqcCorrelation(omegaI,omegaJ,dampingRatio=.05){
  const wi=Math.abs(Number(omegaI)),wj=Math.abs(Number(omegaJ)),z=clamp(Math.abs(Number(dampingRatio)||0),0,.30);if(!(wi>0&&wj>0))return 0;if(Math.abs(wi-wj)<=1e-12*Math.max(wi,wj))return 1;const r=Math.min(wi,wj)/Math.max(wi,wj),num=8*z*z*(1+r)*Math.pow(r,1.5),den=Math.pow(1-r*r,2)+4*z*z*r*Math.pow(1+r,2);return den>EPS?clamp(num/den,0,1):0;
}
function sdofSpectrumPoint(points,period,dampingRatio,timeStep){
  const T=Number(period),z=clamp(Number(dampingRatio)||0,0,.30);if(!(T>0))throw new Error('Espectro: período deve ser positivo.');const omega=2*Math.PI/T,m=1,k=omega*omega,c=2*z*omega,duration=points.at(-1).t,h=Math.min(Math.max(1e-5,Number(timeStep)||minGroundStep(points)),Math.max(1e-5,duration)),steps=Math.max(1,Math.ceil(duration/h)),dt=duration/steps,b=.25,g=.5,A0=1/(b*dt*dt),A1=g/(b*dt),A2=1/(b*dt),A3=1/(2*b)-1,A4=g/b-1,A5=dt*(g/(2*b)-1),keff=k+A0*m+A1*c;let u=0,v=0,a=0,sd=0,absAcc=0;
  for(let step=1;step<=steps;step++){const t=step*dt,ag=groundAcceleration(points,t),p=-ag,rhs=p+m*(A0*u+A2*v+A3*a)+c*(A1*u+A4*v+A5*a),un=rhs/keff,an=A0*(un-u)-A2*v-A3*a,vn=v+dt*((1-g)*a+g*an);u=un;v=vn;a=an;sd=Math.max(sd,Math.abs(u));absAcc=Math.max(absAcc,Math.abs(a+ag))}
  const sv=omega*sd,sa=omega*omega*sd;return{period:T,frequencyHz:1/T,omega,sd,sv,sa,saG:sa/G0,absoluteAcceleration:absAcc,absoluteAccelerationG:absAcc/G0};
}
export function responseSpectrumFromGroundMotion(raw,options={}){
  const points=sanitizeGroundMotion(raw),z=clamp(Number(options.dampingRatio??.05)||0,0,.30),timeStep=Math.max(1e-5,Number(options.timeStep)||minGroundStep(points));let periods;if(Array.isArray(options.periods)&&options.periods.length)periods=[...new Set(options.periods.map(Number).filter(x=>Number.isFinite(x)&&x>0))].sort((a,b)=>a-b);else{const t0=Math.max(.001,Number(options.periodMin)||.02),t1=Math.max(t0,Number(options.periodMax)||4),n=clamp(Math.round(Number(options.periodCount)||80),10,300);periods=Array.from({length:n},(_,i)=>t0+(t1-t0)*(n===1?0:i/(n-1)))}const values=periods.map(T=>sdofSpectrumPoint(points,T,z,timeStep)),pgaG=Math.max(...points.map(x=>Math.abs(x.accelG)));return{dampingRatio:z,timeStep,groundMotionPoints:points,pgaG,pga:pgaG*G0,values,ordinates:{sd:'m',sv:'m/s pseudo',sa:'m/s² pseudo',saG:'g pseudo'}};
}
function combineModalVectors(vectors,omegas,zeta,method){if(!vectors.length)return[];const n=vectors[0].length,out=Array(n).fill(0),kind=method==='srss'?'srss':'cqc';for(let d=0;d<n;d++){let sum=0;if(kind==='srss'){for(const v of vectors)sum+=v[d]*v[d]}else for(let i=0;i<vectors.length;i++)for(let j=0;j<vectors.length;j++)sum+=cqcCorrelation(omegas[i],omegas[j],zeta)*vectors[i][d]*vectors[j][d];out[d]=Math.sqrt(Math.max(0,sum))}return out}
export function combineDirectionalPeaks(x,y,method='srss'){const n=Math.max(x?.length||0,y?.length||0),kind=method==='100-30'?'100-30':'srss',out=Array(n).fill(0);for(let i=0;i<n;i++){const a=Math.abs(Number(x?.[i])||0),b=Math.abs(Number(y?.[i])||0);out[i]=kind==='100-30'?Math.max(a+.3*b,.3*a+b):Math.hypot(a,b)}return out}
function spectrumComponent(project,modal,points,direction,options){const z=clamp(Number(options.dampingRatio??.05)||0,0,.30),dense=responseSpectrumFromGroundMotion(points,{dampingRatio:z,timeStep:options.timeStep,periodMin:options.periodMin,periodMax:options.periodMax,periodCount:options.periodCount}),atModes=responseSpectrumFromGroundMotion(points,{dampingRatio:z,timeStep:options.timeStep,periods:modal.modes.map(m=>m.period)}),specByPeriod=new Map(atModes.values.map(x=>[x.period,x])),vectors=[],omegas=[],modalContributions=[];for(const m of modal.modes){const sp=specByPeriod.get(m.period),participation=Number(m.participation?.[direction])||0,q=participation*sp.sd,vec=m.massNormalizedVector.map(v=>v*q),maxModalTranslational=Math.max(0,...project.nodes.map((n,i)=>Math.hypot(vec[3*i]||0,vec[3*i+1]||0)));vectors.push(vec);omegas.push(m.omega);modalContributions.push({mode:m.mode,period:m.period,frequencyHz:m.frequencyHz,omega:m.omega,participationFactor:participation,effectiveMassRatio:direction==='x'?m.participation?.effectiveMassRatioX:m.participation?.effectiveMassRatioY,sd:sp.sd,sv:sp.sv,sa:sp.sa,saG:sp.saG,generalizedPeak:q,maxModalTranslational})}const combination=options.combination==='srss'?'srss':'cqc',combinedVector=combineModalVectors(vectors,omegas,z,combination),cum=modal.modes.at(-1)?.participation?.[direction==='x'?'cumulativeMassRatioX':'cumulativeMassRatioY']||0;return{direction,spectrum:dense,modalContributions,combinedVector,cumulativeEffectiveMassRatio:cum}}
function targetPoints(raw){return(Array.isArray(raw)?raw:[]).map(x=>({period:Number(x?.period??x?.t),saG:Number(x?.saG??x?.sa)})).filter(x=>Number.isFinite(x.period)&&x.period>0&&Number.isFinite(x.saG)&&x.saG>0).sort((a,b)=>a.period-b.period)}
function interpTarget(points,T){if(points.length<2||T<points[0].period||T>points.at(-1).period)return null;for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1];if(T>=a.period&&T<=b.period){const r=(T-a.period)/(b.period-a.period);return a.saG+r*(b.saG-a.saG)}}return null}
export function compareSpectrumToTarget(spectrum,rawTarget){const target=targetPoints(rawTarget);if(target.length<2)return null;const rows=[];for(const p of spectrum?.values||[]){const tg=interpTarget(target,p.period);if(tg&&p.saG>0)rows.push({period:p.period,recordSaG:p.saG,targetSaG:tg,ratio:p.saG/tg})}if(!rows.length)return null;const logs=rows.map(r=>Math.log(r.ratio)),meanLog=logs.reduce((a,b)=>a+b,0)/logs.length,scaleFactor=Math.exp(-meanLog);return{targetPoints:target,rows,minRatio:Math.min(...rows.map(r=>r.ratio)),maxRatio:Math.max(...rows.map(r=>r.ratio)),geometricMeanRatio:Math.exp(meanLog),rmsLogError:Math.sqrt(logs.reduce((q,x)=>q+x*x,0)/logs.length),scaleFactorToTarget:scaleFactor}}
function geometricMeanSpectrum(a,b){const values=(a?.values||[]).map((x,i)=>{const y=b?.values?.[i]||x;return{...x,sd:Math.sqrt(Math.max(0,x.sd*y.sd)),sv:Math.sqrt(Math.max(0,x.sv*y.sv)),sa:Math.sqrt(Math.max(0,x.sa*y.sa)),saG:Math.sqrt(Math.max(0,x.saG*y.saG))}});return{...a,pgaG:Math.sqrt(Math.max(0,(a?.pgaG||0)*(b?.pgaG||0))),pga:G0*Math.sqrt(Math.max(0,(a?.pgaG||0)*(b?.pgaG||0))),values,recordMeasure:'geometric-mean-X-Y'}}
export function solveResponseSpectrum2D(project,options={}){
  const massFormulation=options.massFormulation==='lumped'?'lumped':'consistent',modesRequested=Math.max(1,Math.min(20,Math.round(Number(options.modes)||6))),modal=solveModal2D(project,{massFormulation,modes:modesRequested}),direction=['x','y','xy'].includes(options.direction)?options.direction:'x',z=clamp(Number(options.dampingRatio??.05)||0,0,.30),prep=preprocessOptions(options.preprocess),px=preprocessGroundMotion(options.groundMotionPoints,prep),py=direction==='xy'?preprocessGroundMotion(options.groundMotionPointsY,prep):null,combination=options.combination==='srss'?'srss':'cqc',cx=spectrumComponent(project,modal,px.points,direction==='y'?'y':'x',{...options,combination,dampingRatio:z});let spectrum=cx.spectrum,combinedVector=cx.combinedVector,modalContributions=cx.modalContributions,spectra=null,cy=null,directionalCombination=null,cumX=direction==='x'?cx.cumulativeEffectiveMassRatio:0,cumY=direction==='y'?cx.cumulativeEffectiveMassRatio:0;
  if(direction==='xy'){cy=spectrumComponent(project,modal,py.points,'y',{...options,combination,dampingRatio:z});directionalCombination=options.directionalCombination==='100-30'?'100-30':'srss';combinedVector=combineDirectionalPeaks(cx.combinedVector,cy.combinedVector,directionalCombination);spectra={x:cx.spectrum,y:cy.spectrum};spectrum=geometricMeanSpectrum(cx.spectrum,cy.spectrum);modalContributions={x:cx.modalContributions,y:cy.modalContributions};cumX=cx.cumulativeEffectiveMassRatio;cumY=cy.cumulativeEffectiveMassRatio}
  const displacements=project.nodes.map((n,i)=>({nodeId:n.id,ux:combinedVector[3*i]||0,uy:combinedVector[3*i+1]||0,rz:combinedVector[3*i+2]||0})),peakCombinedDisplacement=Math.max(0,...displacements.map(d=>Math.hypot(d.ux,d.uy))),comparison=compareSpectrumToTarget(spectrum,options.targetSpectrumPoints),pgaG=direction==='xy'?vectorPgaG(px.points,py.points):cx.spectrum.pgaG;
  return{type:'dynamic-response-spectrum2d',analysisType:'response-spectrum',solverVersion:'0.25.0-exp',dofs:modal.dofs,freeDofs:modal.freeDofs,massFormulation,densityConvention:modal.densityConvention,modal:{modes:modal.modes,requestedModes:modesRequested},direction,dampingRatio:z,combination,directionalCombination,spectrum,spectra,modalContributions,preprocessing:{x:px,y:py},targetComparison:comparison,pgaG,combined:{method:combination,directionalMethod:directionalCombination,peakTranslationalDisplacement:peakCombinedDisplacement,cumulativeEffectiveMassRatio:direction==='xy'?Math.min(cumX,cumY):(direction==='x'?cumX:cumY),cumulativeEffectiveMassRatioX:cumX,cumulativeEffectiveMassRatioY:cumY},displacements};
}
export function solveTimeHistory2D(project,scenarioId,options={}){
  const resolved=resolveScenario(project,scenarioId),p=resolved.project,excitationType=options.excitationType==='base-acceleration'?'base-acceleration':'scaled-load-pattern',sys=assembleDynamicSystem2D(p,{massFormulation:options.massFormulation,includeLoadVector:excitationType==='scaled-load-pattern'}),modal=solveModal2D(p,{massFormulation:options.massFormulation,modes:Math.max(2,Number(options.rayleighMode2)||2)}),rayleigh=rayleighFromModes(modal.modes,{dampingRatio:options.dampingRatio,mode1:options.rayleighMode1,mode2:options.rayleighMode2}),C=matAdd(matScale(sys.Mf,rayleigh.alphaM),matScale(sys.Kf,rayleigh.betaK)),raw=Array.isArray(options.historyPoints)?options.historyPoints:[],loadPoints=raw.map(x=>({t:Number(x.t),scale:Number(x.scale)})).filter(x=>Number.isFinite(x.t)&&Number.isFinite(x.scale)).sort((a,b)=>a.t-b.t),direction=['x','y','xy'].includes(options.groundMotionDirection)?options.groundMotionDirection:'x',prep=preprocessOptions(options.preprocess),px=excitationType==='base-acceleration'?preprocessGroundMotion(options.groundMotionPoints,prep):null,py=excitationType==='base-acceleration'&&direction==='xy'?preprocessGroundMotion(options.groundMotionPointsY,prep):null,groundX=direction==='y'?null:px?.points,groundY=direction==='y'?px?.points:py?.points;
  if(excitationType==='scaled-load-pattern'){if(loadPoints.length<2)throw new Error('História temporal v0.25 requer pelo menos dois pontos {t, scale}.');if(Math.abs(loadPoints[0].t)>1e-12||Math.abs(loadPoints[0].scale)>1e-12)throw new Error('História temporal v0.25 deve iniciar em t=0 com scale=0.');for(let i=1;i<loadPoints.length;i++)if(!(loadPoints[i].t>loadPoints[i-1].t))throw new Error('História temporal: tempos devem ser estritamente crescentes.');}
  const naturalDuration=excitationType==='base-acceleration'?Math.max(groundX?.at(-1)?.t||0,groundY?.at(-1)?.t||0):loadPoints.at(-1).t,duration=Number(options.duration)>0?Number(options.duration):naturalDuration,dt=Number(options.timeStep)||.01;if(!(duration>0&&dt>0))throw new Error('História temporal: duração e passo de tempo devem ser positivos.');if(Math.ceil(duration/dt)>10000)throw new Error('História temporal v0.25 limita a integração a 10.000 passos no navegador.');const nodeId=options.monitorNodeId||p.nodes?.at(-1)?.id,dof=['ux','uy','rz'].includes(options.monitorDof)?options.monitorDof:'uy',monitor=monitorDof(sys,nodeId,dof),peakByNode=new Map(p.nodes.map(n=>[n.id,{nodeId:n.id,ux:0,uy:0,rz:0}])),rx=excitationType==='base-acceleration'?influence(sys.free,'x'):null,ry=excitationType==='base-acceleration'?influence(sys.free,'y'):null,mrx=rx?mul(sys.Mf,rx):null,mry=ry?mul(sys.Mf,ry):null;
  const forceAtTime=t=>excitationType==='base-acceleration'?mrx.map((vx,i)=>-(vx*(groundX?groundAcceleration(groundX,t):0)+mry[i]*(groundY?groundAcceleration(groundY,t):0))):(()=>{const scale=interpolateHistory(loadPoints,t);return sys.Ff.map(v=>scale*v)})(),integrated=newmarkLinearSystem({M:sys.Mf,C,K:sys.Kf,forceAtTime,dt,duration,onStep:row=>{for(let ni=0;ni<p.nodes.length;ni++){const rec=peakByNode.get(p.nodes[ni].id);for(const [key,off] of [['ux',0],['uy',1],['rz',2]]){const pos=sys.free.indexOf(3*ni+off),value=pos>=0?Math.abs(row.u[pos]):0;if(value>rec[key])rec[key]=value}}}}),history=integrated.history.map(row=>{const agx=groundX?groundAcceleration(groundX,row.t):0,agy=groundY?groundAcceleration(groundY,row.t):0,agxG=agx/G0,agyG=agy/G0,relativeAcceleration=row.a[monitor.freePosition],monitorGround=monitor.dof==='ux'?agx:(monitor.dof==='uy'?agy:0);return{step:row.step,t:row.t,scale:excitationType==='scaled-load-pattern'?interpolateHistory(loadPoints,row.t):null,groundAcceleration:direction==='xy'?Math.hypot(agx,agy):(groundX?agx:agy),groundAccelerationG:direction==='xy'?Math.hypot(agxG,agyG):(groundX?agxG:agyG),groundAccelerationX:agx,groundAccelerationY:agy,groundAccelerationXG:agxG,groundAccelerationYG:agyG,displacement:row.u[monitor.freePosition],velocity:row.v[monitor.freePosition],acceleration:relativeAcceleration,absoluteAcceleration:relativeAcceleration+monitorGround,kineticEnergy:row.kineticEnergy,strainEnergy:row.strainEnergy,totalMechanicalEnergy:row.totalMechanicalEnergy}}),peak=history.reduce((best,r)=>Math.abs(r.displacement)>Math.abs(best.displacement)?r:best,history[0]),fullFinal=Array(sys.nd).fill(0);sys.free.forEach((d,i)=>{fullFinal[d]=integrated.final.u[i]});const pgaGX=groundX?Math.max(...groundX.map(x=>Math.abs(x.accelG))):0,pgaGY=groundY?Math.max(...groundY.map(x=>Math.abs(x.accelG))):0;
  return{type:'dynamic-time-history2d',analysisType:'time-history',solverVersion:'0.25.0-exp',scenario:resolved.scenario,dofs:sys.nd,freeDofs:sys.free.length,massFormulation:sys.massFormulation,gravity:sys.gravity,densityConvention:'material.density interpreted as unit weight [kN/m³]; mass density = density/g',modal:{modes:modal.modes,usedForDamping:true},rayleigh,newmark:{method:'average-acceleration',beta:integrated.beta,gamma:integrated.gamma,timeStep:integrated.dt,duration:integrated.duration,steps:integrated.steps},excitation:excitationType==='base-acceleration'?{type:'base-acceleration',baseAcceleration:true,direction,groundMotionPoints:groundX||groundY,groundMotionPointsX:groundX,groundMotionPointsY:groundY,pgaG:direction==='xy'?vectorPgaG(groundX,groundY):(groundX?pgaGX:pgaGY),pgaGX,pgaGY,preprocessing:{x:groundX?px:null,y:groundY?(direction==='y'?px:py):null}}:{type:'scaled-load-pattern',historyPoints:loadPoints,referenceScenarioId:scenarioId||resolved.scenario?.id,baseAcceleration:false},monitor,history,peakResponse:{...peak,absDisplacement:Math.abs(peak.displacement)},peakByNode:[...peakByNode.values()],displacements:p.nodes.map((n,i)=>({nodeId:n.id,ux:fullFinal[3*i],uy:fullFinal[3*i+1],rz:fullFinal[3*i+2]}))};
}
export const DYNAMICS_VERSION='0.25.0-exp';
'''
s=s[:start]+new_tail
p.write_text(s)

# -----------------------------------------------------------------------------
# Solver routing: pass v0.25 preprocessing, XY component and target spectrum.
# -----------------------------------------------------------------------------
p=Path('web/src/solver/index.js');s=p.read_text().replace('v0.24','v0.25')
old="return solveResponseSpectrum2D(project,{massFormulation:s.dynamicMassFormulation,modes:s.modalModes,dampingRatio:s.dynamicDampingRatio,timeStep:s.dynamicTimeStep,direction:s.dynamicGroundMotionDirection,groundMotionPoints:s.dynamicGroundMotionPoints,combination:s.responseSpectrumCombination,periodMin:s.responseSpectrumPeriodMin,periodMax:s.responseSpectrumPeriodMax,periodCount:s.responseSpectrumPeriodPoints});"
new="return solveResponseSpectrum2D(project,{massFormulation:s.dynamicMassFormulation,modes:s.modalModes,dampingRatio:s.dynamicDampingRatio,timeStep:s.dynamicTimeStep,direction:s.dynamicGroundMotionDirection,groundMotionPoints:s.dynamicGroundMotionPoints,groundMotionPointsY:s.dynamicGroundMotionPointsY,combination:s.responseSpectrumCombination,directionalCombination:s.responseSpectrumDirectionalCombination,periodMin:s.responseSpectrumPeriodMin,periodMax:s.responseSpectrumPeriodMax,periodCount:s.responseSpectrumPeriodPoints,targetSpectrumPoints:s.responseSpectrumTargetPoints,preprocess:{baselineCorrection:s.groundMotionBaselineCorrection,taperRatio:s.groundMotionTaperRatio,highPassHz:s.groundMotionHighPassHz,lowPassHz:s.groundMotionLowPassHz,resampleDt:s.groundMotionResampleDt,scaleFactor:s.groundMotionScaleFactor}});"
s=rep(s,old,new,'index response spectrum')
old="return solveTimeHistory2D(project,scenarioId,{massFormulation:s.dynamicMassFormulation,dampingRatio:s.dynamicDampingRatio,rayleighMode1:s.dynamicRayleighMode1,rayleighMode2:s.dynamicRayleighMode2,timeStep:s.dynamicTimeStep,duration:s.dynamicDuration,monitorNodeId:s.dynamicMonitorNodeId,monitorDof:s.dynamicMonitorDof,historyPoints:s.dynamicHistoryPoints,excitationType:s.dynamicExcitationType,groundMotionDirection:s.dynamicGroundMotionDirection,groundMotionPoints:s.dynamicGroundMotionPoints});"
new="return solveTimeHistory2D(project,scenarioId,{massFormulation:s.dynamicMassFormulation,dampingRatio:s.dynamicDampingRatio,rayleighMode1:s.dynamicRayleighMode1,rayleighMode2:s.dynamicRayleighMode2,timeStep:s.dynamicTimeStep,duration:s.dynamicDuration,monitorNodeId:s.dynamicMonitorNodeId,monitorDof:s.dynamicMonitorDof,historyPoints:s.dynamicHistoryPoints,excitationType:s.dynamicExcitationType,groundMotionDirection:s.dynamicGroundMotionDirection,groundMotionPoints:s.dynamicGroundMotionPoints,groundMotionPointsY:s.dynamicGroundMotionPointsY,preprocess:{baselineCorrection:s.groundMotionBaselineCorrection,taperRatio:s.groundMotionTaperRatio,highPassHz:s.groundMotionHighPassHz,lowPassHz:s.groundMotionLowPassHz,resampleDt:s.groundMotionResampleDt,scaleFactor:s.groundMotionScaleFactor}});"
s=rep(s,old,new,'index time history')
p.write_text(s)

# -----------------------------------------------------------------------------
# React analysis panel: preprocessing controls, XY component, target and library.
# -----------------------------------------------------------------------------
p=Path('app/src/AnalysisPanelV13.tsx');s=p.read_text().replace('dinâmica v0.24','dinâmica v0.25').replace('Dinâmica v0.24','Dinâmica v0.25').replace('v0.24</b>','v0.25</b>').replace('v0.24</h3>','v0.25</h3>').replace('Hist. temporal · v0.24','Hist. temporal · v0.25').replace('Espectro · v0.24','Espectro · v0.25')
old="const parseGroundMotionCsv=(raw:string)=>raw.split(/\\r?\\n/).map(line=>line.trim()).filter(Boolean).map(line=>line.split(/[;,\\t ]+/).map(Number)).filter(x=>x.length>=2&&Number.isFinite(x[0])&&Number.isFinite(x[1])).map(x=>({t:x[0],accelG:x[1]}));"
new="const parseGroundMotionCsv=(raw:string)=>{const rows=raw.split(/\\r?\\n/).map(line=>line.trim()).filter(Boolean).map(line=>line.split(/[;,\\t ]+/).map(Number)).filter(x=>x.length>=2&&Number.isFinite(x[0])&&Number.isFinite(x[1]));return{x:rows.map(x=>({t:x[0],accelG:x[1]})),y:rows.filter(x=>x.length>=3&&Number.isFinite(x[2])).map(x=>({t:x[0],accelG:x[2]}))}};\nconst parseGroundText=(raw:string)=>String(raw).split(/[,;]+/).map(x=>x.trim()).filter(Boolean).map(x=>{const [t,accelG]=x.split(':').map(Number);return{t,accelG}}).filter(x=>Number.isFinite(x.t)&&Number.isFinite(x.accelG)).sort((a,b)=>a.t-b.t);\nconst parseTargetText=(raw:string)=>String(raw).split(/[,;]+/).map(x=>x.trim()).filter(Boolean).map(x=>{const [period,saG]=x.split(':').map(Number);return{period,saG}}).filter(x=>Number.isFinite(x.period)&&x.period>0&&Number.isFinite(x.saG)&&x.saG>0).sort((a,b)=>a.period-b.period);"
s=rep(s,old,new,'panel csv parser')
old="  const [dynamicGroundMotionDirection,setDynamicGroundMotionDirection]=useState(project.settings?.dynamicGroundMotionDirection==='y'?'y':'x');\n  const [dynamicGroundMotionText,setDynamicGroundMotionText]=useState((project.settings?.dynamicGroundMotionPoints||[{t:0,accelG:0},{t:.05,accelG:.15},{t:.10,accelG:0},{t:.15,accelG:-.10},{t:.20,accelG:0}]).map((x:any)=>`${num(x.t)}:${num(x.accelG)}`).join(', '));\n  const [responseSpectrumCombination,setResponseSpectrumCombination]=useState(project.settings?.responseSpectrumCombination==='srss'?'srss':'cqc');"
new="  const [dynamicGroundMotionDirection,setDynamicGroundMotionDirection]=useState(['x','y','xy'].includes(project.settings?.dynamicGroundMotionDirection)?project.settings.dynamicGroundMotionDirection:'x');\n  const [dynamicGroundMotionText,setDynamicGroundMotionText]=useState((project.settings?.dynamicGroundMotionPoints||[{t:0,accelG:0},{t:.05,accelG:.15},{t:.10,accelG:0},{t:.15,accelG:-.10},{t:.20,accelG:0}]).map((x:any)=>`${num(x.t)}:${num(x.accelG)}`).join(', '));\n  const [dynamicGroundMotionTextY,setDynamicGroundMotionTextY]=useState((project.settings?.dynamicGroundMotionPointsY||[{t:0,accelG:0},{t:.05,accelG:.10},{t:.10,accelG:0},{t:.15,accelG:-.06},{t:.20,accelG:0}]).map((x:any)=>`${num(x.t)}:${num(x.accelG)}`).join(', '));\n  const [groundMotionBaselineCorrection,setGroundMotionBaselineCorrection]=useState(project.settings?.groundMotionBaselineCorrection||'linear');\n  const [groundMotionTaperRatio,setGroundMotionTaperRatio]=useState(project.settings?.groundMotionTaperRatio??.02);\n  const [groundMotionHighPassHz,setGroundMotionHighPassHz]=useState(project.settings?.groundMotionHighPassHz??0);\n  const [groundMotionLowPassHz,setGroundMotionLowPassHz]=useState(project.settings?.groundMotionLowPassHz??0);\n  const [groundMotionResampleDt,setGroundMotionResampleDt]=useState(project.settings?.groundMotionResampleDt??0);\n  const [groundMotionScaleFactor,setGroundMotionScaleFactor]=useState(project.settings?.groundMotionScaleFactor??1);\n  const [groundMotionLibrary,setGroundMotionLibrary]=useState<any[]>(()=>clone(project.settings?.dynamicGroundMotionLibrary||[]));\n  const [groundMotionRecordName,setGroundMotionRecordName]=useState('Registro sísmico');\n  const [selectedGroundRecord,setSelectedGroundRecord]=useState('');\n  const [responseSpectrumCombination,setResponseSpectrumCombination]=useState(project.settings?.responseSpectrumCombination==='srss'?'srss':'cqc');\n  const [responseSpectrumDirectionalCombination,setResponseSpectrumDirectionalCombination]=useState(project.settings?.responseSpectrumDirectionalCombination==='100-30'?'100-30':'srss');\n  const [responseSpectrumTargetText,setResponseSpectrumTargetText]=useState((project.settings?.responseSpectrumTargetPoints||[]).map((x:any)=>`${num(x.period)}:${num(x.saG)}`).join(', '));"
s=rep(s,old,new,'panel states')
old="  const importGroundMotion=(file:File)=>{const reader=new FileReader();reader.onload=()=>{const pts=parseGroundMotionCsv(String(reader.result||''));if(pts.length>=2)setDynamicGroundMotionText(pts.map(x=>`${x.t}:${x.accelG}`).join(', '))};reader.readAsText(file)};"
new="  const importGroundMotion=(file:File,axis:'x'|'y'='x')=>{const reader=new FileReader();reader.onload=()=>{const pts=parseGroundMotionCsv(String(reader.result||''));if(axis==='x'&&pts.x.length>=2)setDynamicGroundMotionText(pts.x.map(x=>`${x.t}:${x.accelG}`).join(', '));if(axis==='y'){const src=pts.y.length>=2?pts.y:pts.x;if(src.length>=2)setDynamicGroundMotionTextY(src.map(x=>`${x.t}:${x.accelG}`).join(', '))}else if(pts.y.length>=2){setDynamicGroundMotionTextY(pts.y.map(x=>`${x.t}:${x.accelG}`).join(', '));setDynamicGroundMotionDirection('xy')}};reader.readAsText(file)};\n  const saveGroundRecord=()=>{const x=parseGroundText(dynamicGroundMotionText),y=parseGroundText(dynamicGroundMotionTextY);if(x.length<2)return;const rec={id:uid('GM'),name:groundMotionRecordName.trim()||`Registro ${groundMotionLibrary.length+1}`,x,y};setGroundMotionLibrary(old=>[...old.slice(-11),rec]);setSelectedGroundRecord(rec.id)};\n  const loadGroundRecord=(id:string)=>{setSelectedGroundRecord(id);const rec=groundMotionLibrary.find((r:any)=>r.id===id);if(!rec)return;setDynamicGroundMotionText((rec.x||[]).map((x:any)=>`${num(x.t)}:${num(x.accelG)}`).join(', '));if((rec.y||[]).length>=2){setDynamicGroundMotionTextY(rec.y.map((x:any)=>`${num(x.t)}:${num(x.accelG)}`).join(', '));setDynamicGroundMotionDirection('xy')}};"
s=rep(s,old,new,'panel import library')
old="p.settings.dynamicExcitationType=dynamicExcitationType==='base-acceleration'?'base-acceleration':'load-pattern';p.settings.dynamicGroundMotionDirection=dynamicGroundMotionDirection==='y'?'y':'x';const parsedGround=String(dynamicGroundMotionText).split(/[,;]+/).map(x=>x.trim()).filter(Boolean).map(x=>{const [t,accelG]=x.split(':').map(Number);return{t,accelG}}).filter(x=>Number.isFinite(x.t)&&Number.isFinite(x.accelG)).sort((a,b)=>a.t-b.t);p.settings.dynamicGroundMotionPoints=parsedGround.length>=2?parsedGround:[{t:0,accelG:0},{t:.05,accelG:.15},{t:.10,accelG:0},{t:.15,accelG:-.10},{t:.20,accelG:0}];p.settings.responseSpectrumCombination=responseSpectrumCombination==='srss'?'srss':'cqc';p.settings.responseSpectrumPeriodMin=Math.max(.001,num(responseSpectrumPeriodMin,.02));p.settings.responseSpectrumPeriodMax=Math.max(p.settings.responseSpectrumPeriodMin,num(responseSpectrumPeriodMax,4));p.settings.responseSpectrumPeriodPoints=Math.max(10,Math.min(300,Math.round(num(responseSpectrumPeriodPoints,80))));"
new="p.settings.dynamicExcitationType=dynamicExcitationType==='base-acceleration'?'base-acceleration':'load-pattern';p.settings.dynamicGroundMotionDirection=['x','y','xy'].includes(dynamicGroundMotionDirection)?dynamicGroundMotionDirection:'x';const parsedGround=parseGroundText(dynamicGroundMotionText),parsedGroundY=parseGroundText(dynamicGroundMotionTextY);p.settings.dynamicGroundMotionPoints=parsedGround.length>=2?parsedGround:[{t:0,accelG:0},{t:.05,accelG:.15},{t:.10,accelG:0},{t:.15,accelG:-.10},{t:.20,accelG:0}];p.settings.dynamicGroundMotionPointsY=parsedGroundY.length>=2?parsedGroundY:[{t:0,accelG:0},{t:.05,accelG:.10},{t:.10,accelG:0},{t:.15,accelG:-.06},{t:.20,accelG:0}];p.settings.groundMotionBaselineCorrection=['none','mean','linear'].includes(groundMotionBaselineCorrection)?groundMotionBaselineCorrection:'linear';p.settings.groundMotionTaperRatio=Math.max(0,Math.min(.25,num(groundMotionTaperRatio,.02)));p.settings.groundMotionHighPassHz=Math.max(0,num(groundMotionHighPassHz,0));p.settings.groundMotionLowPassHz=Math.max(0,num(groundMotionLowPassHz,0));p.settings.groundMotionResampleDt=Math.max(0,num(groundMotionResampleDt,0));p.settings.groundMotionScaleFactor=Number.isFinite(Number(groundMotionScaleFactor))?Number(groundMotionScaleFactor):1;p.settings.dynamicGroundMotionLibrary=clone(groundMotionLibrary).slice(-12);p.settings.responseSpectrumCombination=responseSpectrumCombination==='srss'?'srss':'cqc';p.settings.responseSpectrumDirectionalCombination=responseSpectrumDirectionalCombination==='100-30'?'100-30':'srss';p.settings.responseSpectrumPeriodMin=Math.max(.001,num(responseSpectrumPeriodMin,.02));p.settings.responseSpectrumPeriodMax=Math.max(p.settings.responseSpectrumPeriodMin,num(responseSpectrumPeriodMax,4));p.settings.responseSpectrumPeriodPoints=Math.max(10,Math.min(300,Math.round(num(responseSpectrumPeriodPoints,80))));p.settings.responseSpectrumTargetPoints=parseTargetText(responseSpectrumTargetText);"
s=rep(s,old,new,'panel apply')
anchor="{dynamicMode&&<section className=\"react-card\" data-testid=\"dynamic-controls\"><div className=\"section-title\"><h3>Dinâmica linear · v0.25</h3><span className=\"chip\">M + C + K</span></div><div className=\"geometry-grid\"><label>Matriz de massa<select data-testid=\"dynamic-mass-formulation\" value={dynamicMassFormulation} onChange={e=>setDynamicMassFormulation(e.target.value)}><option value=\"consistent\">Consistente</option><option value=\"lumped\">Concentrada</option></select></label><label>Nº de modos<input data-testid=\"modal-mode-count\" type=\"number\" min=\"1\" max=\"20\" value={modalModes} onChange={e=>setModalModes(num(e.target.value,6))}/></label></div><div className=\"panel-note\">`density` é peso específico [kN/m³]; a massa volumétrica é ρm=γ/g. Massas nodais adicionais permanecem no Inspector.</div>"
insert=anchor+"{(mode==='time-history'||mode==='response-spectrum')&&<><h3>Registro sísmico · pré-processamento v0.25</h3><div className=\"geometry-grid\"><label>Correção de linha de base<select data-testid=\"ground-baseline-correction\" value={groundMotionBaselineCorrection} onChange={e=>setGroundMotionBaselineCorrection(e.target.value)}><option value=\"none\">Nenhuma</option><option value=\"mean\">Remover média</option><option value=\"linear\">Detrend linear</option></select></label><label>Taper por extremidade<input data-testid=\"ground-taper-ratio\" type=\"number\" min=\"0\" max=\"0.25\" step=\"0.01\" value={groundMotionTaperRatio} onChange={e=>setGroundMotionTaperRatio(num(e.target.value,.02))}/></label><label>High-pass [Hz]<input data-testid=\"ground-high-pass\" type=\"number\" min=\"0\" step=\"0.05\" value={groundMotionHighPassHz} onChange={e=>setGroundMotionHighPassHz(num(e.target.value,0))}/></label><label>Low-pass [Hz]<input data-testid=\"ground-low-pass\" type=\"number\" min=\"0\" step=\"0.5\" value={groundMotionLowPassHz} onChange={e=>setGroundMotionLowPassHz(num(e.target.value,0))}/></label><label>Reamostrar Δt [s] · 0=off<input data-testid=\"ground-resample-dt\" type=\"number\" min=\"0\" step=\"0.001\" value={groundMotionResampleDt} onChange={e=>setGroundMotionResampleDt(num(e.target.value,0))}/></label><label>Fator de escala<input data-testid=\"ground-scale-factor\" type=\"number\" step=\"0.05\" value={groundMotionScaleFactor} onChange={e=>setGroundMotionScaleFactor(num(e.target.value,1))}/></label><label>Nome do registro<input data-testid=\"ground-record-name\" value={groundMotionRecordName} onChange={e=>setGroundMotionRecordName(e.target.value)}/></label><label>Biblioteca local<select data-testid=\"ground-record-library\" value={selectedGroundRecord} onChange={e=>loadGroundRecord(e.target.value)}><option value=\"\">— selecionar —</option>{groundMotionLibrary.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button data-testid=\"ground-record-save\" type=\"button\" onClick={saveGroundRecord}>Salvar registro no projeto</button></div><div className=\"panel-note\">Filtros high/low-pass usam passe RC de 1ª ordem em ida/volta (fase zero). Para registros irregulares, informe Δt de reamostragem antes do filtro. A biblioteca fica embutida no JSON do projeto, sem upload externo.</div></>}"
s=rep(s,anchor,insert,'panel preprocessing block')
old="<label>Direção da base<select data-testid=\"ground-motion-direction\" value={dynamicGroundMotionDirection} onChange={e=>setDynamicGroundMotionDirection(e.target.value)}><option value=\"x\">X global</option><option value=\"y\">Y global</option></select></label><label>Acelerograma t:a[g]<input data-testid=\"ground-motion-points\" value={dynamicGroundMotionText} onChange={e=>setDynamicGroundMotionText(e.target.value)}/></label><label>CSV tempo, a[g]<input data-testid=\"ground-motion-file\" type=\"file\" accept=\".csv,.txt,text/csv,text/plain\" onChange={e=>{const f=e.target.files?.[0];if(f)importGroundMotion(f);e.currentTarget.value='' }}/></label>"
new="<label>Direção da base<select data-testid=\"ground-motion-direction\" value={dynamicGroundMotionDirection} onChange={e=>setDynamicGroundMotionDirection(e.target.value)}><option value=\"x\">X global</option><option value=\"y\">Y global</option><option value=\"xy\">X + Y simultâneos</option></select></label><label>{dynamicGroundMotionDirection==='y'?'Acelerograma Y':'Acelerograma X'} t:a[g]<input data-testid=\"ground-motion-points\" value={dynamicGroundMotionText} onChange={e=>setDynamicGroundMotionText(e.target.value)}/></label>{dynamicGroundMotionDirection==='xy'&&<label>Acelerograma Y t:a[g]<input data-testid=\"ground-motion-points-y\" value={dynamicGroundMotionTextY} onChange={e=>setDynamicGroundMotionTextY(e.target.value)}/></label>}<label>CSV tempo, X[g], Y[g]<input data-testid=\"ground-motion-file\" type=\"file\" accept=\".csv,.txt,text/csv,text/plain\" onChange={e=>{const f=e.target.files?.[0];if(f)importGroundMotion(f,'x');e.currentTarget.value='' }}/></label>"
s=rep(s,old,new,'panel time xy')
old="<label>Direção<select data-testid=\"spectrum-direction\" value={dynamicGroundMotionDirection} onChange={e=>setDynamicGroundMotionDirection(e.target.value)}><option value=\"x\">X global</option><option value=\"y\">Y global</option></select></label><label>Combinação<select data-testid=\"spectrum-combination\" value={responseSpectrumCombination} onChange={e=>setResponseSpectrumCombination(e.target.value)}><option value=\"cqc\">CQC</option><option value=\"srss\">SRSS</option></select></label>"
new="<label>Direção<select data-testid=\"spectrum-direction\" value={dynamicGroundMotionDirection} onChange={e=>setDynamicGroundMotionDirection(e.target.value)}><option value=\"x\">X global</option><option value=\"y\">Y global</option><option value=\"xy\">X + Y</option></select></label><label>Combinação modal<select data-testid=\"spectrum-combination\" value={responseSpectrumCombination} onChange={e=>setResponseSpectrumCombination(e.target.value)}><option value=\"cqc\">CQC</option><option value=\"srss\">SRSS</option></select></label>{dynamicGroundMotionDirection==='xy'&&<label>Combinação direcional<select data-testid=\"spectrum-directional-combination\" value={responseSpectrumDirectionalCombination} onChange={e=>setResponseSpectrumDirectionalCombination(e.target.value)}><option value=\"srss\">SRSS ortogonal</option><option value=\"100-30\">Envelope 100/30</option></select></label>}"
s=rep(s,old,new,'panel spectrum direction')
old="<label>Acelerograma t:a[g]<input data-testid=\"spectrum-ground-motion-points\" value={dynamicGroundMotionText} onChange={e=>setDynamicGroundMotionText(e.target.value)}/></label><label>CSV tempo, a[g]<input data-testid=\"spectrum-ground-motion-file\" type=\"file\" accept=\".csv,.txt,text/csv,text/plain\" onChange={e=>{const f=e.target.files?.[0];if(f)importGroundMotion(f);e.currentTarget.value='' }}/></label>"
new="<label>{dynamicGroundMotionDirection==='y'?'Acelerograma Y':'Acelerograma X'} t:a[g]<input data-testid=\"spectrum-ground-motion-points\" value={dynamicGroundMotionText} onChange={e=>setDynamicGroundMotionText(e.target.value)}/></label>{dynamicGroundMotionDirection==='xy'&&<label>Acelerograma Y t:a[g]<input data-testid=\"spectrum-ground-motion-points-y\" value={dynamicGroundMotionTextY} onChange={e=>setDynamicGroundMotionTextY(e.target.value)}/></label>}<label>CSV tempo, X[g], Y[g]<input data-testid=\"spectrum-ground-motion-file\" type=\"file\" accept=\".csv,.txt,text/csv,text/plain\" onChange={e=>{const f=e.target.files?.[0];if(f)importGroundMotion(f,'x');e.currentTarget.value='' }}/></label><label>Espectro-alvo T:Sa[g]<input data-testid=\"spectrum-target-points\" value={responseSpectrumTargetText} onChange={e=>setResponseSpectrumTargetText(e.target.value)} placeholder=\"0.1:0.6, 0.5:0.8, 1.0:0.4\"/></label>"
s=rep(s,old,new,'panel spectrum inputs')
s=s.replace('A v0.24 calcula <b>Sd</b>','A v0.25 calcula <b>Sd</b>').replace('Dinâmica v0.24: linear-elástica','Dinâmica v0.25: linear-elástica')
p.write_text(s)

# -----------------------------------------------------------------------------
# Postprocess v0.25: preprocessing diagnostics, XY plots and target comparison.
# -----------------------------------------------------------------------------
p=Path('app/src/DynamicsPostprocessPanel.tsx');s=p.read_text().replace('v0.24','v0.25')
old="const modal=result?.analysisType==='modal'?result:null,time=result?.analysisType==='time-history'?result:null,spectrum=result?.analysisType==='response-spectrum'?result:null,modes=(result?.modal?.modes||result?.modes||[]) as any[],specRows=(spectrum?.spectrum?.values||[]) as any[];"
new="const modal=result?.analysisType==='modal'?result:null,time=result?.analysisType==='time-history'?result:null,spectrum=result?.analysisType==='response-spectrum'?result:null,modes=(result?.modal?.modes||result?.modes||[]) as any[],specRows=(spectrum?.spectrum?.values||[]) as any[],isXY=String(time?.excitation?.direction||spectrum?.direction)==='xy',prep=time?.excitation?.preprocessing||spectrum?.preprocessing;"
s=rep(s,old,new,'post variables')
old="{time.excitation?.baseAcceleration&&<PolyChart rows={time.history||[]} xKey=\"t\" yKey=\"groundAccelerationG\" title=\"Acelerograma aplicado à base\" xUnit=\"s\" yUnit=\"g\" testId=\"ground-motion-chart\"/>}"
new="{time.excitation?.baseAcceleration&&(isXY?<><PolyChart rows={time.history||[]} xKey=\"t\" yKey=\"groundAccelerationXG\" title=\"Acelerograma aplicado · X\" xUnit=\"s\" yUnit=\"g\" testId=\"ground-motion-chart-x\"/><PolyChart rows={time.history||[]} xKey=\"t\" yKey=\"groundAccelerationYG\" title=\"Acelerograma aplicado · Y\" xUnit=\"s\" yUnit=\"g\" testId=\"ground-motion-chart-y\"/></>:<PolyChart rows={time.history||[]} xKey=\"t\" yKey=\"groundAccelerationG\" title=\"Acelerograma aplicado à base\" xUnit=\"s\" yUnit=\"g\" testId=\"ground-motion-chart\"/>)}"
s=rep(s,old,new,'post time charts')
old="<div className=\"panel-note\">Excitação: <b>{time.excitation?.baseAcceleration?`aceleração de base ${String(time.excitation?.direction||'x').toUpperCase()} · PGA ${fmt(time.excitation?.pgaG,4)} g`:'vetor de cargas do cenário × história escalar'}</b>.</div></section>"
new="<div className=\"panel-note\">Excitação: <b>{time.excitation?.baseAcceleration?`aceleração de base ${String(time.excitation?.direction||'x').toUpperCase()} · PGA ${fmt(time.excitation?.pgaG,4)} g`:'vetor de cargas do cenário × história escalar'}</b>.</div>{time.excitation?.baseAcceleration&&<section className=\"react-card\" data-testid=\"ground-motion-processing-summary\"><h3>Pré-processamento do registro</h3><div className=\"metrics\"><div><span>Baseline</span><strong>{prep?.x?.options?.baselineCorrection||prep?.y?.options?.baselineCorrection||'none'}</strong></div><div><span>Escala</span><strong>{fmt(prep?.x?.options?.scaleFactor??prep?.y?.options?.scaleFactor??1,3)}×</strong></div><div><span>PGA X</span><strong>{fmt(time.excitation?.pgaGX,4)} g</strong></div><div><span>PGA Y</span><strong>{fmt(time.excitation?.pgaGY,4)} g</strong></div><div><span>Drift final X</span><strong>{fmt(prep?.x?.processedStats?.finalDisplacement,6)} m</strong></div><div><span>Drift final Y</span><strong>{fmt(prep?.y?.processedStats?.finalDisplacement,6)} m</strong></div></div></section>}</section>"
s=rep(s,old,new,'post processing summary')
old="{spectrum&&<><PolyChart rows={specRows} xKey=\"period\" yKey=\"saG\" title={`Pseudo-espectro Sa · ζ=${fmt(100*spectrum.dampingRatio,2)}%`} xUnit=\"s\" yUnit=\"g\" testId=\"response-spectrum-chart\"/>"
new="{spectrum&&<>{isXY?<><PolyChart rows={spectrum.spectra?.x?.values||[]} xKey=\"period\" yKey=\"saG\" title={`Pseudo-espectro Sa · X · ζ=${fmt(100*spectrum.dampingRatio,2)}%`} xUnit=\"s\" yUnit=\"g\" testId=\"response-spectrum-chart-x\"/><PolyChart rows={spectrum.spectra?.y?.values||[]} xKey=\"period\" yKey=\"saG\" title={`Pseudo-espectro Sa · Y · ζ=${fmt(100*spectrum.dampingRatio,2)}%`} xUnit=\"s\" yUnit=\"g\" testId=\"response-spectrum-chart-y\"/><PolyChart rows={specRows} xKey=\"period\" yKey=\"saG\" title=\"Média geométrica Sa(X,Y)\" xUnit=\"s\" yUnit=\"g\" testId=\"response-spectrum-chart\"/></>:<PolyChart rows={specRows} xKey=\"period\" yKey=\"saG\" title={`Pseudo-espectro Sa · ζ=${fmt(100*spectrum.dampingRatio,2)}%`} xUnit=\"s\" yUnit=\"g\" testId=\"response-spectrum-chart\"/>}"
s=rep(s,old,new,'post spectrum charts')
old="<div className=\"section-title\"><h3>Combinação modal · {String(spectrum.combination).toUpperCase()}</h3><span className=\"chip\">{String(spectrum.direction).toUpperCase()} global</span></div>"
new="<div className=\"section-title\"><h3>Combinação modal · {String(spectrum.combination).toUpperCase()}</h3><span className=\"chip\">{String(spectrum.direction).toUpperCase()} global{isXY?` · ${String(spectrum.directionalCombination||'srss').toUpperCase()}`:''}</span></div>"
s=rep(s,old,new,'post directional label')
old="{(spectrum.modalContributions||[]).map((m:any)=><tr key={m.mode}><td>{m.mode}</td><td>{fmt(m.period,5)}</td><td>{fmt(m.participationFactor,5)}</td><td>{fmt(1000*m.sd,4)}</td><td>{fmt(m.sv,5)}</td><td>{fmt(m.saG,5)}</td><td>{fmt(1000*m.maxModalTranslational,4)}</td></tr>)}"
new="{((isXY?spectrum.modalContributions?.x:spectrum.modalContributions)||[]).map((m:any)=><tr key={m.mode}><td>{m.mode}</td><td>{fmt(m.period,5)}</td><td>{fmt(m.participationFactor,5)}</td><td>{fmt(1000*m.sd,4)}</td><td>{fmt(m.sv,5)}</td><td>{fmt(m.saG,5)}</td><td>{fmt(1000*m.maxModalTranslational,4)}</td></tr>)}"
s=rep(s,old,new,'post modal table')
old="<div className=\"panel-note\">Sa e Sv são pseudo-ordenadas derivadas de Sd. CQC usa correlação modal para amortecimento uniforme; SRSS permanece disponível para modos bem separados.</div></section>"
new="<div className=\"panel-note\">Sa e Sv são pseudo-ordenadas derivadas de Sd. CQC usa correlação modal para amortecimento uniforme; SRSS permanece disponível para modos bem separados. Em X+Y, a combinação direcional é aplicada após a combinação modal de cada componente.</div>{spectrum.targetComparison&&<section className=\"react-card\" data-testid=\"spectrum-target-summary\"><h3>Comparação com espectro-alvo</h3><div className=\"metrics\"><div><span>Razão geométrica</span><strong>{fmt(spectrum.targetComparison.geometricMeanRatio,3)}</strong></div><div><span>Razão mín.</span><strong>{fmt(spectrum.targetComparison.minRatio,3)}</strong></div><div><span>Razão máx.</span><strong>{fmt(spectrum.targetComparison.maxRatio,3)}</strong></div><div><span>Escala sugerida</span><strong>{fmt(spectrum.targetComparison.scaleFactorToTarget,3)}×</strong></div></div><PolyChart rows={spectrum.targetComparison.rows||[]} xKey=\"period\" yKey=\"ratio\" title=\"Sa registro / Sa alvo\" xUnit=\"s\" yUnit=\"—\" testId=\"spectrum-target-ratio-chart\"/></section>}</section>"
s=rep(s,old,new,'post target summary')
s=s.replace('Ainda não há múltiplos apoios, componentes simultâneas X+Y, espectro normativo de projeto, combinação direcional normativa, dinâmica geometricamente/materialmente não linear, contato ou amortecimento histerético.','Ainda não há movimento diferencial de múltiplos apoios, espectro normativo de projeto incorporado, combinação normativa automática entre sismo e ações gravitacionais, dinâmica geometricamente/materialmente não linear, contato ou amortecimento histerético. A opção 100/30 é um envelope direcional genérico e não constitui verificação normativa automática.')
p.write_text(s)

# -----------------------------------------------------------------------------
# Results panel labels for v0.25 XY metadata.
# -----------------------------------------------------------------------------
p=Path('app/src/App.tsx');s=p.read_text()
s=s.replace('Pseudo-espectros Sa/Sv/Sd derivados do acelerograma e resposta modal combinada.','Pseudo-espectros Sa/Sv/Sd derivados do acelerograma, com pré-processamento v0.25 e resposta modal/direcional combinada.')
p.write_text(s)

# -----------------------------------------------------------------------------
# New smoke benchmark and browser workflow.
# -----------------------------------------------------------------------------
Path('tests/ground-motion-v025-smoke.mjs').write_text(r'''import assert from 'node:assert/strict';
import { preprocessGroundMotion, compareSpectrumToTarget, responseSpectrumFromGroundMotion, solveTimeHistory2D, solveResponseSpectrum2D, combineDirectionalPeaks } from '../web/src/solver/dynamics2d.js';

const biased=Array.from({length:101},(_,i)=>{const t=i*.01;return{t,accelG:.03+.02*t+.12*Math.sin(2*Math.PI*2*t)}});
const prep=preprocessGroundMotion(biased,{baselineCorrection:'linear',taperRatio:.05,resampleDt:.005,highPassHz:.2,lowPassHz:20,scaleFactor:1.5});
assert.equal(prep.points.length,201);assert(Math.abs(prep.processedStats.meanAccelG)<2e-3);assert(Math.abs(prep.points[0].accelG)<1e-12);assert(prep.processedStats.pgaG>0);assert(prep.filter.nyquistHz>20);
for(let i=2;i<prep.points.length;i++)assert(Math.abs((prep.points[i].t-prep.points[i-1].t)-(prep.points[1].t-prep.points[0].t))<1e-10,'resampling must be uniform');

const gmX=[{t:0,accelG:0},{t:.04,accelG:.20},{t:.08,accelG:0},{t:.12,accelG:-.10},{t:.20,accelG:0}],gmY=[{t:0,accelG:0},{t:.04,accelG:.12},{t:.08,accelG:0},{t:.12,accelG:-.06},{t:.20,accelG:0}];
const project={nodes:[{id:'N1',x:0,y:0},{id:'N2',x:2,y:0}],elements:[{id:'T1',type:'truss2d',n1:'N1',n2:'N2',materialId:'S',sectionId:'TR',A:.01,I:0}],materials:[{id:'S',type:'steel',E:200e6,density:78.5,alpha:12e-6,fy:355}],sections:[{id:'TR',family:'truss',A:.01,I:0}],supports:[{nodeId:'N1',ux:true,uy:true,rz:true},{nodeId:'N2',ux:false,uy:true,rz:false}],loads:[],elementLoads:[],nodeSprings:[],nodalMasses:[],settlements:[],loadCases:[{id:'LC1',name:'D',type:'user'}],loadCombinations:[],settings:{activeLoadCaseId:'LC1',analysisScenarioId:'LC1'}};
const th=solveTimeHistory2D(project,'LC1',{massFormulation:'consistent',dampingRatio:.02,rayleighMode1:1,rayleighMode2:1,timeStep:.001,duration:.2,monitorNodeId:'N2',monitorDof:'ux',excitationType:'base-acceleration',groundMotionDirection:'xy',groundMotionPoints:gmX,groundMotionPointsY:gmY,preprocess:{baselineCorrection:'none'}});
assert.equal(th.solverVersion,'0.25.0-exp');assert.equal(th.excitation.direction,'xy');assert(Math.abs(th.excitation.pgaGX-.2)<1e-12);assert(Math.abs(th.excitation.pgaGY-.12)<1e-12);assert(th.excitation.pgaG>=.2);assert(th.history.some(r=>Math.abs(r.groundAccelerationXG)>.19));

const spec=responseSpectrumFromGroundMotion(gmX,{dampingRatio:.05,timeStep:.001,periodMin:.01,periodMax:.5,periodCount:30}),target=spec.values.map((p,i)=>i%5===0?{period:p.period,saG:p.saG*1.25}:null).filter(Boolean),cmp=compareSpectrumToTarget(spec,target);assert(cmp&&cmp.rows.length>0);assert(cmp.geometricMeanRatio<1);assert(cmp.scaleFactorToTarget>1);
assert.deepEqual(combineDirectionalPeaks([3,4],[4,3],'srss').map(x=>Math.round(x)),[5,5]);assert.deepEqual(combineDirectionalPeaks([10],[5],'100-30'),[11.5]);
const rs=solveResponseSpectrum2D(project,{massFormulation:'consistent',modes:3,dampingRatio:.05,timeStep:.001,direction:'xy',groundMotionPoints:gmX,groundMotionPointsY:gmY,combination:'cqc',directionalCombination:'100-30',periodMin:.01,periodMax:.5,periodCount:30,targetSpectrumPoints:target,preprocess:{baselineCorrection:'none'}});assert.equal(rs.solverVersion,'0.25.0-exp');assert.equal(rs.direction,'xy');assert.equal(rs.directionalCombination,'100-30');assert(rs.spectra.x.values.length===30&&rs.spectra.y.values.length===30);assert(rs.targetComparison);assert(rs.combined.peakTranslationalDisplacement>0);
console.log('v0.25 ground-motion preprocessing / XY spectrum smoke: OK',{samples:prep.points.length,pgaXY:th.excitation.pgaG,scaleToTarget:cmp.scaleFactorToTarget,peak:rs.combined.peakTranslationalDisplacement});
''')

Path('tests/e2e/ground-motion-v025.spec.ts').write_text(r'''import {test,expect} from '@playwright/test';
import {installProject,openCommand} from './helpers';

test('v0.25 XY seismic preprocessing and target spectrum workflow',async({page})=>{await installProject(page);await openCommand(page,'Tipo de análise');await page.getByTestId('analysis-time-history').click();await page.getByTestId('dynamic-excitation-type').selectOption('base-acceleration');await page.getByTestId('ground-motion-direction').selectOption('xy');await page.getByTestId('ground-baseline-correction').selectOption('linear');await page.getByTestId('ground-taper-ratio').fill('0.02');await page.getByTestId('ground-motion-points').fill('0:0, 0.04:0.20, 0.08:0, 0.12:-0.10, 0.20:0');await page.getByTestId('ground-motion-points-y').fill('0:0, 0.04:0.12, 0.08:0, 0.12:-0.06, 0.20:0');await page.getByTestId('dynamic-time-step').fill('0.001');await page.getByTestId('dynamic-duration').fill('0.20');await page.getByTestId('dynamic-monitor-node').selectOption('N2');await page.getByTestId('dynamic-monitor-dof').selectOption('ux');await page.getByTestId('analysis-apply').click();await page.getByTestId('analyze-button').click();await expect(page.getByTestId('dynamic-results-time')).toContainText('N2/UX');await openCommand(page,'Diagramas/envelopes');await expect(page.getByTestId('ground-motion-chart-x')).toBeVisible();await expect(page.getByTestId('ground-motion-chart-y')).toBeVisible();await expect(page.getByTestId('ground-motion-processing-summary')).toContainText('linear');await page.getByTestId('panel-dynamics-postprocess').locator('button[aria-label="Fechar"]').click();await openCommand(page,'Tipo de análise');await page.getByTestId('analysis-response-spectrum').click();await page.getByTestId('spectrum-direction').selectOption('xy');await page.getByTestId('spectrum-directional-combination').selectOption('100-30');await page.getByTestId('spectrum-ground-motion-points').fill('0:0, 0.04:0.20, 0.08:0, 0.12:-0.10, 0.20:0');await page.getByTestId('spectrum-ground-motion-points-y').fill('0:0, 0.04:0.12, 0.08:0, 0.12:-0.06, 0.20:0');await page.getByTestId('spectrum-target-points').fill('0.01:0.05, 0.10:0.25, 0.50:0.08');await page.getByTestId('spectrum-time-step').fill('0.001');await page.getByTestId('analysis-apply').click();await page.getByTestId('analyze-button').click();await expect(page.getByTestId('dynamic-results-spectrum')).toContainText('XY');await openCommand(page,'Diagramas/envelopes');await expect(page.getByTestId('response-spectrum-chart-x')).toBeVisible();await expect(page.getByTestId('response-spectrum-chart-y')).toBeVisible();await expect(page.getByTestId('spectrum-target-summary')).toContainText('Escala sugerida');await expect(page.locator('[role="alert"]')).toHaveCount(0)});
''')

# helpers may not exist in older tree: rewrite E2E to standalone if needed
helper=Path('tests/e2e/helpers.ts')
if not helper.exists():
    q=Path('tests/e2e/ground-motion-v025.spec.ts')
    q.write_text(q.read_text().replace("import {installProject,openCommand} from './helpers';", "const installProject=async(page:any)=>{await page.goto('/');await page.evaluate(()=>localStorage.clear());await page.reload();};\nconst openCommand=async(page:any,label:string)=>{const b=page.getByRole('button',{name:label}).first();await b.click();};"))

# update old v0.24 expectations to v0.25 while preserving benchmark semantics
for name in ['tests/seismic-spectrum-smoke.mjs','tests/dynamics-smoke.mjs','tests/e2e/dynamics.spec.ts','tests/e2e/seismic-spectrum.spec.ts']:
    p=Path(name);t=p.read_text().replace("'0.24.0-exp'","'0.25.0-exp'").replace('v0.24','v0.25');p.write_text(t)

p=Path('package.json');s=p.read_text();s=rep(s,'node tests/seismic-spectrum-smoke.mjs\"','node tests/seismic-spectrum-smoke.mjs && node tests/ground-motion-v025-smoke.mjs\"','package test');p.write_text(s)

# README + documentation
p=Path('README.md');s=p.read_text();marker='## Estado atual';note='''## AstraStruct v0.25 — tratamento de registros sísmicos\n\nA v0.25 acrescenta pré-processamento de acelerogramas (remoção de média/detrend linear, taper, filtros high/low-pass RC zero-phase, reamostragem e escala), componentes simultâneas X+Y, biblioteca de registros persistida no JSON do projeto, combinação direcional SRSS ou envelope 100/30 e comparação do espectro do registro com um espectro-alvo fornecido pelo usuário. O núcleo continua linear-elástico e não representa movimento diferencial de múltiplos apoios.\n\n''';s=note+s if marker not in s else s.replace(marker,note+marker);p.write_text(s)
Path('docs/ground-motion-v025.md').write_text('''# AstraStruct v0.25 — Ground-motion processing and bidirectional seismic input\n\n## Scope\nThe v0.25 seismic path extends v0.24 without changing the linear structural mass/stiffness formulation. Uniform support acceleration may act in X, Y or X+Y simultaneously.\n\n## Pre-processing\nFor each component the pipeline is: sanitize time axis → optional mean or least-squares linear baseline removal → cosine taper → optional uniform resampling → optional first-order RC high-pass/low-pass applied forward and backward (zero phase) → scale factor. Raw and processed PGA, mean acceleration, sampling metrics and final integrated velocity/displacement are reported. The RC implementation is intentionally transparent and is not a substitute for a validated signal-processing package in regulatory work.\n\n## Bidirectional base motion\nThe relative-coordinate equation is\n\n`M u¨ + C u˙ + K u = -M (r_x a_gx(t) + r_y a_gy(t))`.\n\nThis is uniform base motion. Differential support excitation and wave-passage effects remain outside scope.\n\n## Response spectra\nEach component generates Sd, pseudo-Sv and pseudo-Sa by Newmark average acceleration. Modal responses are combined first (SRSS or CQC), then orthogonal component peaks are combined by either SRSS or the generic envelope `max(Rx + 0.3 Ry, 0.3 Rx + Ry)`. The latter is exposed as `100-30` but is not automatic code compliance.\n\nFor X+Y record characterization, the displayed record spectrum is the geometric mean of the X and Y pseudo-spectral ordinates.\n\n## Target comparison\nA user-supplied target curve `(T, Sa[g])` is interpolated over the common period range. AstraStruct reports min/max ratio, geometric-mean ratio, RMS log error and a geometric scale factor that centers the record spectrum on the target. It does not automatically enforce any national code acceptance band.\n\n## Record library\nUp to 12 record pairs can be stored in project settings and therefore travel with exported/imported AstraStruct JSON. No external upload is required.\n\n## Validation\nThe permanent v0.25 smoke test checks detrending/resampling/filter limits, X+Y base-motion metadata, target-spectrum metrics, SRSS/100-30 directional combination and bidirectional response-spectrum solution. Browser E2E covers X+Y time history and target-spectrum workflow.\n\n## Limitations\nLinear elastic dynamics only; rigid frame-element ends in the dynamic kernel; no nonlinear time-history, soil-structure interaction, multiple-support differential motion, automatic record matching, code-specific design spectra, rotational ground motion or vertical/horizontal code combination rules.\n''')
