import{foundationGeotechnicalModelFromProject}from'../foundation/geotechnical.js';
import{foundationSSIResults}from'../foundation/ssi.js';
import{nodePoint,projectPoint3D}from'./spatialView3d.js';

export const GEOTECHNICAL_VIEW3D_VERSION='0.53.5-exp';
export const GEOTECHNICAL_VIEW3D_CONTRACT='foundation-geotechnical-overlay3d/v1';
const PALETTE=['#9c7a55','#c29a64','#9b8e73','#7f937c','#75899b','#8e7b91','#8f8267'];
const finite=v=>v!==''&&v!==null&&v!==undefined&&Number.isFinite(Number(v))?Number(v):null;
const reviewId=(x,i)=>String(x?.id||x?.nodeId||`F${i+1}`);
const colorForLayer=(layer,index)=>/^#[0-9a-f]{6}$/i.test(String(layer?.color||''))?layer.color:PALETTE[index%PALETTE.length];
const clamp01=v=>Math.max(0,Math.min(1,v));
function resultColor(value,max,kind){const t=max>1e-12?clamp01(Math.abs(value)/max):0;return kind==='pressure'?`rgb(${Math.round(78+154*t)},${Math.round(139-55*t)},${Math.round(182-81*t)})`:`rgb(${Math.round(63+158*t)},${Math.round(145-55*t)},${Math.round(118+18*t)})`;}
function footprint(review,node,camera,size){const B=finite(review?.geometry?.B),L=finite(review?.geometry?.L);if(!(B>0&&L>0))return null;const x=finite(review?.x)??Number(node?.x)||0,y=finite(review?.y)??Number(node?.y)||0,z=finite(review?.z)??Number(node?.z)||0,pts=[[x-B/2,y-L/2,z],[x+B/2,y-L/2,z],[x+B/2,y+L/2,z],[x-B/2,y+L/2,z]].map(p=>projectPoint3D(p,camera,size));return pts.every(p=>p.visible)?pts:null;}

export function foundationGeotechnicalOverlayScene(project={},result=null,camera,size,charLength=1){
  const model=foundationGeotechnicalModelFromProject(project),profiles=model.profiles.map((p,pi)=>{if(p.x==null||p.y==null||p.groundZ==null)return{...p,visible:false,segments:[]};const anchor=projectPoint3D([p.x,p.y,p.groundZ],camera,size),segments=p.layers.flatMap((layer,li)=>{if(layer.topDepthM==null||layer.bottomDepthM==null||!(layer.bottomDepthM>layer.topDepthM))return[];const a=projectPoint3D([p.x,p.y,p.groundZ-layer.topDepthM],camera,size),b=projectPoint3D([p.x,p.y,p.groundZ-layer.bottomDepthM],camera,size);return a.visible&&b.visible?[{layerId:layer.id,label:layer.label,soilClass:layer.soilClass,source:layer.source||p.source,color:colorForLayer(layer,li),topDepthM:layer.topDepthM,bottomDepthM:layer.bottomDepthM,a,b,state:layer.state}]:[]});return{...p,anchor,visible:anchor.visible,segments,maxDepthM:p.maxDepthM,color:PALETTE[pi%PALETTE.length]};});
  const post=foundationSSIResults(project,result),postMap=new Map(post.items.map(x=>[String(x.foundationId),x])),reviews=Array.isArray(project?.foundationReview?.items)?project.foundationReview.items:[],reviewMap=new Map(reviews.map((x,i)=>[reviewId(x,i),x])),nodes=project.nodes||[];
  const rawSamples=model.links.filter(x=>x.state==='READY').flatMap(link=>{const r=postMap.get(String(link.foundationId)),review=reviewMap.get(String(link.foundationId));if(!r||!review)return[];const node=nodes.find(n=>String(n.id)===String(review.nodeId));if(!node)return[];const anchor=projectPoint3D(nodePoint(node),camera,size);if(!anchor.visible)return[];return[{foundationId:link.foundationId,profileId:link.profileId,label:review.label||link.foundationId,anchor,footprint:footprint(review,node,camera,size),state:r.state,settlementMm:r.displacement&&post.governance.resultNature==='physical'?1000*(Number(r.displacement.uz)||0):null,pressureKPa:r.averageContactPressureKPa!=null&&post.governance.resultNature==='physical'?Number(r.averageContactPressureKPa):null,resultNature:post.governance.resultNature}];});
  const maxSettlement=Math.max(0,...rawSamples.map(x=>Math.abs(Number(x.settlementMm)||0))),maxPressure=Math.max(0,...rawSamples.map(x=>Math.abs(Number(x.pressureKPa)||0))),samples=rawSamples.map(x=>({...x,settlementColor:x.settlementMm==null?null:resultColor(x.settlementMm,maxSettlement,'settlement'),pressureColor:x.pressureKPa==null?null:resultColor(x.pressureKPa,maxPressure,'pressure')}));
  return{contract:GEOTECHNICAL_VIEW3D_CONTRACT,version:GEOTECHNICAL_VIEW3D_VERSION,profiles,samples,summary:{profiles:profiles.length,readyProfiles:model.summary.readyProfiles,pendingProfiles:model.summary.pendingProfiles,invalidProfiles:model.summary.invalidProfiles,validLinks:model.summary.validLinks,settlementSamples:samples.filter(x=>x.settlementMm!=null).length,pressureSamples:samples.filter(x=>x.pressureKPa!=null).length},ranges:{maxAbsSettlementMm:maxSettlement,maxAbsPressureKPa:maxPressure},governance:{lateralLayerExtrapolation:false,resultInterpolation:'none',profileCoordinates:'explicit-only',ssiStiffnessInference:false,resultNature:post.governance.resultNature},legend:{profiles:'Perfis pontuais explicitamente cadastrados; sem extrapolação lateral de camadas.',settlement:'Recalque vertical discreto nas fundações vinculadas; sem interpolação.',pressure:'Pressão média q̄ discreta nas fundações vinculadas; sem interpolação.'}};
}
