const EPS=1e-12;
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const DEFAULT_HOLE_DAMAGE={gap:.001,bearingStiffness:250000,yieldForce:70,hardeningRatio:.02,damageLength:.004,maxDamage:.70,stiffnessLossRatio:.65};
function normalize(input={}){const c={...DEFAULT_HOLE_DAMAGE,...input};return{...c,gap:Math.max(0,finite(c.gap,.001)),bearingStiffness:Math.max(EPS,finite(c.bearingStiffness,250000)),yieldForce:Math.max(EPS,finite(c.yieldForce,70)),hardeningRatio:Math.max(0,finite(c.hardeningRatio,.02)),damageLength:Math.max(1e-6,finite(c.damageLength,.004)),maxDamage:clamp(finite(c.maxDamage,.7),0,.95),stiffnessLossRatio:clamp(finite(c.stiffnessLossRatio,.65),0,.99)}}
function initialState(){return{plasticPositive:0,plasticNegative:0,cumulativePlastic:0,damage:0,dissipatedEnergy:0}}
function stepResponse(u,state,c){const side=u>=0?'positive':'negative',sgn=u>=0?1:-1,pKey=side==='positive'?'plasticPositive':'plasticNegative',penetration=Math.max(0,Math.abs(u)-c.gap),k=c.bearingStiffness*(1-c.stiffnessLossRatio*state.damage),p=state[pKey];if(!(penetration>p+EPS))return{force:0,state:{...state},side,penetration,elasticPenetration:0,effectiveStiffness:k,status:penetration>0?'unloaded-gap':'gap',plasticIncrement:0};const elastic=penetration-p,trial=k*elastic,hard=k*c.hardeningRatio,yieldNow=c.yieldForce+hard*p;let force=trial,dp=0,status='bearing-elastic';if(trial>yieldNow){dp=(trial-yieldNow)/(k+hard+EPS);force=trial-k*dp;status='bearing-plastic'}const ns={...state};if(dp>0){ns[pKey]+=dp;ns.cumulativePlastic+=dp;ns.damage=Math.min(c.maxDamage,1-Math.exp(-ns.cumulativePlastic/c.damageLength));ns.dissipatedEnergy+=Math.max(0,force*dp)}return{force:sgn*force,state:ns,side,penetration,elasticPenetration:Math.max(0,penetration-ns[pKey]),effectiveStiffness:k,status,plasticIncrement:dp}}
export function solveHoleBearingDamage({history=[],config={}}={}){const c=normalize(config),inputHistory=Array.isArray(history)?history.map(v=>finite(v)):[];if(inputHistory.length<2)throw new Error('Dano de furo: informe histórico com ao menos dois deslocamentos relativos.');let state=initialState();const points=[];for(let i=0;i<inputHistory.length;i++){const r=stepResponse(inputHistory[i],state,c);state=r.state;points.push({step:i,displacement:inputHistory[i],displacementMm:inputHistory[i]*1000,force:r.force,side:r.side,penetration:r.penetration,penetrationMm:r.penetration*1000,status:r.status,plasticIncrement:r.plasticIncrement||0,plasticPositive:state.plasticPositive,plasticNegative:state.plasticNegative,permanentOvalization:state.plasticPositive+state.plasticNegative,permanentOvalizationMm:(state.plasticPositive+state.plasticNegative)*1000,damage:state.damage,effectiveStiffness:r.effectiveStiffness,dissipatedEnergy:state.dissipatedEnergy})}return{type:'hole-bearing-damage-1d',solverVersion:'0.31.0',inputHistory,path:points,finalState:state,permanentOvalization:state.plasticPositive+state.plasticNegative,permanentOvalizationMm:(state.plasticPositive+state.plasticNegative)*1000,damage:state.damage,dissipatedEnergy:state.dissipatedEnergy,events:{firstPlastic:points.find(p=>p.status==='bearing-plastic')||null,maxDamage:points.reduce((a,b)=>b.damage>a.damage?b:a,points[0])||null},assumptions:['contato reduzido a um eixo de carregamento por direção','folga bilateral simétrica inicial','plasticidade de bearing bilinear com memória separada por lado do furo','ovalização permanente medida pela soma das indentacões plásticas opostas','dano escalar reduz a rigidez de bearing em recarregamentos','sem propagação explícita de trinca, rasgamento de borda ou malha 2D evolutiva']}}
export function makeSymmetricCyclicHistory({amplitudes=[.0005,.0015,.003,.005],cycles=1}={}){const out=[0];for(const a0 of amplitudes){const a=Math.abs(finite(a0));for(let c=0;c<Math.max(1,Math.round(finite(cycles,1)));c++)out.push(a,0,-a,0)}return out}
