from pathlib import Path


def rep(path, old, new):
    p=Path(path); t=p.read_text()
    if old not in t:
        raise SystemExit(f'anchor not found in {path}: {old[:180]!r}')
    p.write_text(t.replace(old,new,1))

# -----------------------------------------------------------------------------
# Analysis controls
# -----------------------------------------------------------------------------
path='app/src/AnalysisPanelV13.tsx'
rep(path,
"  const [arcConstraintTolerance,setArcConstraintTolerance]=useState(project.settings?.arcLengthConstraintTolerance??1e-6);",
"  const [arcConstraintTolerance,setArcConstraintTolerance]=useState(project.settings?.arcLengthConstraintTolerance??1e-6);\n  const [stabilityTracking,setStabilityTracking]=useState(project.settings?.stabilityTracking!==false);\n  const [stabilityEigenTolerance,setStabilityEigenTolerance]=useState(project.settings?.stabilityEigenTolerance??0.05);\n  const [stabilityAsymmetryTolerance,setStabilityAsymmetryTolerance]=useState(project.settings?.stabilityAsymmetryTolerance??1e-6);\n  const [stabilityMaxDofs,setStabilityMaxDofs]=useState(project.settings?.stabilityMaxDofs??120);\n  const [branchSwitchEnabled,setBranchSwitchEnabled]=useState(!!project.settings?.branchSwitchEnabled);\n  const [branchSwitchSign,setBranchSwitchSign]=useState(project.settings?.branchSwitchSign??1);\n  const [branchSwitchAmplitude,setBranchSwitchAmplitude]=useState(project.settings?.branchSwitchAmplitude??0.08);")
rep(path,
"    p.settings.arcLengthMonitorNodeId=arcMonitorNodeId||null;p.settings.arcLengthMonitorDof=['ux','uy','rz'].includes(arcMonitorDof)?arcMonitorDof:'uy';p.settings.arcLengthInitialLoadIncrement=Math.max(1e-5,Math.abs(num(arcInitialLoadIncrement,.05)));p.settings.arcLengthInitialSign=num(arcInitialSign,1)<0?-1:1;p.settings.arcLengthTargetIterations=Math.max(2,Math.min(20,Math.round(num(arcTargetIterations,6))));p.settings.arcLengthMaxCutbacks=Math.max(0,Math.min(16,Math.round(num(arcMaxCutbacks,8))));p.settings.arcLengthConstraintTolerance=Math.max(1e-10,num(arcConstraintTolerance,1e-6));",
"    p.settings.arcLengthMonitorNodeId=arcMonitorNodeId||null;p.settings.arcLengthMonitorDof=['ux','uy','rz'].includes(arcMonitorDof)?arcMonitorDof:'uy';p.settings.arcLengthInitialLoadIncrement=Math.max(1e-5,Math.abs(num(arcInitialLoadIncrement,.05)));p.settings.arcLengthInitialSign=num(arcInitialSign,1)<0?-1:1;p.settings.arcLengthTargetIterations=Math.max(2,Math.min(20,Math.round(num(arcTargetIterations,6))));p.settings.arcLengthMaxCutbacks=Math.max(0,Math.min(16,Math.round(num(arcMaxCutbacks,8))));p.settings.arcLengthConstraintTolerance=Math.max(1e-10,num(arcConstraintTolerance,1e-6));\n    p.settings.stabilityTracking=!!stabilityTracking;p.settings.stabilityEigenTolerance=Math.max(1e-5,Math.min(1,Math.abs(num(stabilityEigenTolerance,.05))));p.settings.stabilityAsymmetryTolerance=Math.max(1e-12,Math.min(.1,Math.abs(num(stabilityAsymmetryTolerance,1e-6))));p.settings.stabilityMaxDofs=Math.max(6,Math.min(500,Math.round(num(stabilityMaxDofs,120))));p.settings.branchSwitchEnabled=!!branchSwitchEnabled&&!!stabilityTracking;p.settings.branchSwitchSign=num(branchSwitchSign,1)<0?-1:1;p.settings.branchSwitchAmplitude=Math.max(1e-4,Math.min(.45,Math.abs(num(branchSwitchAmplitude,.08))));")
rep(path,
"<small>Núcleo geom. v0.13.6 · caminhos não lineares v0.17.</small>",
"<small>Núcleo geom. v0.13.6 · estabilidade e caminhos v0.18.</small>")
rep(path,
"<h3>Newton–Raphson incremental · v0.17</h3>",
"<h3>Newton–Raphson incremental · v0.18</h3>")
old="<div data-testid=\"arc-length-control-note\" className=\"panel-note\">O método v0.17 usa uma restrição esférica de Crisfield no espaço generalizado <b>(Δu, Δλ)</b>. O preditor é orientado pela projeção positiva no incremento convergido anterior; o corretor resolve o sistema bordado e o raio é adaptado conforme o número de iterações, com cutback automático em falha de convergência. O nó/DOF acima é apenas <b>monitor</b> para traçar a curva, não um deslocamento imposto.</div></>}"
new="<div data-testid=\"arc-length-control-note\" className=\"panel-note\">O método v0.18 mantém a restrição esférica de Crisfield no espaço generalizado <b>(Δu, Δλ)</b>, com raio adaptativo e cutback. O nó/DOF acima é apenas <b>monitor</b>, não um deslocamento imposto.</div><div className=\"section-title\"><h3>Estabilidade tangente · v0.18</h3><span className=\"chip\">espectral</span></div><div className=\"geometry-grid\"><label className=\"checkbox-line\"><input data-testid=\"stability-tracking\" type=\"checkbox\" checked={stabilityTracking} onChange={e=>{setStabilityTracking(e.target.checked);if(!e.target.checked)setBranchSwitchEnabled(false)}}/><span>Monitorar singularidades</span></label><label>Tol. |μ/μ₀|<input data-testid=\"stability-eigen-tolerance\" type=\"number\" min=\"0.00001\" max=\"1\" step=\"0.01\" value={stabilityEigenTolerance} onChange={e=>setStabilityEigenTolerance(num(e.target.value,.05))}/></label><label>Tol. assimetria<input data-testid=\"stability-asymmetry-tolerance\" type=\"number\" min=\"1e-12\" max=\"0.1\" step=\"1e-6\" value={stabilityAsymmetryTolerance} onChange={e=>setStabilityAsymmetryTolerance(num(e.target.value,1e-6))}/></label><label>Máx. DOFs espectrais<input data-testid=\"stability-max-dofs\" type=\"number\" min=\"6\" max=\"500\" value={stabilityMaxDofs} onChange={e=>setStabilityMaxDofs(num(e.target.value,120))}/></label><label className=\"checkbox-line\"><input data-testid=\"branch-switch-enabled\" type=\"checkbox\" disabled={!stabilityTracking} checked={branchSwitchEnabled} onChange={e=>setBranchSwitchEnabled(e.target.checked)}/><span>Troca de ramo experimental</span></label>{branchSwitchEnabled&&<><label>Sentido modal<select data-testid=\"branch-switch-sign\" value={branchSwitchSign<0?-1:1} onChange={e=>setBranchSwitchSign(num(e.target.value,1)<0?-1:1)}><option value={1}>+ modo crítico</option><option value={-1}>− modo crítico</option></select></label><label>Amplitude modal / raio<input data-testid=\"branch-switch-amplitude\" type=\"number\" min=\"0.0001\" max=\"0.45\" step=\"0.01\" value={branchSwitchAmplitude} onChange={e=>setBranchSwitchAmplitude(num(e.target.value,.08))}/></label></>}</div><div data-testid=\"stability-control-note\" className=\"panel-note\">A estabilidade é rastreada pelo autovalor de menor módulo da <b>parte simétrica da tangente escalada</b>. Cruzamento de zero com reversão de Δλ é classificado como ponto‑limite; sem reversão, como <b>candidato a bifurcação</b> apenas quando a tangente é suficientemente simétrica. Com forças follower/não conservativas, o diagnóstico é somente candidato a singularidade. A troca de ramo, desativada por padrão, usa um único passo de semeadura com amplitude no modo crítico e depois retorna ao Arc‑Length.</div></>}"
rep(path,old,new)
rep(path,
"A v0.17 acrescenta <b>Arc-Length/Riks esférico</b> com adaptação automática de raio e cutback, além do pushover por controle de deslocamento da v0.16.",
"A v0.18 acrescenta <b>diagnóstico espectral de estabilidade</b>, classificação experimental de ponto‑limite/bifurcação e semeadura modal opcional de ramo sobre o Arc-Length/Riks esférico da v0.17, além do pushover por controle de deslocamento da v0.16.")

# -----------------------------------------------------------------------------
# Postprocess: stability markers + summary
# -----------------------------------------------------------------------------
path='app/src/NonlinearPostprocessPanel.tsx'
p=Path(path);t=p.read_text()
start=t.index('function ArcLengthChart({arc}:{arc:any}){')
end=t.index('\nfunction extrema(',start)
new_chart=r'''function ArcLengthChart({arc}:{arc:any}){
  const rows=arc?.curve||[];if(!rows.length)return null;
  const stability=arc?.stability||{},events=stability.events||[],limitEvents=events.filter((e:any)=>e.type==='limit-point'),bifEvents=events.filter((e:any)=>e.type==='bifurcation-candidate'),nonConservative=events.filter((e:any)=>e.type==='nonconservative-singularity-candidate'),switches=stability.branchSwitch?.switches||[],rotational=arc?.monitor?.dof==='rz',factor=rotational?1:1000,unit=rotational?'rad':'mm',W=650,H=250,L=58,R=18,T=28,B=38,xs=rows.map((r:any)=>num(r.monitoredDisplacement)*factor),ys=rows.map((r:any)=>num(r.loadFactor)),xmin=Math.min(...xs,0),xmax=Math.max(...xs,0),ymin=Math.min(...ys,0),ymax=Math.max(...ys,0),dx=Math.max(xmax-xmin,1e-12),dy=Math.max(ymax-ymin,1e-12),xlo=xmin-.06*dx,xhi=xmax+.06*dx,ylo=ymin-.08*dy,yhi=ymax+.08*dy,sx=(x:number)=>L+(x-xlo)/Math.max(xhi-xlo,1e-12)*(W-L-R),sy=(y:number)=>T+(yhi-y)/Math.max(yhi-ylo,1e-12)*(H-T-B),path=rows.map((r:any,i:number)=>`${i?'L':'M'} ${sx(num(r.monitoredDisplacement)*factor).toFixed(1)} ${sy(num(r.loadFactor)).toFixed(1)}`).join(' '),turning=(arc.turningPoints||[]).filter((e:any)=>e.type==='load-factor-turning');
  const eventPoint=(e:any)=>({x:sx(num(e.criticalMonitoredDisplacement)*factor),y:sy(num(e.criticalLoadFactor))});
  return <div className="chart-card" data-testid="arc-length-path-chart"><div className="chart-title"><b>Caminho de equilíbrio · λ × {arc.monitor?.nodeId}/{String(arc.monitor?.dof||'').toUpperCase()}</b><span>{rows.length} passos · {limitEvents.length} limite(s) · {bifEvents.length} bifurcação(ões) candidata(s)</span></div><svg viewBox={`0 0 ${W} ${H}`} className="react-chart"><line x1={L} y1={T} x2={L} y2={H-B}/><line x1={L} y1={H-B} x2={W-R} y2={H-B}/>{xlo<=0&&xhi>=0&&<line className="zero" x1={sx(0)} y1={T} x2={sx(0)} y2={H-B}/>} {ylo<=0&&yhi>=0&&<line className="zero" x1={L} y1={sy(0)} x2={W-R} y2={sy(0)}/>}<path className="line" d={path}/>{turning.map((e:any,i:number)=><circle data-testid="arc-length-turning-marker" key={`turn-${i}-${e.step}`} cx={sx(num(e.monitoredDisplacement)*factor)} cy={sy(num(e.loadFactor))} r="4"><title>{`Reversão local de λ · passo ${e.step}`}</title></circle>)}{limitEvents.map((e:any,i:number)=>{const q=eventPoint(e);return <circle data-testid="stability-limit-marker" key={`lim-${i}`} cx={q.x} cy={q.y} r="6"><title>{`Ponto-limite · λ≈${fmt(e.criticalLoadFactor,5)}`}</title></circle>})}{bifEvents.map((e:any,i:number)=>{const q=eventPoint(e);return <rect data-testid="stability-bifurcation-marker" key={`bif-${i}`} x={q.x-5} y={q.y-5} width="10" height="10"><title>{`Bifurcação candidata · λ≈${fmt(e.criticalLoadFactor,5)} · ${e.dominant?.nodeId}/${String(e.dominant?.dof||'').toUpperCase()}`}</title></rect>})}{nonConservative.map((e:any,i:number)=>{const q=eventPoint(e);return <circle data-testid="stability-nonconservative-marker" key={`nc-${i}`} cx={q.x} cy={q.y} r="5"><title>{`Singularidade não conservativa candidata · λ≈${fmt(e.criticalLoadFactor,5)}`}</title></circle>})}{switches.map((s:any,i:number)=>{const row=rows.find((r:any)=>r.step===s.appliedStep);if(!row)return null;const x=sx(num(row.monitoredDisplacement)*factor),y=sy(num(row.loadFactor));return <polygon data-testid="branch-switch-marker" key={`sw-${i}`} points={`${x},${y-7} ${x+7},${y} ${x},${y+7} ${x-7},${y}`}><title>{`Semeadura modal · passo ${s.appliedStep} · retenção=${s.retained?'sim':'não'}`}</title></polygon>})}{rows.filter((r:any)=>r.newlyYieldedHinges?.length).map((r:any)=><circle key={`yield-arc-${r.step}`} cx={sx(num(r.monitoredDisplacement)*factor)} cy={sy(num(r.loadFactor))} r="3"><title>{`Nova plastificação · passo ${r.step}`}</title></circle>)}</svg><div className="panel-note">v0.18: círculos maiores = pontos‑limite espectrais; quadrados = bifurcações candidatas; losangos = passo de semeadura modal. Para tangente materialmente não simétrica, o espectro da parte simétrica é apenas um diagnóstico de singularidade, não uma prova de bifurcação conservativa.</div></div>;
}
'''
t=t[:start]+new_chart+t[end:];p.write_text(t)
rep(path,
"arc=solved.value?.arcLength,hasArc=!!arc?.enabled,arcUnit=arc?.monitor?.dof==='rz'?'rad':'mm',arcFactor=arc?.monitor?.dof==='rz'?1:1000;",
"arc=solved.value?.arcLength,hasArc=!!arc?.enabled,arcUnit=arc?.monitor?.dof==='rz'?'rad':'mm',arcFactor=arc?.monitor?.dof==='rz'?1:1000,stability=arc?.stability,stabilityEvents=stability?.events||[],limitEvents=stabilityEvents.filter((e:any)=>e.type==='limit-point'),bifurcationEvents=stabilityEvents.filter((e:any)=>e.type==='bifurcation-candidate'),nonConservativeEvents=stabilityEvents.filter((e:any)=>e.type==='nonconservative-singularity-candidate'),branchSwitches=stability?.branchSwitch?.switches||[];")
rep(path,
"{hasArc&&<div data-testid=\"arc-length-summary\" className=\"panel-note\"><b>Arc-Length/Riks v0.17:</b> monitor {arc.monitor?.nodeId}/{String(arc.monitor?.dof||'').toUpperCase()}, λ final={fmt(arc.finalLoadFactor,5)}, λ pico={fmt(arc.peakLoadFactor,5)}, Δλ inicial={fmt(arc.initialLoadIncrement,4)}, raio inicial={Number(arc.initialRadius||0).toExponential(3)}, escala λ={Number(arc.loadScale||0).toExponential(3)} m. Foram detectados <b>{(arc.turningPoints||[]).filter((e:any)=>e.type==='load-factor-turning').length}</b> ponto(s)-limite de λ. O raio é adaptado por esforço iterativo e pode sofrer cutback. O monitor não é uma restrição cinemática.</div>}",
"{hasArc&&<><div data-testid=\"arc-length-summary\" className=\"panel-note\"><b>Arc-Length/Riks v0.18:</b> monitor {arc.monitor?.nodeId}/{String(arc.monitor?.dof||'').toUpperCase()}, λ final={fmt(arc.finalLoadFactor,5)}, λ pico={fmt(arc.peakLoadFactor,5)}, Δλ inicial={fmt(arc.initialLoadIncrement,4)}, raio inicial={Number(arc.initialRadius||0).toExponential(3)}. O raio permanece adaptativo com cutback.</div>{stability?.enabled&&<div data-testid=\"stability-summary\" className=\"panel-note\"><b>Estabilidade tangente v0.18:</b> {limitEvents.length} ponto(s)-limite, {bifurcationEvents.length} bifurcação(ões) candidata(s) e {nonConservativeEvents.length} singularidade(s) não conservativa(s) candidata(s). {bifurcationEvents[0]?<>Primeira bifurcação: λ≈<b>{fmt(bifurcationEvents[0].criticalLoadFactor,5)}</b>, modo dominante {bifurcationEvents[0].dominant?.nodeId}/{String(bifurcationEvents[0].dominant?.dof||'').toUpperCase()}.</>:null} Troca de ramo: {stability.branchSwitch?.enabled?`${branchSwitches.length} semeadura(s) modal(is) aplicada(s)`:'desativada'}. Método espectral: {stability.method}.</div>}</>}")
rep(path,
"<div><small>Pontos-limite</small><b>{(arc.turningPoints||[]).filter((e:any)=>e.type==='load-factor-turning').length}</b></div><div><small>Raio final</small>",
"<div><small>Pontos-limite</small><b>{limitEvents.length}</b></div><div><small>Bifurcações cand.</small><b>{bifurcationEvents.length}</b></div><div><small>Trocas de ramo</small><b>{branchSwitches.length}</b></div><div><small>Raio final</small>")

# -----------------------------------------------------------------------------
# Report: spectral stability subsection
# -----------------------------------------------------------------------------
path='app/src/NonlinearReportPanel.tsx'
rep(path,
"arc=r?.arcLength,hasArc=!!arc?.enabled,arcFactor=arc?.monitor?.dof==='rz'?1:1000,arcUnit=arc?.monitor?.dof==='rz'?'rad':'mm';",
"arc=r?.arcLength,hasArc=!!arc?.enabled,arcFactor=arc?.monitor?.dof==='rz'?1:1000,arcUnit=arc?.monitor?.dof==='rz'?'rad':'mm',stability=arc?.stability,stabilityEvents=stability?.events||[],limitEvents=stabilityEvents.filter((e:any)=>e.type==='limit-point'),bifurcationEvents=stabilityEvents.filter((e:any)=>e.type==='bifurcation-candidate'),nonConservativeEvents=stabilityEvents.filter((e:any)=>e.type==='nonconservative-singularity-candidate'),branchSwitches=stability?.branchSwitch?.switches||[];")
rep(path,
"<div><small>Pontos-limite λ</small><b>{(arc.turningPoints||[]).filter((e:any)=>e.type==='load-factor-turning').length}</b></div>",
"<div><small>Pontos-limite</small><b>{limitEvents.length}</b></div><div><small>Bifurcações cand.</small><b>{bifurcationEvents.length}</b></div>")
anchor="<p><b>Limitação:</b> a continuação geométrica pode atravessar snap-through e, dependendo da parametrização, snap-back; entretanto as rótulas de fibras atuais continuam usando uma lei monotônica sem história cíclica. Reversões constitutivas não devem ser interpretadas como histerese física.</p>"
insert="<section data-testid=\"stability-report\"><h3>2.3. Singularidades e bifurcações · v0.18</h3><p>A cada estado convergido do Arc-Length, a v0.18 calcula o autovalor de menor módulo da <b>parte simétrica da matriz tangente escalada</b>, com rotações convertidas por Lc. Um cruzamento de zero acompanhado por reversão de Δλ é classificado como <b>ponto-limite</b>; sem reversão de Δλ é registrado como <b>bifurcação candidata</b> somente quando a assimetria da tangente permanece abaixo da tolerância. Para cargas follower ou outros casos não conservativos, a classificação é deliberadamente limitada a <b>singularidade não conservativa candidata</b>.</p><div className=\"metrics-row\"><div><small>μref</small><b>{Number(stability?.referenceEigenvalue||0).toExponential(3)}</b></div><div><small>Tol. relativa</small><b>{fmt(stability?.relativeTolerance,4)}</b></div><div><small>Pontos-limite</small><b>{limitEvents.length}</b></div><div><small>Bifurcações cand.</small><b>{bifurcationEvents.length}</b></div><div><small>Sing. não conserv.</small><b>{nonConservativeEvents.length}</b></div><div><small>Semeaduras de ramo</small><b>{branchSwitches.length}</b></div></div>{stabilityEvents.length?<div className=\"table-scroll\"><table><thead><tr><th>Tipo</th><th>Entre passos</th><th>λ crítico</th><th>u monitor [{arcUnit}]</th><th>Modo dominante</th><th>Assimetria Kt</th></tr></thead><tbody>{stabilityEvents.map((e:any,i:number)=><tr key={`stab-${i}`}><td>{e.type}</td><td>{(e.betweenSteps||[]).join(' → ')}</td><td>{fmt(e.criticalLoadFactor,6)}</td><td>{fmt(Number(e.criticalMonitoredDisplacement)*arcFactor,4)}</td><td>{e.dominant?`${e.dominant.nodeId}/${String(e.dominant.dof||'').toUpperCase()}`:'—'}</td><td>{Number(e.tangentAsymmetry||0).toExponential(3)}</td></tr>)}</tbody></table></div>:<p>Nenhum cruzamento espectral de zero foi detectado nos incrementos calculados.</p>}{stability?.branchSwitch?.enabled&&<p><b>Troca de ramo experimental:</b> após a primeira bifurcação candidata, um único passo substitui temporariamente a esfera do Arc-Length por uma restrição de amplitude ao longo do modo crítico; o passo seguinte retorna à continuação esférica. Foram aplicadas {branchSwitches.length} semeadura(s). Esse procedimento não resolve multiplicidade modal, autovalores complexos nem garante a descoberta de todos os ramos.</p>}</section>"
rep(path,anchor,insert+anchor)

# -----------------------------------------------------------------------------
# README label
# -----------------------------------------------------------------------------
path='README.md';p=Path(path);t=p.read_text();
if 'v0.18' not in t[:1200]:
    t=t.replace('v0.17','v0.18',1)
    p.write_text(t)

# -----------------------------------------------------------------------------
# E2E stability test
# -----------------------------------------------------------------------------
Path('tests/e2e/stability-bifurcation.spec.ts').write_text(r'''import { expect, test, type Page } from '@playwright/test';

async function storedProject(page:Page){return page.evaluate(()=>{const raw=localStorage.getItem('astrastruct.project');return raw?JSON.parse(raw):null})}
async function openCommand(page:Page,label:string){const width=page.viewportSize()?.width||1280;if(width<=1100){const more=page.locator('button[aria-label="Mais comandos"]:visible').first();await expect(more).toBeVisible();await more.click();const command=page.locator(`.command-sheet button[aria-label="${label}"]:visible`).first();await expect(command).toBeVisible();await command.click();return}const direct=page.locator(`button[aria-label="${label}"]:visible`).first();if(await direct.isVisible().catch(()=>false)){await direct.click();return}const library=page.locator('.library-tools button').filter({hasText:label}).first();await expect(library).toBeVisible();await library.click()}
async function installEulerColumn(page:Page){await page.goto('./');await page.evaluate(()=>{const raw=localStorage.getItem('astrastruct.project');if(!raw)throw new Error('Projeto inicial ausente');const p=JSON.parse(raw),L=4,n=8,P=10000,E=200e6,I=8e-5,A=.01;p.name='E2E — stability v0.18';p.materials=[{id:'S',name:'Steel elastic',type:'steel',E,nu:.3,density:0,alpha:12e-6,fy:355}];p.sections=[{id:'SEC',name:'Column',family:'rect',b:.1,h:.8,A,I}];p.nodes=Array.from({length:n+1},(_,i)=>({id:`N${i}`,x:0,y:L*i/n}));p.elements=[];for(let i=0;i<n;i++)p.elements.push({id:`E${i+1}`,type:'frame2d',n1:`N${i}`,n2:`N${i+1}`,materialId:'S',sectionId:'SEC',A,I,releases:{rz1:false,rz2:false},rotationalSprings:{rz1:null,rz2:null}});p.supports=[{nodeId:'N0',ux:true,uy:true,rz:false},{nodeId:`N${n}`,ux:true,uy:false,rz:false}];p.loads=[{id:'P',caseId:'LC1',nodeId:`N${n}`,fx:0,fy:-P,mz:0}];p.elementLoads=[];p.nodeSprings=[];p.settlements=[];p.settings={...(p.settings||{}),analysisType:'linear',activeLoadCaseId:'LC1',analysisScenarioId:'LC1',nonlinearSteps:30,nonlinearMaxIterations:70,nonlinearTolerance:1e-9,nonlinearLineSearch:true,imperfection:{...(p.settings?.imperfection||{}),enabled:false}};localStorage.setItem('astrastruct.project',JSON.stringify(p))});await page.reload()}

test('v0.18 detects Euler bifurcation and seeds the critical branch',async({page})=>{await installEulerColumn(page);await expect(page.getByTestId('astra-app')).toBeVisible();await openCommand(page,'Tipo de análise');await page.getByTestId('analysis-corotational').click();await page.getByTestId('nonlinear-control-mode').selectOption('arc-length');await page.getByTestId('arc-length-monitor-node').selectOption('N4');await page.getByTestId('arc-length-monitor-dof').selectOption('ux');await page.getByTestId('arc-length-initial-load-increment').fill('0.06');await page.getByTestId('nonlinear-steps').fill('30');await expect(page.getByTestId('stability-tracking')).toBeChecked();await page.getByTestId('stability-eigen-tolerance').fill('0.08');await page.getByTestId('stability-asymmetry-tolerance').fill('0.0000001');await page.getByTestId('branch-switch-enabled').check();await page.getByTestId('branch-switch-amplitude').fill('0.12');await page.getByTestId('analysis-apply').click();await expect.poll(async()=>{const p=await storedProject(page);return [p?.settings?.analysisType,p?.settings?.nonlinearControlMode,p?.settings?.stabilityTracking,p?.settings?.branchSwitchEnabled,Number(p?.settings?.branchSwitchAmplitude)]}).toEqual(['corotational','arc-length',true,true,.12]);await page.getByTestId('analyze-button').click();const results=page.locator('.results-content');await expect(results).toContainText('frame2d-corotational-arc-length-experimental');await expect(results).toContainText('0.18.0-exp');await expect(page.locator('[role="alert"]')).toHaveCount(0);await openCommand(page,'Diagramas/envelopes');const post=page.getByTestId('panel-nonlinear-postprocess');await expect(post).toBeVisible();await expect(page.getByTestId('stability-summary')).toContainText('bifurcação');await expect(page.getByTestId('stability-bifurcation-marker')).toHaveCount(1);await expect(page.getByTestId('branch-switch-marker')).toHaveCount(1);await post.locator('button[aria-label="Fechar"]').click();await openCommand(page,'Relatório técnico');const report=page.getByTestId('panel-nonlinear-report');await expect(report).toBeVisible();await expect(page.getByTestId('stability-report')).toContainText('bifurcation-candidate');await expect(page.getByTestId('stability-report')).toContainText('Troca de ramo experimental');await expect(page.locator('[role="alert"]')).toHaveCount(0)});
''')

# Existing arc E2E now sees v0.18 Arc solver.
p=Path('tests/e2e/arc-length.spec.ts');t=p.read_text().replace("'0.17.0-exp'","'0.18.0-exp'").replace('v0.17 configures Arc-Length/Riks','v0.18 configures Arc-Length/Riks');p.write_text(t)

print('v0.18 UI patch applied')
