from pathlib import Path

def repl(t,old,new,label):
    if old in t:return t.replace(old,new,1)
    if new in t:return t
    raise SystemExit(f'{label} anchor missing')

# Inspector
p=Path('app/src/InspectorPanel.tsx'); t=p.read_text()
t=repl(t,"const defaultFiberHinge={enabled:false,hingeLength:.35,nFibers:80,hardeningRatio:.01};","const defaultFiberHinge={enabled:false,hingeLength:.35,nFibers:80,hardeningRatio:.01};\nconst defaultDistributedPlasticity={enabled:false,integrationPoints:5,nFibers:80,hardeningRatio:.01};",'inspector default')
t=repl(t,"setDraft({label:entity.label||entity.id,materialId:entity.materialId,sectionId:entity.sectionId,A:entity.A,I:entity.I,releases:{rz1:false,rz2:false,...entity.releases},fiberHinges:{rz1:{...defaultFiberHinge,...entity.fiberHinges?.rz1},rz2:{...defaultFiberHinge,...entity.fiberHinges?.rz2}},uniform:clone(uniform)});","setDraft({label:entity.label||entity.id,materialId:entity.materialId,sectionId:entity.sectionId,A:entity.A,I:entity.I,releases:{rz1:false,rz2:false,...entity.releases},fiberHinges:{rz1:{...defaultFiberHinge,...entity.fiberHinges?.rz1},rz2:{...defaultFiberHinge,...entity.fiberHinges?.rz2}},distributedPlasticity:{...defaultDistributedPlasticity,...entity.distributedPlasticity},uniform:clone(uniform)});",'inspector draft')
t=repl(t,"  const applyElement=()=>{const p=clone(project),e=p.elements.find((x:any)=>x.id===entity.id),fiberHinges={rz1:normalizedHinge(draft.fiberHinges?.rz1),rz2:normalizedHinge(draft.fiberHinges?.rz2)};Object.assign(e,{label:draft.label,materialId:draft.materialId,sectionId:draft.sectionId,A:Math.max(1e-12,num(draft.A)),I:e.type==='frame2d'?Math.max(1e-16,num(draft.I)):0,releases:{...draft.releases},fiberHinges});","  const normalizedDistributed=(raw:any)=>({enabled:!!raw?.enabled,integrationPoints:[3,5].includes(Math.round(num(raw?.integrationPoints,5)))?Math.round(num(raw?.integrationPoints,5)):5,nFibers:Math.max(8,Math.min(400,Math.round(num(raw?.nFibers,80)))),hardeningRatio:Math.max(1e-6,Math.min(.25,Math.abs(num(raw?.hardeningRatio,.01))))});\n  const applyElement=()=>{const p=clone(project),e=p.elements.find((x:any)=>x.id===entity.id),distributedPlasticity=normalizedDistributed(draft.distributedPlasticity),fiberHinges=distributedPlasticity.enabled?{rz1:{...normalizedHinge(draft.fiberHinges?.rz1),enabled:false},rz2:{...normalizedHinge(draft.fiberHinges?.rz2),enabled:false}}:{rz1:normalizedHinge(draft.fiberHinges?.rz1),rz2:normalizedHinge(draft.fiberHinges?.rz2)};Object.assign(e,{label:draft.label,materialId:draft.materialId,sectionId:draft.sectionId,A:Math.max(1e-12,num(draft.A)),I:e.type==='frame2d'?Math.max(1e-16,num(draft.I)):0,releases:distributedPlasticity.enabled?{rz1:false,rz2:false}:{...draft.releases},fiberHinges,distributedPlasticity});",'inspector apply head')
t=repl(t,"e.rotationalSprings={rz1:e.rotationalSprings?.rz1??null,rz2:e.rotationalSprings?.rz2??null};for(const key of ['rz1','rz2'])if(fiberHinges[key].enabled){e.releases[key]=false;e.rotationalSprings[key]=null}if(fiberHinges.rz1.enabled||fiberHinges.rz2.enabled)p.settings={...(p.settings||{}),analysisType:'corotational'};","e.rotationalSprings=distributedPlasticity.enabled?{rz1:null,rz2:null}:{rz1:e.rotationalSprings?.rz1??null,rz2:e.rotationalSprings?.rz2??null};for(const key of ['rz1','rz2'])if(fiberHinges[key].enabled){e.releases[key]=false;e.rotationalSprings[key]=null}if(fiberHinges.rz1.enabled||fiberHinges.rz2.enabled||distributedPlasticity.enabled)p.settings={...(p.settings||{}),analysisType:'corotational'};",'inspector apply compat')
t=repl(t,"  const patchHinge=(key:'rz1'|'rz2',patch:any)=>setDraft({...draft,fiberHinges:{...draft.fiberHinges,[key]:{...draft.fiberHinges[key],...patch}},releases:patch.enabled?{...draft.releases,[key]:false}:draft.releases});","  const patchHinge=(key:'rz1'|'rz2',patch:any)=>setDraft({...draft,fiberHinges:{...draft.fiberHinges,[key]:{...draft.fiberHinges[key],...patch}},distributedPlasticity:patch.enabled?{...draft.distributedPlasticity,enabled:false}:draft.distributedPlasticity,releases:patch.enabled?{...draft.releases,[key]:false}:draft.releases});\n  const patchDistributed=(patch:any)=>{const enabled=patch.enabled??draft.distributedPlasticity?.enabled;setDraft({...draft,distributedPlasticity:{...draft.distributedPlasticity,...patch},fiberHinges:enabled?{rz1:{...draft.fiberHinges.rz1,enabled:false},rz2:{...draft.fiberHinges.rz2,enabled:false}}:draft.fiberHinges,releases:enabled?{rz1:false,rz2:false}:draft.releases})};",'inspector patch functions')
old="<h4>Rótulas de fibras · v0.16</h4>{!fiberEligible&&<div data-testid=\"fiber-hinge-ineligible\" className=\"panel-note\">Disponível para <b>aço</b> com seção paramétrica <b>retangular</b>, <b>I/H</b> ou <b>RHS</b>. Perfis I/H usam h, b, tw e tf; RHS usa h, b e t.</div>}{hingeEditor('rz1','Extremidade 1')}{hingeEditor('rz2','Extremidade 2')}<p className=\"hint\">Ao ativar uma rótula de fibras, o extremo deixa de usar release/mola linear e o projeto passa automaticamente para Geom. não linear. Modelo monotônico bilinear com equilíbrio N–M e Newton constitutivo embutido; não representa resposta cíclica.</p>"
new="<h4>Plasticidade distribuída · v0.20</h4>{!fiberEligible&&<div data-testid=\"distributed-plasticity-ineligible\" className=\"panel-note\">Disponível para <b>aço estrutural</b> com seção paramétrica <b>retangular</b>, <b>I/H</b> ou <b>RHS</b>.</div>}<div className=\"react-card\" data-testid=\"distributed-plasticity-card\"><label className=\"checkbox-line\"><input data-testid=\"distributed-plasticity-enabled\" type=\"checkbox\" disabled={!fiberEligible} checked={!!draft.distributedPlasticity?.enabled} onChange={e=>patchDistributed({enabled:e.target.checked})}/><span><b>Integração ao longo da barra</b> · fibras</span></label>{draft.distributedPlasticity?.enabled&&<div className=\"inspector-grid\"><label>Pontos Lobatto<select data-testid=\"distributed-plasticity-points\" value={draft.distributedPlasticity.integrationPoints} onChange={e=>patchDistributed({integrationPoints:Number(e.target.value)})}><option value={3}>3</option><option value={5}>5</option></select></label><label>Fibras/seção<input data-testid=\"distributed-plasticity-fibers\" type=\"number\" min=\"8\" max=\"400\" step=\"4\" value={draft.distributedPlasticity.nFibers} onChange={e=>patchDistributed({nFibers:e.target.value})}/></label><label>Et/E<input data-testid=\"distributed-plasticity-hardening\" type=\"number\" min=\"0.000001\" max=\"0.25\" step=\"0.005\" value={draft.distributedPlasticity.hardeningRatio} onChange={e=>patchDistributed({hardeningRatio:e.target.value})}/></label></div>}</div><p className=\"hint\">A v0.20 integra seções de fibras por Gauss–Lobatto ao longo do elemento e permite espalhamento da plastificação. Nesta versão usa extremidades rígidas e é mutuamente exclusiva com rótulas concentradas/releases/molas rotacionais. Lei de aço bilinear monotônica, sem histerese.</p><h4>Rótulas de fibras · concentradas</h4>{!fiberEligible&&<div data-testid=\"fiber-hinge-ineligible\" className=\"panel-note\">Disponível para <b>aço</b> com seção paramétrica <b>retangular</b>, <b>I/H</b> ou <b>RHS</b>. Perfis I/H usam h, b, tw e tf; RHS usa h, b e t.</div>}{hingeEditor('rz1','Extremidade 1')}{hingeEditor('rz2','Extremidade 2')}<p className=\"hint\">As rótulas concentradas continuam disponíveis como alternativa. Ao ativá-las, a plasticidade distribuída é desligada. Modelo monotônico bilinear com equilíbrio N–M; não representa resposta cíclica.</p>"
t=repl(t,old,new,'inspector distributed UI')
p.write_text(t)

# Postprocess
p=Path('app/src/NonlinearPostprocessPanel.tsx'); t=p.read_text()
old="branchExplorations=stability?.branchExploration?.explorations||[],finalClusters=stability?.finalClusters||[];"
new="branchExplorations=stability?.branchExploration?.explorations||[],finalClusters=stability?.finalClusters||[],distributed=solved.value?.distributedPlasticity,hasDistributed=!!distributed?.enabled,distributedRecord=(distributed?.records||[]).find((x:any)=>x.elementId===response?.elementId);"
t=repl(t,old,new,'post distributed vars')
t=t.replace("{hasMaterial&&<span className=\"chip\">material não linear</span>}","{hasMaterial&&<span className=\"chip\">material não linear</span>}{hasDistributed&&<span className=\"chip\">plasticidade distribuída</span>}",1)
marker="{hasMaterial&&<div data-testid=\"material-postprocess-note\""
insert="{hasDistributed&&<div data-testid=\"distributed-plasticity-note\" className=\"panel-note\"><b>Plasticidade distribuída v0.20:</b> integração Gauss–Lobatto com {distributedRecord?.integrationPoints||'—'} seções e {distributedRecord?.nFibers||'—'} fibras por seção. No elemento selecionado: <b>{distributedRecord?.yieldedPointCount||0}</b> ponto(s) de integração plastificado(s), fração máxima de fibras escoadas {fmt(100*num(distributedRecord?.maxYieldFraction),1)}% e comprimento plástico integrado ≈ {fmt(distributedRecord?.plasticLengthEstimate,4)} m. {(distributedRecord?.sections||[]).map((s:any)=>`ξ=${fmt(s.xi,3)}: M=${fmt(s.M,2)} kN·m, κ=${Number(s.kappa||0).toExponential(2)} 1/m, fibras=${s.yieldedFibers}/${s.fiberCount}`).join('; ')||'O elemento selecionado não possui integração distribuída.'} <b>Escopo:</b> aço bilinear monotônico; sem descarga/recarga ou histerese.</div>}"
if marker not in t:raise SystemExit('post material note marker missing')
t=t.replace(marker,insert+marker,1)
# add metrics next to material metrics
old="{hasMaterial&&<><div><small>Newton material local</small><b>{material.maxLocalIterations??material.outerIterations??'—'}</b></div><div><small>Resíduo M material</small><b>{Number(material.maxMomentResidual||0).toExponential(2)}</b></div></>}"
new="{hasDistributed&&<><div><small>Pontos plastificados</small><b>{distributedRecord?.yieldedPointCount??0}/{distributedRecord?.integrationPoints??'—'}</b></div><div><small>Lp distribuído</small><b>{fmt(distributedRecord?.plasticLengthEstimate,4)} m</b></div></>}{hasMaterial&&<><div><small>Newton material local</small><b>{material.maxLocalIterations??material.outerIterations??'—'}</b></div><div><small>Resíduo M material</small><b>{Number(material.maxMomentResidual||0).toExponential(2)}</b></div></>}"
t=repl(t,old,new,'post distributed metrics')
p.write_text(t)

# Report
p=Path('app/src/NonlinearReportPanel.tsx'); t=p.read_text()
old="branchExplorations=stability?.branchExploration?.explorations||[],finalClusters=stability?.finalClusters||[];"
new="branchExplorations=stability?.branchExploration?.explorations||[],finalClusters=stability?.finalClusters||[],distributed=r?.distributedPlasticity,hasDistributed=!!distributed?.enabled,distributedRecords=distributed?.records||[];"
t=repl(t,old,new,'report distributed vars')
t=t.replace("{hasMaterial?' com rótulas de fibras v0.17':''}.","{hasMaterial?' com rótulas concentradas de fibras':''}{hasDistributed?' com plasticidade distribuída v0.20':''}.",1)
old="{hasMaterial?'. A resposta material inclui rótulas concentradas de seção de fibras de aço com lei bilinear monotônica e equilíbrio local N–M.':'. O material dos elementos permanece elástico linear.'}"
new="{hasDistributed?'. A resposta material inclui integração distribuída de seções de fibras de aço por Gauss–Lobatto ao longo dos elementos habilitados.':hasMaterial?'. A resposta material inclui rótulas concentradas de seção de fibras de aço com lei bilinear monotônica e equilíbrio local N–M.':'. O material dos elementos permanece elástico linear.'}"
t=repl(t,old,new,'report scope distributed')
marker="      <h3>3. Imperfeição geométrica inicial</h3>"
section="      {hasDistributed&&<section data-testid=\"distributed-plasticity-report\"><h3>2.4. Plasticidade distribuída · v0.20</h3><p>Os elementos habilitados usam formulação <b>displacement-based Euler–Bernoulli</b> co-rotacional com integração de seções de fibras em pontos <b>Gauss–Lobatto</b>, incluindo as extremidades. As deformações generalizadas básicas geram deformação axial uniforme e curvatura linear ao longo do elemento; forças e rigidez tangente são obtidas por integração de <b>Bᵀs</b> e <b>BᵀDB</b>. No limite elástico, a formulação recupera a matriz básica clássica de dois nós.</p><div className=\"metrics-row\"><div><small>Elementos distribuídos</small><b>{distributedRecords.length}</b></div><div><small>Pontos plastificados</small><b>{distributed?.yieldedPointCount||0}</b></div><div><small>Fibras escoadas</small><b>{distributed?.yieldedFiberCount||0}</b></div><div><small>Comprimento plástico integrado</small><b>{fmt(distributed?.plasticLengthEstimate,5)} m</b></div></div>{distributedRecords.map((rec:any)=><div key={`dp-${rec.elementId}`} className=\"table-scroll\"><table><thead><tr><th colSpan={7}>{rec.elementId} · {rec.integrationPoints} pontos · {rec.nFibers} fibras/seção</th></tr><tr><th>ξ</th><th>x [m]</th><th>κ [1/m]</th><th>N [kN]</th><th>M [kN·m]</th><th>Fibras escoadas</th><th>Fração</th></tr></thead><tbody>{(rec.sections||[]).map((s:any,i:number)=><tr key={`${rec.elementId}-${i}`}><td>{fmt(s.xi,4)}</td><td>{fmt(s.x,4)}</td><td>{Number(s.kappa||0).toExponential(3)}</td><td>{fmt(s.N,3)}</td><td>{fmt(s.M,3)}</td><td>{s.yieldedFibers}/{s.fiberCount}</td><td>{fmt(100*Number(s.yieldFraction||0),1)}%</td></tr>)}</tbody></table></div>)}<p><b>Limitações:</b> a lei constitutiva nesta versão é o envelope bilinear monotônico do aço; não há memória irreversível de descarga/recarga, Bauschinger, pinching ou degradação. Releases, molas rotacionais e rótulas concentradas no mesmo elemento são bloqueados para evitar condensação não linear inconsistente.</p></section>}\n"
if marker not in t:raise SystemExit('report section insertion marker missing')
t=t.replace(marker,section+marker,1)
# Update limitation prose if present
if 'plasticidade distribuída' in t:
    t=t.replace('Ainda não há plasticidade distribuída', 'A plasticidade distribuída v0.20 está disponível para aço; ainda não há história cíclica')
p.write_text(t)

# New E2E test
p=Path('tests/e2e/distributed-plasticity.spec.ts')
p.write_text(r'''import { expect, test, type Page } from '@playwright/test';

async function storedProject(page:Page){return page.evaluate(()=>{const raw=localStorage.getItem('astrastruct.project');return raw?JSON.parse(raw):null})}
async function openCommand(page:Page,label:string){const width=page.viewportSize()?.width||1280;if(width<=1100){const more=page.locator('button[aria-label="Mais comandos"]:visible').first();await expect(more).toBeVisible();await more.click();const command=page.locator(`.command-sheet button[aria-label="${label}"]:visible`).first();await expect(command).toBeVisible();await command.click();return}const direct=page.locator(`button[aria-label="${label}"]:visible`).first();if(await direct.isVisible().catch(()=>false)){await direct.click();return}const library=page.locator('.library-tools button').filter({hasText:label}).first();await expect(library).toBeVisible();await library.click()}
async function install(page:Page){await page.goto('./');await page.evaluate(()=>{const raw=localStorage.getItem('astrastruct.project');if(!raw)throw new Error('Projeto inicial ausente');const p=JSON.parse(raw),b=.1,h=.2,A=b*h,I=b*h**3/12;p.name='E2E — distributed v0.20';p.materials=[{id:'S',name:'S355',type:'steel',E:200e6,nu:.3,density:0,alpha:12e-6,fy:355}];p.sections=[{id:'SEC',name:'Rect',family:'rect',b,h,A,I}];p.nodes=[{id:'N1',x:0,y:0},{id:'N2',x:2,y:0}];p.elements=[{id:'E1',type:'frame2d',n1:'N1',n2:'N2',materialId:'S',sectionId:'SEC',A,I,label:'Distributed beam',releases:{rz1:false,rz2:false},rotationalSprings:{rz1:null,rz2:null}}];p.supports=[{nodeId:'N1',ux:true,uy:true,rz:true}];p.loads=[{id:'P',caseId:'LC1',nodeId:'N2',fx:0,fy:-100,mz:0}];p.elementLoads=[];p.nodeSprings=[];p.settlements=[];p.settings={...(p.settings||{}),analysisType:'linear',activeLoadCaseId:'LC1',analysisScenarioId:'LC1',nonlinearSteps:20,nonlinearMaxIterations:70,nonlinearTolerance:1e-9,imperfection:{...(p.settings?.imperfection||{}),enabled:false}};localStorage.setItem('astrastruct.project',JSON.stringify(p))});await page.reload()}
async function openInspector(page:Page){const editor=page.getByTestId('distributed-plasticity-enabled'),width=page.viewportSize()?.width||1280;if(width<=1100){const inspector=page.locator('button[aria-label="Inspector"]:visible').first();await expect(inspector).toBeVisible();await inspector.click()}await editor.scrollIntoViewIfNeeded();await expect(editor).toBeVisible()}

test('v0.20 configures and solves distributed steel fiber plasticity',async({page})=>{await install(page);await expect(page.getByTestId('astra-app')).toBeVisible();const canvas=page.getByTestId('model-canvas');const box=await canvas.boundingBox();if(!box)throw new Error('Canvas sem geometria');await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await openInspector(page);await page.getByTestId('distributed-plasticity-enabled').check();await page.getByTestId('distributed-plasticity-points').selectOption('5');await page.getByTestId('distributed-plasticity-fibers').fill('120');await page.getByTestId('distributed-plasticity-hardening').fill('0.02');const apply=page.getByRole('button',{name:'Aplicar alterações'}).last();await apply.scrollIntoViewIfNeeded();await apply.click();await expect.poll(async()=>{const p=await storedProject(page),e=p?.elements?.find((x:any)=>x.id==='E1');return [p?.settings?.analysisType,e?.distributedPlasticity?.enabled,Number(e?.distributedPlasticity?.integrationPoints),Number(e?.distributedPlasticity?.nFibers),Number(e?.distributedPlasticity?.hardeningRatio),e?.fiberHinges?.rz1?.enabled||false,e?.fiberHinges?.rz2?.enabled||false,e?.releases?.rz1,e?.releases?.rz2]}).toEqual(['corotational',true,5,120,.02,false,false,false,false]);if((page.viewportSize()?.width||1280)<=1100){const close=page.locator('.inspector-panel.open button[aria-label="Fechar"]:visible').first();if(await close.isVisible().catch(()=>false))await close.click()}await openCommand(page,'Tipo de análise');await page.getByTestId('analysis-corotational').click();await page.getByTestId('nonlinear-control-mode').selectOption('displacement');await page.getByTestId('displacement-control-node').selectOption('N2');await page.getByTestId('displacement-control-dof').selectOption('uy');await page.getByTestId('displacement-control-target').fill('-40');await page.getByTestId('nonlinear-steps').fill('20');await page.getByTestId('analysis-apply').click();await page.getByTestId('analyze-button').click();const results=page.locator('.results-content');await expect(results).toContainText('frame2d-corotational-displacement-control-experimental');await expect(page.locator('[role="alert"]')).toHaveCount(0);await openCommand(page,'Diagramas/envelopes');const post=page.getByTestId('panel-nonlinear-postprocess');await expect(post).toBeVisible();await expect(post).toContainText('0.20.0-exp');await expect(page.getByTestId('distributed-plasticity-note')).toContainText('Gauss–Lobatto');await expect(page.getByTestId('distributed-plasticity-note')).toContainText('ponto(s) de integração plastificado(s)');await post.locator('button[aria-label="Fechar"]').click();await openCommand(page,'Relatório técnico');await expect(page.getByTestId('distributed-plasticity-report')).toBeVisible();await expect(page.getByTestId('distributed-plasticity-report')).toContainText('displacement-based Euler–Bernoulli');await expect(page.locator('[role="alert"]')).toHaveCount(0)});
''')
